### ISSUE TITLE
User Interface Scripting Extension

### ISSUE THREAD

**Issue by vishnubob** [MarlinFirmware/Marlin#1001]
Hi there,

I'm a long time user of Marlin, and it's a marvelous piece of work.  I've tromped around the code base a bit, and I've managed a few tweaks, but I'm thinking about busting out and trying to add features.  Towards this end, I wanted to open a dialog about an idea I recently had.

When I am maintaining my printer, there are many times I wish I could access pre-programmed macros that could assist in automating the process.  A classic example is bed-leveling.  I often find myself with a wireless mouse working OctoPrint from half way across the room so that I can move the head around.  What I would like to implement is an extension to the GCODE playback that would engage the control surface (I use an UltiController).  For my example, I would preprogram a set of waypoints I could step through using the dial, lowering the bed and then raising it between each waypoint so that I can get an accurate reading on a dial indicator.  The script would look just like a GCODE file, but the dial would serve as the program counter, allowing the user to fast-forward or rewind to different lines.  The LCD could simply display the line number and text content.

Thoughts?

**Comment by nicpottier** [comment]
@boelle Just curious, was this fixed or just deemed not something Marlin is interested in doing?

I found myself here because I had much the same idea as @vishnubob and I've built a few things like this. Having a way of building scrips that run off the SD card, can interact with the LCD, execute GCODE, seems like it could open up a new ecosystem of utilities for bed leveling / live z calibration / temp towers etc.. 

Can get into more detail on thoughts there but just want to understand the state of the world first. Obviously this would likely be a 2.0 only thing just because of space.

**Comment by InsanityAutomation** [comment]
That's really what EXTui is for nowadays. Not quite off SD, but a good externalized API for stuff. Anything not gcode based off the SD is asking for trouble imo.

**Comment by nicpottier** [comment]
Will do some exploration of EXTui, though for what it's worth, in my experience if you lower the barriers for this kind of thing such that a full recompile cycle isn't needed and hobbiest can get into it then wonderful things can happen.

> Anything not gcode based off the SD is asking for trouble imo.

Just for my own education can you elaborate? What kind of trouble?
