### ISSUE TITLE
M600 - continue print then trigger change

### ISSUE THREAD

**Issue by discojon** [MarlinFirmware/Marlin#10067]
Is there a way to wait or cache an m600 and continue printing for x mm of filament before triggering the filament change?  My filament sensor is approximately 22" from the nozzle (Taz 5, sensor on filament spinner).  I'd like the sensor to trigger, and the print to continue a defined amount of filament then trigger. 

 If this isn't currently in Marlin I'd like to request it.

**Comment by Roxy-3D** [comment]
We could add a #define to delay the trigger of the M600 by the specified amount of filament.

That would be possible.   The problem is finding somebody with time to code it up.

**Comment by ghost** [comment]
I love the idea , i have 22" too
But not with delay ,  and with an odometer 😄 
Is Marlin already have an odometer somewhere inside , to use it  ?
Change your title 
[FR] ADD M600 FILAMENT DISTANCE BEFORE TRIGGING

**Comment by ghost** [comment]
[#9934](https://github.com/MarlinFirmware/Marlin/issues/9934)

**Comment by tcm0116** [comment]
I would suggest adding this as a function of the filament monitor and not M600. If you add a delay to M600, then this will cause issues when using M600 to actually change the filament at a certain point in the print, as opposed to changing the filament due to run out.

**Comment by ghost** [comment]
It's not so easy that you can believe
In a dual extrusion or mixing or multiplexed multi extrusion, if a tool change appears , you will eject the bad filament at the bad moment

It's only possible 
- If no tool change
- If no dual extrusion
- If no in the first layer , that have a very low feedrate
- If no buffered lines ' because i have large format , and sometimes , 16 lines of G1 can eat a very long distance of extrusion

This feature seems to be easy , but in reality ..... will breaks so much elsewhere
To make a ' sure ' system ..... you have to lock the tool change , and make an odometer to calculate the filament but impossible to set a timer , except for ' known configuration '

But with a good programming , and the new sensor multi sensor detection , it's possible

-Memorisation of the tool on runout
-Odometer only for the tool on runout
-Multiplexed long bowden loading on tool change ' not allowed ' because filament return problems
AND MORE

GOOD LUCK

i have created ' THE TOOL MIGRATION FEATURE' , download my release ' always up to date '
You just need 2 extruders , when runout , the next extruders runs ' automaticly'

So if only one extruder .... It's better to eat 22" of filament or manually you  insert it , and a few second later , you insert manually the new spool , and you can leave your printer

**Comment by InsanityAutomation** [comment]
FYI this was implemented by Marcio and this should now be closed.

**Comment by guestisp** [comment]
Dumb question but... usually the filament sensor is very close to the extruder, but above it. If you have the filament sensor at 22'' from the nozzle, but 1'' from the extruder, when the filament sensor says that filament is out, who is pushing the filament to the nozzle? You can still extrude for the distance between the filament sensor and the extruder (in this example, 1''), but in a bowden setup (like you have, if the sensor is 22' above the nozzle) you can't extrude for the whole lenght of the bowden tube....

**Comment by InsanityAutomation** [comment]
Some machine have the sensor mounted by the spool quite a bit away from the extruder. Even in the case of 3 or 4mm feed allowed, it still works as a debounce for finicky sensors.
