### ISSUE TITLE
UBL +  tool change = HOTEND_OFFSET_Z doesnt work

### ISSUE THREAD

**Issue by alexxy** [MarlinFirmware/Marlin#10302]
Hi all!

Even after recent updates to UBL + tool change code HOTEND_OFFSET_Z doesnt work. 
In my case i'm using dondolo like extruder with tool change. HOTEND_OFFSET_Z = -0.6, so i assume that if i set it correcly then it should work just with T0 T1 switch. 

However it seems it doesnt metter what HOTEND_OFFSET_Z value set, but T1 starts print only since Z=0.6.

**Comment by GMagician** [comment]
I confirm this issue but is not related to ubl.

I see 2 strange things:
1) Z raises correctly (0.3mm more to avoid workpiece collision)
2) It moves correctly XY to new position (displayed position doesn't change and it's ok) and raises again Z by 1mm (but is not required since in point 1 it already raised more then required tool offset)
3) Z lowers correct amount but displayed position is different and it shouldn't

**Comment by alexxy** [comment]
@GMagician I'm testing your change... :)

**Comment by alexxy** [comment]
@GMagician  seems like it works =) If there will be no more issues with UBL

**Comment by GMagician** [comment]
that's good. Now I refine it and make a PR for 1.1. Thanks for testing

**Comment by alexxy** [comment]
I'll report another issue if i find it
