### ISSUE TITLE
[2.0.x] unified utf8 font

### ISSUE THREAD

**Issue by yhfudev** [MarlinFirmware/Marlin#10429]
### Description
The fonts used for the graphic display were mixed with different size and style. The next figures shows the differences:

![font-diff-2](https://user-images.githubusercontent.com/4012731/38787003-8a5a2d4c-40f9-11e8-8ff5-ab533d21ea69.png)

### Suggestion
The font file need to be re-designed to fulfill support for the language data files.
There's no single font file can cover all of the charset to used in the firmware, one of fast solution is to merge multiple fonts files with similar style and size to a near complete font file.

The 6x12.bdf which is in public domain is a good candidate, it has similar style to our current used font, and covers most of western characters. It also would be nice to merge with WQY 9pt bitmap to cover all of current supported language.

**Comment by rmoravcik** [comment]
I just tried 6x12.bdf font on PR 10417 and yes indeed, this font looks very similar to the font that is present 1.1.x branch. Only number 0 looks better in 1.1.x, but that's my personal opinion.

I had to also change value of TALL_FONT_CORRECTION from 1 to 0, because menu with 5 items didn't fit on screen using 6x12.bdf font.

Here are some pictures from bugfix-1.1.x (left side) and PR 10417 + 6x12.bdf font (right side)

![img_20180416_155120](https://user-images.githubusercontent.com/2954118/38815149-8b22cb22-4193-11e8-9eeb-b3553493e0b6.jpg)
