### ISSUE TITLE
TMC2130 X axis stepper broken after update to latest bugfix-1.1.x.

### ISSUE THREAD

**Issue by chrisqwertz** [MarlinFirmware/Marlin#10456]
### Description

updating from 69c993092bf3e2efb89d0f61190594ebea4d0e53 to https://github.com/MarlinFirmware/Marlin/commit/df6becfb076cffbcdd42fb4509be8c077a3a659f broke my X-axis stepper.

### Steps to Reproduce

after updating, issuing a move command on the X-axis will move the X stepper only a few mm and will subsequently block all other move commands, even on the other axes. When I then try to disable the stepper I get a busy processing in the terminal which repeats and cannot be escaped anymore, except for a reset.

#### Additional Information

Checking the TMC debug output I can see that stepper registers have changed between boot and a attempted x-axis move.

Included 2 zips with configuration.h, configuration_adv.h and pins_ramps.h, one with the working old configuration and the other one with the new configuration, which doesn't work anymore.

[new_broken.zip](https://github.com/MarlinFirmware/Marlin/files/1927232/new_broken.zip)
[old_working.zip](https://github.com/MarlinFirmware/Marlin/files/1927233/old_working.zip)

**Comment by thinkyhead** [comment]
A lot of changes have been made since January. Can you find a more recent commit where it still works for you? The `<>` links on the commits page https://github.com/MarlinFirmware/Marlin/commits/bugfix-1.1.x will take you to the page where you can download the ZIP archive of the commit. See if you can find a commit-point from mid-March that is still working, and then see if you can find one after that which is broken.

Don't forget to issue M502, M500 after every install.

**Comment by chrisqwertz** [comment]
Cannot reproduce issue anymore, everything works as it should. Maybe I missed M502 & M500.
