### ISSUE TITLE
(Malyan) Monoprice firmware / configurations

### ISSUE THREAD

**Issue by LotDev** [MarlinFirmware/Marlin#10552]
In the license it states, “Marlin is published under the GPLv3 license because we believe in open development. The GPL comes with both rights and obligations. Whether you use Marlin firmware as the driver for your open or closed-source product, you must keep Marlin open, and you must provide your compatible Marlin source code to end users upon request.” 

This all meaning that anyone that uses and modifys the marlin firmware must post their source code but Monoprice yet uses Marlin but does not put out the source code for the 3D printers. This is a huge violation of the license terms of Marlin. I myself had tried 2 times to get them to send the source code but instead they never replied, but did send a confirmation email saying they received it. So please, makers of Marlin try to get them to release the firmware for their 3D printers (maker select Plus) and distribute it to us by a suit or settlement.

**Comment by boelle** [comment]
yet better, dont by their printers :-D

**Comment by thinkyhead** [comment]
![image](https://user-images.githubusercontent.com/698003/39390458-5ac0ebba-4a5a-11e8-88de-96c5b40845c3.png)

**Comment by jslay88** [comment]
Nice, I could definitely use this to validate between my custom FW

**Comment by thinkyhead** [comment]
I will get a copy from Sebastien tomorrow. I also have configs for the Monoprice Select mini from https://github.com/asantoni/marlin-monoprice-select-mini which will be added to the example configs pretty soon.

**Comment by xC0000005** [comment]
Those configs look right for a V1 and later-run V2s.

**Comment by thinkyhead** [comment]
@xC0000005 — When we add them to the examples, how should we label them?
I'm thinking just putting them into the folder `Monoprice/select-mini/`
but maybe `Monoprice/select-mini/V1/` is better, at least initially.

**Comment by xC0000005** [comment]
This is an interesting intersection of naming and hardware. Malyan is the company who manufactures the Monoprice Select Mini. The MP Select Mini is a rebrand (as is the Prima Creator, and a few more). The config files we have in Marlin 2.0 for the Malyan M200 are literally mine for running on the stock hardware (STM32F103 version). 

These new config files, on the other hand, are for a common operation - replacing Malyan’s sometimes-flaky board with a RAMPS stack. I tend to think they belong under the Malyan/M200 directory (perhaps a Ramps subdir?), but this is a case where the rebrand is the better known name, so perhaps Monoprice/select-mini makes more sense - that’s where people will think to look. 

The V1s are largely uniform and a single config works for every stock one I’ve encountered.  The V2s, on the other hand, have at least three variants with different steps per mm, stepper inverting, and (!) main CPU.

If Marlin were to have example configs for everything, it would need to split them out as:
RAMPS/V1
RAMPS/V2
STM32Fx/V1
STM32Fx/V2

Even then, getting the exact right config will require some testing, since the user may not know which version of the V2 they have.

**Comment by thinkyhead** [comment]
Too many variants. Sometimes we'll add some lines to a single config to select among variants. That might be the way to deal with these.

**Comment by xC0000005** [comment]
That’s what I did for the existing ones - if you search for V1 and V2 in that config, I have notes in there for people using it.

**Comment by xC0000005** [comment]
A simpler way to approach this would be to add a comment to the existing malyan M200 configuration file noting that you can change the motherboard to RAMPS and change the display type to do this.

**Comment by boelle** [comment]
@LotDev i think we can close this one since the firmware was released

@thinkyhead am i right?

**Comment by LotDev** [comment]
@boelle yes!
