### ISSUE TITLE
PlatformIO & teensy20 boards - does it work?

### ISSUE THREAD

**Issue by Bob-the-Kuhn** [MarlinFirmware/Marlin#10606]
I was playing with PlatformIO & tried to download my TEENSYLU.  To my surprise the Teensy download ICON popped up and then immediately disappeared.  No chance to actually do the download.

This might be because I had managed to blow away the original teensy bootloader in my card and had to flash it with another.

Could someone try to upload their board via PlatformIO?

5DPRINT
BRAINWAVE
BRAINWAVE_PRO
PRINTRBOARD
PRINTRBOARD_REVF
SAV_MKI
TEENSY2
TEENSYLU

----

FYI - there's a new method that allows you to upload your board **using only 2 or 3 mouse clicks**.  It's documented in the latest [docs WIKI](http://marlinfw.org/docs/basics/install_platformio.html).

**Comment by fiveangle** [comment]
PlatformIO does not know about the bootloader on the specific Teensy20pp based printer control boards, so unless you have a board made with an actual Teensy2.0++ device from Paul (none that I am aware of) uploading using PIO will never work on any of them since PIO will only try to flash teensy targets with the assumption they have Paul's Halfkay bootloader loaded, which I think is pretty much none.

Correct method is to compile then flash the hex with the appropriate tool for your bootloader.  For Printerboard RevF (DFU boot loader by default from Printrbot Co.) connected to Raspberry Pi for example:

1. jumper the boot jumper
2. punch reset button on board
3. `lsusb` (confirm connected board appears as DFU device)
4. `sudo dfu-programmer at90usb1286 erase`
5. `sudo dfu-programmer at90usb1286 flash Marlin.hex`
6. remove boot jumper
7. depress reset button on board
8. drink 🍺 

For Windows, use the Atmel FliP utility.

-=dave

**Comment by Bob-the-Kuhn** [comment]
I'm getting an education.  I had **assumed** that all the AT90USB boards used the Teensy download tool.  

My goal is to automate the PlatformIO build & download process for the mentioned boards.  Any info on the correct download tool and/or  PlatformIO environment would be much appreciated.

**Comment by Bob-the-Kuhn** [comment]
Do all the boards come with a DFU bootloader?

I have an HID bootloader on my Teensylu.  Can you point me to a useable DFU bootloader I can flash to my board?

Once I get my board updated I can start to play and have some confidence it applies to this class in general.

**Comment by fiveangle** [comment]
All [Printrboard](http://reprap.org/wiki/Printrboard) Rev D and newer from Printrbot Co. absolutely come with DFU bootloader from the factory and so is likely present on 99% of all Printrboards since the bulk of users never venture into burning bootloaders via the ISP interface except when being forced to (like with Creality melzi boards that don't have a bootloader, etc).

I believe to burn the Atmel official DFU boot loader you need to register and download Atmel Studio from Atmel directly and burn using it (warning, it's literally gigabytes of bloat).  Here are instructions for doing this with the Uno, but AT90USB1286 should be same process and Atmel Studio should program the MCU with the correct bootloader for the target (DFU in the case of the AT90USB1286):

https://startingelectronics.org/tutorials/arduino/arduino-uno-burning-bootloader-avr-studio/

Alternatively, you may try and burn the DFU boot loader hex from [Sam Lin's blog](http://blog.lincomatic.com/?p=548) using the usual utilities, but I haven't confirmed if the DFU boot loader hex he has for download is the genuine one or not and have never tried the hex myself.  Be careful of Sam's content on that old post as I'm not sure it's 100% accurate, but is still useful.

Any firmware flash instructions that include using the Atmel FliP utility mean that board uses the Atmel default DFU bootloader, so looks like [5DPrint does](https://bitbucket.org/makible/5dprint-firmware/wiki/Flash%20Instructions).

[Brainwave](http://reprap.org/wiki/Brainwave), [SAV_MKI](http://www.reprap.org/wiki/SAV_MKI), and [Teensylu](http://reprap.org/wiki/Teensylu) apparently use the CDC boot loader by default according to the RepRapWiki.

Good luck Bob !  Let me know if you run into any craziness…

-=dave

**Comment by Bob-the-Kuhn** [comment]
> Let me know if you run into any craziness…

I resemble that remark!  🙂🙂🙂🙂

Some progress.

I was able to download the At90USB1286 DFU bootloader from the Microchip website and burn it to my Teensylu.  I was then able to program it via the Linux commands that Dave provided.  I was not able to program it via PlatformIO.

The Brainwave_PRO that I have was NOT found by the dfu-programmer.

As best I can tell PlatformIO can't program any of the AT90USB boards.  The Teensy20 environment is the only one that officially supports the AT90USB but it won't download.  

The standard Atmel AVR platform in PlatformIO will compile the AT90USB1286 but it's not on any of the 500 supported boards so there's not a nice way of programming them.

----

CDC bootloader
- BRAINWAVE
- BRAINWAVE_PRO
- SAV_MKI
- TEENSYLU

DFU/TeensyDuino bootloader
- TEENSY2.0++
- Printerboard (except possibly for some early ones)
- PRINTRBOARD_REVF

Unknown bootloader
- 5DPRINT

**Comment by Bob-the-Kuhn** [comment]
I have PlatformIO generating images for the Brainwave_PRO board.  

If I upload them via the USBtinyISP and AVRDUDUE they run.

If I upload them via the bootloader and AVRDUDUE they **don't** run.  Dumping the memory and the fuses (again via AVRDUDE) shows that everything is the same.

ideas?

**Comment by thinkyhead** [comment]
@whosawhatsis — Any idea about this??

**Comment by whosawhatsis** [comment]
@thinkyhead I've never used PlatformIO. My boards have a CDC bootloader, and I use a version of the Teensy board definition that is slightly modified (just enough to customize the device identifiers).

Last time I tried, something in Marlin was failing to compile for the AT90USB1286. I've been meaning to see if it's fixed, but applying the necessary modifications to a fresh pull takes time I haven't had to spare recently.

**Comment by Bob-the-Kuhn** [comment]
Sounds like you create the image using the Teensy support in the Arduino IDE.

How do you upload the image?

I'm using AVRDUDE and the AVR109 protocol to do the upload.

**Comment by fiveangle** [comment]
> The Brainwave_PRO that I have was NOT found by the dfu-programmer.

Which is expected, as it uses the CDC bootloader (which you already realized :smile:)

> Unknown bootloader
> 
> 5DPRINT

As I mentioned above, according to 5DPrint themselves, they use the DFU bootloader: https://bitbucket.org/makible/5dprint-firmware/wiki/Flash%20Instructions

> I'm using AVRDUDE and the AVR109 protocol to do the upload.

That should work [according to the LUFA CDC documentation](https://w0.dk/~chlor/lufa/Bootloaders/CDC/Documentation/html/): 

> To load a new HEX file with AVRDude, specify "AVR109" as the programmer, with the allocated COM port. On Windows platforms this will be a COMx port name:
> 
> avrdude -c AVR109 -p at90usb1287 -P COM0 -U flash:w:Mouse.hex
> 
> On Linux systems, this will typically be a /dev/ttyACMx port name:
> 
> avrdude -c AVR109 -p at90usb1287 -P /dev/ttyACM0 -U flash:w:Mouse.hex
>
> Refer to the AVRDude project documentation for additional usage instructions.

-=dave

**Comment by fiveangle** [comment]
Hey Bob, if you're in there compiling for BRAINWAVE_PRO anyway, maybe do a quick test on the kossel pro example config ?  It wasn't compiling when I was going through all the configs, and not sure if it was ever resolved:   https://github.com/MarlinFirmware/Marlin/issues/8795

-=dave

**Comment by Bob-the-Kuhn** [comment]
I was able to compile the example configuration by changing the pins_BRAINWAVE_PRO.h file.

The problem was that the file only had one Z endstop (Z_STOP_PIN) but the configuration used Z_MIN for the Z_MIN_PROBE and Z_MAX for homing.  I just selected Z_STOP and added Z_MIN and Z_MAX pins.

**Comment by Bob-the-Kuhn** [comment]
Here's a link to the [latest version](https://www.dropbox.com/s/465l6034bjovjeb/Marlin-Bob-2_final_C.zip?dl=0).

CDC & DFU compile just fine.

DFU downloads reliably.

CDC downloads are still a problem.  Smaller images download but don't run.  Larger ones blow away the bootloader.

**Comment by Bob-the-Kuhn** [comment]
Finally able to download to the CDC bootloader cards.

I had to go back to an older version of AVRDUDE.


The latest one was getting confused at the 32K boundaries and leaving gaps in FLASH.
