### ISSUE TITLE
[FR] Thermocouple options for heated bed

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#10600]
i just wonder why this is not an option?

if it has just never been thought off what would i need to change to test it out?

**Comment by Iamturbo1978** [comment]
I have thermocouples for both my hotend, and my bed. I just changed 
`#define TEMP_SENSOR_BED 0` to `#define TEMP_SENSOR_BED -1` to work with my azteeg x3 pro controller. And I changed the bed pin to what thermocouple amplifier I am using for the bed.

**Comment by boelle** [comment]
i use  -3 : thermocouple with MAX31855 (only for sensor 0)

and i wanted to use that on the bed also

**Comment by boelle** [comment]
i know it's a bit overkill for the bed, but i could as well do the bed while i have to add wires for the hotend

**Comment by thinkyhead** [comment]
> I just wonder why this is not an option?

No demand.

I can posit some rationales why it's better not to use a MAX thermocouple for the bed.
- The bed temperature range is well within what a simple bead thermistor can handle, so it's somewhat wasteful to use a high temperature thermocouple for the bed.
- If one chooses to use a thermocouple, an ADC-amplifier-based thermocouple (_e.g._, AD595) is preferable because it takes almost no time to read, whereas the SPI / shift-register interface requires a hard loop with µs delays to acquire the temperature. Since this modal loop swallows up valuable computation time, shift-register-based thermocouples are generally not recommended unless they are actually needed.

**Comment by boelle** [comment]
I guess the waste depends on the person, I got a great deal on the max
boards as they where the last ones in stock. Got 4 of them

And got the cartridge type thermo couple and the normal one from e3d, that
will take a bit longer to get as it's not local

I picked the max chip as it's digital and I assume a bit more immune to
electrical noise from fan wires and the power wires

**Comment by boelle** [comment]
what are the downsides that computation time are used to read the max chip?

and how does it compare to that it also takes time to convert an analog value to digital?

**Comment by thinkyhead** [comment]
> what are the downsides that computation time are used to read the max chip?

Reduced performance while the SPI loop blocks all other activity.

> and how does it compare to that it also takes time to convert an analog value to digital?

The temperature timer starts the ADC, then returns back to the main loop. It just picks up the ADC result on the next entry to the temperature timer.

**Comment by boelle** [comment]
> Reduced performance while the SPI loop blocks all other activity.

How would the avg. user experience this?  a bit slower printing?

what code changes would be needed to get the thermocouple for the bed? i could test it out and see if i notice anything. Just need to get the filament unload and load thing in place first

**Comment by thinkyhead** [comment]
> what code changes would be needed to get the thermocouple for the bed

Code changes I'm disinclined to pursue right now, given all the other issues we have on the list. Maybe you can hire someone to do this. Be sure to pay them well!

**Comment by boelle** [comment]
no problemo

i will prepare for it thou since i have all the parts at hand and i need to remove the ramps etc to mod/hack in the wires needed for the max board on the hotend

**Comment by boelle** [comment]
closing this one as i could not get any thermocouples that actually work

next comes that there is a max lenght to the spi bus that makes it near impossible to reach the bed

**Comment by Grogyan** [comment]
>
> SPI must be kept short!

And my understanding is that you have used only the E3D thermocouples?

**Comment by boelle** [comment]
yes

**Comment by Grogyan** [comment]
Can you please, if possible, use a none cartridged thermocouple and see if
the readback works as intended when heating up and cooling down?

Ie a thermocouple with nothing but a piece of kapton tape over the bare
wires at the end when making contact to the heat source?

I believe the issue is down to E3D having a non electrically isolated
thermocouple, and where it has been welded to the inside of the can.

**Comment by boelle** [comment]
i got both the cartridge type and the welded tip from e3d.

and i have gone back to thermistors, the thermocouples was more trouble than good and i spent a month trying to get it to work

**Comment by Grogyan** [comment]
I find this quite upsetting.

Will personally look into the E3D thermocouple issue.

**Comment by boelle** [comment]
they worked fine when not "uncoiled" ie just out the plastic bag

and i found the max lenght for the spi wires so i could get to the hotend.

and when i uncoiled it i took very great care not to bend the wires or have any sharp turns. but still it got both shorts to vcc, shorts to gnd and open circuit on both types.

but e3d has shown customer service, first time they sorted through their entire stock to replace the cartridge type, and while i was wait for the replacement i did experiment with the normal type. and when both failed they replaced it all with a normal thermistor. i still have the 2 cartridge type and the normal one in an envelope in case they want to have a look at them

**Comment by Grogyan** [comment]
I am also gonna follow up on this,
Could you please send me photos of the thermocouple board, and each of the thermocouples that failed.

Before I start blaming anyone any further, I will need to have more data to look at and see if I can find a root cause.
Can either PM here or via FaceBook if that works for you.

**Comment by boelle** [comment]
Yep will do photos in the morning when light are better

but the thermocouple board is this one: https://www.sparkfun.com/products/13266

i took a 2 way screw terminal and broke it in to 2 and solder each screw clamp on the back side of the board to avoid shorts. i also tried to solder them in from the top side with as much distance i could but the outcome was the same.

the 2 thermocouples are these ones: https://e3d-online.com/type-k-thermocouple   and    https://e3d-online.com/type-k-thermocouple-cartridge

but yes photos will follow when light is good enough :-D

**Comment by boelle** [comment]
my own photos: https://photos.app.goo.gl/ahs3HArw1jTmaShh1
