### ISSUE TITLE
Strange UBL behavior

### ISSUE THREAD

**Issue by smoki3** [MarlinFirmware/Marlin#10643]
I updated my printer at the weekend to the actual 2.x branch from a Februar (also 2.x) build. 

Then I tried to redo my bed leveling. I started to regenerate the UBL mesh with a G29 P1.

But my printer is only probing **4 points**. On the old config build it was probing the whole bed. 

So is the behavior changed? Or is there a reason why its only probing 4 points?

Config file: https://pastebin.com/bssuC37e

**Comment by ManuelMcLure** [comment]
The probing logic has changed recently - it now takes into account MIN_PROBE_EDGE (10 in your configuration). MIN_PROBE_EDGE is a configuration setting that ensures that the probe doesn't check too close to the edge of the bed (inductive and capacitive sensors tend to be quite inaccurate if too close to the edge of the bed). Since your MESH_INSET is smaller than MIN_PROBE_EDGE it can't probe the points closest to the edge of the bed and you only get the four middle points.

If you have a sensor like the BLTouch you can reduce the value of MIN_PROBE_EDGE since those do not have any problems probing the very edge of the bed. If you have a capacitive or inductive sensor it's not a good idea to reduce MIN_PROBE_EDGE - instead either increase MESH_INSET to 10 (this will reduce your printing area) or increase the number of points in your mesh. The latter is probably best - you still won't be able to probe the very edge, but you can use G29 P3 to fill in the unprobed spots and fine tune them with G26 and G29 P4. I use a 10x10 grid with MESH_INSET of 2 and MIN_PROBE_EDGE of 15 with this method.

**Comment by smoki3** [comment]
So now I am confused. You said if my mesh_inset is smaller than the min_probe_edge than I only get the four points. 

But you are using Mesh_inset 2 and min_probe_edge 15. So you also get only the four point? Because you inset is the smaller value?

**Comment by Roxy-3D** [comment]
Do a G29 W   It will tell you the locations of all the mesh points.   (And where the edges of the bed are)    That should help you figure out what you are seeing.

**Comment by ManuelMcLure** [comment]
I don't get the points nearest the edge probed - only the points in the middle. I use a 10x10 grid so I actually end up with 64 points probed - the 8x8 grid in the middle of the bed. I use G29 P3 after the G29 P1 so that UBL fills those points in with reasonable values and then use G26 and G29 P4 to fine tune the mesh.

**Comment by Roxy-3D** [comment]
Can you post a G29 T W      That will show us what it probed and where it thinks the mesh points are located.

**Comment by smoki3** [comment]
This is the G29 T W answer: https://pastebin.com/VsuWjZMK

**Comment by Roxy-3D** [comment]
This is a 5 x 5 mesh?    And all points are present?

**Comment by smoki3** [comment]
So it only probe 4 points. Maybe this because the mesh fill?

**Comment by Roxy-3D** [comment]
```
Recv: GRID_MAX_POINTS_X  5
Recv: GRID_MAX_POINTS_Y  5
Recv: MESH_X_DIST  48.50
Recv: MESH_Y_DIST  46.00
Recv: X-Axis Mesh Points at: 8.000  56.500  105.000  153.500  202.000
Recv: Y-Axis Mesh Points at: 8.000  54.000  100.000  146.000  192.000
```

**Comment by smoki3** [comment]
But shouldn't it probe 5x5 (25) points?

**Comment by smoki3** [comment]
On my previous firmware it was probing many many point on the whole bed. no only 4 points

**Comment by thinkyhead** [comment]
Whenever there are homing or leveling issues, we now ask everyone to follow a standard procedure to gather more information so that we're not just taking stabs in the dark. Here is the boilerplate:

- Download Marlin `bugfix-1.1.x` or `bugfix-2.0.x` to test with the latest code.
- Enable `DEBUG_LEVELING_FEATURE` and `M114_DETAIL` and re-flash the firmware.
- Connect to your printer from host software such as Cura, Printrun or Repetier Host.
- Issue the command `M111 S247` to enable maximum logging.
- Perform a `G28` to do your standard homing procedure.
- Do a `G29` to probe the bed.
- Copy the log output into a **.TXT file** and attach it to your next reply.

**Comment by smoki3** [comment]
If comment out  `min_probe_edge` it works as expected

**Comment by thinkyhead** [comment]
Interesting! Same if you set it to 0, I expect. The purpose of that setting is to prevent probing beyond certain bounds, even if your grid happens to be there. So it all makes sense.
