### ISSUE TITLE
[advise help] RRD Fan Extender, protected pins and Gcode

### ISSUE THREAD

**Issue by Amachete** [MarlinFirmware/Marlin#10703]
Hello

I am trying to update to Bugfix 2.0, and add the RRD Fan extender, which works with pin 11 and 6 on a RAMPS 1.4. I have not tried on 1.1.

I update the configuration. and configuration_adv.h with the following:
```cpp
#define CONTROLLER_FAN_PIN 11

#define E0_AUTO_FAN_PIN 6
```

I know perfectly that those pins work, and the fans spin right, when I tried an small program with arduino and RAMPS, just pullin up those pins.

Now I am trying to "try"  if these pins work on Marlin...with the following GCODE:
```gcode
M42 P11 S255
M42 P6 S255
```
And Marlin says:
```
Error: Protected Pin
```
on both cases

The question is:

Is there any Gcode to try these fans? How can I try and see if the fans are running right without burning anything.
```cpp
#define CONTROLLER_FAN_PIN 11  to cool  RAMPS Board

#define E0_AUTO_FAN_PIN 6 to cool the extruder.
```
Let me know if you need more information, I have been reading and seeking how to do it myself, I even dig in the marlin code, but is beyond my knowledge.

Thank you for your help

**Comment by thinkyhead** [comment]
Since you've assigned the pins to protected function, you can't set them with `M42`. To test `E0_AUTO_FAN_PIN`, heat up your extruder. To test the `CONTROLLER_FAN_PIN` do a move with `G1`.

If you must test them with `M42` don't assign `CONTROLLER_FAN_PIN` or `E0_AUTO_FAN_PIN` to any pins. Leave them set to -1.
