### ISSUE TITLE
Possible TMC2130 overheat?

### ISSUE THREAD

**Issue by MarioStoilov** [MarlinFirmware/Marlin#10733]
I sometimes get a driver error (randomly) when printing. Sometimes it's 30 minutes into the print, sometmes it's 30 hours into the print (DAMN IT!!!!).

The last time I got an error, I looked at the logs (attached as images, because octoprint doesn't handle copy-paste very elegantly) and the only troubling thing I'm noticing is the otpw, which my understanding is that it should not trigger an error, or am I wrong?
[Logs.zip](https://github.com/MarlinFirmware/Marlin/files/1998829/Logs.zip)

**Comment by thinkyhead** [comment]
Correct. It shouldn't abort just for optw (at least not in the current bugfix versions). If you disable `STOP_ON_ERROR` then it won't abort for _any_ error.

Be sure to test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch. If you still get freezes with `STOP_ON_ERROR` disabled, then we should look deeper.

**Comment by marcio-ao** [comment]
We had so much overheating issues with the TMC2130 that we ended up having to use thermal tape and a metal block across the back of our driver chips to conduct heat from the drivers to the controller chassis.

Our experience is that the TMC2130 are certainly the hottest thing in 3D printing right now...

**Comment by Garyr14** [comment]
Hello,
I'm relatively new to this, so please excuse my ignorance...  My MKS GEN V 1.4 with TMC2130's on all axis's was working fine until I removed the bed to re-solder the thermistor wire.  Ever since, I've been getting layer shifting on Y axis only.  I've done just about everything troubleshooting wise that I can think of including reverting back to Marlin 1.1.6 (was on 1.1.x bugfix), I've swapped the drivers, wires and motor.  I thought it was the cable catching but that does not seem to be the problem. 

I am curious about the temperature issue.  I've been measuring the temperature using a non-contact digital laser infrared thermometer.  Temps range from 26-33 c max when running.  Motors are lower.  I'm only using heatsinks on the drivers.  I'm curious as to why I'm not having the overheating problems that everyone seems to have with the TMC2130's.  I'm running them between 50 - 70 mms.  Am I taking the temperature right or is there another way to do so?  Again, the only shifting I'm having is on the Y axis.  Everything else is fine.

If there is a more appropriate place to post this, please let me know.

Thanks

**Comment by thinkyhead** [comment]
> Ever since, I've been getting layer shifting on Y axis only

@Garyr14 — Please join the party at #10446. I'm not sure you have the same issue, but there's a lot of speculation about what's going on, most especially with the Y axis.

**Comment by MarioStoilov** [comment]
Well, I'm on the latest bugfix branch and there is SOME improvement. There is no longer an error, but the extruder (the problematic driver) starts skipping steps. I am using a geared extuder, so it's doing more work than usual.

I'll try decreasing the current as I didn't need that much torque and see what happens.

**Comment by boelle** [comment]
@MarioStoilov do you have heatsinks mounted with thermal tape? do you have a fan blowing air at the drivers?

**Comment by MarioStoilov** [comment]
Yes, a 120mm fan and heatsinks on all drivers

**Comment by boelle** [comment]
did it solve this issue?

**Comment by MarioStoilov** [comment]
No, it did not.

As I said, the extruder is geared (titan with a gear ratio 1:3) which means it's doing 3 times more work than a normal extruder would, so I think that is the main problem

**Comment by boelle** [comment]
i have same extruder (from e3d) and a 80mm fan do work fine or me

what version are you running?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
