### ISSUE TITLE
2.0 BUG? #define FAST_PWM_FAN - not compiling

### ISSUE THREAD

**Issue by rockman256** [MarlinFirmware/Marlin#10782]
Ramps FD V1
Fan Pin  - 2
```
sketch\src\module\temperature.cpp: In static member function 'static void Temperature::setPwmFrequency(pin_t, int)':

sketch\src\module\temperature.cpp:1385:36: error: 'digitalPinToTimer' was not declared in this scope

       switch (digitalPinToTimer(pin)) {
```
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2019629/Marlin.zip)

**Comment by Bob-the-Kuhn** [comment]
The short term fix is to disable **FAST_PWM_FAN** in Configuration.h.

I'll need to investigate further on what DUE is capable of and what we've implemented.

**Comment by Bob-the-Kuhn** [comment]
FAST_PWM_FAN is only supported by the 8 bit AVR CPUs.  There are no plans to support it on the 32 bit CPUs.

I'll add a sanity check for this.

**Comment by rockman256** [comment]
I want to explain the problem of PWM signal and turbo fans.
https://www.aliexpress.com/item/Original-Sunon-EF50151B1-C02C-A99-5015-12V-1-92W-50-50-15mm-Ultra-Quiet-Humidifier-Turbo/32820917468.html
With direct connection to the source, the fan starts smoothly from 4 volts.
But when you connect to the PWM signal - it either does not work, or works at full power at 250.
I tried to use #define FAN_SOFT_PWM - the same result.
So I thought that #define FAST_PWM_FAN will help to solve this problem.

**Comment by ghost** [comment]
@rockman256 If your board is Arduino Due, there is a way to change the PWM frequency without using FAST_PWM.

Change the `PWM_FREQUENCY` and `TC_FREQUENCY` in `variant.h` to the frequency you want to use.
Overwrite the variant.h and flash the sketch.
variant.h is usually in`C:\Users\%username%\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.11\variants\arduino_due_x`.

I have set the values of these two places to 20000.
This is because we want to use the air pump used for "Berd Air" at 20 kHz outside the audible range.
I do not know if changing this setting will cause another problem.
But for now, my Arduino Due and Ramps-FD V 2.2 are working without problems.

**Comment by rockman256** [comment]
Another Chinese turbo fan also works fine, but it's cheap and vibrates strongly.

**Comment by rockman256** [comment]
change to 900 Hz - it is optimal worked.

**Comment by nonodu74** [comment]
Hi rockman256,

Which parameter did you change to 900Hz ?

**Comment by nonodu74** [comment]
Hi rockman256,

Where do you change frequency to 900Hz ?
Does it affects other components on the board ?

Thks
