### ISSUE TITLE
I can't make bilinear bed autoleveling work correctly 

### ISSUE THREAD

**Issue by Loooooouuuuu** [MarlinFirmware/Marlin#10783]
Hello ! 

I'm using an Anet A8 with a MKS gen 1.4 board with TMC2130 stepper drivers and a BLTouch. It seems to work correctly, but when I print after a G28 & G29, it looks like it doesn't compensate at all. The prints are uneven :/

Here's my configuration files : 

https://zerobin.net/?c227086df040487f#aIwMxO1OHOpDUchnKkY97z6U+7VyD/1yMx7/Ni/jThA=

https://zerobin.net/?a43ffc7dcba61515#ILtaWg/OB6Cmo/8Nk4VdbaSkYkCNiYx/DGSpH8TTDM0=

I tried with multiple probing, more probing points, ... My bed should be even (It's an ultrabase glass & bed)

I didn't try 2.0.0 (Should I ? Would it work well with an MKS gen 1.4 ?)

Thanks a lot for your help !

**Comment by thinkyhead** [comment]
Try the current `bugfix-1.1.x`.

Also, instead of jumping straight into printing, do some basic movement with leveling enabled and see how it behaves. If you see a certain pattern of misbehavior, please describe it.

You can also set exaggerated values using the `M421` command to see if bed leveling moves in the right direction and by the right distance based on the points you set.

With `DEBUG_LEVELING_FEATURE` enabled, you can do `G29 Q` to query Marlin about the current position and find out how much compensation is being applied there. If you find unexpected values, we'd like to know about that.

**Comment by Loooooouuuuu** [comment]
Hey, thanks for your help ! 

It looks like adding the G29 command to the print's gcode (and not do it before, then start the print) seems to work. I thought doing G29 before the print was the same.

Thanks again !

**Comment by ManuelMcLure** [comment]
> It looks like adding the G29 command to the print's gcode (and not do it before, then start the print) seems to work. I thought doing G29 before the print was the same.

If your gcode has a `G28`, that will usually disable bed leveling and you need to do a `G29` after the `G28`. You can change this behavior by setting `RESTORE_LEVELING_AFTER_G28`.
