### ISSUE TITLE
E Maximum Acceleration not working

### ISSUE THREAD

**Issue by Phaelz** [MarlinFirmware/Marlin#10825]
Hi all.

I am playing with the maximum settings on my printer and I've come to realize that E Maximum Acceleration is not working as I expected and as the other axis.

I am using the M code M201, that modifies Maximum Acceleration on each axis. When I modify the values on X, Y and Z the speed is limited by the value. But not for E.

Then I used M204, that modifies Acceleration on moves (Print, Retract and Travel), and then the E speed is limited. Only by M204, but not by M201.

Is it correct?

**Comment by thinkyhead** [comment]
The factor set for E by `M201` does get applied in the planner along with the other axes.
```cpp
// Limit acceleration per axis
if (block->step_event_count <= cutoff_long) {
  LIMIT_ACCEL_LONG(A_AXIS, 0);
  LIMIT_ACCEL_LONG(B_AXIS, 0);
  LIMIT_ACCEL_LONG(C_AXIS, 0);
  LIMIT_ACCEL_LONG(E_AXIS, ACCEL_IDX);
}
else {
  LIMIT_ACCEL_FLOAT(A_AXIS, 0);
  LIMIT_ACCEL_FLOAT(B_AXIS, 0);
  LIMIT_ACCEL_FLOAT(C_AXIS, 0);
  LIMIT_ACCEL_FLOAT(E_AXIS, ACCEL_IDX);
}
```
You could try adding debugging messages to the planner to see what's going on in your case.

`M204` should have a more visible effect, since it's the value that acceleration starts out with for E-only moves. The value for `M201 E` will probably only be evident if it is set very low, since E tends to move at a much slower rate than other axes do.

**Comment by boelle** [comment]
@Phaelz did you try what thinky suggested?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
