### ISSUE TITLE
Y axis reversed.

### ISSUE THREAD

**Issue by klausbfrederiksen** [MarlinFirmware/Marlin#10824]
I use Marlin 1.1.8 on an I3. 
I have realized that my Y axis is reversed:

My endstops are in Xmin, Ymax, Zmin, and X_HOME_DIR -1, Y_HOME_DIR 1 & Z_HOME_DIR -1.
And I use USE_XMIN_PLUG, USE_YMAX_PLUG, USE_ZMIN_PLUG.

When I home X, it homes correct to the left. Homing Y moves buildplate to the rear. Again correct.
Here is the problem now: Having homed X & Y axes, position values are X=0 and Y=0.
I did expect Y to home at Y=0 in front of the buildplate.

If I do G28 x100 Y100, the extruder centers on the buildplate.
If I then do a G28 x0 y0, the extruder returns to the left, and rear of the buildplate.

Somehow the home position is at the rear of Y axis, and not the front.

Changing the endstop position to the front, do not change that Y=0 is at the rear.

Any suggestions to this problem?

**Comment by siana** [comment]
First off it generally makes sense to supply complete configuration files: the nature of unexpected issues is generally that they aren't where you're looking, so when you post just the snippets you're looking at, someone trying to help often has as little to go on as you are.

That the movement in positive coordinate on Y induces a movement in the opposite direction is an indication that INVERT_Y_DIR for the stepper direction is set wrong.

You can use M206 together with EEPROM save to shift the origin of coordinates from the endstop position.

That being said, i'm surprised M502 resets home_offset to zero rather than to the preprocessor-computed values of X_HOME_POS and friends? In fact Y_HOME_POS appears to be completely unused except in one specific edge case of G29!

**Comment by thinkyhead** [comment]
If you have a moving bed with the endstop switch mounted at the back your `Y_HOME_DIR` should be -1.

Since `Y_HOME_DIR 1` moves the bed towards the back on `G28`, your Y axis is set to move in the wrong direction. You must either flip the plug connecting the Y stepper motor to the board, or change your `INVERT_Y_DIR` setting.

---
If you moved the Y endstop switch to the front of the machine, your `Y_HOME_DIR` would need to be 1, and your `Y_HOME_POS` would need to be 200. Then, homing with `G28` should bring the bed forward.

In both cases, it's apparent that you need to flip the plug connecting the Y stepper motor to the board, or change your `INVERT_Y_DIR` setting.

**Comment by klausbfrederiksen** [comment]
It actually works (had to connect endstop to Ymin [USE_YMIN_PLUG]- thank you for the solution.
I find it to be a bit reversed :-) here is why. I have used this figure, as a guide https://3dprinting.stackexchange.com/questions/2593/how-does-the-home-position-work-on-a-prusa-i3-reprap-printer
From this, the Ymax is to the rear of the buildplate, not to the front.
I do not find the solution logical at all. But it works, so I am a happy man.
Stay Cool - I try to in 25 C

**Comment by thinkyhead** [comment]
> had to connect endstop to Ymin

If the endstop is in back of the moving bed, that is correct.
If you had a Z bed and an XY moving gantry, the Ymin endstop would be in front.

In both cases, Y=0 has the nozzle aligned to the front edge of the bed.

**Comment by sidhant** [comment]
@thinkyhead I reached this thread because I have the same confusion. Please help?

My config:
```
#define USE_XMIN_PLUG
//#define USE_YMIN_PLUG
#define USE_ZMIN_PLUG
//#define USE_XMAX_PLUG
#define USE_YMAX_PLUG
//#define USE_ZMAX_PLUG

// Invert the stepper direction. Change (or reverse the motor connector) if an axis goes the wrong way.
#define INVERT_X_DIR false
#define INVERT_Y_DIR true
#define INVERT_Z_DIR false

// Direction of endstops when homing; 1=MAX, -1=MIN
// :[-1,1]
#define X_HOME_DIR -1
#define Y_HOME_DIR 1
#define Z_HOME_DIR -1

// Invert the stepper direction. Change (or reverse the motor connector) if an axis goes the wrong way.
#define INVERT_X_DIR false
#define INVERT_Y_DIR true
#define INVERT_Z_DIR false

// Travel limits (mm) after homing, corresponding to endstop positions.
#define X_MIN_POS 0
#define Y_MIN_POS 0
#define Z_MIN_POS 0.5 //Disable software endstop beore moving to Z0 to allow this to happen
#define X_MAX_POS X_BED_SIZE
#define Y_MAX_POS Y_BED_SIZE
#define Z_MAX_POS 100

//#define MANUAL_X_HOME_POS 0
//#define MANUAL_Y_HOME_POS 0
//#define MANUAL_Z_HOME_POS 0
```

With this current config, when I home using Pronterface, I end up with the nozzle at X=0, Y = 120, Z=0.5.

```
SENDING:M503
echo:  G21    ; (mm)
echo:Filament settings: Disabled
echo:  M200 D1.75
echo:  M200 D0
echo:Steps per unit:
echo:  M92 X93.00 Y93.00 Z400.00 E97.00
echo:Maximum feedrates (units/s):
echo:  M203 X300.00 Y300.00 Z5.00 E25.00
echo:Maximum Acceleration (units/s2):
echo:  M201 X3000 Y3000 Z100 E10000
echo:Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
echo:  M204 P3000.00 R3000.00 T3000.00
echo:Advanced: Q<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> X<max_x_jerk> Y<max_y_jerk> Z<max_z_jerk> E<max_e_jerk>
echo:  M205 Q20000 S0.00 T0.00 X10.00 Y10.00 Z0.30 E5.00
echo:Home offset:
echo:  M206 X0.00 Y0.00 Z0.00
echo:Unified Bed Leveling:
echo:  M420 S0 Z10.00
Unified Bed Leveling System v1.01 inactive.
Active Mesh Slot: -1
EEPROM can hold 7 meshes.
echo:PID settings:
echo:  M301 P22.20 I1.08 D114.00
echo:Z-Probe Offset (mm):
echo:  M851 Z0.70
echo:Stepper driver current:
echo:  M906 X280 Y350 Z1000
  M906 T0 E1200
>>> G28
SENDING:G28
echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: processing
>>> M114
SENDING:M114
**X:0.00 Y:120.00 Z:0.50 E:0.00 Count X:0 Y:11160 Z:200**
>>> G28 X0,Y0
**SENDING:G28 X0,Y0**
echo:busy: processing
>>> M114
SENDING:M114
**X:0.00 Y:120.00 Z:5.00 E:0.00 Count X:0 Y:11160 Z:2000**
```

My Y-endstop is at the front of the Y-table, that is, if I push the table away from me all the way, it gets triggered. The endstop is plugged into the Y_MAX_PIN.

If I jog manually, the motor moves as expected. +Y move the table away from me (the way I think, the nozzle sees an increasing Y coordinate space below it). 

Why is my home position 0,120 with nozzle at left, front corner of bed. Executing a G1 F200 Y0, brings the bed all the way forward. With G1 F200 Y120, it pushes bed all the way back and engages the endstop switch.

Using Marlin-bugfix-1.1.x 

EDIT: I also used the same figure to understand as the OP posted link to. I think, I am realizing one small confusion. This is a Monoprice Select Mini. The switch is on the front such that the front inner lip of the bed triggers it. When looking at the Prusa picture, that would be equivalent to Y(MAX) switch as the figure indicates. 

Edit 2: **Nevermind**. I flipped everything back because I realized my endstop is NOT Y(MAX) as that crazy Prusa figure illustrates!! It was source of all confusion. Plugged Y endstop into Y_MIN, no `INVERT_Y_DIR false` and `Y_HOME_DIR  -1`. Works as intented.

**Comment by boelle** [comment]
@klausbfrederiksen 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by boelle** [comment]
@thinkyhead think we can close this one
