### ISSUE TITLE
Sensorless Homing CoreXY issue

### ISSUE THREAD

**Issue by smoki3** [MarlinFirmware/Marlin#10889]
Hi,
I have a problem with sensorless homing on my coreXY. 

After a reboot of the printer or firmware reset, on the first homing the printer crashes at the end positions and the motors are **losing** a few steps. After a few seconds the homing will **succeed** anyway.

After the first homing is finished, it is working as expected (no crashes).

Using TMC2130 on XY Axis on my RADDS board. 

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/2045957/Config.zip)

**Comment by thinkyhead** [comment]
We've recently updated the endstop code, so there are bound to be some glitches. Are you able to use the `ENDSTOP_INTERRUPTS_FEATURE` on your board?

**Comment by dw-0** [comment]
I have some issues with Sensorless Homing again as well. (no CoreXY but Prusa-Style-Printer)
Right now i am using commit `cbcb284` and didn't changed anything on my setup so far.
I get quite a decent amount of false positives and setting the Bump Sensitivity to a higher value doesn't affect anything but i can't really explain why the issue occurs.

When i do an initial homing of all axes, everything is fine, the nozzle parks at Z0 in the middle of the print bed. For testing purposes i then tried to home X alone. So i send a G28 X to the machine, Z raises a little bit and then nothing. X doesn't move at all. When i send a M122 i get this output:
```
Send: M122
Recv: 		X	Y	Z	E1
Recv: Enabled		false	false	false	false
Recv: Set current	670	670	670	670
Recv: RMS current	642	642	642	642
Recv: MAX current	905	905	905	905
Recv: Run current	20/31	20/31	20/31	20/31
Recv: Hold current	10/31	10/31	10/31	10/31
Recv: CS actual		20/31	10/31	10/31	10/31
Recv: PWM scale	117	68	67	63
Recv: vsense		1=.18	1=.18	1=.18	1=.18
Recv: stealthChop	true	true	true	true
Recv: msteps		16	16	16	16
Recv: tstep		1048575	1048575	1048575	1048575
Recv: pwm
Recv: threshold		79	79	658	276
Recv: [mm/s]		100.08	100.08	3.00	30.03
Recv: OT prewarn	false	false	false	false
Recv: OT prewarn has
Recv: been triggered	false	false	false	false
Recv: off time		5	5	5	5
Recv: blank time	24	24	24	24
Recv: hysteresis
Recv: -end		2	2	2	2
Recv: -start		3	3	3	3
Recv: Stallguard thrs	35	26	0	0
Recv: DRVSTATUS	X	Y	Z	E1
Recv: stallguard				X
Recv: sg_result		810	0	0	0
Recv: fsactive
Recv: stst		X	X	X	X
Recv: olb
Recv: ola				X
Recv: s2gb
Recv: s2ga
Recv: otpw
Recv: ot
Recv: Driver registers:	X = 0x80:14:03:2A
Recv: 	Y = 0x80:0A:00:00
Recv: 	Z = 0xA1:0A:00:00
Recv: 	E1 = 0x80:0A:00:00
```
I guess the `sg_result` of 810 for X is the indicator that stallguard kicked in in this case? Sometimes i get a value of only 4, sometimes of 860. So the value isn't always the same. As you can see i already cranked up the Bump Sensitivity to 35 (was 26 before - same as Y and Y is working flawless - X worked flawless before too).

When i send a M18 and disable the steppers, then i can home X alone and it works fine.
But as soon as i home all axes again and then try to home X alone, it stucks again.
Something there is triggering something :D 
My mechanics are fine, since it worked before, so that's not the issue (i even freshly oiled the bearings and the X-Rods to make it glide even smoother again).

I also activated the `ENDSTOP_INTERRUPTS_FEATURE` and tried again, no change. Still the same issue.

I hope this is the correct place for my issue? Maybe my issue is correlating to the initial issue?

**Comment by smoki3** [comment]
yes i am able to activate ENDSTOP_INTERRUPTS_FEATURE. It seems that this doesn't fix my crashes

**Comment by dw-0** [comment]
I guess my issue then is not correlated to yours hahaha :D

**Comment by smoki3** [comment]
https://photos.app.goo.gl/WrK6mUcAgC4QPuRR2

I made a short video to describe the issue. The first homing is the initial, the second after the initial.

You can see that after the first homing, there is no bump. The axis is moving against the endposition **and** loses steps

**Comment by thinkyhead** [comment]
It could be that the endstop hit state isn’t getting cleared after the initial hit, though we did attempt to patch that possibility just a couple days ago. I’ll take a closer look at the corexy endstop testing code-path and see if I can discern a logical flaw.

Give it a test both with and without quick-home to see if there’s any noticeable difference.

**Comment by smoki3** [comment]
So I just enabled quick home. Still the crashing

https://photos.app.goo.gl/cTgA6vD6AeKDwf3G3

**Comment by thinkyhead** [comment]
Sure, that was expected. I’ll scrutinize the new video to see if there are any clues about the issue I can discern in the behavior.

**Comment by thinkyhead** [comment]
In the second video the initial quick-home XY move is stopping way too soon. There must be a false trigger happening during that first XY move. That might indicate that the sensorless homing sensitivity is set too sensitive. The fact that it doesn’t trigger right away is telling.

But then the first video shows that non-quick-home works okay after the first funky homing, which is harder to make sense of.

As in the first video, does quick-home also work okay on a second homing?

Note that Marlin is responding this way because it sees endstops as triggered. Whether that’s due to an old hit-state bit not getting cleared, due to a floating pin, or due to oversensitive sensorless homing is still up in the air.

**Comment by thinkyhead** [comment]
Another thing you can test is to set `HOME_Y_BEFORE_X` and see what effect, if any, that has on the behavior.

**Comment by smoki3** [comment]
> As in the first video, does quick-home also work okay on a second homing?


Yes the second homing is fine again. But also this **weird** move on the Y axis. 
For me it doesn't looks like that the homing sensitivity is related to this because after is stop/short move on the Y axis, the y axis is homing fine anyway

**Comment by thinkyhead** [comment]
Well, the initial diagonal move on quick-home isn’t going to just cease on its own. Either it thinks it’s reached a distance of double the size of the axes (unlikely) or it’s reading one of the endstops as triggered (the only likely possibility).

**Comment by smoki3** [comment]
I will try tomorrow to increase the sensitivity.
Also will do an test with Hom_Y_Before_X. 

But anyway it's **weird** that it's working after the first homing

**Comment by thinkyhead** [comment]
Let’s get a closer look…

- Enable `DEBUG_LEVELING_FEATURE` and re-flash the firmware.
- Connect to your printer from host software such as Cura, Printrun or Repetier Host.
- Issue the command `M111 S247` to enable maximum logging.
- Perform a `G28` to do your standard homing procedure.
- Repeat the `G28`.
- Copy the log output into a **.TXT file** and attach it to your next reply.

Try this with quick-home first, since it has that “interesting” short XY move.

**Comment by smoki3** [comment]
Sorry for my late replay. I don't had time to test it. I will do it this week!

But I found out that when I home my X and Y axis separately (G28 X0 and G28 Y0) than everything is fine.

**Comment by smoki3** [comment]
this with `QUICK_HOME`:
https://pastebin.com/acwQXFx8

**Comment by smoki3** [comment]
this when I separately home X and Y axis:
https://pastebin.com/yLSDk4tq

**Comment by smoki3** [comment]
@thinkyhead  I tried to figure out I don't find what's going wrong

**Comment by thinkyhead** [comment]
We've patched an issue with sensorless homing that might help with this. Please test the latest `bugfix-1.1.x` or `bugfix-2.0.x` branch to see if it's working any better.

**Comment by smoki3** [comment]
Yeah it's working now
