### ISSUE TITLE
[Bugfix 1.1.x] Linear Advance 1.5 start/stop layer issue

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#10912]
I am trying to tune linear advance 1.5 but I keep getting an issue at the start and stop of the layer.  See attached pics of the calibration pattern (hard to see since I did it with black) and the benchy.  The benchy has a line down the hull, a line down the corner of the cabin (hard to see), and a line down the top pipe.  I am using a K value of 0.15 with looked the most uniform to me, however, it has a wide start and stop point.  

![20180528_003006](https://user-images.githubusercontent.com/21220408/40819428-90c408ae-654a-11e8-842e-c25d296b827e.jpg)
![20180531_230735](https://user-images.githubusercontent.com/21220408/40819432-9616d9e4-654a-11e8-8c50-ec17f82964fd.jpg)
![20180531_230839](https://user-images.githubusercontent.com/21220408/40819435-98d0f6e2-654a-11e8-9ead-4b62b458a90e.jpg)
![20180531_231159](https://user-images.githubusercontent.com/21220408/40819436-98ed1516-654a-11e8-9bfb-88482416e19c.jpg)

[3DBenchy gcode and Confg files.zip](https://github.com/MarlinFirmware/Marlin/files/2060868/3DBenchy.gcode.and.Confg.files.zip)

**Comment by Sebastianv650** [comment]
You will never be able to eliminate the seam completely. The reason why the seam is especially bad on the hull is because the start/stop point of the perimeter is placed on an overhang here. Not a smart choice from your slicer. When we start/stop a line, the printer always has to accelerate to or from speed = 0, meaning we are inducing more heat in this place. As overhangs tends to curl always, inducing more heat while accelerating makes it even worse.

The size of the start and stop points can be tuned by the retraction settings. Your goal should be to minimize the time the printer needs for retraction (or prime) between the line is finished and the travel move can start. There are mainly two ways to do this:
- increase retraction speed
- minimize retraction length.

**Comment by ghost** [comment]
Thanks for the info.  I had the slicer set to start in that location and forgot to change it.  Either way though,  if there is no corner (i.e. like a cal cube), then it is very hard to hide the seam.  I have tried for many hours to get a decent seam with LA and I cannot.  I either get bad blobs or holes (missing filament).  I have even tried bumping the K factor up/down by hundredth's with pretty much no difference in results.  Are others seeing this behaviors well?

**Comment by gloomyandy** [comment]
Are your results better or worse with LA than without?

**Comment by Sebastianv650** [comment]
Yes, a seam picture with and without LA would give some indication.
Looking at your config file, there are two things which will influence LA:
- Your e-jerk setting is extremly low (0.6mm/s). LA offsets the speed of the extruder during acceleration and deceleration to adjust the pressure, but your e-jerk setting only allows for a 0.6mm/s speed offset. This will result in very low acceleration values used as LA will throttle them down so it can do it's job using your jerk limits. This can definitly be the reason for your seam problems. Usualy an e-jerk of around 5mm/s is needed to adjust the pressure in real time without lowering acceleration. As you are also using quite low acceleration values, you can maybe also go with an ejerk of 2-3.
- 2670steps/mm is a unusual high value for e, this might overload the CPU with extruder ISRs using LA. If nothing else results in better seam, I would try lowering microstepping for the extruder to keep the value around 1000 or lower. There is no real reason to use such high numbers.

**Comment by boelle** [comment]
@X7JAY7X is this still an issue with latest bugfix 2.0?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
