### ISSUE TITLE
My E Stepper always move in same direction TMC2130

### ISSUE THREAD

**Issue by obor00** [MarlinFirmware/Marlin#10964]
### Description
When doing a G1 E10 or G1 E-10, the E-stepper always move  in the same direction.

### Steps to Reproduce

Configuration:
- last version Marlin-bugfix-1.1.x from 04/06/18
- board Rumba
- 5 steppers TMC2130, X and Y use sensor less
- Stealthhchop mode 
- coreXY 
- Dual Z motors

To reproduce:
1. Power on
2. Turn on the heater 0
3. wait temperature ok
4. execute a G1 E10 and check direction
5. Execute a G1 E-10 and see same direction

**Expected behavior:** 
G1 E10 move in one direction
G1 E-10 move in opposite direction

**Actual behavior:**
G1 E10 move in one direction
G1 E-10 move in same direection than G1 E10

#### Additional Information

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2085519/Configuration.zip)

**Comment by thinkyhead** [comment]
Are you using Linear Advance?

@teemuatlut, @Sebastianv650 — What did we determine will cause this? The only issues I could find that mentioned a steppers going only one way or the wrong way were #9816, #10335, and #10605.

**Comment by Sebastianv650** [comment]
@thinkyhead according to his config, he isn't using LA. Reading the two last linked issues, I would think it's something TMC2130 related.

**Comment by teemuatlut** [comment]
If you can, please test with another type of driver to narrow down the cause. Leave the configuration the same.

There are only two ways to determine the direction of rotation for the TMC drives. One is through software by setting the `shaft_dir` bit and another one is toggling the DIR pin which is sampled by the driver.
Marlin does not use the former and testing with another driver would help with the DIR pin cause.
The stepper library does set pin modes in `begin`, so that's another possibility as well.

**Comment by obor00** [comment]
Hi guys, thanks for your hot support ! :)
I replaced the E-stepper with a classic one TMC2110 without SPI, and comment out E in  the config file:

 //#define E0_IS_TMC2130

Now, both Direction works fine, it can extrude and retract.

So there may be something wrong with my driver TMC2130.  I'll test it on another axis to check if it works

**Comment by obor00** [comment]
Confirmed: the  TMC2130 initially on extruder  had a problem  and works only one way. 

So I confirm it was hardware problem,  and not a bug
