### ISSUE TITLE
[FR] Timeout while printing via USB

### ISSUE THREAD

**Issue by Vabe7** [MarlinFirmware/Marlin#11021]
Two days ago I printed from Octoprint via USB. For some reason Octoprint crashed midprint and the printer just remained at the last position and also the temperature was kept at the same level. 
To make Marlin more secure I would wish for a timeout that sets the temperature to zero after a in Configuration.h specified time passed without a received G-Code-command. Especially in times where reports of burning printers I see a need for such a function.

**Comment by forkoz** [comment]
I've had the same thing happen when my PC blue screened mid print. Just sat there cooking a blob on the hot end. It would really worry me only printing things like nylon and PC.

**Comment by comps** [comment]
http://marlinfw.org/docs/gcode/M085.html is probably what you're looking for.

I set it to 10 seconds in my "start gcode" in a slicer just before it starts executing gcode for the first layer (after wiping, leveling and heating up). Then, I disable it (`S0`) in "end gcode".

**Comment by AcHub** [comment]
Personally I would feel better if this protection would be hardcoded into the firmware, instead of just a Gcode. Start and End-gcode can be altered way to easy and I can very well imagine a situation where I could accidentially delete such a command from the script without noticing. Disabling a safety feature should not be possible by accident, because we all know - bad things will eventually happen, if they can happen.

Maybe thats a stupid question, as I never used M85, so I don't exactly know how it works and what it considers to be "activity" regarding the timeout-timer, but if this command halts the whole printer after timeout, wouldn't that also be an issue with for example filament change? If the printer waits for the user to interact, and the user doesn't change filament fast enough, the whole print would be lost. However if the heaters are shut down only, the fire hazzard is probably banned but you would still be able to resume your print after reheating the nozzle. Sure - you could think ahead and add M104 S0 to your filament change script to cool down your nozzle while it waits, but again, that is unsafe and might depend on an external controller for sending the command if not printing from SD card.

**Comment by AnHardt** [comment]
If my printers couldn't stand "print temperature" for a "unlimited time", i wouldn't dare to use them at all.

**Comment by Vabe7** [comment]
With Octoprint this shouldn't be a problem, it sends a command (not sure which right now) every second or so to get the temperature reading. M85 seems to be exactly what I need, I simply wasn't aware of this command.  Edit: Okay, just looked it up once more, M85 checks for moves, so there might be a problem during filament change... And of course I wouldn't trust my printer if it couldn't stand operating temperatures but I think it's just another risk that could be avoided.

**Comment by thinkyhead** [comment]
I think that `M85` pretty much covers it. The one thing we could do to augment it is to add a default `MAX_INACTIVE_TIME` configuration option. Then the machine would, by default, call `kill` whenever it was idle for a period of time.

**Comment by gege2b** [comment]
Damn, I got this problem too, and I was thinking of a similar FR while going back home, glad to see someone did it :)
I was unaware of M85 and, for me, it's just perfect and I'll insert it on my start GCode as soon as I finish this post (with more than 10s btw, maybe something like 5 minutes)

@AnHardt , safety is not the only concern... Leaving a printer with heaters elements on for nothing is not really a good thing, even if the printer is perfectly safe.  this feature would avoid a big mess of filament, and reduce useless power consumption too

**Comment by forkoz** [comment]
Did not know about this either, I'll definitely add it to the start/end code. To me its enough. I don't think my printer would start a fire but it could very well melt the nozzle into the printed item, burn the PEI sheet, destroy the heating element, etc.

**Comment by thinkyhead** [comment]
It would be more comprehensive to have the machine time out after some period of inactivity, then (if it has an LCD) put the machine into a "paused" state with an on-screen option to reheat to the last-set temperature and resume. Essentially this is what the parking function does now, so it could be done as an add-on to the `ADVANCED_PAUSE_FEATURE` in future.

**Comment by bruce356** [comment]
I was also not aware of M85
On a dual x carriage dual extrusion printer there is also inactivity while one hot end is cooled at park and wait temperature and the other heated to extrusion temperature, this time can vary from job to job.
So I guess one needs to decide on a max time.
Also leaving filament sitting in the heated hot end without extrusion over a long period of time also has consequences.
regards
PS by the way I also use Pi3 with octopi and have never had any usb problems or octopi to crash on any of my printers.

**Comment by gege2b** [comment]
@thinkyhead it could be interesting then to move the head a little bit to avoid direct contact with the object underneath the nozzle. Resume would then move the head back to the expected position after reheat

@bruce356 Idem, but since a few weeks, there are different reports in octoprint's repo about printers that stops mid-print with heaters on (it happened to me, too), foosel is still investigating on what could cause this 

Actually, M85 is a good way to mitigate potential damages when this happens, but I agree that with some setup it could be more tricky

**Comment by comps** [comment]
I still think this is a valid FR for a keepalive protocol, perhaps as a new concept, perhaps extending [M113](http://marlinfw.org/docs/gcode/M113.html) with a new flag that requires hosts to report back (and sending requests more regularly, not just on long operations), perhaps simply as expecting [M105](http://marlinfw.org/docs/gcode/M105.html) in regular intervals after its first use, for hosts that don't use [M155](http://marlinfw.org/docs/gcode/M155.html), like printrun.

Having it as a separate feature would allow the host software to use this transparently (wouldn't be used on sd card print) and gcodes wouldn't have to embed [M85](http://marlinfw.org/docs/gcode/M085.html). Also, `FILAMENT_RUNOUT_SCRIPT` wouldn't have to work around it, etc.

**Comment by thinkyhead** [comment]
> it could be interesting then to move the head a little bit to avoid direct contact with the object underneath the nozzle.

If it were done as an extension to `ADVANCED_PAUSE_FEATURE` the filament would retract, then the nozzle would raise up, move to the park position, and cool down after a short time. This would only occur when the nozzle was heated and the machine were "idle" for a long enough period.

If the idea was then to "wake up" in response to a resumption of serial-printing activity, then the nozzle would wait till it was re-heated, move back to the previous position, lower back down, and re-prime the extruder before processing the next serial command. The host would need to wait while Marlin output "busy" messages during heating, and so `HOST_KEEPALIVE` would also be required for this to be viable.

**Comment by boelle** [comment]
@Vabe7 is this still relavant?

**Comment by Vabe7** [comment]
To be honest I didn't follow the development but I think M85 fits the problem nicely. On the other hand the mentioned ideas would improve Marlin further, especially from a safety point of view... So to me it isn't relevant personally, but for the wider audience I still think that a timeout feature would be handy.
Maybe also the others could share their opinion?

**Comment by boelle** [comment]
for me it's a bit of mjeeh, i figured out by a lot of testing that i get better prints when printing from sd card, 

since i upgraded to re-arm i 'm now testing printing from a raspberry pi 3 so there are a potential now that the pi might stop sending data and the printer just cooks whats in the nozzle

so if there should be a feature i would vote for a feature in the firmware so its independant from the gcode

**Comment by filipgoc** [comment]
If some of the thinking is guided by basically an extension of thermal protection, some sort of flag could be for killing the printer not after idler for a time, but after being at certain temperature for a time. That's the more dangerous case.

**Comment by boelle** [comment]
missing a label

**Comment by Legionofone** [comment]
Had this happen to me last night, PC that was sending gcode to a printer crashed and left the nozzle over a print. This definitely seems like a nice piece of mind safety feature. 

It looks like this was implemented into prusa's firmware as the M86 command.

**Comment by thisiskeithb** [comment]
Added in #16362 with `HOTEND_IDLE_TIMEOUT`.
