### ISSUE TITLE
Z-axis goes down at home and then up. 

### ISSUE THREAD

**Issue by xero83** [MarlinFirmware/Marlin#11038]
Hi, there,
I have a strange thing with my printer, I have a modified ulticampy type, and it is that when I give home the axle down a few cm and then go up, the problem is when the base is completely down, is a problem.
And from time to time it makes me move the x-axes manually, it makes me lower the z-axis and then it goes up to the same point, which is very rare.

You know what happens or how I can solve it, I use marlin (logically) and rumba plate.

**Comment by italocjs** [comment]
Mine is the same, but this feature is useful because if the bed is too close to the nozzle and you try homing XYZ without lowering the bed, it would probably hit stuff (like the clampers).

I would suggest you to solve this using a Z-MAX endstop, this way it would still try to go down, but once it hits the ZMAX endstop, it wouldnt move anymore.

**Comment by thinkyhead** [comment]
Try enabling this option and see if it works for your situation…
```cpp
//#define UNKNOWN_Z_NO_RAISE // Don't raise Z (lower the bed) if Z is "unknown." For beds that fall when Z is powered off.
```

**Comment by boelle** [comment]
@xero83 tried what @thinkyhead said?
