### ISSUE TITLE
[FR] Automatic Dual-Z offset calibration

### ISSUE THREAD

**Issue by mikeytoo** [MarlinFirmware/Marlin#11031]
### Description

De-skewing Z-axis

### Steps to Reproduce

I don't know whether you can drive the Z-axis motors independently, but if you can it would be possible to de-skew the Z-axis to the bed during auto homing.  Once auto homing is complete, average the left-side Z values and the right-side Z values separately then subtract one average from the other.  The resulting value is the amount of skew on the platform.  Drive one motor this amount and your platform is parallel to the bed.

**Comment by boelle** [comment]
problem: what if both the bed and X axis is skewed?

when you say Z axis i assume you do mean that X is not parallel to bed

**Comment by bjbeare** [comment]
I've been thinking about this problem for a while... and looked at the dual z stepper code a while ago. I need to look at it again. IIRC, the code needs to first be reworked to allow the steppers to be handled independently.

My concept would then be to tweak one of the Z steppers after an autolevel. Depending on the orientation of the dual z steppers (front/back or right/left), this would correct the leveling of either Y or X. The other axis can't be corrected... but it could significantly reduce the amount of autolevel correction required.

What do you think of the concept? I could invest some time in this... since I'd like the feature for my printer (homebrew Vulcanus large-bed variant).

**Comment by kAdonis** [comment]
@bjbeare  What about G34 Z_STEPPER_AUTO_ALIGN?

**Comment by bjbeare** [comment]
@kAdonis Wow... you guys are amazing. You put that in about a month after I researched the issue. :o). Can't wait to try it out.

**Comment by boelle** [comment]
@bjbeare did it do the trick?

**Comment by boelle** [comment]
@thinkyhead think we can close this one
