### ISSUE TITLE
Amax value

### ISSUE THREAD

**Issue by 3Dmaniac** [MarlinFirmware/Marlin#11167]
Hi guys,

So, checking the acceleration menu (Control>Motion>Acceleration) i can see several acceleration settings.

Acceleration
A-travel
Amax X,Y,Z,E

Reading the configuration.h it says:

Acceleration=X, Y, Z and E acceleration for printing moves.
A-travel= X, Y, Z acceleration for travel (non printing) moves.
Amax=Maximum start speed for accelerated moves.

It's not very clear for me what Amax is.
So...Amax value is a velocity speed or acceleration?
And it's for printing moves or non printing moves?

Thanks

**Comment by tig33r** [comment]
This is probably jerk value...

**Comment by 3Dmaniac** [comment]
Thanks for the reply.
Actually it's not jerk.
Jerk menu is separate from the acceleration menu with different values.

**Comment by gloomyandy** [comment]
I think that Amax is what it says, the maximum acceleration allowed by the machine for the particular axis. The other values are the "default" acceleration used for the various types of move (and should probably always be <= the corresponding Amax value). .

**Comment by hexane360** [comment]
Basically, if you use M204 or the LCD to set an acceleration higher than Amax, the planner will cap it to Amax. Note that this is done on a per-axis basis while acceleration is set based on move type. Setting accelerations higher than max accelerations can be fine, because that's a linear acceleration which is then translated into per-axis. For example, if you set M204 P500 with a Z max acceleration of only 50, you can potentially reach 500 mm/s^2 if the move requires little to no Z movement. As another example, a 45 degree XY move at 500 mm/s^2 requires only 500/sqrt(2) = 354 mm/s^2 of acceleration for each the X and Y axis (assuming a non-core Cartesian printer).

So set Amax to something really high, and then test out some single-axis moves at different accelerations. Then bring Amax back down to the highest you're comfortable with, or just before it starts skipping steps.

The relevant code starts about [here](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/module/planner.cpp#L2078) in `planner.cpp`.
