### ISSUE TITLE
UBL Mesh edit loop hangs on all axis known

### ISSUE THREAD

**Issue by silentninja1** [MarlinFirmware/Marlin#11223]
### Description

UBL Mesh edit screen hangs

### Steps to Reproduce

Select any method of getting to the UBL mesh edit screens

**Expected behavior:Turn dial and hotend moves

**Actual behavior:System not responsive to commands

#### Additional Information
Commenting out the following line (2416) in ultralcd.cpp resolves the issue
if (!all_axes_known()) return lcd_goto_screen(_lcd_ubl_map_homing);

Im not sure this line is necessary as the homing command prior blocks this menu until its complete. Ive commented it out for my build, however I wanted to confirm if the function is still desired as a fail safe or if its safe to remove before issuing a PR

**Comment by GMagician** [comment]
Yes it's important. Once you have done homing and don't move anything, motors will be turned off.
As every stepper, when turned off it may move to a "rest" position that is a full step.
This command will ensure to inhibit ubl when positions are not known exactly.

If this will solve maybe you have such timeout too short, or you wait too much time before doing ubl edit, or maybe a real bug is present.

Check your lcd if something is blinking or ?? appears instead of position.

Be sure to test bugfix branches beacuse 1.1.8 is "old" and some bug have been fixed in between.

**Comment by silentninja1** [comment]
Forgot to mention that was from bugfix as of this morning. It was displaying the grid screen and homing was done, but not accepting commands. I added a logger statement and it was in the main loop but returning at that function every time. The grid display was up, not the homing display. The home move had already completed, and returned to the grid display. It was sitting there immediately after homing and opening the menu.

The home statement is completed prior to entering this loop, and steppers are still locked and enabled at that point.

Also, no way to check if any axis are blinking, as its sitting on the grid screen ignoring all input.

**Comment by Roxy-3D** [comment]
@silentninja1    Thank you for the fix...   I've zapped both bugfix branches with your correction.

> Commenting out the following line (2416) in ultralcd.cpp resolves the issue
```
if (!all_axes_known()) return lcd_goto_screen(_lcd_ubl_map_homing);
```

**Comment by GMagician** [comment]
> Thank you for the fix...

what it means to not know Marlin in deep. I thought that was a protection and it was a bug.....lol

**Comment by InsanityAutomation** [comment]
Gmagician I hear ya there! Following the process though, that validation was done before that line and the edit should already have been active so it jumped out as suspect. When I put braces around it and added serial pair outputs to look at the conditions through there, it showed it was stuck since that value was cleared when the homing finished and that screen was brought up. Still much simpler of a fix than what Scott's working on with the power recovery!
Note : seems my phone is logged into my other account, same person as above lol

**Comment by silentninja1** [comment]
With this - https://github.com/MarlinFirmware/Marlin/commit/fae2929b6b513c5ff6b68a7a8a88274d381f76e7  Im going to close the issue.
