### ISSUE TITLE
Incorrect TCI Ultimaker thermocouple AD595 PCB calculation

### ISSUE THREAD

**Issue by moth4017** [MarlinFirmware/Marlin#11227]
See #11221

using the TCI AD595 PCB for a thermocouple in Marlin V2 with Re-arm  calculation incorrect.
8 deg + offset at 16 Deg  C  as well as the isses in #11221

**Comment by thinkyhead** [comment]
The formulae for AVR readings of these thermocouples are…
```cpp
#define TEMP_AD595(RAW)  ((RAW) * 5.0 * 100.0 / 1024.0 / (OVERSAMPLENR) * (TEMP_SENSOR_AD595_GAIN) + TEMP_SENSOR_AD595_OFFSET)
#define TEMP_AD8495(RAW) ((RAW) * 6.6 * 100.0 / 1024.0 / (OVERSAMPLENR) * (TEMP_SENSOR_AD8495_GAIN) + TEMP_SENSOR_AD8495_OFFSET)
```
I presume that for the ReARM (and other boards) it's the 5.0, 6.6, `TEMP_SENSOR_AD*95_GAIN` and `TEMP_SENSOR_AD*95_OFFSET` values we need to modify. If you can determine the proper values, then it should be simple enough to modify them as appropriate for each MCU.

**Comment by p3p** [comment]
Having looked at the AD595 and AD597 datasheets I'm slightly happier about doing the conversion in software, Max signal output should be Vin - 2V assuming that there is a typo .. otherwise the AD595A specifically can output Vin + 2V on the signal line .. making things worse. If this max signal includes failure modes (and it is a typo) then we can probably just apply the scaling.

**Comment by thinkyhead** [comment]
Anything actionable here? Do we need to get some thermocouples for testing? AD595, AD597, AD8495, PT100…?

**Comment by p3p** [comment]
Any device that has a set amount of V per degree (rather than resistive) will not work on any of the 3.3V boards as the ADC reference is wrong so we will need to add the ability to adjust the calculations based of the ADCVref.

Although there is the problem that most of these devices are 5V in nature, and given enough temperature the signal will be more than 3.3V more than likely destroying the ADC.

**Comment by moth4017** [comment]
Hi i still have my thermocouple set up  with the error i can do some testing .

**Comment by craftoscar** [comment]
> Although there is the problem that most of these devices are 5V in nature, and given enough temperature the signal will be more than 3.3V more than likely destroying the ADC.

mostly, but AD8495 supply voltage can be as lowed as 2.7v 
I'm currently using two AD8495 with RAMPS-FD plus Due

**Comment by p3p** [comment]
@craftoscar The devices I meant were the boards that users have before they upgrade to 32bit that they will just plug into their new system, I know that the chips themselves don't necessarily have this issue. 

Requiring the platforms to define an ADCVRef to be used in the equations wouldn't be a problem I don't think, or just assuming ARM boards are 3.3v.

**Comment by boelle** [comment]
@moth4017 tried with latest bugfix 2.0?

**Comment by boelle** [comment]
@thinkyhead think we can close this one
