### ISSUE TITLE
UBL, Could not complete LSF! error when using real numbers for Probe Offset

### ISSUE THREAD

**Issue by cmroche** [MarlinFirmware/Marlin#11245]
### Description

In the bugfix-1.1.x branch, set the `PROBE_OFFSET_X` and `PROBE_OFFSET_Y` to any fractional number such as 20.99 and 19.20.

If `DEBUG_LEVELING_FEATURE` is defined, you will receive a compilation error related to types

However if this define is not set it will compile fine. You will be able to execute the following functions without any problem:

`G29 P1`
`G29 P3 T`
`G29 A`
`G29 S1`
`G29 J` (No argument to J)

If you send `G29 J5` though it will error out with "Unable to complete LSF" and it will not probe the bed. By changing the values for `PROBE_OFFSET_X` and `PROBE_OFFSET_Y` back to whole numbers the problem is rectified.

### Steps to Reproduce

1. Compile with real numbers for PROBE_OFFSET_X and PROBE_OFFSET_Y
2. Run `G29 J5`

**Expected behavior:** [What you expect to happen]

I guess there are two possible outcomes here:

1) Real numbers are supported and the bed probing completes with real numbers in the offset.
2) A compilation error is generated preventing compilation when real numbers are used.

**Actual behavior:** [What actually happens]

Compilation succeed, running `G29 J5` produces "Could not complete LSF" error on the console

**Comment by AnHardt** [comment]
Users ignoring instructions are annoying.

https://github.com/MarlinFirmware/Marlin/blob/bugfix-1.1.x/Marlin/Configuration.h#L728

**Comment by cmroche** [comment]
I gather by your response that I am not the only one. It's not ignoring so much as not seeing unfortunately, I assure you that I re-read this trying to understand the potential causes from problem since I suspected configuration from the onset.

This does however tell me which solution is expected then, that it probably shouldn't be compilable. While I do not know the development philosophy for this project, would this type of error warrant a sanity check? Are lanaguage features sufficient to support one?

In any case, thank you for clarifying

**Comment by AnHardt** [comment]
Supporting Marlin for users not being able to read at least the confg. files is an even more hopeless nightmare.
How can we assume they would be able to understand our answers then.

The x/y probe offsets could easily be floats if there won't be that  sanity checks where we currently need to calculate in the preprocessor. Since we are using more and more static assertions instead, we could rethink about that. But we already have seen too much improvements in that area what finally have been regressions needing more fixes. Currently that area of code seems to work, more or less, but is hard to understand.

This all would not be necessary if users would be able to configure 4 points describing the probable area in probe coordinates. But since they are neither able to read instructions, nor to do some simple calculations, nor willing or being able to do some simple tests, to find the right points by experiment - it's hopeless.

Sorry. Maybe i'm a bit depressive today. :-(


PS
Don't take this personally!
Marlin is becoming increasingly complicated because it's trying to be simple.
Simplicity attracts idiots.

Making the use of Marlin simple is a valid target.
Configuring Marlin was, is and will ever be, a task for a kind of experts.

**Comment by cmroche** [comment]
I know the feeling of having to respond to the same answered questions over and over.

I would be more than happy to prepare a change to add static assertions if it is an appropriate solution for the project. It could lead to less annoying bug reports :)

In retrospect I added the decimals out of compulsion (and to make it consistent with the Z value which is always fractional), but in reality I wonder if sub-millimeter precision is really necessary here? Do you think that effort would be valuable to pursue? I am very unfamiliar with this code base, but I am not adverse to implementing this change if it's going to actually help someone. I certainly didn't need this level of precision in the end.

In any case this is clearly not a bug, and the documentation is clear as you've pointed out so I will close the issue.

**Comment by AnHardt** [comment]
> but in reality I wonder if sub-millimeter precision is really necessary here?

It is NOT! All our bed leveling can't work if a sub-mm horizontal shift could cause a noticeable difference in Z. Maybe if wed have a sub-mm grid - but that bed would be really bumpy/unusable.

**Comment by AnHardt** [comment]
Printing on a wide file would probably stick well, but you'd probably don't want to follow it's tooth shape. Likely you want to sense the tooth tops, or an other constant level, by making the sensors sensitive area (unsharpness) big enough to not detect once the valleys once the tops.

**Comment by Roxy-3D** [comment]
>> but in reality I wonder if sub-millimeter precision is really necessary here?

> It is NOT! All our bed leveling can't work if a sub-mm horizontal shift could cause a noticeable difference in Z. Maybe if wed have a sub-mm grid - but that bed would be really bumpy/unusable.

From a math perspective....  What AnHardt is saying is the angle the bed is off by should be very small.   The value of sin(theta) goes to 0 as theta approaches 0.   And the limit of sin(theta)/theta approaches 1.0 as theta goes to 0.0.  So that translates into the Z-Height correction going to almost no change as you add fractional millimeter distances (for X & Y_PROBE_OFFSET_FROM_EXTRUDER) into the equation.
