### ISSUE TITLE
X Axis problems 

### ISSUE THREAD

**Issue by Matej1006** [MarlinFirmware/Marlin#11321]
The problem is with the x axis when the home function is end, the x axis does not move anymore in the bed leveling function makes it in one point of 6 measurements. and only the Y and Z axis move.

But if the printer is off and I move the x axis from X0 by hand, it returns to X0 with the command G28 and does not move anymore with any command

If I turn on Z_SAFE_HOMING, I will do the measurement at Y150 and X0 and not in the Y150 X100

### Steps to Reproduce

1. Home all axes
2. Run auto bed leveling

That the X axis will work

Make a measurement on the Y150 and X0, then the auto bed leveling steps are done. In auto bed leveling, the X axis does not move, only the Z and Y axis operate.

I use Marlin with Ramps 1.4 with full graphic display and TMC2130

**Comment by crystalhand** [comment]
I have a similar issue to this.  It seems that the z_safe_homing is not always triggering properly.  Randomly after homing the X and Y axis they stop moving.  The z then tries to home but never triggers because the x and y axis endstops are not above the bed.  After a reboot it works.  


Using a core XY running the latest version of the bugfix.
