### ISSUE TITLE
CURRENT_STEP_DOWN correcting current can go negative

### ISSUE THREAD

**Issue by mmrvelj** [MarlinFirmware/Marlin#11348]
https://github.com/MarlinFirmware/Marlin/blob/9b63430f349f7083d09d2db24d24908e1d277379/Marlin/Marlin_main.cpp#L13917

There is no check if current goes to negative value here. I believe this is incorrect.

**Comment by teemuatlut** [comment]
Thanks, this is something I've already fixed in my dev branch that targets 2.0.x releases. It'll be merged a bit after 1.1.9 release.

Technically if everything would be working correctly there would be no situation where the current would be set that low. If that happens there is something more urgent wrong so I consider this to be more of a sanity check.
