### ISSUE TITLE
IDEA: Extract selftest from prusa??

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#11464]
hi

just wondering  if it would make sense to extract the selftest procedure from here?

https://github.com/prusa3d/Prusa-Firmware/blob/MK3/Firmware/ultralcd.cpp    (search for selftest)

of course parts like testing the fans requires the tacho signal to be feed back

it might also make sense to allow individual items to be tested

throw in your 0.02$ :-D

**Comment by boelle** [comment]
oh yes... i know that on the mk3 it also has a sense option to for power to the bed and hotend, but those could simple be connected to a resistor divider to bring down the voltage to 5/3.3V levels

i'm also looking at their design for the power panic to see if it can be made for a reasonble price, you are welcome to chip in on what you think is reasonble

**Comment by forkoz** [comment]
Prusa has the advantage of uniform hardware. My fans don't have speed sense. I'd have to downgrade the speed of the fans or get larger ones. It can't test my end stops but homing already does that. Power to the HE/bed is tested by heating it up, if it doesn't heat for long enough the printer shuts off, etc. 

So in short I don't there would be much of a point.

**Comment by Grogyan** [comment]
@boelle Josef's Power Panic is seriously simple, and because it is designed for being on the back of a IEC connector, means that it should already be mass made.

The self test can be put into Marlin, however, because a lot of people use a lot of different electronics, it is hard to know if there are any available pins to read tachos.

Once Marlin is 32bit ready, this can be something to look at again I reckon.  As 32bit micro's have a lot more pins available than 8bit AVRs

**Comment by Roxy-3D** [comment]
> Once Marlin is 32bit ready, this can be something to look at again I reckon. As 32bit micro's have a lot more pins available than 8bit AVRs

Actually...  So far...  It is the opposite.   On the Re-ARM which is our 'Reference Platform', when the RAMPS board is plugged in, not every GPIO pin is active.   

The Re-ARM board is made to plug into a RAMPS board.   But it has a LPC1768 32-bit processor on it.   That is what we chose to use as a 'Reference Platform' for the 32-bit work.   It is up and running.  There are (of course!!!!) some issues.   But it does work and can drive a printer.

The problem is the LPC1768 processor chip does not have enough GPIO pins to fully handle everything on the RAMPS board that you plug into it.   The designer did a good job assigning the available pins to important things.   But some of the pins are not connected to anything.   

[Re-ARM pinouts.pdf](https://github.com/MarlinFirmware/Marlin/files/2274303/Re-ARM.pinouts.pdf)

**Comment by boelle** [comment]
with a Ramps+Mega2560 board there is plenty free pins on aux1 or aux2

of course a small addon board is needed as tacho can not go directly to the MCU nor can thermistors or the voltage monitor input needed

**Comment by forkoz** [comment]
Yea, I struggled to find interruptible pins for end stops. Add somebody using TMCs into the mix and all those self tests are getting //

**Comment by Roxy-3D** [comment]
I understand the desire to have interruptible pins for the end stops...  But...   The 8-Bit AVR's at 20 MHz work just fine with Programmed IO on the end stops.   A 32-bit processor at 100 MHz really doesn't need interrupts on its end stops.

With that said...  I do understand people want certain things even if they aren't necessary!!!

**Comment by boelle** [comment]
my idea was to have some kind of self test as an option, not as a forced thing

and if prusa can do it so can marlin, and their ensy board is nothing more than a glorified ramps board with some extra flash memory. i did look for quite a bit on the schematic that ultimachine has published and did not find much new there other than that the power panic also disables the heaters, but only if it gets a signal (if left unconnected it will not disable anything)

since i have a slow day and we have a pause in those heatwaves here in europe i will look at it again and see what changes are really needed on a Ramps and also on a Ramps FD v2.3, if nothing else just for the fun of it and to keep my mind in gear :-D

**Comment by boelle** [comment]
@Grogyan so no one is producing these power panic boards?

**Comment by thinkyhead** [comment]
Geeetech's current crop of machines includes early power-loss detection and a big capacitor to hold the charge for several seconds.
