### ISSUE TITLE
MKS SBASE setup with LCD 12864 - TFT35 - PS_DEFAULT_ON - relay or rele - POWER_LOSS_RECOVERY - TMC2208

### ISSUE THREAD

**Issue by hectori4502** [MarlinFirmware/Marlin#11515]
Hello everyone
I want to share my experience with my sbase board and clarify some doubts I have.
At the moment I have configured and working.

USB to PC, TFT35, LCD12864 Reprap Discount Full Graphics Smart Controller, with SD at the same time.
PS_DEFAULT_ON ATX with relay.
I'm stuck on POWER_LOSS_RECOVERY
dealing with: #define POWER_LOSS_PIN P1_18 // LCD_PINS_ENABLE // P4_28
receiving: Power-Loss Recovery
PRINTE HALTED
Please reset
I wonder ? what is the pin to use ???? if I need to connect some cable ??? from where to where ???

The TFT35 screen comes with POWER_LOSS_RECOVERY   I already test it and works fine.

At the moment I am working with the original drivers, I am waiting for the Expansion Board to install the TMC2208 I will have to disconnect the 12864 LCD to use the pins).

Another thing I plan is to use an encoder to measure the extruded filament
(if anyone has any information, it will be well received thank you).

USB to PC, TFT35, LCD12864 with SD at the same time.
#define BAUDRATE 115200 // tft35
#define SERIAL_PORT -1 // USB
#define SERIAL_PORT_2 0 // BIQU TFT35
![lcd-tft](https://user-images.githubusercontent.com/36092499/43982347-14b8f8a2-9cbb-11e8-90c1-4a221d437d65.jpg)
![exp2hack](https://user-images.githubusercontent.com/36092499/43982351-1cb8e648-9cbb-11e8-9b93-40488a12d2fe.jpg)

PS_DEFAULT_ON ATX with relay
#define PS_ON_PIN          P0_25 //TH3 Connector
![atx-relay](https://user-images.githubusercontent.com/36092499/43983528-9363d10e-9cc0-11e8-8f9a-c3ffd524cf69.jpg)

**Comment by gloomyandy** [comment]
Interesting. What expansion board do you plan to use?

I have an SBase with a Reprap Discount Full Graphics Smart Controller (which I think is the same as the LCD12864 you have) with working SD card reader, I also have TMC2208 drivers for X and Y (mounted on my own expansion card). As you will have noticed the SBase does not have a lot of useful spare pins, because of this I currently operate my TMC2208s in standalone mode (set to use Stelathchop2 and 16 microsteps with interpolation to 256). So far this has been working very well for me. Have you considered just using standalone mode? I'm not sure how much the benefits of hooking up the UART interface are worth, it seems to me that other than being able to more easily configure them, most of what you get is just extra diagnostics (temperature etc.). Do you have a particular need for any features provided via the UART interface?

Can't help with your power loss issue I'm afraid as I've never really looked at the TFT35. From a quick glance it just seems to be a standalone interface that sends G-Code to the SBase, is that correct? How well have you found it works?

**Comment by hectori4502** [comment]
I will use this with TMC2208
![extdriver](https://user-images.githubusercontent.com/36092499/43993847-62cf01f0-9d59-11e8-85a2-4aca0e9fcc62.jpg)

**Comment by hectori4502** [comment]
I just connected the CNC Shield and the steps motors 0.9 degrees work as if they were 1.8 degrees.
(the speed is high and the motors are silent).
![cnc shield](https://user-images.githubusercontent.com/36092499/46572740-8e7e2b00-c950-11e8-9b0b-9ab05b2a8c10.jpg)

https://www.youtube.com/watch?v=1SyfiDOHEWY&t=13s
