### ISSUE TITLE
[1.1.9] TMC2130: axis not moving when stepper current is not set to 800 (standard)

### ISSUE THREAD

**Issue by jb2304** [MarlinFirmware/Marlin#11520]
### Description

My axes stop moving when i set the current to 1000 (standard is 800). With 1.1.8 it worked flawless. I use an MKS_GEN_L Board with TMC2130 drivers on all axes.
With the current set to 800 alls axes home and move as expected. But every axis i set to the current of 1000 does not move at all. 
I flashed 1.1.8 again to make sure its not a hardware Problem. All axis work flawless regardless of the current i set the steppers to.

### Steps to Reproduce

1. Edit configuration_adv.h OR use M906 command to set the stepper current to 1000.
2. Flash firmware OR save setting with M500.
3. Home/move axis with new current.

**Expected behavior:** 
Axis should move and home like usual regardless of the set current.

**Actual behavior:** 
Axis does not move at all and Printer halts when i try to home the axis.

#### Additional Information

[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2280276/configuration.zip)

**Comment by marcio-ao** [comment]
I suggest enabling TMC_DEBUG and M122. Check to see what the "Run current" is set to. It should be a fraction, like 28/31. Now, compare the values when the current is 800 vs when it is 1000. Make sure that the fraction is larger on the second case.

The reason I suggest this is that in one occasion I had to troubleshoot a similar problem, and it turned out that the "Run current" value was overflowing, causing it to wrap around to a lower value.

**Comment by thinkyhead** [comment]
@jb2304 — See if the latest bugfix code is working better for you.

**Comment by boelle** [comment]
@jb2304 tried latest bugfix 2.0?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
