### ISSUE TITLE
[FR] Support 3-wire fans

### ISSUE THREAD

**Issue by svs072477** [MarlinFirmware/Marlin#11642]
Is it possible to add support for three-wire fans. For example, to get information on the signal wire, about whether the fan rotates, and if it does not rotate, turn off the hotend heating

**Comment by AnHardt** [comment]
The pulses are short and relatively high frequent. You'll need an interrupt.

For the poor tiny 8-bitters you'll probably need a hardware pulse divider like a counter from the 74xx series and a custom interrupt header to be able to do something else than checking the fan. Maybe you can find and set up an unused hardware counter in the AVR.

**Comment by svs072477** [comment]
I do board on stm32f429, and hardware problems with the counting of the pulses will not be there. The problem is that I'm not a professional programmer. Processing code pulses from the fan, I will write, but not sure that will be able to add it in the right place in Marlin

**Comment by marcio-ao** [comment]
@AnHardt : AFAIK, Prusa's FW does it, so it should be feasible in an 8-bit CPU.

**Comment by AnHardt** [comment]
I did not say it does not work. I said: "It needs an interrupt and a pre divider would help to lower the load."

https://github.com/prusa3d/Prusa-Firmware/blob/168bc74102fc462c0343f554ee03c26e0d65eb3a/Firmware/Marlin_main.cpp#L8338-L8370

**Comment by Weruminger** [comment]
Sorry for late input, but i'm new here :-)
i did it with an monostable flip flop timer based on the very cheap NE555 
to monitor two fans you can use a NE556 (double timer)
it works fine to just identify a coolinf issue (500 ms timewindow is fast enough) and you can use it like a filament sensor or an end stop sensor. I use it instead of a Filament sensor and it works fine without any FW changes. Just configure it. Same with end stop.

**Comment by AnHardt** [comment]
Also compare to https://github.com/prusa3d/Prusa-Firmware/pull/1193#issuecomment-430587423

**Comment by Weruminger** [comment]
Nice Link but not for the given issue. The link's content is related to model cooler PWM controlled. ( this is unmanaged too noisy… but that's another issue) In this Issue the user want to monitor the Hotend Fan via its Tacho wire. I sent only a hint to change the Tacho pulses into a Switch signal (ON/OFF) that can be handled easily from every 8-Bit Controller and refines the requirement: stop printing and heating if Hotend Fan is switched on but does not run.

**Comment by AnHardt** [comment]
The link seems to be relevant because it pretty well explains why you could, on a PWMd fan, see pulses even if its not turning. Did you test that with your solution?

It also explains very well why Prusas solution does not work to everyone's satisfaction.  
The link is perfectly on topic for  "[FR] Support 3-wire fans".

**Comment by Rincewind08** [comment]
I run several water cooled hot end units and I am dying for this feature to become implemented. I'm sure that everyone who's going to go so far as to use water cooling will be on a 32-bit board or at least I hope so but regardless if we could get an implementation to control an array or a single fan output based off of tachometer that would really change the game for some of us.

**Comment by thinkyhead** [comment]
Closing, as this is now underway.
