### ISSUE TITLE
[2.0 Request] Mechanical/Motors menus missing on SDCARD printing

### ISSUE THREAD

**Issue by studiodyne** [MarlinFirmware/Marlin#11721]
Hi
The new configuration menus need more about mechanical and motors.
-Travel speed ' if too high , impossible to reduce it ' ' this speed is according to filament stringing properties' and need to be set in real time ' Travel speed is the VMAX and not accessible'
-Jerk ' printing is the only real moment when we adjust the jerk , but not possible now '
-Firmware retract settings too ' why use firmware retract if not possible to adjust it in real time by lcd'
-Firmware retact zlifting too
Please can you add , more essentials setting for sdprinting.
Thks

**Comment by hamster65** [comment]
I am missing the following LCD Menu functions during print (by USB/Octoprint):
- Adjust acceleration values
- Adjust jerk values
- Adjust speed values
- Save values to eeprom to make them permanent.
I used to adjust those values while printing so that I could listen to noise and vibrations. When it was running fine, I saved them to eeprom, including the z probe offset.

Maybe it would make sense to also add feedrate to the tune menue. I know it can be adjusted by turning the encoder knob when the info screen is displayed, but I think this option should be visible in the tune menue, too, for the sake of completeness.

**Comment by marcio-ao** [comment]
See this comment:

https://github.com/MarlinFirmware/Marlin/pull/10360#issuecomment-417802100

**Comment by hamster65** [comment]
Those values definitely were accessible during printing.
K-Factor for linear advance is missing as well.

**Comment by studiodyne** [comment]
I've closed the old , because , i ask the community here , to use the sensor with some differences , no measurement , just used to detect a stopped filament , and it's perfect 

THks
