### ISSUE TITLE
EMERGENCY_PARSER and Arduino Mega (AT90)

### ISSUE THREAD

**Issue by NickRimmer** [MarlinFirmware/Marlin#11828]
### Description

Hello everyone! I tested EMERGENCY_PARCER feature, and I found something.

In "Configuration_adv.h" you said it doesn't work on boards with AT90USB, but it works property with my Arduino Mega (AT90). 

Probably there is mistake, and it works only on AT90 instead ch340? Or need someone, who can test it with board using CH340.

### Steps to Reproduce
1. I sent a GCODE with a few slow commands to printer
2. Right after that, I sent M112 command to printer
3. M112 command executed immediately, with "printer halted" message

**Expected behavior:** It must be executed from buffer, in some order

**Actual behavior:** But command executed immediately

#### Additional Information
Slow GCODE looks like:
```
G0 Z50 F200
G0 Z100 F200
G0 Z150 F200
G0 Z200 F200
```

In Configuration_adv.h I just uncomment `//#define EMERGENCY_PARSER`

**Comment by MrAlvin** [comment]
It would seem that M112 has been discussed here: https://github.com/MarlinFirmware/Marlin/issues/836
And have been implemented here: https://github.com/MarlinFirmware/Marlin/pull/851

It would also seem that the M112 command (Emergency stop) was always intended to be executed immediately, but that a full (serial) command buffer, would delay this process. 

It would seem that the original intent of enabling the EMERGENCY_PARSER define, would ensure execution of the M112 command just a little sooner than the "normal" already high priority of executing the M112 command. 

It is possible that the wording of why, when and how the EMERGENCY_PARSER define is an advantage, has not been worded optimally, and could indeed lead to expectation of functionality like you have described above; that even execution of the M112 (Emergency Stop) command should wait it's turn like every other G/M-code, unless the High-priority flag was raised.  

Such a (delayed) functionality was however never the intention of the M112 command.  It is after all called an "Emergency Stop". Not an (in and orderly fashion) Stop command. 

I would suggest that other G/M-code commands, that will wait their turn in the command sequence (to be executed), are to be used to reach the same end result, but in an orderly fashion, rather than to change the current behavior of the M112 command. 

And then the wording about; how, why and when to enable the EMERGENCY_PARSER define, perhaps be adjusted to reflect the current (emergency optimized) implementation. 

I think that an emergency command, should always be reacted upon, and be executed with the utmost urgency. 

For the above described orderly stop, it might be considered to implement a Stop command. 
But perhaps all the current "turn this off" commands will have to do.

**Comment by AnHardt** [comment]
> In "Configuration_adv.h" you said it doesn't work on boards with AT90USB, but it works property with my Arduino Mega (AT90).
Probably there is mistake, and it works only on AT90 instead ch340? Or need someone, who can test it with board using CH340.

Almost all Arduino boards like the Mega have USB_co_processors like the CH340, smaller AVR-chips with a native USB_port oer FTDI_chips. They convert the USB serial to a two wire TTL-serial. You can usually see the communication on the pins 0 and 1. The main processor usually communicates over this real serial interface and has no native USB_interface. A few boards do have a **main** processor with native USB-interface (AT90USB... ). The emergency command parser is not implemented for them. It's located in the driver of the *real* hardware serials receive interrupt before the content is stored in the input buffer. Because i don't have a clue about USB-drivers and because they are not part of Marlin, but of the Arduino core, **I** can not do that for these processors.

> G0 Z50 F200
G0 Z100 F200
G0 Z150 F200
G0 Z200 F200

For Marlins parser this is not long lasting because if the planer buffer is not full these commands do return quite immediately. Think about testing with the 'waiting' heater commands M109, M190, probing for the levelling G29 or potentially for ever lasting M0.

**Comment by boelle** [comment]
@NickRimmer is this still a problem when using latest bugfix 2.0?

**Comment by boelle** [comment]
@Thinkyhead i think we can close this one
