### ISSUE TITLE
Layer misalignment

### ISSUE THREAD

**Issue by 14015** [MarlinFirmware/Marlin#11885]
Hello,
I'm using cartesian 3D printer, which is my own project, with Marlin firmware and I have the following problem:
When I print something larger, in first 3 milimeters the print overhangs (it is like layer misalignment) and after the 3rd milimeter it is stable. 
It seems like layer misalignment or steps skipping, but only for the first 3 milimeters, only in X AXIS and only in one direction EVERYTIME on larger prints. 
I've tried with different filaments, different temperatures and different speeds and the problem is the same everytime. 
Do you have any idea how can I fix this? Is it something like scew correction in Marlin firmware but only for the first 3 milimeters ?

P.S. The printer is with linear movement and I'm shure that the problem is not in the belts. 

Thank you! :)

![img_20180920_203353](https://user-images.githubusercontent.com/43451100/45839521-44286780-bd1d-11e8-9679-a2a4c7ffb0e6.jpg)
![img_20180920_203426](https://user-images.githubusercontent.com/43451100/45839523-44286780-bd1d-11e8-9eff-62ae110d94e9.jpg)

**Comment by dgrat** [comment]
I would guess that based on your pictures there are several problems. 

- Your extrusion rate seems too high
- Layer shifts are commonly caused by too high or too low current on the stepper driver, or if there is too much friction on one of the axes
=> I sometimes touch the driver, if it feels like you burn yourself in the moment you touch, it is probably too much current, if it feels just hot like 90/100°C it might be fine.
- I have the feel in your case one axis might be loose, because in my first printer I had a similar looking problem once (it was the z axis connector)

**Comment by 14015** [comment]
Thank you for your response! 
Now everything works fine. 
I'm using Nema23 with PoStep256 drivers and they operate on its normal temperature - around 50°C, but I lowered the current because the stepper doesnt sounds well (on lower speeds) . 
The stepper motor was 30°C and may be it doesn't works well on lower temps. 
I changed the current only on this axis - from 2 to 3Amps and now the stepper motor is on 70°C which is normal. 
The problem with the lower print quality is expected, because I'm using 1mm nozzle and 400mms print speed. 
I changed only the current and nothing else, but the impact is huge. 
Thanks a lot! 
![img_20180921_145915](https://user-images.githubusercontent.com/43451100/45880389-7040f880-bdb0-11e8-9be5-85362a0406e0.jpg)
![img_20180921_145910](https://user-images.githubusercontent.com/43451100/45880399-746d1600-bdb0-11e8-91ae-0fbd4b9a4ee4.jpg)
