### ISSUE TITLE
Error in Marlin 2.0 when using STM32F4 and REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

### ISSUE THREAD

**Issue by bipsendk** [MarlinFirmware/Marlin#12234]
### Description

Error reported during build of STM32F4 configuration with `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` defined

### Steps to Reproduce

Set up build environment
Enable `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` in `Configuration.h`
Compile

**Expected behavior:** [What you expect to happen]
Successful compile

**Actual behavior:** [What actually happens]
Error thrown:
```
C:\Users\user\AppData\Local\Temp\arduino_build_295107\sketch\src\lcd\dogm\ultralcd_st7920_u8glib_rrd_AVR.cpp:88:4: error: #error "No valid condition for delays in 'ultralcd_st7920_u8glib_rrd_AVR.h'"

   #error "No valid condition for delays in 'ultralcd_st7920_u8glib_rrd_AVR.h'"

    ^~~~~
```
It looks as if the error is triggered by that apparently no F_CPU has been defined, the MB definition not has been included in the list of if/defines - and the check is made even if ST7920_DELAY_1/2/3 already have been defined.

**Comment by ktand** [comment]
I think It's because there is no delays defined for the board you are using in
ultralcd_st7920_u8glib_rrd_AVR.cpp

Instead of checking for different STM32 boards:

#elif MB(REMRAM_V1)
  #define CPU_ST7920_DELAY_1 DELAY_NS(0)
  #define CPU_ST7920_DELAY_2 DELAY_NS(0)
  #define CPU_ST7920_DELAY_3 DELAY_NS(0)
#elif MB(ARMED)
  #define CPU_ST7920_DELAY_1 DELAY_NS(0)
  #define CPU_ST7920_DELAY_2 DELAY_NS(0)
  #define CPU_ST7920_DELAY_3 DELAY_NS(0)

I think a better solution would be define the delays per STM32 CPU, like
this:

#elif defined (STM32F4xx)
  #define CPU_ST7920_DELAY_1 DELAY_NS(0)
  #define CPU_ST7920_DELAY_2 DELAY_NS(0)
  #define CPU_ST7920_DELAY_3 DELAY_NS(0)
#elif defined (STM32F7xx)
  #define CPU_ST7920_DELAY_1 DELAY_NS(0)
  #define CPU_ST7920_DELAY_2 DELAY_NS(0)
  #define CPU_ST7920_DELAY_3 DELAY_NS(0)
#elif ...

What do you say, @thinkyhead and @hasenbanck?

**Comment by hasenbanck** [comment]
Yeah, that might be better. Radical idea: Why not just use `#elif defined(ARDUINO_ARCH_STM32)`? Then we could later add exceptions to the rule when needed.

**Comment by ktand** [comment]
Yes, @hasenbanck, that's better. I will provide a PR for this.
