### ISSUE TITLE
Marlin 2 compile error with REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER enabled

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#12259]
I enabled REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER in configuration.h file, and I got this error:
```
Marlin\src\lcd\ultralcd_impl_DOGM.h:295:83: error: no matching function for call to 'U8GLIB_ST7920_128X64_RRD::drawStr(const ui
nt8_t&, int, double)'
.piolibdeps\U8glib-HAL_ID1932\src/U8glib.h:179:16: note:   no known conversion for argument 3 from 'double' to 'const char*'
*** [.pioenvs\LPC1768\src\src\lcd\ultralcd.cpp.o] Error 1
```
don't know how to proceed from there. :-(

**Comment by gloomyandy** [comment]
It is much easier for people to help with problems like this if you include your configuration files (and details of exactly which version of Marlin you are using - so for instance when did you download it, or the actual git id).

**Comment by ghost** [comment]
here is my configuration file, and I am trying to compile Marlin 2 which I downloaded last night, and just now. [Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2523076/Configuration.zip)

**Comment by gloomyandy** [comment]
Couple of things I can see which may cause problems...
1. You have defined SPEAKER, I'm pretty sure that this display simply has a buzzer.
2. You have set STRING_SPLASH_LINE1 to 1.0:
#define STRING_SPLASH_LINE1 1.0 
this should almost certainly be a string...
#define STRING_SPLASH_LINE1 "1.0"

I'm pretty sure the compilation error is caused by 2 above.

**Comment by ghost** [comment]
thanks for the reply, I re download the zip again and reconfig everything in the new file, it compiles just fine, so I guess I can close the issue now :-)
