### ISSUE TITLE
boards.h documentation missing

### ISSUE THREAD

**Issue by Louis-Cypher** [MarlinFirmware/Marlin#12536]
### Description

I want to contribute a pin file for BIQU Ramps 1.6 plus. Reading boards.h I am already lost. To my understanding boards.h is undocumented, I find a 

`define BOARD_WHATEVER  123` and I don't have the roughest ideas what happens in the chain from Configuration.h boards.h through pins.h to the final PIN file without digging through a lot of code. The MOTHERBOARD variable in Configurations.h has no `BOARD_` infront (which very likely is stripped off somewhere in the code) and I do not have the slightest idea what the number after is and what it is good for. The steps given in the devolpment documentation are incomplete as well. This keeps newbies like me from contributing pin files.
### Steps to Reproduce

read the code of boards.h

**Expected behavior:** [What you expect to happen]
At least one line of explanation what happens in the board definition. What is the convention for `BOARD_xxx` and what is the number (I guess an ID? How fo find a unique one? What are the conventions to choose one?

**Actual behavior:** [What actually happens]
Undocumented code

**Comment by Louis-Cypher** [comment]
The BOARD_ is stripped in the last line of boards.h (undocumented) but what happens to the number/ID still stays a miracle to me

**Comment by Louis-Cypher** [comment]
Spent a while to figure out what has to be done to **really add a board** and it is far away from what the documentation says. Doesn't one have to change the makefile?

The documentation given here [http://marlinfw.org/docs/development/boards.html](url) is not sufficient for people new to the project from my point of view

**Comment by ghost** [comment]
I've got a nice pin file too for Anet A8 modded with a Geetech GT256 Board, but don't really know what to do with it...

**Comment by Ludy87** [comment]
i read this files without documentation tags and understand this function and implementation. I am not a Freak. The code is very simple.

The Board number be random, respectively +1 if it a same manufactor a new board created

**Comment by Louis-Cypher** [comment]
That's good for you but not very helpful. The question is about undocumented code maybe preventing people from contributing to Marlin. What is the random number good for? If it is good for nothing, why is it there? Should it match something? Since random is pretty likely to collide, we will end up with numbers of 8 digits pretty soon if there is no rule how to generate numbers.   

Furthermore, the documentation of how to add a board is not helping much regardless whether you managed to solve the problem on your own or not. If there is documentation it should be of use in my eyes.

**Comment by Ludy87** [comment]
the number defination is for compare

example:

`#define MOTHERBOARD BOARD_RAMPS_14_EFB`

```c++
boards.h

BOARD_RAMPS_14_EFB equal 43
```

```c++
pins.h

#define MB(board) (defined(BOARD_ ## board) && MOTHERBOARD==BOARD_ ## board)

MB(RAMPS_14_EFB)

```
just shorter like

`defined(BOARD_RAMPS_14_EFB)  && MOTHERBOARD==BOARD_RAMPS_14_EFB)`

**Comment by AnHardt** [comment]
Every open source project is always completely documented by its source code. Even better, the source always describes its actual version. Any secondary documentation will always document a historic state - except someone actuaises it - then it will be actual for a few minutes to month.

If you can't find a system in the boards numbers take into account there is no system. A long time ago there was a system, and rests of it can still be found in boards.h. But that system was always difficult to see for some and we accepted always contributions not following any system - except the number was not unice. The number as souch really does not matter as long as it is unice. If its unice, is easily found out by searching it in 'boards.h'. If indeed two developers would pick the same number and publish their PRs at the same time the problem would be easily fixed by changing one of the numbers in not more than two files. If you'd pick a number above (currently) 1999 you'd be asked if you have a special reason for that - and if you have, that probably would be accepted.

For a `Ramps 1.6 plus` i'd suggest `163` and followers. 3 is early RAMPS, 33 is RAMPS1.3. 43 is RAMPS1.4. 143 is a RAMPS plus (what is likely to be a RAMPS1.4 plus). So 163 could be a nice number for a  RAMPS1.6 plus. 63 could be a RAMPS1.6 but is already in use for the MELZI. 
If that board us not for AVR but a 32bit processors use a number above 1000.

For most of us MAKEFILE is completely uninteresting. Neither Arduino-IDE nor Platform-IO use it. We assume they, who use it, are able to add missing things to it.

**Comment by Louis-Cypher** [comment]
Great, Thanks a lot for clarifying. I agree on documentation in source code being better than external documents. From my point of vie boards.h could be documented better. Maybe I find time to add some comments (as soon as I fully understood what's happening there; not a C programmer at all.)

**Comment by AnHardt** [comment]
The C PreProcessor (CPP) can't compare strings - just integer numbers. `boards.h` gives numbers a human memorisable names - or if you want, the other way around.

**Comment by AnHardt** [comment]
```cpp
// The following define selects which electronics board you have.
// Please choose the name from boards.h that matches your setup
#ifndef MOTHERBOARD
  #define MOTHERBOARD BOARD_RAMPS_14_EFB
#endif
``` 
If you want you can fill in the number (43) here instead of the boardname.
If `MOTHERBOARD` is already defined here the value comes from the MAKEFILE where the compiler is called with a that -D parameter. 
Later on this number is just and only used to pick the right pin file

**Comment by thinkyhead** [comment]
We can always use help with the MarlinFirmware/MarlinDocumentation project to expand the website documentation on various subjects. We haven’t written up a very lengthy development guide beyond coding conventions and making PRs, so that is one area where contributions would be helpful. I’m aiming to make more videos and tutorials on Marlin features and on general Marlin development. I’ll plan to make a short video on the subject of adding new boards, new features, etc., as video production gets going.

**Comment by GPTKEY** [comment]
我觉得目前的配置方式 过于麻烦, 应该直接让用户 设置每个MCU的IO对应Marlin接口的功能

**Comment by thinkyhead** [comment]
请把它做得更好！
