### ISSUE TITLE
[2.0.x] SWITCHING_NOZZLE doesn't raise hotend before switching nozzle

### ISSUE THREAD

**Issue by scott0122** [MarlinFirmware/Marlin#12563]
Manually switching nozzle doesn't raise hotend before switching nozzle.
And after nozzle switched, hotend lower TOOLCHANGE_ZRAISE.
If hotend switches 5 times, hotend lower TOOLCHANGE_ZRAISE*5 but no raise performed. 

Why "no_move" at line 645 in tool_change.cpp?

Please take a look at the video for detail.
https://drive.google.com/file/d/1VrWl4w-bKRG25sbjCk7RTzCCj40wxEXp/view?usp=sharing

**Comment by GMagician** [comment]
Do you have SWITCHING_NOZZLE enabled?
Maybe posting your configuration may help

Edit: 

> Why "no_move" at line 645 in tool_change.cpp?

where is nothing there with `no_move`

**Comment by scott0122** [comment]
@GMagician Yes, SWITCHING_NOZZLE is enabled.

Look at the video for detail.
https://drive.google.com/file/d/1VrWl4w-bKRG25sbjCk7RTzCCj40wxEXp/view?usp=sharing

After deleteing [if (!no_move)] at line 645 in tool_change.cpp, problem is gone.

**Comment by GMagician** [comment]
I think code has been changed and such line may be moved

**Comment by GMagician** [comment]
@scott0122 don't know if it's my PC but video doesn't start

**Comment by scott0122** [comment]
@GMagician here~ https://www.facebook.com/scott0122/videos/10217433481006970/

**Comment by GMagician** [comment]
I saw the video by the way I need you configuration to try to figure out why it act this way (why is this called with `no_move`)
I had Dondolo previously and it worked perfectly so or code has been changed or something in your configuration is not as expected

**Comment by scott0122** [comment]
Here is my configuration 
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2637269/Configuration.zip)

**Comment by GMagician** [comment]
You may try to change line 634 (current 2.0):
`current_position[Z_AXIS] += MAX(-zdiff, 0.0) + toolchange_settings.z_raise;`
with
`current_position[Z_AXIS] += MAX(-zdiff, 0.0) + (no_move ? 0 : toolchange_settings.z_raise);`
but logic has been changed since I used Dondolo and someone should take a look at this because the
`NOMORE(current_position[Z_AXIS], soft_endstop_max[Z_AXIS]);`
may create some bad behaviour when it limit position destroying real Z position

**Comment by GMagician** [comment]
@InsanityAutomation / @thinkyhead what do you think about above post? I think you changed last these lines

Edit: I really think that Z should also raise when `no_move` because nozzle should be far from workpiece when changing

**Comment by silentninja1** [comment]
Prior, there were several different z raise variables, and switching extruders were forced to a static 1mm. There is now a tool change z raise height defined in configuration_adv. Do you have anything defined here?

Also, no move should only be active when the machine is not homed or would move outside the limits. Typically that flag should not be set when printing by any accurate machine configuration and gcode.

**Comment by GMagician** [comment]
@silentninja1 the problem here, with this cnf, is that above code will change Z position but Z is not moved. Here is summary of involded code:
`current_position[Z_AXIS] += MAX(-zdiff, 0.0) + toolchange_settings.z_raise;` raised new tool position
`if (!no_move)planner.buffer_line(current_position, planner.settings.max_feedrate_mm_s[Z_AXIS], active_extruder);` axis is not really moved
`current_position[Z_AXIS] += zdiff;` current position is adjusted (raise is still there)
`sync_plan_position();` now system thinks z is raised with adjusted pos for new tool
`do_blocking_move_to_z(destination[Z_AXIS], planner.settings.max_feedrate_mm_s[Z_AXIS]);` move to original pos (but raise has never been done so axis move down)

**Comment by scott0122** [comment]
@GMagician @silentninja1  If no_move is true, raise is not performed. But after nozzle switched, hotend  is lowered.
I used to print with dual nozzles or T0 only, so I didn't find this problem.
I found this problem because I switch to T1 as active hotend and print by T1 only. 
When the printing starts, T1 drops below the platform.  Then the tragedy happens.

**Comment by GMagician** [comment]
@scott0122 have you tried my temporary solution?

**Comment by thinkyhead** [comment]
> `current_position[Z_AXIS] += zdiff;` … current position is adjusted (raise is still there)

The adding of `zdiff` is to deal with the configured difference in height of the two nozzles. The new nozzle may be at a slightly different height, even without any movement having been done.

> `current_position[Z_AXIS] += MAX(-zdiff, 0.0) + toolchange_settings.z_raise;` raised new tool position.

The `zdiff` is also used in deciding how far to (actually) raise the nozzle, at minimum, to ensure clearance when the newly-selected nozzle could be at a slightly lower height.

**Comment by GMagician** [comment]
@thinkyhead in second line I agree about zdiff but since you also add `z_raise` but you don't really move the axis because of `no_move` .. next in code you sync planner and again you move to destination hence Z will go move z_diff (and this is ok) but also z_raise (and this is wrong)

**Comment by scott0122** [comment]
@GMagician I just delete "if (!no_move)"
My opinion is that if Z HOME is not Z_MAX, Z will rarely reach Z_MAX. So if Z HOME is Z MIN, regardless of whether there is autohome or not, it is better to raise hotend before switching nozzles.

**Comment by GMagician** [comment]
I agree that nozzle must be always raised, my solution just adjust to new nozzle. Don't know what is better and I leave judgement to guys most smart than me

**Comment by InsanityAutomation** [comment]
I see two possible ways to make it work for everyone

One is a config option for tool change forced z raise, just like the lift for homing on a bltouch
that will raise that amount if !all_axes_homed(). This would be somewhat in line with what @GMagician mentioned above.

Second is a force homing before tool change config option so that the scenario that caused the servo to move a nozzle into the bed cant occur as it wont move a servo until its been homed, and in that case it will raise the configured amount as no_move will be off.

Any thoughts between the two methods?

**Comment by boelle** [comment]
@scott0122 problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by scott0122** [comment]
> @scott0122 problem solved?

What I need is always raise hotend, no matter what it is homed or not.
I think it should be configurable in Config.h or Config_adv.h

**Comment by thinkyhead** [comment]
I think we have an option for this now. Remind me to check. I vaguely recall we added it for beds that fall when not powered.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
