### ISSUE TITLE
M20 command cuts file names down to 8.3 format

### ISSUE THREAD

**Issue by bortek** [MarlinFirmware/Marlin#1263]
God bless MS-DOS but we do not want it here. :)

If you issues M20 command to list the files on the SD card , the returned list contain names which are cut down the length of 8 characters for filename and 3 characters to file extension. Here is an example

```
Send: M20
Recv: Begin file list
Recv: QUADCO~1.GCO
Recv: LAMPSK~1.GCO
Recv: GERLIT~1.GCO
Recv: End file list
Recv: ok
```

So was in older Windows versions when dir command issues in command prompt truncated long file names.

Can this be fixed in this project so we can upstream fix it in the Ultimaker2 firmware?

**Comment by nophead** [comment]
> The longer filenames are stored in a separate name translation file. That separate file can potentially be quite large

No they aren't. They are stored in small chunks in the directory as hidden volume id records, in reverse order IIRC. You need a buffer long enough to reconstruct one long name and a buffer for the directory records, but you need that anyway as they are the same size as the 8.3 entries.

**Comment by HedronUser** [comment]
Wish I could see what commit/code change fixed the SD filename truncation issue. This or something related is causing M23 to fail/work on my  Melzi 1284.

**Comment by thinkyhead** [comment]
@HedronUser It would be hard to track down exactly one change, as there have been several to the SD card code since this issue was originally posted. But we can start from where the code is now and try to solve your problem. Do you want to post a new issue about it?

**Comment by GrueMaster** [comment]
Just found this thread and I am puzzled.  I have two printers (Hictop 3DP-17 and CR-10S), both have different firmware (Hictop has Marlin 1.1.0-RC8 - haven't updated to 1.1.5 yet, and CR-10S has stock firmware).  Both have no problem displaying long names on the display (truncated to 40 character display width).  Since the displays are going through the Arduino boards to read the SD, there must be something there you can use.
