### ISSUE TITLE
Glitches on SD card SPI CLK line

### ISSUE THREAD

**Issue by jeffstaley** [MarlinFirmware/Marlin#12985]
I'm bringing Marlin up on a RemRam board (STM32F7) and I'm noticing glitches on the SD card's SPI clock line.  In the scope capture you can see three glitches on the clock (purple trace) line while the the chip_select (yellow) line is held low.  You can also see glitches on the MOSI line but those aren't so important. These glitches occur because Marlin is (re)initializing the SPI bus.  The STM32 core releases any existing resources (e.g. the CLK line) before (re)initializing the SPI bus, hence you see the CLK (and MOSI) line start to float high. A not unreasonable behavior.  But glitches on the CLK line is very bad while CS is held low.

My first thought is that Marlin shouldn't be (re)initializing the SPI bus while it's in the middle of using it (CS line held low) since -- I assume -- you can't expect frameworks to always (re)initialize the SPI bus glitch free.

Any thoughts?  Something that I'm missing?

![spi clock glitches](https://user-images.githubusercontent.com/3244368/51506625-0d815d00-1da2-11e9-8815-f13c10163f7f.PNG)

**Comment by hasenbanck** [comment]
Referencing the issue on the affected boards issue tracker:
https://github.com/hasenbanck/remram/issues/12

The glitch will produce consistent errors when an interrupt is firing while the device in initialized. Then it WILL be pulled to HIGH. This behavior of the CLK line and SPI device initialization while asserting the device (SD card) to active low is problematic for all SD card operations.

I don't know why this behavior is only manifesting on this STM32F7 board, but non the less, we shouldn't call ```spiInit()``` while the device is asserted to active low. I will try different fixes in software and will report back, once I found some solutions.

**Comment by gloomyandy** [comment]
Hmm the code in the Marlin SD2 interface is a little sloppy. It basically has a function (cardCommand) used to send a command, this will always call a function (chipSelect) before sending data. This chopSelect call will call spiInit and then set chip select low. The problem is that there can be multiple calls to cardCommand and each one will be calling chipSelect and hence spiInit. Which will cause the glitch with CS low.  I guess there are a few solutions...
1. In the spiInit code check to see if anything has changed and only actually do the init if needed (probably not a good idea, as it may be hard to be sure).
2. Refactor the SD2 layer so that chipSelect is no longer called from cardCommand, but is called from the outer functions just once.
3. Modify (or bodge!) the chipSelect (and chipDeselect) to track the state of the select line and only do anything if needed.

**Comment by hasenbanck** [comment]
@gloomyandy I would have tried to implement your suggestion number 1, since I'm familiar with the STM32 HAL. This might be enough, but I would still need to test it.

But I personally think that your proposed solution number 2 might be the cleanest solution overall, since it would solve the problem at the root cause. But I'm not familiar with that part of the codebase, so I might not be able to provide a fast implementation for that approach.

**Comment by gloomyandy** [comment]
Yes I think solution 2 is the best from a long term point of view. 

I'd be tempted to instrument the chipSelect and chipDeselect calls with a counter and check that to make sure that it was always 0 when select was called and always 1 when delelect was called, I'd also add code to the cardCommand to check it had a value of 1 when that call was made. Perhaps a little over the top, but it only takes a few minutes to add the code and it would help catch any special cases!

**Comment by hasenbanck** [comment]
Catching special cases is always a good idea.

**Comment by jeffstaley** [comment]
The major problem here is that the SD code is reinitializing the SPI bus numerous times once it has taken the bus (by pulling the CS line low). Good SPI practice is to 

	1. initialize the SPI HW
	2. take the SPI bus by pulling CS line low
	3. do the work (without reinitializing the SPI HW)
	4. release the SPI bus by pulling CS line high

I took a more in-depth look at just *one* of the SD card routines `Sd2Card::init`.  It's has multiple places where the SPI HW is reinitialized once the bus is taken.

	1. spiInit() is called directly after the bus is taken.
	2. spiSend() initializes the SPI HW
	3. cardCommand() initializes the SPI HW
	4. spiRec() initializes the SPI HW
	5. waitNotBusy() initializes the SPI HW

Some of these initialize the SPI HW via `spiInit()` and others via `spi_init()` but I suspect that this an STM32 Core issue.

I don't really know the SPI framework used here but you really want to use one that allows you to send and receive SPI data without initializing the SPI HW.  

Alternatively, you can consider not taking the SPI bus for the entire time. Perhaps you can release the SPI bus between each data packet. This might fit the framework usage pattern better since it wants to initialize the bus before each packet.  But you'd need to know whether this is acceptable for the SD card protocol since it might require the CS line held low for multiple packets.

**Comment by gloomyandy** [comment]
Not a good idea to release the CS during SD card operations. 

During initialisation of the SD card you need to change the speed used to communicate and it is spiInit that lets you do that, so there will need to be at least one call made while CS is low. But that is a special case and there are steps to ensure things are synchronised correctly after that call. In all of the other cases it should be possible to call the init before chip select is taken low.

@jeffstaley I'm a bit confused about your comments that spiRec, spiSend and waitNotBusy initialise the hardware. Is that STM32 specific, because I'm pretty sure that is not the case when running on the LPC1768X.

**Comment by jeffstaley** [comment]
@gloomyandy I saw SD card initialization changing the clock speed.  I've taken a brief look at the SD SPI protocol and from what I can see, once the card is initialized you can release the CS line, reset the clock speed and then take the CS line again.  But… I've only taken a brief look and these things are always more difficult than they first look.

Regarding those other commands and the LPC176x.  I drilled down and I think you are correct.  The LPC176x code directly sends the byte to the SPI HW (without a SPI init), while the STM32 and Teensy do a full
```
  SPI.beginTransaction(spiConfig);
  SPI.transfer(b);
  SPI.endTransaction();
```
which cause the SPI init.  The Due probably doesn't do a SPI init but appears to toggles the CS line on every byte so I don't see how that works at all.  It's all a bit of a mess.

As far as I can tell everyone is doing a SPI init on a `cardCommand`

**Comment by jeffstaley** [comment]
BTW the LPC176x method makes a lot of sense.  You really need a framework that'll allow you to send and receive bytes without initializing the SPI HW.

**Comment by gloomyandy** [comment]
The spiInit call made from cardCommand is wrong really and the code should be refactored so that spiInit is not called every time. As to releasing CS during the initialisation I'm really not sure to be honest. What I do know is that the SD card interface is not a typical SPI device and there are various special cases. The best reference I've found is this http://elm-chan.org/docs/mmc/mmc_e.html.

Yes the way that the different HALs handle SPI is very confusing, actually MArlin SPI in general is very confusing. I'm not at all convinced that the Due code is correct as as you have seen it messes around with the CS line, which does not seem correct to me.

**Comment by boelle** [comment]
@jeffstaley problem solved?

**Comment by jeffstaley** [comment]
No, it hasn’t been solved.

**Comment by boelle** [comment]
and this is a marlin issue not hardware?

**Comment by jeffstaley** [comment]
Definitely a Marlin issue.  Looks to me like there needs to be some 1) significant refactoring of SPI code  with regard to SD `cardCommand` since it's initializing the SPI bus and 2) a serious looking at the various SPI HAL code implementations.  I'm seeing wildly different different implementations of the SPI HAL such that I can't figure who's right.  For example, some SPI HAL's on a SPI Write initialize the SPI bus, others don't. One even toggles the CS line which seems totally weird.

**Comment by boelle** [comment]
@thinkyhead any thoughts on this one?

**Comment by boelle** [comment]
missing label
