### ISSUE TITLE
Autoleveling point grid

### ISSUE THREAD

**Issue by swario** [MarlinFirmware/Marlin#13004]
Hi
Can you add a voice in the menu with i can change the grid size for auto leveling???
The only way that i can find is modifying the firmware and then flashing it.
A controllable size can help to have a better estimate mesh for the bedvisualizer octoprint plugin 
Or another way can be to give to g29 command an extra optional argument that change teporarily the grid size.

**Comment by ManuelMcLure** [comment]
This is quite difficult due to processor limitations. To limit the amount of RAM being used things like `malloc()` and other functions that are available in C/C++ are not used in the Marlin code because they add a lot of memory overhead, so array sizes (such as the one that stores leveling data) need to be defined at compile time.

When/if Marlin runs on processors with multiple megabytes of RAM things may change, but I wouldn't recommend holding your breath.

**Comment by MasterPIC** [comment]
I still see the opportunity to "use" a smaller grid (made of fewer probing points than the available ones) at runtime to speed up probing for small prints.
With ABL it's still not possible. #10547

**Comment by boelle** [comment]
@swario problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
