### ISSUE TITLE
[Question] Pause lcd menu

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#13165]
Not sure but now when you put printer in pause (M25) when you restart default selected item is "purge" and not "resume"...shouldn't be default "resume"?

**Comment by InsanityAutomation** [comment]
There's a few reasons for the switch. Continue now has logic around the button to replace it with a disable run out if the switch is still in the open state. Every Purge statement checks again and tries to reset the run-out condition. The change in order allowed us to use a single conditional block for both of those swapping buttons instead of identical conditions above and below. Also Purge More is the safe function where resume is not therefore it most likely should have always been at the top.

**Comment by GMagician** [comment]
ok thanks for explanation
