### ISSUE TITLE
Display print time HH:MM:SS possible in 1.1.x?

### ISSUE THREAD

**Issue by n9jcv** [MarlinFirmware/Marlin#13224]
Has there ever been a request to have the current print time display the seconds as well as hours and minutes?  I looked thru the configuration but did not see any options like this.

Thanks
Bruce

**Comment by AnHardt** [comment]
Yes.
But what for?

**Comment by boelle** [comment]
and go for bugfix 2.0, its here things happens these days

**Comment by thinkyhead** [comment]
Marlin is open source so that customizations like this can be made for users that really want them. But this is not something we will be rolling into the main Marlin as a new feature. You should ask around the - RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415) for help if you're not sure how to make the needed modifications to get seconds to show on the display.
