### ISSUE TITLE
endstop settings

### ISSUE THREAD

**Issue by ebubekirn** [MarlinFirmware/Marlin#13375]
İ am using delta type 3d printer. Can anybody help about the endstop settings. Normally endstop settings like that:
//===========================================================================
//============================== Endstop Settings ===========================
//===========================================================================

// @section homing

// Specify here all the endstop connectors that are connected to any endstop or probe.
// Almost all printers will be using one per axis. Probes will use one or more of the
// extra connectors. Leave undefined any used for non-endstop and non-probe purposes.
//#define USE_XMIN_PLUG
//#define USE_YMIN_PLUG
#define USE_ZMIN_PLUG // a Z probe
#define USE_XMAX_PLUG
#define USE_YMAX_PLUG
#define USE_ZMAX_PLUG

// Enable pullup for all endstops to prevent a floating state
//#define ENDSTOPPULLUPS
#if DISABLED(ENDSTOPPULLUPS)
  // Disable ENDSTOPPULLUPS to set pullups individually
  #define ENDSTOPPULLUP_XMAX
  #define ENDSTOPPULLUP_YMAX
  #define ENDSTOPPULLUP_ZMAX
  //#define ENDSTOPPULLUP_XMIN
  //#define ENDSTOPPULLUP_YMIN
  #define ENDSTOPPULLUP_ZMIN
  //#define ENDSTOPPULLUP_ZMIN_PROBE
#endif

// Mechanical endstop with COM to ground and NC to Signal uses "false" here (most common setup).
#define X_MIN_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Y_MIN_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Z_MIN_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define X_MAX_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Y_MAX_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Z_MAX_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Z_MIN_PROBE_ENDSTOP_INVERTING false // set to true to invert the logic of the probe.

Do ı have to change something?

**Comment by shitcreek** [comment]
I grabbed this from the "generic" delta config file
[Configuration.h.zip](https://github.com/MarlinFirmware/Marlin/files/2955064/Configuration.h.zip)
Hope it helps. Also, this blog might have some useful information: http://wp.boim.com/?p=54

`// Specify here all the endstop connectors that are connected to any endstop or probe.
// Almost all printers will be using one per axis. Probes will use one or more of the
// extra connectors. Leave undefined any used for non-endstop and non-probe purposes.
//#define USE_XMIN_PLUG
//#define USE_YMIN_PLUG
#define USE_ZMIN_PLUG // a Z probe
#define USE_XMAX_PLUG
#define USE_YMAX_PLUG


#define USE_ZMAX_PLUG

// Enable pullup for all endstops to prevent a floating state
#define ENDSTOPPULLUPS
#if DISABLED(ENDSTOPPULLUPS)
  // Disable ENDSTOPPULLUPS to set pullups individually
  //#define ENDSTOPPULLUP_XMAX
  //#define ENDSTOPPULLUP_YMAX
  //#define ENDSTOPPULLUP_ZMAX
  //#define ENDSTOPPULLUP_XMIN
  //#define ENDSTOPPULLUP_YMIN
  //#define ENDSTOPPULLUP_ZMIN
  //#define ENDSTOPPULLUP_ZMIN_PROBE
#endif

// Mechanical endstop with COM to ground and NC to Signal uses "false" here (most common setup).
#define X_MIN_ENDSTOP_INVERTING true  // set to true to invert the logic of the endstop.
#define Y_MIN_ENDSTOP_INVERTING true  // set to true to invert the logic of the endstop.
#define Z_MIN_ENDSTOP_INVERTING true  // set to true to invert the logic of the endstop.
#define X_MAX_ENDSTOP_INVERTING true  // set to true to invert the logic of the endstop.
#define Y_MAX_ENDSTOP_INVERTING true  // set to true to invert the logic of the endstop.
#define Z_MAX_ENDSTOP_INVERTING true  // set to true to invert the logic of the endstop.
#define Z_MIN_PROBE_ENDSTOP_INVERTING true  // set to true to invert the logic of the probe.`

**Comment by 7eggert** [comment]
You should understand the meaning of the settings before changing them. Also you should test them by typing "M119" at the arduino serial console.

**REWRITE**, may still contain errors.

### Warning:
Do this at your own risk and make sure you understand what you are doing

### Switch types and inverting

There are NC and NO type sensors and switches.

NC switches will connect to GND* while NOT being triggered. There will be a pullup resistor connecting to VCC to provide a weak signal, this signal will be cancelled out by a strong connection to GND. VCC is the signal level of your mainboard, NOT 12 V but e.g. 5 V or 3.3 V

  _* They could connect to VCC instead, but I've yet to see this and this configuration is not subject of this text._

NO means no connection / VCC if the switch is detected or the sensor is active and connection to GND / 0V if the switch is pressed or the sensor detects proximity. This is called "INVERTING" because usually VCC means an active signal.

A switch could connect the signal wire to VCC / GND depending on it's state. Some sensors DO connect to VCC / GND depending on proximity.

### Existing setups

Just measure the voltage or use M119 and toggle the flag if the corresponding values are inverted.

### Beware of voltage

Some probes do send a signal of e.g. 12 V, higher than the mainboard logic can accept without damage. Be sure to have a level converter for these kind of probes - an optocoupler is recommended. If you are using a diode, the signal will be at 0.7 v and the AVR is not guaranteed (by manufacturer) to detect it correctly. Many sensors will need 6 V to work correctly (and thus send overvoltage).

### Probes

In addition to NC / NO logic, you need to mind NPN vs. PNP type and probes being neither nor.

NPN probes behave like a switch connecting to GND, PNP like a switch to VCC. You'll most likely want NPN types, I'll not talk about PNP.

Some probes do contain pullup resistors (or pulldown in case of PNP), and some probes are a combination of NPN and PNP by providing a direct connection to VCC and GND depending on their state. Consult the manual.

### Sharing

A probe using the Z endstop pin needs to be of the same type as the pin it's using, otherwise they'd interfere.
NO switches go in parallel to the NO probe, NC switches in series to NC sensors.

If the probe (or one of the switches) has two strong signal levels, connecting a switch in parallel is harmful. Instead the switch should go between the probe's signal wire and your mainboard. A NC switch should work and you need a pullup / pulldown resistor:

VCC when triggered: Pullup between switch output and VCC
Probe 0 V, switch not triggered: Signal from probe: not triggered
Probe VCC, switch not triggered: Signal from probe: triggered.
Probe any, switch triggered: Signal 5 V from **pullup**: triggered

VCC when NOT triggered: Pulldown between switch output and VCC, INVERTING
Probe 5 V, switch not triggered: Signal from probe: not triggered
Probe 0 V, switch not triggered: Signal from probe: triggered
Probe any, switch triggered: Signal 0 V from **pulldown**: triggered

### Optocouplers
(I'll write VCCp for the high voltage)

Optocouplers ("OC") are LED plus optical transistors, both sides operating at different voltages.
They need an input suitable to connect a LED. The output is usually - as far as I can tell - an NPN transistor.

On an NPN sensor, the input side of the OC should be connected:
Anode -> Resistor (e.g. 470 Ohm) -> VCCp
Cathode -> Probe Signal
Collector -> Mainboard signal, also pullup resiststor to VCC*
Emitter -> GND

 * may be internal on mainboard or in CPU

On a PNP sensor:
Anode -> Resistor -> Probe Signal
Cathode -> GND
Collector -> Mainboard signal, also pullup resiststor to VCC
Emitter -> GND

Probes having strong voltage: Chose one of the above and switch to invert the high-voltage LED logic.

Use a LED instead or in series with the OC to see the status:
LED on if triggered: Mainboard signal is GND when triggered, set INVERTING in Config
LED off if triggered: Mainboard signal is VCC when triggered, NOT set INVERTING in config

To add a switch:
NO switch, Mainboard signal is GND when triggered: Connect the switch to Collector and Emitter
NO switch, Mainboard signal is VCC when triggered: Insert switch in series with OC on the **low** voltage side
NC switch, Mainboard signal is VCC when triggered: Insert switch in series with OC on the **high** voltage side
NC switch, Mainboard signal is GND when triggered: You need to invert the high-voltage LED logic (not described here) or to add a second OC (easy solution).

There are **modules** with optocoupler - they may be inverting, contain additional drivers or pullup/pulldowns etc.. If you can tell by looking at the module, that's OK, otherwise beware.

### finally
I hope I got this right this time. Sorry for posting in a hurry. Also I didn't plan to write that much.

**Comment by kAdonis** [comment]
@7eggert Thanks for this elaborate explanation!
~~This is not quite correct.
It is possible to use NC Switches like you describe, but~~ I'm using NC (normally closed) switches with COM to GROUND and these also need  **pullup** resistors. This is what is described as "most common setup", because it has the advantage, that if a cable comes loose, the switch shows triggered, the axis doesnt move when homing, and you know that something is wrong.
With a NO (normally open) switch and a loose cable, you realize an error **after** the axis reached its mechanical limit with possible damage.

**Comment by 7eggert** [comment]
Sorry, you are correct.

**Comment by ebubekirn** [comment]
I have another problem about my endstops. When the arms touching the endstops they are not stop. They still trying to go up. İs this about NO NC settings? Can you help me? And ı am using three wire mechanical endstops. How must ı connect to my ramps 1.4 board? İn the inthernet generally 2 wire types. Please give some advices :) Thank you

**Comment by 7eggert** [comment]
What is your mainboard type? I'll assume RAMPS 1.4 (I'm currently in the process of changing my Anet to RAMPS).

Since I have a cartesian printer, I googled and found that: reprap.org/forum/read.php?178,495853 "Deltas never have min endstops". Thus your endstops would need to be connected to the max endstop pins. Make sure to not connect the switch to VCC and GND.

On my RAMPS, the sensor pins are blue, GND is black and VCC is red. The red pins should be unused, and the `#define ENDSTOPPULLUPS` should be set.

Having three pins, you can use NC or NO,  kAdonis suggested using NC if possible.

Some switches say "NC" and "NO" on the corresponding pins - use that pin and the third one, connect these to the signal pin GND. Don't configure inverting endstops. (If you had two-pin switches or an unlabeled switch, you can measure or guess.)

Open the arduino console, verify the baud setting (if you see a lot of lines starting with "echo", the baud setting is correct. On my RAMPS, I had to change the configuration from 250000 baud to 125200 and re-upload to make it work). Manually press each endstop (or gently move the mechanics, whatever is easier for you) and compare the result of M119 with the actual status of the switches. Do the values being displayed change by pressing a switch? Do they match your expectation?

(If you have two-pin switches, the status will be inverted. If you have three-pin switches and connect the NC and NO wire, ist should not work at all. If no switch is connected, all should read as "TRIGGERED").

If you have a voltage meter, you can measure the voltage at the switch's pins. It should read 5 V (or 3.3 V) and change to 0 V while pressing the switch for NO switches and the other way around for NC switches. (It may display negative voltages instead of positive, that's no problem.) If you always have 0 V, you may need to turn on the endstop settins or you may have connected the switch to the wrong pins.


My printer after homing (thus touching all the switches):
(I type M119)
Reporting endstop status
x_min: TRIGGERED
y_min: TRIGGERED
z_min: TRIGGERED

Move X away from the switch:
Reporting endstop status
x_min: open
y_min: TRIGGERED
z_min: TRIGGERED

Therefore I know that the X min switch is working correctly. I'd continue with Y and Z doing the same.

**Comment by boelle** [comment]
@ebubekirn figured it out?

since this is more a question than a bug please consider using discord or facebook

**Comment by 7eggert** [comment]
I think the answer should be in the documentation / moved to the wiki. (after being verified).
Also incidentally I stubled on this: www.thingiverse.com/thing:2906283
