### ISSUE TITLE
BIGTREETRECH SKR V1.3 32bit LPC1768

### ISSUE THREAD

**Issue by forkoz** [MarlinFirmware/Marlin#13448]
Since the old thread is closed....

My SKR 1.3 arrived today. Look forward to getting it working over the weekend. I know some pins have changed and I'm still not sure if they fixed the LCD cable orientation. Either way, sBase goes in the box and LV8729s can come out and play again. 

Going to try 1/64 stepping. I know most are going to use with TMCs and the wire-less software configuration. Maybe one day in the future.

I know marlin is ready for v1.1 but I haven't looked to see if 1.3 is set up already.

**Comment by ddB0515** [comment]
Pins for SKR 1.3 is already there and supported, check [pins_BIGTREE_SKR_V1.3.h](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/pins/pins_BIGTREE_SKR_V1.3.h) for more details

If you already tried it post issue what is specific related to board/config issue

**Comment by forkoz** [comment]
![SKR V1 3-STEP-DIR-Mode](https://user-images.githubusercontent.com/12354546/54791923-ead8bc80-4c09-11e9-9cc8-5eaa2741b7ec.png)
Ok what are the 5 jumpers there? They all came filled in. Not in any diagrams.

**Comment by ddB0515** [comment]
Here is example (Explained on page 15 [DRV8834](https://www.pololu.com/file/0J617/drv8834.pdf))
Hope this gonna help you to understand (also it is different for each motor driver) so best advice would be check datasheet

Here are details for [TMC2130](https://www.trinamic.com/fileadmin/assets/Products/ICs_Documents/TMC2130_datasheet.pdf) page 85

**Comment by forkoz** [comment]
Yea but what pin is that? To gnd or vcc? Most boards only give you the MSx pins and in their documentation that jumper doesn't even exist.

**Comment by ddB0515** [comment]
If you look schematic for SKR-V1.1 on their github **SKR-V1.1SchDoc.pdf** you can see that one side is connected to 3.3V(on this board that would be red pins) and other side to step motor driver (black pins)
(if you have multi-meter you can check connection easily)

Example
If you  wanna TMC-2130 to work in:
- SPI -  (jumper should be set to RED side) 
- STEP/DIR (all 3 opened/jumper removed) will give you 1/256 / Stealthchop1 (more in datasheet)

I can't  confirm yet as still didn't get my 1.3 board and schematic is missing so till than this is my assumption (based on 1.1 schematic)

**Comment by forkoz** [comment]
You misunderstand, there is no red side. There is only off and on. Its a 2 pin jumper.
![jumper](https://user-images.githubusercontent.com/12354546/54821304-bac40480-4c6f-11e9-97f1-991fdb3a5758.jpg)

**Comment by gloomyandy** [comment]
If you mean the red two pin socket that is vertical in your picture I think you will find that is provided to allow TMC drivers to feed the diag pin output into the board for sensorless homing etc. It is not a jumper it is an extension to the normal driver socket.

**Comment by forkoz** [comment]
YES! Thank you. It looked like a jumper.

**Comment by landodragon141** [comment]
I also just got mine yesterday. Anyone had a chance to play with it yet? I'll be running mine with 4 TMC2130s in SPI mode.

**Comment by gloomyandy** [comment]
I have a couple of TMC2208s hooked up and working to check that the new software serial works with it. But other than that I've not tried very much.

**Comment by forkoz** [comment]
Whats the max step rate for LPC boards? Think I can get away with 1/128?

**Comment by p3p** [comment]
80K before multistepping even kicks in, I haven't really tested at really high rates other than verifying pulse train generation though.

**Comment by forkoz** [comment]
It said on the reprap step page that 1/128 was achievable at 150mm/s and since I never exceed that I guess I'll give it a go. I think with what I have it gives something like 6k steps/mm when added up. So possibly its going into multistepping at that point. If I'm doing this right with it being 1500 @ 1/32 right now, its already hitting multistep after 53mm/s. If it sucks I guess I can just go lower.

**Comment by forkoz** [comment]
So of course I install my board and serial port "code 10: cannot start" and LCD doesn't display anything.
E0 is bad which is the cause of this.

Some observations on 1/128:
The printer is silent except for the Z axis.
It moves... real... sloooooooooooow.
Sending it g-code to go fast leaves it moving slow: ie:
G1 X180 F19200
G1 X20 F19200

At 1/64, motion is normal but for some reason I cannot turn up LV8729 past .50 which is 1A output power. I was able to on mks gen, here it just returns to 0. I will try on 1/32 it may be an issue with the board or the drivers or both.

Its all for nothing, e1 doesn't move.

**Comment by Yannik** [comment]
Anyone else having issue with E1? 

I've opened issues #13469 and #13470.

**Comment by forkoz** [comment]
heh, you made my sunday... i really hope its a marlin bug.

**Comment by p3p** [comment]
@forkoz 6K steps/mm @ 150 mm/s is 900K steps/s that's a fair bit above what we can support, I wouldn't go above 80K myself, micro-stepping is not that useful apart from making the motors quieter.

**Comment by forkoz** [comment]
Yep, I'm leaving it at 1/64... if that extruder can extrude. We could have just gotten 2 boards with defects.

**Comment by forkoz** [comment]
@yannik: you just made my week.....

Turns out marlin won't work if you have an E1 but no E0. Redefining the extruder pins did the trick.

**Comment by forkoz** [comment]
So all drivers in this board are run at 3.3v, there is a mod to fix it 
![LV8729](https://user-images.githubusercontent.com/12354546/54929893-45ad3500-4ee4-11e9-9eb1-559cc1136d7f.jpg)

**Comment by kAdonis** [comment]
@forkoz 
The above mod shouldn't be necessary. All drivers (in Stepstick- format) I know are fine with 3,3V,
even LV8729 and, according to Pololu, STSPIN820

**Comment by forkoz** [comment]
That's what I thought but my LV8729 vref would not adjust past .50 until I did this. Plus multiple people are telling me that LV8729 can't be used in E0 because of some compatibility issue.

**Comment by choryuidentify** [comment]
Bigtreetech publish SKR 1.3 Schematic.

https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/blob/master/hardware/SKR-V1.3-SCH.pdf

**Comment by stoicastefanv** [comment]
Hi guys. Hope you do not mind, im asking the same question ... Im an owner of skr1.3 about 12 ours .. Mi issue is with the lcd2004 i just uploaded the firmware and changed 2 perfectly working lcd2004 with ramps board. Had you encountered this issue how did you resolved it. I read something on the web that i need rotate 180 exp1 and exp2 plugins before putting them into the bord. Im asking because i do not whant to toast my board so quickly. 

Kind regards all and thanks

**Comment by forkoz** [comment]
Rotating EXP1 and EXP2 at only ONE end  is how I got my reprap discound full graphics display working on sBase.  I've put them the wrong way around before and didn't blow anything up. Supposedly SKR1.3 fixed the rotation issue on the connectors, and that holds true for RRGLCD. My 2004 is collecting dust since it never worked on sBase... so try it both ways and see if it works. On the FB group I saw a lot of people complaining that LCD2004 never worked.

**Comment by stoicastefanv** [comment]
No way ...:(( thank you alot ... Test time!

**Comment by stoicastefanv** [comment]
Yessss is working, allmost. For all others i had flipped 180 degrees the EXP1 connector..  But when i try to rotate the knob to go thru menue the MCU reset .. But i olso have an error (TMC connection error). Maybe if i clear the error it will stop reset itself.

**Comment by stoicastefanv** [comment]
i'm back with questions because i can not go further 
1. what is for the BOOT connector? located above the MCU?
2. i still get TMC connection error :( what i had done : 
for all TMC2130 V1.1 from BIGTREETECH soldered the two small pads and removed the R5 and diagnose pin for the endstops

![20190407_105825](https://user-images.githubusercontent.com/42040154/55680914-c29ace80-5928-11e9-981d-b2885006639f.jpg)

![20190407_102648](https://user-images.githubusercontent.com/42040154/55681164-c54af300-592b-11e9-950b-efd2f45f59e6.jpg)

mounted the jumpers according to image below
![jumpers](https://user-images.githubusercontent.com/42040154/55680978-bc592200-5929-11e9-9784-390830be4745.jpg)
but when i send M122 bad luck 

		X	Y	Z	E
Enabled		false	false	false	false
Set current	800	800	800	800
RMS current	1436	1436	1436	1436
MAX current	2025	2025	2025	2025
Run current	25/31	25/31	25/31	25/31
Hold current	12/31	12/31	12/31	12/31
CS actual		0/31	0/31	0/31	0/31
PWM scale	0	0	0	0
vsense		0=.325	0=.325	0=.325	0=.325
stealthChop	false	false	false	false
msteps		256	256	256	256
tstep		0	0	0	0
pwm
threshold		0	0	0	0
[mm/s]		-	-	-	-
OT prewarn	false	false	false	false
off time		0	0	0	0
blank time	16	16	16	16
hysteresis
-end		-3	-3	-3	-3
-start		1	1	1	1
Stallguard thrs	8	0	0	0
DRVSTATUS	X	Y	Z	E
stallguard
sg_result		0	0	0	0
fsactive
stst
olb
ola
s2gb
s2ga
otpw
ot
Driver registers:
		X	0x00:00:00:00	 Bad response!
		Y	0x00:00:00:00	 Bad response!
		Z	0x00:00:00:00	 Bad response!
		E	0x00:00:00:00	 Bad response!
Testing X connection... Error: All LOW
Testing Y connection... Error: All LOW
Testing Z connection... Error: All LOW
Testing E connection... Error: All LOW 
 
When i made the M122 test, the board was supplied from 24 v (jumper between INT and 5v)

Then started to look at the board to check the connections are according to the schematic:
[https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/blob/master/hardware/SKR-V1.3-SCH.pdf](url) 
and the MOT_MOSI MOT_SCK MOT_MISO are short to ground ???
![20190407_105552](https://user-images.githubusercontent.com/42040154/55681123-49e94180-592b-11e9-94be-ddad2e33c69d.jpg)
![20190407_105600](https://user-images.githubusercontent.com/42040154/55681124-4bb30500-592b-11e9-978a-6208c1695f0c.jpg)
![20190407_105635](https://user-images.githubusercontent.com/42040154/55681127-4ce43200-592b-11e9-800f-2128a6936395.jpg)
![20190407_105623](https://user-images.githubusercontent.com/42040154/55681128-4eadf580-592b-11e9-8c4f-0c147b4a5b18.jpg)
Can someone check this ? and sorry for the mess on my table
Is my interpretation wrong ? I'm doing something wrong?
Kind regards all

**Comment by jeroen85** [comment]
Did you enable #define TMC_USE_SW_SPI in configuration_adv.h? (that was my mistake while setting up the TMC2130 SPI on this board..)

**Comment by stoicastefanv** [comment]
Yes i double checked and is on enabled..!

**Comment by gloomyandy** [comment]
Have you tried just installing a single driver at a time into say the X location to see if any of the drivers work? Check them one at a time, if there is a problem with any of them it may cause all to report an error if you have the bad one installed.

**Comment by stoicastefanv** [comment]
Gllomyandy . Yes ... I done that too. All the drivers i put them in different places.  I olso removed sd card from hardware and software.... 
1.Maybe i undersood wrog .. I need jumper wires for SPI? Because no big thing .. I Installed everything according to the bigtreetech youtube video for skr1.3
2.Please while you keep the printer off on skr1.3 remove one driver and please check the continuity between mosi miso sck pins to GND.. As i made above. My big fear is that i have a short between pins and groud even i do no see it. Please someone chech
3.What is for the boot pins above MCU ?

Kind regars

**Comment by Hawxxer** [comment]
Same problem "TMC connection error". The "X-DIAG" pins must also be connected to the board right?

**Comment by stoicastefanv** [comment]
Hi there 
X-diag pin if you what not to use endstops and you use the TMC2130 as endstop
But i soldered only one pin not both as jumpers in the board because one is diagnostic and one is vref used by the driver. I was afraid not to interfear with MKS board
Can you please check continuity as i requested above ?   Kind regards

**Comment by Hawxxer** [comment]
OK I checked mine again and two of my drivers dont want to communicate. M122 shows that the other two works so thats my fault. But I checked you request. MOSI and SCK fluctuating around 100 Ohm MISO is HIGH Ohm. But you should definitly check with an logic analyser or oszi. Did you check when the Controller is off, than they should all be HIGH Ohm. 
![logic](https://user-images.githubusercontent.com/46371370/55876048-f844ef00-5b96-11e9-9235-6f1b9f2d7172.PNG)

**Comment by stoicastefanv** [comment]
What logic analyzer did you use?? I need one because i do not have. 
Yes the board was off and removed all the jumpers in order to eliminate anny posibility to be a short circuit ..  And that is why i think something is in short ... With the board on and off measurements are Low Ohm.
Your oppinion is not a defective bord but 5 defective TMC2130 drivers? 
Anny other ideas for me to check because im out.

**Comment by jeroen85** [comment]
I measured the same pins (X-axis) on my machine (no power). 
All four are about 600 Ohms. 
When the board is On, the values are different (some lower, some higher).

When I got the board there was some metal dirt on the connectors of the NXP CPU. Can there be some dirt on your pcb causing shorts?

**Comment by Hawxxer** [comment]
I use a saleae one, cause I got student discount idk if they are better than others, the build quality is good and bus sniffing works fine, software is some kind of strange but works too, maybe check them out. 

So I unpluged every Jumper on board (except of the Power Jumper set to Int +5V) + the board ist not plugged in and I always get HIGH Ohm  on every pin. 

> When I got the board there was some metal dirt on the connectors of the NXP CPU. Can there be some dirt on your pcb causing shorts?

Yeah check this definitly I killed three tmc2130 cause of solder or dust on the pcb maybe also connected solder joints like on the picture. 

No I dont think all of your five TMC2130 are defect, maybe its the board





 
![WIN_20190410_14_10_40_Pro](https://user-images.githubusercontent.com/46371370/55907361-dc613d80-5bd6-11e9-8a78-703cf3bd6083.jpg)

**Comment by zombu2** [comment]
turns out when the board is only connected to usb the trinamics don't talk they need power from the 24v input

**Comment by ghost** [comment]
BigTreeTech/MKS have no QC and don't test their boards properly (if at all), you often get faulty boards with components badly placed, shorts between pads etc :( .. I know from experience.

**Comment by zombu2** [comment]
It sure looks like some components moved on that board or didn t get aassembled right 
the 2 board i have are clean

**Comment by stoicastefanv** [comment]
Ive done everything so far... Nothing works...thank you all for help... As last resort i will try using dupond cables (not to bend or cut the tmc2130 pins) to install them on ramps board and then back to skr1.3 but to use different mosi moso sck pins i think the one used for the LCD. I will get back with updates.
Kind regards all

**Comment by stoicastefanv** [comment]
Hi all, as previously told i got back with updates:
I used 12V ATX power supply +  Arduino mega + ramps 1.4 + Marlin 1.1.9
Do not lough because it works, :))

![20190416_182156](https://user-images.githubusercontent.com/42040154/56233208-42443e00-608b-11e9-8291-4652a1834f5a.jpg)
![20190416_182219](https://user-images.githubusercontent.com/42040154/56233216-46705b80-608b-11e9-8183-22821b2684d2.jpg)
![20190416_210329](https://user-images.githubusercontent.com/42040154/56233224-48d2b580-608b-11e9-88d3-888944e890bd.jpg)

I use Dupond wires to connect TMC2130 and ramps because i did not wanted to bend or cut mosi miso sck and cs pins
Attention when define the CS pin not to overlap with MOSI MISO SCK default pins in pins_RAMPS.h

Changes i had done in Marlin:

Configuration.h
> #define SERIAL_PORT 0
> #define POWER_SUPPLY 1
> #define X_DRIVER_TYPE  TMC2130
> // For Inverting Stepper Enable Pins (Active Low) use 0, Non Inverting (Active High) use 1
> // :{ 0:'Low', 1:'High' }
> #define X_ENABLE_ON 1
> //#define SDSUPPORT`

Configuration_adv.h
> // Microstep setting (Only functional when stepper driver microstep pins are connected to MCU.
> #define MICROSTEP_MODES { 16, 16, 16, 16, 16 } // [1,2,4,8,16]
> #define X_MAX_CURRENT     1000 // in mA
> #define X_SENSE_RESISTOR    91 // in mOhms
> #define X_MICROSTEPS        16 // number of microsteps
> //#define TMC_USE_SW_SPI
if i uncomment define #define TMC_USE_SW_SPI and set CS to 44 will not work because il interface with the pins defined in pins_RAMPS.h
> #define STEALTHCHOP
> #define TMC_DEBUG

pins_RAMPS.h
> #define X_STEP_PIN         54
> #define X_DIR_PIN          55
> #define X_ENABLE_PIN       38
> //#define X_CS_PIN         53
> #define X_CS_PIN         44
> //#ifndef X_CS_PIN

if you uncomment above //#define TMC_USE_SW_SPI below pins will be assigned and will not work because will conflict pin 44
> /**
>  * Default pins for TMC software SPI
>  */
> #if ENABLED(TMC_USE_SW_SPI)
>   #ifndef TMC_SW_MOSI
>     #define TMC_SW_MOSI    66
>   #endif
>   #ifndef TMC_SW_MISO
>     #define TMC_SW_MISO    44
>   #endif
>   #ifndef TMC_SW_SCK
>     #define TMC_SW_SCK     64
>   #endif
> #endif

by uncommenting //#define TMC_USE_SW_SPI will use by default 
> pin 50 MISO
> pin 51 MOSI
> pin 52 SCK

result is 

> SENDING:M122
> 		X
> Enabled		true
> Set current	800
> RMS current	795
> MAX current	1121
> Run current	25/31
> Hold current	12/31
> CS actual		12/31
> PWM scale		255
> vsense		1=.18
> stealthChop	true
> msteps		16
> tstep		1048575
> pwm
> threshold		0
> [mm/s]		-
> OT prewarn	false
> OT prewarn has
> been triggered	false
> off time		5
> blank time	24
> hysteresis
> -end		2
> -start		3
> Stallguard thrs	0
> DRVSTATUS	X
> stallguard
> sg_result		0
> fsactive
> stst		X
> olb
> ola
> s2gb
> s2ga
> otpw
> ot
> Driver registers:	X = 0x80:0C:00:00

i think everything is ok, at least TMC2130 is communicating with the Arduino board, i did not make any move. i did not connect the stepper to the driver 
If i had done something wrong please correct me.
Now i will try to move everything i had learned to SKR 1.3 i will get beck with updates

**Comment by glebozaur** [comment]
Hi guys. I have a delta. Please help me solve the problem with SKR v1.3 + TMC 2130 v1.1 via SPI. Drivers work correctly, but the Sensorless Homing does not work. With mechanical endstops drivers work fine. I tried to weld a pin to diag1 connection on X,Y,Z and it caused no any changes. I put all jumpers correctly as indicated in Biqu instruction and I modify Config files also as indicated in official youtube BIQU video instruction. I dont know what to do. Here is my video of Sensorless Homing failed: [https://youtu.be/jiGckFfKWgE](url)
![20190416_195954](https://user-images.githubusercontent.com/49695258/56237873-bbe12980-6095-11e9-955f-c7ca00b866a4.jpg)
![image](https://user-images.githubusercontent.com/49695258/56237916-db785200-6095-11e9-8981-e18810bef58e.png)
![2019-04-15_22-56-58](https://user-images.githubusercontent.com/49695258/56237972-019df200-6096-11e9-8723-3b138d6f5a37.png)
![2019-04-15_22-56-21](https://user-images.githubusercontent.com/49695258/56237973-019df200-6096-11e9-9ff8-3a208a30b7ec.png)
![2019-04-15_22-56-06](https://user-images.githubusercontent.com/49695258/56237974-02368880-6096-11e9-8d9c-f8e5bf4c4771.png)
![2019-04-15_22-55-27](https://user-images.githubusercontent.com/49695258/56237975-02368880-6096-11e9-8ca6-fe8299cd6807.png)

**Comment by Black6spdZ** [comment]
In the same boat.. CANNOT get movement from my TMC2130s.. M122 shows connection OK on all 5 but enabled is "false". Invert stepping pins enable makes no difference. Im at a loss

**Comment by Black6spdZ** [comment]
Ahah.. Success.. I had enable invert to 1 and software enable to 1 as well, used those on previous 1.1 board

**Comment by ritor1sefa** [comment]
Black6spdZ, 
I did not find the possibility of private messages here, unfortunately.
So what did you do in the end? I get garbage, as I do not switch: https://i.imgur.com/cfzi3qq.png
X	0xFF:FF:FF:FF	 Bad response!
Testing X connection... Error: All HIGH
Share, please, configs: Configuration.h Configuration_adv.h & pins_RAMPS.h

**Comment by Black6spdZ** [comment]
Make sure your drivers are configured for SPI mode like this photo.. "Jumpers on cfg4-5 and NO R5
https://cdn.shopify.com/s/files/1/1619/4791/files/wire.png?v=1531713659

**Comment by ritor1sefa** [comment]
I bought the kind of already configured in the mode.
https://i.imgur.com/7Qopqy1.jpg

**Comment by stoicastefanv** [comment]
Guys i have an issue / i whant to prevent some smoke... 
1.I have some new steppers 42GYGHM810 is 0.9 degrees 2.4A 0.8 ohms
2.I use 24v 10A power supply
3.And TMC2130 ...with 1.2A max RMS and 2.5A Peak

I would expect if i use a bigger voltage 24v i will lower the amps used by the stepper. But if i go to ohms law... I=v/r = 24v/0.8 ohm = 30A is backwords. And something will blow up

And going to marlin to set up the rms current 
2.4A/1.41 = 1.702v = 1702 mv in marlin 

The question is... Im doing something wrong ? 
Somethig will blow up?
The 24v 10A power supply will blow up? 
I will use 4 x 2.4A stepper (2 for z) + 1.5A for E + 24v heat bed ... What do you think too much load.? Again i was expecting to rise the voltage to lower the amps 


Kind regards all

**Comment by ritor1sefa** [comment]
stoicastefanv, 2130 is not the best choice for high loads.  Also, 2130 is very hot.
5160 is more profitable in terms of parameters (but also 2 times more expensive -_-).
https://github.com/teemuatlut/TMCStepper/issues/3

**Comment by ritor1sefa** [comment]
Black6spdZ, In a mysterious way, everything worked for me. Mysteriously. With the chip, I did nothing, in the end, I did not solder my legs, I did not change anything.
The problem was somewhere in the firmware.
Thanks for the help.

**Comment by Black6spdZ** [comment]
@stoicastefanv , current isn't calculated using simple ohms law with steppers.. the drivers are smart in that they use a closed loop feedback PWM to modulate the current to whatever you set either the pot or SPI software setting at regardless of input voltage

@ritor1sefa glad you got it going, I fought with mine for a couple days until I realized that there was a hardware setting on the BIQU 2130s for either standalone or SPI mode

**Comment by ritor1sefa** [comment]
@Black6spdZ, Yes, I had to turn on TMC_USE_SW_SPI, which is strange, I think. Because I physically placed all the jumpers, why also programmatically include? -_-

**Comment by Black6spdZ** [comment]
@ritor1sefa  oh yea, definitely need that enabled if using the 2130s in SPI mode and not standalone mode

**Comment by ghost** [comment]
I have been messing the Bigtreetech SKR v1.3 for just about a week now trying to get Marlin 2.0 loaded up on this board, but it’s definitely not functioning properly and I will probably be returning it. First problem I am having is The board, when plugged in via usb to my computer is not recognized as a USB device. I’ve tried different drivers, removing the SD card and running that via usb, reformatting the SD, nothing works. So there’s that. But the main issue is that for some reason, Marlin 2.0 does not seem to like this processor NXP 1786. Using the Bigtreetech github version of Marlin 2.0 does not help. A freash version of Marlin 2.0 does not work, changing the Motherboard type within the Configuration.h file to the Bigtreetech SKR v1.3 board does not help. There is a compilation error no matter what I do with this board as the selected motherboard in Marlin 2.0. I've obviously referenced boards.h to ensure I am defining the correct board. If I change the motherboard to something different, the firmware.bin file compiles just fine! And before anybody says to downgrade to Marlin 1.9, this board is not supported is any previous versions of Marlin! I’ve tried everything. No dice. By the way- I am using VScode with the PlatformIO extension. Changing the environment within the Platform.ini file to the 1768 environment. No dice. I keep getting a bunch of errors. I can show you my error log if anybody is willing to help?

**Comment by Grogyan** [comment]
One thing you can try is to upload the Smoothieware bootloader
You will need a USB to UART converter to do so

**Comment by ghost** [comment]
Thanks but I had my sights set on Marlin. I just ordered a MKS Gen L v1.0 going to give that board a shot I guess.

**Comment by stoicastefanv** [comment]
I can give you my drivers ... And my marlin file but how do i send you the files?  Watch out i have an windows 10 and when i wanted to install the working driver it told me that is not valid... It was needed to desactivate windows driver chech.. Shif + restart... You done something like this?
Your goal is to have access to sd card not to skr board because this time you upload the firmware to sd. 
I have an issue with slow compile times. Comparing arduino with vs stidion is 10 times slower

1 I have a question of my own.... Guys when homing did you have an issue to go in the other way ... Or go in other way and camming back ? 
2 anny one tried to install leds on skr ?

**Comment by ghost** [comment]
The windows USB driver for the SKR 1.3 board is in ..

Marlin\src\HAL\HAL_LPC1768\win_usb_driver

**Comment by ghost** [comment]
@stoicastefanv @doggyfan thank you both very much. I will try that driver file. Would you email me your Firmware.bin file for testing? Email is: yigavegu@air-blog.com (it’s a temp email address). Thank you.

**Comment by stoicastefanv** [comment]
Guys why drv8825 provide enough current to move both z steppers and TMC2130 is skipping steps (no movement at all) VREF on tmc2130 is 2.3v and in marlin i set up rms 2290 i think is maximum ?
Can i change anything else in order to rise up current
@Mbombace your email is still availabe?  I will send you the bin file.. I dont think is good because i have different settings.. But if you think is ok i will send.

**Comment by stoicastefanv** [comment]
Guys why drv8825 provide enough current to move both z steppers and TMC2130 is skipping steps (no movement at all) VREF on tmc2130 is 2.3v and in marlin i set up rms 2290 i think is maximum ?
Can i change anything else in order to rise up current
@Mbombace your email is still availabe?  I will send you the bin file.. I dont think is good because i have different settings.. But if you think is ok i will send.

**Comment by Bob-the-Kuhn** [comment]
As you increase the number of microsteps and enable things like stealth mode you need more current to drive the stepper.  

If you disable all the fancy TMC modes and set the microsteps the same, the DRV & TMC behave almost the same until you run up against the lower current capabilities of the TMC2130.

Seems strange to invest almost as much into the stepper drivers as in the controller but the TMC5160 is your best bet for a quiet system that isn't stressed thermally.  You do need to be careful about the temperature of the steppers when running the TMC5160.

**Comment by ritor1sefa** [comment]
I have the same problem.
I checked the motor-wires - the E1 extruder is working.
After, did:
#define EXTRUDERS 1 // was, for checking, 2
#define Z_DUAL_STEPPER_DRIVERS // uncommented
Does not work!

I tried to change in pins.h:
#define Z2_STEP_PIN E1_STEP_PIN
#define Z2_DIR_PIN E1_DIR_PIN
#define Z2_ENABLE_PIN E1_ENABLE_PIN

Similarly.

I also tried to change pins in pins_BIGTREE_SKR_V1.3.h
#define E1_STEP_PIN P0_22 // P0_01 -def
#define E1_DIR_PIN P2_11 // P0_00
#define E1_ENABLE_PIN P0_21 // P0_10
#ifndef E1_CS_PIN
#define E1_CS_PIN P1_10 // P1_01
#endif

Does not react. (I left Z_DUAL_STEPPER_DRIVERS enabled)
What could be the problem?

**Comment by ritor1sefa** [comment]
solved. just:
define
#define Z2_DRIVER_TYPE TMC2130
and comment
//#define E1_DRIVER_TYPE TMC2130
https://github.com/MarlinFirmware/Marlin/issues/13470
