### ISSUE TITLE
2.0 UI extruder steps adjustment error

### ISSUE THREAD

**Issue by cinealfa** [MarlinFirmware/Marlin#13696]
Steps adjustment for extruder doesn't work as expected

1 Go to steps per mm menu
2 try to adjust extruder steps let's say the current setting is 400 steps
.

**Expected behavior:** [What you expect to happen]
The number should reflect the setting in memory and you should be able to go higher than 168.

**Actual behavior:** When the adjustment number is brought up it is now 5
 If you try to bring the adjustment back to 400 it will not go higher than 168.
 if you stop at 168 and the reselect it will NOT go any higher. You can reset the eeprom and the correct number will return
[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/3077591/Archive.zip)

**Comment by zombu2** [comment]
i see the same thing happening also extrusion does not work when you use the display and it resets the board

**Comment by cinealfa** [comment]
interesting, What board are you using? I am using MKS Sbase

**Comment by zombu2** [comment]
bigtreetech SKR v1.3

**Comment by marcio-ao** [comment]
I confirm this problem on an 8-bit RAMBO board.

**Comment by marcio-ao** [comment]
I know what is happening. Will make a PR with the fix.

**Comment by marcio-ao** [comment]
So, the reason this is happening is because the format used for steps is float62. This has a multiplier of 100:

```
DECLARE_MENU_EDIT_TYPE(float,    float62,     ftostr62rj,    100     );   // 1234.56    right-justified
```

At  400 steps, 400*100 is 40,000, which is greater than the maximum int16_t values used in MenuItemBase:

```
class MenuItemBase {
  private:
    ...
    static int16_t minEditValue, maxEditValue;
    ...
}
```

Notice that the maximum values expressed by `int16_t` is 0x3FFF, which translates to 16383. Divide out the multiplier of 100 and you get 163.83.

So, a couple possible solutions:
  1) Change the types of minEditValue, maxEditValue to int32_t
  2) Change the formatting used in the menu items for steps from float62 (which uses a multiplier of 100) to float51 or float3 (which uses a multiplier of 10 and 1, respectively)

In our LULZBOT FW, we use float3, because it does not make sense to us to have faction of steps. If there is a need for maintaining fractional steps, changing the format to float51 will allow a 10th of step while increasing the range from -163.83 to 163.82 to -1638.3 to 1638.2, which is probably sufficient for most cases.

@thinkyhead: I was going to do a PR, but since I am not sure what solution you prefer, I am throwing this in your court :)

**Comment by marcio-ao** [comment]
Actually, I just tried float51 and it allows the value to go negative... So that's not a fix.

**Comment by cinealfa** [comment]
Marcio,
What a clear concise explanation. Thank you very much.
Does it make sense to put some check to prevent a negarive number?

**Comment by marcio-ao** [comment]
@cinealfa: That's not the problem. The problem is that the use of `int16_t` in `MenuItemBase` is not large enough to capture the entire number when multiplied by the multiplier.

Here is a table of the edit values, the multiplier, and product of the two:

| Format      |       Range     | Mult  | Range * Mult     |
| ----------- | --------------- | ----- | ---------------- |
| percent     |     0%     100% |  1    |    0        100  |
| int3        |   -99       999 |  1    |  -99        999  |
| int4        |  -999      9999 |  1    | -999      9,999  |
| int8        |  -128       128 |  1    | -128        128  |
| uint8       |     0       255 |  1    |    0        255  |
| uint16_3    |   -99       999 |  1    |  -99        999  |
| uint16_4    |  -999      9999 |  0.1  |  -99        999  |
| float3      |     0       999 |  1    |    0        999  |
| float52     |     0    999.99 |  100  |    0     99,999  |
| float43     |     0     9.999 |  1000 |    0      9,999  |
| float5      |     0     99999 |  0.01 |    0        999  |
| float51     | -9999.9 +9999.9 |  10   | -99,999  99,999  |
| float52sign | -999.99 +999.99 |  100  | -99,999  99,999  |
| float62     |     0   9999.99 |  100  |    0    999,999  |
| long5       |     0     99999 |  0.01 |    0        999  |

Since the range of `int16_t` is only -32768 and 32768, it seems that any LCD items using `float52`, `float51`, `float52sign` and `float62` will not be able to cover the entire range.

Given the pervasiveness of the problem, I think changing the types of `minEditValue` and `maxEditValue` from `int16_t` to `int32_t`. The downside of this is that it may increase Marlin's compiled size by quite a bit.

**Comment by marcio-ao** [comment]
> Given the pervasiveness of the problem, I think changing the types of minEditValue and maxEditValue from int16_t to int32_t. The downside of this is that it may increase Marlin's compiled size by quite a bit.

Just an updated, this didn't work either. The fundamental problem is that the encoder using an int16_t. See my PR for an alternative fix that lops one decimal point of the steps per mm adjustment in order to give an effective range of 0.0 through 3276.7

**Comment by marcio-ao** [comment]
@cinealfa: Can you check the latest build and close this ticket if it resolves the issue for you?

**Comment by ghost** [comment]
Still faulty for me in the latest build.

**Comment by marcio-ao** [comment]
@doggyfan: What is your steps/mm set to?

**Comment by ghost** [comment]
X: 40
Y: 40
Z: 400
E0: 84.9
 
I go to edit them on the LCD I get 3108.2 with all of them.

**Comment by marcio-ao** [comment]
Hummm, interesting. Let me double check.

**Comment by marcio-ao** [comment]
I'm definitely not seeing that problem. Do you have an 8-bit or 32-bit board?

**Comment by ghost** [comment]
32-bit BTT SKR v1.3

I'll try it on the MKS GEN v1.4 8-bit board, hold on

**Comment by ghost** [comment]
It's OK on the 8-bit MKS board, just not on the BTT SKR 32-bit board.

I'm using Atom/PlatformIO for compiling.

**Comment by marcio-ao** [comment]
@doggyfan: Okay, I'll rig up a 32-bit board and do some testing.

**Comment by marcio-ao** [comment]
@doggyfan: Able to confirm this on a 32-bit Archim. I will look into it. Thanks for reporting.

**Comment by marcio-ao** [comment]
@doggyfan: Easy fix. I made a PR for it. #13737

**Comment by ghost** [comment]
Well done :)

I'll test it when it's out.

**Comment by ghost** [comment]
That's fixed it :)

Well done and thank you Marcio.

**Comment by cinealfa** [comment]
I will try the fix as well thank you @marcio-ao

**Comment by cinealfa** [comment]
Well I cant seem to compile I dont recal changing anything but 
![Screen Shot 2019-04-20 at 1 18 51 PM](https://user-images.githubusercontent.com/32920432/56461892-e6b9cf00-636e-11e9-96b5-2dac718afda0.png)
now I get this error: 
[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/3100558/Archive.zip)

**Comment by cinealfa** [comment]
still unable to compile...

**Comment by cinealfa** [comment]
anyone?

**Comment by marcio-ao** [comment]
@cinealfa: No clue. We build both 32-bit and 8-bit firmwares and I have not come across that error. Have you done a pull recently from the repo?

**Comment by cinealfa** [comment]
@marcio-ao thank you for your response
Forgive me but I don't know what "a pull recently from the repo" means. I am a bit of a noob :) From what i do understand i belive you are asking if I changed the code? The answer is no, I simply downloaded the latest zip and tried to compile it.

**Comment by marcio-ao** [comment]
@cinealfa: Try the absolute latest source.

**Comment by cinealfa** [comment]
Well good news, bad news I now can successfully compile the latest version but unfortunately I get the thermal runaway error #13783 so I am stuck until that is actually addressed. Frowny face lol

**Comment by cinealfa** [comment]
Works as advertised!!!!

**Comment by marcio-ao** [comment]
@cinealfa: Glad to hear!
