### ISSUE TITLE
[Help] Bl Touch V.3 Setup

### ISSUE THREAD

**Issue by SpaceTunez** [MarlinFirmware/Marlin#13700]
### **Description**

I'm going to be completely honest, i am a noob when it comes to the programming aspect in regards to the marlin firmware.

I am aware there is a bug with the Bl Touch v.3 that is being worked on for the CR10 but supposedly marlin bug fix 2.0.x works with the proper settings. If it isn't too much to ask can i get a step by step on how to implement this code because i constantly get an error that says "Error compiling for board Sanguino" and i don't know what to do.

**Comment by reloxx13** [comment]
Do you want to ask a question? Are you looking for support? Please don't post here. Instead please use the Marlin Firmware forum at http://forums.reprap.org/list.php?415 or the Marlin Facebook Group https://www.facebook.com/groups/1049718498464482/.

Before filing an issue be sure to test the 1.1 and/or 2.0 "bugfix" branches to see whether the issue is already addressed.


#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
