### ISSUE TITLE
SKR 1.3 TMC2208 bad comms

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#13748]
At startup Marlin v2 sends a byte (should be 4 ?) to the TMC2208 and receives an 8 byte zero response for an unknown reason (Using SoftwareSerial).

I notice the UART data doesn't go all the way down to 0V, but that's a hardware design thing, although haven't yet look to see how the CPU pin is set in the software serial code. The TMC2208 chip seems to see the data OK (it responds) ?

If the TMC2208 driver is moved to my 8-bit MKS Gen 1.4 board with the same compiled Marlin code (but 8-bit), it's fine, no problems at all.

![Sds00003](https://user-images.githubusercontent.com/49303635/56354021-afaab880-61ca-11e9-9702-be80b5aa692b.jpg)

**Comment by ghost** [comment]
The boards seem to be talking to the TMC2208 chips, but the SKR 1.3 board displays "TMC CONNECTION ERROR" on the LCD, and the TMC2208 is not configured properly. 

The MKS Gen board works fine with the very same TMC2208's boards plugged in.

Any ideas ?

8-bit MKS Gen v1.4 ..`

![8bit_MKS_Gen_1_4](https://user-images.githubusercontent.com/49303635/56356844-dcae9980-61d1-11e9-98f9-5a6d84ee71ce.jpg)

32-bit BTT SKR v1.3 ..

![32bit_SKR_1_3](https://user-images.githubusercontent.com/49303635/56356846-dfa98a00-61d1-11e9-9962-822b5a285e06.jpg)

My heavily edited config files ..

[Config_Files.zip](https://github.com/MarlinFirmware/Marlin/files/3094121/Config_Files.zip)

**Comment by gloomyandy** [comment]
Many, many folks have TMC2208 working with Marlin on that board (it has been very popular) so I'm pretty sure that whatever problem you have is either down to your setup or hardware. Things to check...
1. Are you using the latest Marlin from the Marlin github (not the one from bigtreetech)?
2. Is you platformio up to date (you need to be using the latest LPC1768 framework).
3. Are you sure you have the jumpers on the SKR board configured correctly. Remove all jumpers from under the board, make sure that you have the UART jumpers in place (just in front of the driver boards). Post a picture if possible.
4. Make sure that you are powering your board using the power jumper set to "int" not to "usb" and that you have 12/24V supplied.
5. Are you sure that you have your driver boards setup correctly? There are many slightly different boards and each one needs a different configuration. In particular the SKR board uses the pin next to the PDN pin for UART comms, many other setups use the PDN pin. On some boards this is marked NC on others UART. Some driver boards require that you add a solder bridge between the PDN pin and the NC/UART pin. Just because your drivers work on the MKS board does not mean that are configured correctly for the SKR. Again post information as to which drivers you have and pictures of how you have them setup.

I've tried to look at your configuration files but I can't unzip them (how did you create the zip file?). Either way I would suggest that rather than using a heavily modified config you start with the basic Marlin files and make minimum changes to just get your drivers working, then add the complex stuff later.

**Comment by ghost** [comment]
Yes to all 5 questions. That's what's stumped me, I didn't want to bother anyone on here but am at a loss at the moment.

The board is powered with a stable 24V.

I'll use clean config files to start with but am sure it won't make any difference, I'm many years development engineer in hardware and software and firmware etc, so not a boob that's for sure.

It's good to know many others have them working fine, that's encouraging. Thank you for replying etc GloomyAndy. I followed your thread on here about you updating the SoftwareSerial code to the lower baudrate etc, good work!

I contacted BigTreeTech about the board saying that the software UART for the TMC2208's can work in single pin mode and to maybe produce a 1.4 version board to free up the UART TXD pins for whatever the user wants to do with them (5 extra pins), extra servo pins or whatever.

I'll get back to you guys shortly. I may have to try some debugging in the software serial driver code etc to get a better idea of what's going wrong, because it does look like the TMC2208 is replying, though not yet sure, I'll check the scope without the TMC2208 plugged in, see what the UART data line is like then.

![Dsc00104](https://user-images.githubusercontent.com/49303635/56364792-5bfa9800-61e7-11e9-809b-7c14e51cdcdc.jpg)
![Dsc00105](https://user-images.githubusercontent.com/49303635/56364797-5ef58880-61e7-11e9-9010-e65f084bf802.jpg)

Try this zip file (I use WinRAR) ..

[Config_Files.zip](https://github.com/MarlinFirmware/Marlin/files/3094647/Config_Files.zip)

**Comment by ghost** [comment]
My bad :(

The SKR 1.3 board UART is fed to the N.C pin on the TMC2208 driver boards (I missed that difference).

My MKS Gen 1.4 board has the UART pin on the PDN pin on the TMC2208 driver boards.

Soldered the PDN to the N.C pin on each driver board and now the SKR 1.3 is working.

This thread can be deleted if you want. So sorry I bothered you with this gloomyandy.

**Comment by gloomyandy** [comment]
No problem! Glad you found the cause. Yes it is a little unfortunate that they choose to use the "UART" pin rather then PDN. It has caused a lot of people issues!

**Comment by ghost** [comment]
;)
