### ISSUE TITLE
[BUG] (Long beep on start or reset)

### ISSUE THREAD

**Issue by SISLANGER** [MarlinFirmware/Marlin#13965]
### Description
Printing well on SKR V1.3 set EEFFB

On startup and reset getting large beep even if speaker disabled.
Weird blips before the Marlin Logo not weird characters from firmware update via SD.

Any ideas Why the beeping?

### Steps to Reproduce
In my case turning on or resetting.

**Expected behavior:** [What you expect to happen]
No beep on startup

**Actual behavior:** [What actually happens]
Banned from using printer at night because of loud long beep when resetting or turning on. I am trying to get PS-On and neopixel working on it so constantly changing config at moment.

**Comment by ManuelMcLure** [comment]
Let me guess... you have a ReprapDiscount Full Graphics display? Unfortunately there's nothing Marlin can do about this - the RRD display will beep from receiving power until it has been properly initialized and that doesn't happen until after the bootloader has actually started Marlin. You'll notice that it actually beeps for longer when you upload new firmware because the bootloader takes longer to start Marlin in that case.

**Comment by SISLANGER** [comment]
Well that answers that one, crap umm will have to look at other displays or maybe cut the buzzer pin wire thank you for your help

**Comment by ghost** [comment]
Solder a 10k resistor from **pin 1** to **GND** on the **EXP1** socket.
https://reprap.org/mediawiki/images/5/51/RRD_FULL_GRAPHIC_SMART_CONTROLER_SCHEMATIC.pdf

That will default the buzzer to being **OFF** rather than **ON**, which should fix your night time exploits ;)

or

Stick some blu-tack over the buzzer.

![591px-RRD_FULL_GRAPHIC_SMART_CONTROLER_BACKSIDE_buzzer_mod](https://user-images.githubusercontent.com/49303635/57512514-c3e26100-7303-11e9-929c-086c077ad5fd.jpg)

![Dsc00110](https://user-images.githubusercontent.com/49303635/57515025-9e585600-7309-11e9-834a-c52a4ab7c9db.jpg)

It does work, the buzzer will then only come on when Marlin tells it too.

**Comment by SISLANGER** [comment]
@doggyfan Brillant will give that a go the resistor that is ;-)

**Comment by SISLANGER** [comment]
@doggyfan thank you works a treat

**Comment by ManuelMcLure** [comment]
Yes, thank you @doggyfan - it worked great here as well.

**Comment by xenon2008** [comment]
Hello!

Today i have set up my first SKR 1.3 Board fornmy Ender 3 Pro.
When i Power on the Printer or use the Reset Button of the SKR 1.3, i will get a terrible beep.
So i think this is this issue.. but i have the stock ender 3 display (activated cr_10 Stockdisplay in marlin..)

Any ideas what i can do?
At the first time i thought i havr made a mistske because this is my first skr...
With marlin 2.0 bugfix (older release) on stock ender 3 melzi board it doesnt beep so terrible.
Its sounds like an little explosion *lol*

I hope everbody can understand my bad english :(

Best regards
Mark

**Comment by Kabaniero** [comment]
> Hello!
> 
> Today i have set up my first SKR 1.3 Board fornmy Ender 3 Pro.
> When i Power on the Printer or use the Reset Button of the SKR 1.3, i will get a terrible beep.
> So i think this is this issue.. but i have the stock ender 3 display (activated cr_10 Stockdisplay in marlin..)
> 
> Any ideas what i can do?
> At the first time i thought i havr made a mistske because this is my first skr...
> With marlin 2.0 bugfix (older release) on stock ender 3 melzi board it doesnt beep so terrible.
> Its sounds like an little explosion _lol_
> 
> I hope everbody can understand my bad english :(
> 
> Best regards
> Mark

Working solution: solder a 100KΩ resistor between the 1th and 9th pin of exp3 port on Creality stock LCD board. 

Мне помогло припаять резистор на 100КОм между первым и девятым пином на стоковой плате дисплея Creality.
![CrealityLCD](https://user-images.githubusercontent.com/59473700/71721464-34f7fb00-2e36-11ea-8cdd-6575483c1b98.jpg)
