### ISSUE TITLE
[FR] Move drivers to subfolders

### ISSUE THREAD

**Issue by Ionic97** [MarlinFirmware/Marlin#14598]
The driver-specific section in configuration_adv is getting pretty lengthy. It should be better to extract them like it was recently done with the pin layouts.

**Comment by sjasonsmith** [comment]
Config file reorganization is something that has come up several times recently. @thinkyhead has expressed that the direction things are headed is toward tool-assisted configuration, rather than further fragmentation of the configuration headers.

Based on this I am going to close this feature request, as it seems like it would be undesirable for anyone to invest time into this without previously coordinating efforts to ensure the change is actually desired.
