### ISSUE TITLE
Remove Configuration.h and Configuration_adv.h in project root from git 

### ISSUE THREAD

**Issue by marchelh** [MarlinFirmware/Marlin#14590]
All,

Please remove the Configuration.h and Configuration_adv.h from the default location, so that pulling the latest version does not conflict your local configuration setting. Also add these to the .gitignore file, so that user/developers are not adding them by accident.

Kind regards,
Marcel

**Comment by reloxx13** [comment]
1this would make it harder to merge if new defines get added or default values changes.

i use marlin 2.0.x for a year now and had never merging issues.

yes i get conflicts, but this is correct for being uptodate with the configs and is fixed in no time.

e.g. bltouch configs got moved to config_adv. with ignoring them u need to check the hole config urself on every pull, which would be more work.



if u dont update ur local marlin with git already, learn to use git.

start with sourcetree, a free windows git gui.

fork marlin, make a new branch which mirrors the orginal marlin by setting the remote of the branch to the marlin git. now create another branch for ur config/changes.


on update first pull the marlin remote branch, merge it in ur fork and then merge it from the fork in ur config branch.

**Comment by sl1pkn07** [comment]
or directly in the main if you don't want push changes to upstream:

- clone the repo
~~~
git clone https://github.com/MarlinFirmware/Marlin.git
cd Marlin
git checkout <your preferable branch, you can use TAB for the list>
~~~

- change you code and commit it with:
~~~
commit -am 'you changes'
~~~
you not need add more commits with you changes, you can add them in the created commit, see below:

- if you need add more changes, edit the files you want and apply it in the repo with:
~~~
git add *
git commit --amend --no-edit
~~~
the new changes is applied automagically in the commit created by you with 'git commit' in the earlier step


- when exist new update in github:
~~~
git fetch origin
git rebase origin/<the branch you use>
~~~

- if have more updates, repeat steps above

- if the git rebase make a file conflicts, resolve it with the editor text. add the changes and continue with:
~~~
git add *
git rebase --continue
~~~

**Comment by marchelh** [comment]
Of cause, you can do some stuff via git commands, and when new options are added, you have to add them in the config. But there you have the config/defaults files for here you place the new option every time there is an update. I really don't like the fact that changeable "config" file are part of the git repository.

**Comment by reloxx13** [comment]
read this, it got declined already

https://github.com/MarlinFirmware/Marlin/pull/12541



in 99% u dont need to edit/fix anything if u r using git for updating.


it would be way more work to update if its not in git.

**Comment by reloxx13** [comment]
if u did not use git till now, use it and tell us ur experience back here after 1-2 month active using/updating marlin 2.0.x.

im updating at least once a week.
