### ISSUE TITLE
[BUG] pid bed temp causes printer halt SKR 1.3

### ISSUE THREAD

**Issue by cinealfa** [MarlinFirmware/Marlin#14741]
pid bed temp causes printer halt

Printer throws a error and halts bed heating when pidtemp is selected
if pid bedtemp is commented out bed heats normally.

### Steps to Reproduce

1. select pid bed temp in config
2. compile
3. watch the fun begin...

**Expected behavior:** [What you expect to happen]
pid control of the bed

**Actual behavior:** [What actually happens]
printer is halted
[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/3437864/Archive.zip)

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by thisiskeithb** [comment]
Your configs are a bit dated, so try pulling down a fresh copy of [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) and see if the bug persists. I was able to run a bed PID autotune on my SKR 1.3 successfully running a current version.

**Comment by cinealfa** [comment]
ah will do! I have been using marlin config tool to set them. I suspected it wasn't updating the build reliably.

**Comment by mikeshub** [comment]
When you enabled it did you remember to load the default settings or set the PID gains? That happened to me early today when I turned on bed PID because the gains loaded as zero. M502 then M500 should sort you out or use M304 then M500. Be warned the current state of the autotuner might result in an over tuned bed that has temp oscillations. YMMV. Check this PR for more info:

https://github.com/MarlinFirmware/Marlin/pull/14746

How did the autotune settings work for you in their current form?

**Comment by cinealfa** [comment]
it was a older version of marlin apparently the Mct is no longer being updated so the numerous bugs in it are starting to make it unusable. There hasn't been any work done on it for some time and Ifear it has been orphaned.
