### ISSUE TITLE
Don't use string literals in ulterlcd.c

### ISSUE THREAD

**Issue by AnHardt** [MarlinFirmware/Marlin#1482]
EDIT: ultralcd.cpp i mean.

Most annoying for me is "Extruder" in line 738.
But "X",  "Y", "Z" are not much better. (line 718-720)
Numbers may be ok ( lines 594, 596, 599, 602, 617, 619,622, 625 )
" 1" - space+number is questionable for me (lines 815, 818, 821,  429, 432, 435)
Abbreviations with numbers 'E1' are not ok (lines 851, 853, 854, 864, ...  ,)
G-codes are OK.

Why numbering differs? (" 234" "1234" " 23")
Is there a way to distinguish better between Extruder and Noozel?

**Comment by thinkyhead** [comment]
I'm the blame, during my languages overhaul. These are all consistent with the original translation text. Redundant translation strings were removed to reduce the amount of translation work. The space in front of a number replaces the space at the end of the translation string (because it's easy for translators to forget, and they often do). If you'd prefer to remove the literals and make them into translation strings as well, that would be a good middle ground - instead of restoring all those numbered translation strings.
