### ISSUE TITLE
[BUG] Conditionals_LCD.h not expanding #define pins in pins_BOARD.h scope

### ISSUE THREAD

**Issue by soimy** [MarlinFirmware/Marlin#14998]
### Description

When I tried to compile the new `bugfix-2.0.x` branch with sample Ultimaker configuration, I face the compiling error:
```
HAL_AVR/fastio_AVR.h:76:41: error: 'DIOLCD_PINS_D6_RPORT' was not declared in this scope
```
After some digging, I found the error is at https://github.com/MarlinFirmware/Marlin/blob/ed86550061ab94f10dd1d310c994bd74db582740/Marlin/ultralcd_impl_DOGM.h#L364
expanding `LCD_RESET_PIN` all the way to `DIOLCD_PINS_D6_DDR` which is set by:
https://github.com/MarlinFirmware/Marlin/blob/85c82ab28e13cb25043ae166062785bff39434b9/Marlin/Conditionals_LCD.h#L148

I think there must be some potential scope error between `Conditinals_LCD.h` and `pins_BOARD.h` but that is beyond my skill to solve.

### Steps to Reproduce

1. Use configuration files inside `config\examples\AliExpress\UM2pExt\` ;
2. Compile

**Comment by soimy** [comment]
This bug is annoying! I can bypass it by defining LCD_RESET_PIN in ‘pin _BOARD.h’ but it’s not an elegant approach.

**Comment by thinkyhead** [comment]
The issue is now patched.

I don't have one of these boards on hand. Do you know what the `LCD_PINS_D6` pin (pin 5) is labeled on that board or in its schematic, or which header contains pin 5?

I am asking because in the future we may want to have pins like `AUX01...AUX10` in the pins files, and then define LCD (or other) pins based on those `AUXnn` pins. That way we can, for example, assign either a reset or an LCD function to a pin without assuming it is always or primarily an LCD function pin.

**Comment by soimy** [comment]
Ultimaker mainboard is a bit different in EXP1 layout compared to RAMPS compatible boards because it uses I2C signal to connect the UltiController which is SSD1309 i2c 12864 OLED screen. According to the schematic, EXP1 Pin7 is `LCD_PINS_D6` and stand for `LCD_RESET_PIN`, which is `PE3` on Mega2560
<img width="611" alt="WX20190831-142210@2x" src="https://user-images.githubusercontent.com/1550237/64060097-ca6e4e80-cbfa-11e9-826c-675cc2ea3f3a.png">
<img width="708" alt="WX20190831-142106@2x" src="https://user-images.githubusercontent.com/1550237/64060098-cb9f7b80-cbfa-11e9-96f3-05208cacb35b.png">
