### ISSUE TITLE
[FR] add M666 command to burn down your house

### ISSUE THREAD

**Issue by zbigos** [MarlinFirmware/Marlin#15063]
### Description
Command to burn down the house

### Steps to Reproduce
1. input M666 to the terminal.
2. 3D printer should disable thermal protections.
3. 3D printer should enable heaters for bed and all extruders.
4. 3D printer should burn down the house
5. ...
6. profit

The 3D printer should play a chiptune with the buzzer/stepper motors during the process.

#### Additional Information
Demonstration 
https://hackaday.com/2018/03/18/3d-printer-halts-and-catches-fire-analysis-finds-a-surprising-culprit/

**Comment by Roxy-3D** [comment]
They don't say what firmware was being used in the HackaDay article.    But Marlin ends up on 80% (or more) of the 3D Printers that get manufactured and sold.    Probably, somebody did not turn on Thermal Protection.    

As it turns out...  Thermal Protection is in the firmware and rigorously  tested for a reason.

Needless to say:   We won't be adding an M666 code to deliberately burn down somebody's house.
