### ISSUE TITLE
[BUG] can't get my extruder motor move.

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#15071]
I am using SKR V1.3 with 4 TMC2208 in UART,
X, Y, Z all work well and home correctly, when I was trying to do extrusion calibration tonight, I found that my E motor doesn't move at all.

I disabled/comment out the  cold extrusion prevention.

steps I've tried so far to narrow down the problem:
1. swap the E TMC2208 to Z and Z works fine.
2. swap the E motor to Z and when I home Z, the E motor turns
3. use a spare motor on Z and E, it turns on Z but not E
so I think I can eliminate the problem with my driver and motor

4. I turned off LA in firmware
5. STEALTHCHOP_E is disabled (because LA was on, this one I just left it disabled)

6. I adjust the voltage both by using M906 and on 2208 up to 1.3v
now I don't know what I can try to get the motor to work.

when I click extrude/retract the motor is engaged and when the voltage is at 1.3v, I can't turn it by hand, but it just won't turn.

anything I am missing in config?  thanks

**Comment by boelle** [comment]
if you attach your 2 config files as zip there is a chance someone might spot an error, without them its just a guessing game

**Comment by macasero** [comment]
same here

**Comment by macasero** [comment]
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3548404/Marlin.zip)
extruder won´t move, with an older version of bugfix 2, works fine

**Comment by ghost** [comment]
> [Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3548404/Marlin.zip)
> extruder won´t move, with an older version of bugfix 2, works fine

how far you have to go back to get a working version? I am still trying, but till dec 2018 I haven't find a working one.

**Comment by boelle** [comment]
https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x

then click commits, direct link https://github.com/MarlinFirmware/Marlin/commits/bugfix-2.0.x

pick a commit  and click <> next to it

**Comment by ghost** [comment]
thanks, I just found it, :D, now I have to try how far I have to go back to get this to work

**Comment by macasero** [comment]
I have a working one from july 26th or so.
https://github.com/MarlinFirmware/Marlin/tree/7084f3647a87966e1df6af9ef3e86c5dec3c1bfd

**Comment by davidcgu** [comment]
Exactly same issue here with version from 27 Jul and latest libraries TMC0.4.6 and with TMC2209

**Comment by davidcgu** [comment]
In case it helps..... my config is TMC2209 on XYE0 and LV8729 on ZZ2 all at 128 microsteps board SKR v1.3 interpolate.

Test I made so far:

tried to modify pinout file and swap E0 driver with Z driver.
Tried to dissable double Z and let only first Z.
Tried to dissable interpolate.
Tried to move from 128 to 32 microsteps.
Change TMC library version from latest 0.4.6 to previous release 0.4.5
Tried to copy the config files from my marlin folder downloaded on 27 july to a version downloaded on 22 July, complie and upload.

Other config:  UBL,cabin light,runout sensor,2004 LCD,SD support, Eprom enabled.Bltouch

Any of the mentioned test make it turn so I have to run E0 with an LV for now to have it running.

I can also mention that making an M122 return me status ok of all driver on UART and when trying to move I hear some noise as doing is trying to do, extruder wheel gets blocked at this moment and can not be moved by hand just then. It's strange because something is trying to do, but does not move.

Regards

**Comment by davidcgu** [comment]
Well guys.... I have good news for you.... After a hundred of test and flashes I found issue comes as soon as you enable linear advance, whatever the value you have set for K.

At the begining I though maybe was in convination with juntion deviation however disabling this options makes no change.

As conclusion... you need to disable linear advance until they fix the issue and raise a new release.

Regards

**Comment by ManuelMcLure** [comment]
Try enabling SQUARE_WAVE_STEPPING.

**Comment by ManuelMcLure** [comment]
Or increase MINIMUM_STEPPER_PULSE.

**Comment by davidcgu** [comment]
I'm on direct drive so just will let linear advance disabled as I don't think it's necessary, in fact I was not using it since I moved from bowden to direct drive.

However if is the case that someone is on bowden and furthermore with a long teflon tube will worth to test for him. 

Regards

**Comment by ghost** [comment]
I can't get mine move even I disable the linear advance, so I give up for now and ordered some lv driver for extruder and see if that will work.  swap back the sbase with external 2208 setup,

**Comment by davidcgu** [comment]
In my case was clear, and I tested more than once to be sure, linear advance enabled = extruder not working independently of the value of K.

From other side and to be fair... I have a ser of TMC2209 and after test TMC2209 vs LV8729 same print, same setups, suprinsingly LV are less noisy than TMC.

As conclusion I have installed back my LV drivers and now have only TMC2209 on extruder as I only have 4 LVs on hand.

I think I will sell part of my TMC2209 as I think I will stay on LV drivers.

I also have better results on accelerations, with TMC was doing something strange and I had to reduce drastically the acc to avoid suddent noises.

Regards

**Comment by macasero** [comment]
> SQUARE_WAVE_STEPPING

My setting posted here: https://github.com/MarlinFirmware/Marlin/issues/15071#issuecomment-525515446

I did enable SQUARE_WAVE_STEPPING and extruder moves...with it disable didn´t move.

So as far as I know.

2208 spreadcycle ON (stealthchop off) , linear advance ON, and square wave-stepping OFF: extruder DOES NOT MOVE 

2208 spreadcycle ON (stealthchop off) , linear advance ON, and square wave-stepping ON: extruder DOES MOVE

**Comment by macasero** [comment]
updated previous post, because had wrong data

**Comment by davidcgu** [comment]
As far as I remember from the tests I done stealchop or spreadcycle does not makes any change, however is curious I have version from 27 Jul and I have disabled square wave and in my case what made the change was to disable linear advance.

Regards

**Comment by Snagi0** [comment]
You can also try to enable junction deviation, instead of using jerk settings. That also seemed to have a positive effect on my setup. As stated earlier, enable SQUARE_WAVE_STEPPING and set MINIMUM_STEPPER_PULSE to 1 or 2.

I have a TMC2208 with UART as an extruder on bowden system. I have above settings enabled and running only in STEALTHCHOP. There is no problems if I have linear advance disabled. If I enable linear advance, I can see a clear benefit on print quality, but the extruder stepper starts to make rattling noises when it compensates for the pressure. There is no skipping or any mechanical problems. I can see that the extruder is running in both directions very rapidly during the rampup or rampdown phase when controlling the pressure. Those quick jerk jumps should be integrated to the normal extruder movements instead of handled separately. There has been multiple bug reports with TMC drivers and linear advance, but all of them has been closed without fixing.

To sum it up: **TMC2208 with UART control as extruder on bowden system running only stealthchop. Works very well and silent without linear advance. Prints even better with linear advance, but there is terrible noise caused by the control scheme used with linear advance.** This rattle mechanical vibrations prevent the use of linear advance for me.

We really **need linear advance v.2** to correct this problem (and I guess s-curve handling with lin adv also?).
I'm using **bugfix2.0.x (28.8.2019)**.

Here is an example of the other bugs. Artem-B had the same problem and scoped his step and dir channels where you can see rapid direction changes in 10ms range. There is no point on having that kind of control, instead the main movement direction should be slowed down. 
https://github.com/MarlinFirmware/Marlin/issues/10272#issue-310340937

**Comment by uloxer** [comment]
Same problem, solved by setting minimum stepper pulse to 1 in advanced config. 

Notes:
No extruder movement
Skr v1. 3
TMC2209
Lin Adv enabled and set to zero

**Comment by boelle** [comment]
@Ke5han still having issues?

**Comment by hidara2000** [comment]
Finally got the x y z working. Unbelievably quiet. That said, having extruder issues. Running gcode that worked before and purge lines print perfectly but the extruder starts skipping when it starts printing the part. 
If I put my fingers on the extruder gear I can feel it slipping. I've tried various currents. Vrefs are spot on ??? I've reduced all acceleration and jerk settings to next to nothing. Tried Stealthchop on and off.
Any help would be appreciated. 

Skr v1.3

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3693100/Marlin.zip)

**Comment by Snagi0** [comment]
Skipping is filament sliding in relation to the extruder gear. Are you sure your filament is also skipping? 

Are you using linear advance? Could you be experiencing fast back and forth movements on the extruder gear, like here? #10272

If it's really skipping, that may have various causes. I would start by examining the complete filament path. Is there some specific situations or differences (directions/layer height/bed level/fan/temp/speeds/feeds etc) on the system or slicer settings that differentiate the two behavior? What have you changed since last working setup? A lot more info would probably be needed to give any good specific advice in this case.

**Comment by hidara2000** [comment]
Linear advance is disabled and the filament is definately not slipping. When I put a finger on the extruder gear I can feel very brief times when the motor is not engaged. 
I think I might just give up and use lV8729s for the extruders and use the TMC2209s for a new build over Xmas.

**Comment by Snagi0** [comment]
Oops, I might not have been quite accurate with my earlier skipping description. That does sound a bit like servo skipping steps. My last paragraph should still apply. Are you using status monitoring on the driver? Have you tried the MINIMUM_STEPPER_PULSE setting? I would still try to find what changes between purge lines and main part to point you in right direction.

**Comment by hidara2000** [comment]
I've tried adjusting the min stepper pulse, force the stepper into 32/64 microstepping mode (in the hopes that the 128 microsteppping interpolation was the issue). As I explained the stepper works perfectly when creating the purge lines but begins to slip when printing the main piece.
I attached a zip in my earlier post with configs and the relevant gcode.
Cheers for the help

**Comment by Lumanet2012** [comment]
Hello everyone, 

so I be running Marlin 2.0.7.2 on an SKR 1.4 Turbo board. And after messing around with my settings I found out a few things. 

  //#define SQUARE_WAVE_STEPPING

has to stay disabled on my TMC2226 which I run as a TMC2209. Once I done this change I got a step further. 
But because safety is a big thing on Marlin when I do run my stepper motors they all do work with exception of the extruder. 
For the extruder I get the NOZZLE not hot warning and even if I ignore it it will not let me move my extruder. 

But if I heat up my hot end it works just fine.   

So as long you leaving SQUARE WAVE STEPPING off and have your hot end hot enough it works just fine.
