### ISSUE TITLE
[BUG] skr 1.3 12864 LCD reboot loop after more than 15 files

### ISSUE THREAD

**Issue by wolfgangmauer** [MarlinFirmware/Marlin#15353]
### Description
I have a SKR 1.3 and a 12864 LCD-Grafik-Smart-Display-Controller
If i have more than 15 files on the sdcard in the LCD marlin won't boot (boot/reset/boot/reset/...)

### Steps to Reproduce
Put more than 15 files on the sdcard an insert in the 12864 LCD and reboot
After that -> reboot loop

### Workaround
Remove the sdcard before booting
If finish booting reinsert -> works fine

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3646559/Configuration.zip)

**Comment by shitcreek** [comment]
Does the SD card contain a .cur, .bin or an auto0.g file?

**Comment by wolfgangmauer** [comment]
No, just gcode files.

If i delete some to get less than 16 everything works fine

**Comment by shitcreek** [comment]
I have well over 16 gcode files on my sd card without this issue.
Have you tried a different SD card?

**Comment by gloomyandy** [comment]
I suspect that you are seeing a variant on this issue https://github.com/MarlinFirmware/Marlin/issues/14326
I think that you will be getting a watchdog reset during boot. You could either try the fix I suggested or try disabling: USE_WATCHDOG in configuration_adv.h.NOTE you probably should not run your printer with the watchdog disabled. I am suggesting this only to help track down what is going on.

The reason you see this but others may not is probably because something in your boot sequence is taking a little longer than other systems to run (or you may have other things enabled that others do not have). This extra delay means that the watchdog timer expires on your system, but not on others.

**Comment by wolfgangmauer** [comment]
THX!

Yes i have the „SDCARD_SORT_ALPHA“ enabled…

I will check without

 

Von: Andy Shaw <notifications@github.com> 
Gesendet: Mittwoch, 25. September 2019 22:43
An: MarlinFirmware/Marlin <Marlin@noreply.github.com>
Cc: Wolfgang Mauer <wolfgang.mauer@kabelmail.de>; Author <author@noreply.github.com>
Betreff: Re: [MarlinFirmware/Marlin] [BUG] skr 1.3 12864 LCD reboot loop after more than 15 files (#15353)

 

I suspect that you are seeing a variant on this issue #14326 <https://github.com/MarlinFirmware/Marlin/issues/14326> 
I think that you will be getting a watchdog reset during boot. You could either try the fix I suggested or try disabling: USE_WATCHDOG in configuration_adv.h.NOTE you probably should not run your printer with the watchdog disabled. I am suggesting this only to help track down what is going on.

The reason you see this but others may not is probably because something in your boot sequence is taking a little longer than other systems to run (or you may have other things enabled that others do not have). This extra delay means that the watchdog timer expires on your system, but not on others.

**Comment by wolfgangmauer** [comment]
Disable "SDCARD_SORT_ALPHA" fix this issue

**Comment by firepower9966** [comment]
You need to make sure you have sort use ram or stack enabled, I got same issue with mega2560 when I disable ram defines in sort alpha.  Also sorting alpha is limited to 40 entries I think.

**Comment by thinkyhead** [comment]
> sorting alpha is limited to 40 entries I think

The limit is 255. A Melzi with 16K of SRAM can handle this with no problem.
