### ISSUE TITLE
[BUG] Not properly passing through SD card over USB to raspberry pi (2.0.x)

### ISSUE THREAD

**Issue by Kokorone** [MarlinFirmware/Marlin#15500]
### Description

SD card will not mount and instead have Disk I/O errors with recent marlin 2.0.x firmware (10/5/2019 and newer tested, 9/19/2019 version confirmed working properly). Tested with manual mounting attempts and with USBMount.

### Steps to Reproduce

1. Set up a new marlin build and flash to board (SKR 1.3)
2. Connect board over usb to raspberry pi, (shouldnt matter if running octo or not)
3. Mount the sd card to the pi, I used USBMount configured as outlined with Octoprint-FirmwareUpdater to auto mount.

**Expected behavior:** [What you expect to happen]
SD card properly mounts to the raspberry pi and is RW accessible

**Actual behavior:** [What actually happens]
SD card fails to properly pass though and never mounts, with an I/O error

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
[ConfigFiles.zip](https://github.com/MarlinFirmware/Marlin/files/3709778/ConfigFiles.zip)

* Provide pictures or links to videos that clearly demonstrate the issue.
![unknown](https://user-images.githubusercontent.com/32761171/66527447-168d9800-eab1-11e9-9b2d-aec829e26209.png)

* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by tvixen** [comment]
Which version of Octoprint is running on your Pi? (Stable or Release Candidate)
Did you try with a older version of Octoprint?

**Comment by Kokorone** [comment]
Currently using stable octopi release with updated raspbian

**Comment by tvixen** [comment]
Hmm, I still think the problem is on your Pi side. Does it auto update (look in manager)?
Can Windows still see your SD card as a drive, when switching USB to windows ?

**Comment by gloomyandy** [comment]
That status string looks very much like the one that you get when Marlin has mounted the SD card (which means it is no longer available via USB, hence we report no media). What happens if you release the SD card from the LCD or send M22? That should allow USB access. 

Is it possible that Octoprint has mounted the SD card (via M21)? Try stopping Octoprint and rebooting Marlin to see if that makes any difference?

Oh and make sure you have a good SD card, the one that comes "free" with the SKR board causes all sorts of odd problems, I suspect it is not fast enough especially when using USB access.

**Comment by Kokorone** [comment]
Updated to the dev version of usbmount as recommended here and it appears to be fixed

[https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/issues/109#issuecomment-538698635](url)
