### ISSUE TITLE
[QUESTION] Use marlin in EFF but ALSO have a Heated Bed

### ISSUE THREAD

**Issue by safaenet** [MarlinFirmware/Marlin#15615]
Hi, i use marlin on ramps 1.4.
my question is: Is there a way to use marlin in EFF mode but still have heated bed via an external MOSFET ?
My goal is to use both D8 and D9 pins for Fans (D10 for Heater) and connect a heated bed to it using an external MOSFET  (Don't wanna use RRD fan extender) 
If So what codes in marlin must be edited to do that ? May i simply remap Heated Bed pin to a free pin ? Which free pin is suitable for Heat Bed ?

**Comment by boelle** [comment]
have you asked any of these places first?

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by safaenet** [comment]
I just asked the same question in Marlin [forum](https://reprap.org/forum/read.php?146,861137,861137#msg-861137)

**Comment by boelle** [comment]
oki, i will close this one  because the list is for bugs only

if this turns out to be a bug we can reopen it or you can create a new

**Comment by AnHardt** [comment]
Due to the diversification into EBF, EFF, ... and use in multiple different pins files as an include RAMPS pin file is a bit complicated to read and understand. For the predefined configurations it's working fine (mostly).
When is comes to a special custom pinning, forgetting about the pre configurations is much simpler then  altering them.
Comment out the definitions based on the pre configurations and just define the 3-4 needed pins unconditional by yourself.
