### ISSUE TITLE
[FR] (feature request title) Microsoft Standard Driver for 3D Printers

### ISSUE THREAD

**Issue by Glod76** [MarlinFirmware/Marlin#15912]
Can this be integrated into marlin to be detected by windows 10?

https://docs.microsoft.com/en-us/windows-hardware/drivers/3dprint/microsoft-standard-driver-for-3d-printers-

**Comment by BeatSlayer** [comment]
I don't believe that's possible for most of the boards we use because of the fdti/chg serial conversion chips they have.

Edit: Just to add that it's possible for those using atmegas for serial conversion but that requires flashing that chip itself.
It shouldn't be too difficult to do after some research.

**Comment by ellensp** [comment]
I'm against this.
Marlin/Reprap is for all platforms not just one.  
Would have to write new drivers for all platforms.

**Comment by sl1pkn07** [comment]
NO

**Comment by InsanityAutomation** [comment]
It could be standard per platform (eg lpc17xx, avr, stm32) but too many differences between platforms to be global. Just not feasible.

**Comment by ejtagle** [comment]
At some time, i did implement it for Arduino Due, and it worked. But, suddenly, it stopped to work. The microsoft 3d printer driver uses standard Gcode, so, it does not require any change to the gcode processing.. just the addition of some USB descriptors..

**Comment by LinoBarreca** [comment]
Can be done for sure on STM, I would not do it though: Too much hassle and too little ROI. I would suggest Microsoft to add a second layer driver on com ports to recognize most common 3d firmware reset messages and be immediately compatible with 99.5% of printers worldwide...

**Comment by extesy** [comment]
@LinoBarreca Why do you think adding usb descriptors is too much hassle? If you were to quantify the effort, how long would it take to implement?

**Comment by LinoBarreca** [comment]
@extesy it isn't "just a descriptor" to override.
You got to implement the whole CDC (for every family of processors).
If you are wondering "how difficult can it be" download STM32Cube and look at the CDC application (which is a basic "serial port")
And I see no real benefit in doing it since the "driver" for windows doesn't provide any added value now besides letting microsoft know you got a 3d printer and its bed size.

**Comment by ellensp** [comment]
Design a interface box.  A real reprap type 3d printer on one side, the crap MS wants on the other side...   Then any printer can be used.  If it provides bed size, then add a gcode to return bed size so the interface can query it.  But I'm not going to do this, waste of time and resources.

**Comment by LinoBarreca** [comment]
@ellensp or a second layer driver without any extra hardware.....but I'm not going to do this because it's just useless.
