### ISSUE TITLE
[FR] Rumba32 for PlatformIO

### ISSUE THREAD

**Issue by leseaw** [MarlinFirmware/Marlin#16201]
### Description

To build with PlatformIO for the Rumba32 board.
That everyone can use it.

### Feature Workflow
add this to platformio.ini

#
# RUMBA32
#
[env:rumba32_f446ve]
platform      = ststm32
framework     = arduino
board         = rumba32_f446ve
build_flags   = ${common.build_flags}
  -DSTM32F4xx
  -DARDUINO_RUMBA32_F446VE
  -DARDUINO_ARCH_STM32
  "-DBOARD_NAME=\"RUMBA32_F446VE\""
  -DSTM32F446xx
  -DUSBCON
  -DUSBD_VID=0x0483
  "-DUSB_MANUFACTURER=\"Unknown\""
  "-DUSB_PRODUCT=\"RUMBA32_F446VE\""
  -DHAL_PCD_MODULE_ENABLED
  -DUSBD_USE_CDC
  -DDISABLE_GENERIC_SERIALUSB
  -DHAL_UART_MODULE_ENABLED
  -Os
lib_deps      = ${common.lib_deps}
lib_ignore    = Adafruit NeoPixel
src_filter    = ${common.default_src_filter} +<src/HAL/HAL_STM32> +<src/HAL/HAL_STM32_F4_F7> -<src/HAL/HAL_STM32_F4_F7/STM32F7>
monitor_speed = 500000
upload_protocol = dfu

#### Additional Information
thanks to @wap32 who wrote it down.
It just shouldn't go under because of that the FR

**Comment by thisiskeithb** [comment]
See https://github.com/MarlinFirmware/Marlin/pull/16202

**Comment by mks-viva** [comment]
MKS has added RUMBA32 to compile Marlin 2.0 by platformio, and passed the test. Compile and download are supported. Can refer to: https://github.com/makerbase-mks/MKS-RUMBA32
build:
![image](https://user-images.githubusercontent.com/16629551/70772093-6db03180-1dae-11ea-87ff-720920feb9be.png)
![image](https://user-images.githubusercontent.com/16629551/70772104-76a10300-1dae-11ea-8d8f-94577894aa66.png)
upload(Hold down BOOT, press RESET, release RESET, release BOOT, enter DFU mode)
![image](https://user-images.githubusercontent.com/16629551/70772209-ced80500-1dae-11ea-8828-d2552301f2ea.png)
![image](https://user-images.githubusercontent.com/16629551/70772254-ea431000-1dae-11ea-9a30-83f76e4b3a02.png)
![image](https://user-images.githubusercontent.com/16629551/70772289-faf38600-1dae-11ea-9643-91e25a282079.png)
But usb have bug, because it does not recognize COM properly, I think it is a problem with the platformio.ini board settings.
![image](https://user-images.githubusercontent.com/16629551/70772399-5faee080-1daf-11ea-9802-3dbb10b30c4d.png)

**Comment by thisiskeithb** [comment]
Does MKS' RUMBA32 board adhere to Aus3D's RUMBA32 specs/work the same? It'd be good to know if it should work exactly like the original or if there are special settings for MKS' version.

**Comment by mks-viva** [comment]
MKS' RUMBA32 only adds TMC2208 / 2209 UART interface circuit on Aus3D RUMBA32 hardware version ，and AUX-1 interface of MKS TFT……

**Comment by mks-viva** [comment]
RUMBA32 platformio.ini
![image](https://user-images.githubusercontent.com/16629551/70773368-3d6a9200-1db2-11ea-89a2-a49954dc18e6.png)

**Comment by thisiskeithb** [comment]
> RUMBA32 platformio.ini

That's what PR #16202 was going to add, but RUMBA32 should build with the existing `STM32F4` environment:

https://github.com/MarlinFirmware/Marlin/blob/6a514a1e8e96bcd26985615377523d1e45ca7b10/Marlin/src/pins/stm32/pins_RUMBA32.h#L24-L25

**Comment by mks-viva** [comment]
But I tested it and everything works.
About USB does not recognize COM properly problme, need manually modify to STM32 virtual serial port.
![image](https://user-images.githubusercontent.com/16629551/70787283-4dda3700-1dc9-11ea-97f1-b9fc608717da.png)
![image](https://user-images.githubusercontent.com/16629551/70787316-5e8aad00-1dc9-11ea-9052-3ebbea2ce27c.png)
