### ISSUE TITLE
[BUG]( LCD SD-card 'Insert' Not Detected For MKS_SGEN_L Board )

### ISSUE THREAD

**Issue by ShareEC** [MarlinFirmware/Marlin#16340]
mks sgen-L + mks 12864 mini.

I've already read about it. 
https://github.com/MarlinFirmware/Marlin/issues/16223

I want to add one more thing here.
If a micro sd card is plugged into the MKS SGEN-L board, the same problem still occurs.
If you remove the card from the board, it works fine.

Can you solve this problem?

**Comment by borland1** [comment]
Why would you need to plug in a SD-card in a slot that is not enabled with Marlin?

For MKS_SGEN_L board, since both the ONBOARD and LCD SD-CARDs share the same SD_DETECT processor pin, it is not practical to enable both slots at the same time. The board designer must have considered this as a limitation.  Regardless of which slot is enabled by firmware, the ONBOARD SD-slot is still active by bootloader during power-up, so that firmware updates can be accomplished.

I noticed on the SKR1.x 32-bit board schematic/wiring diagram, that the ONBOARD SD-slot SD_DETECT is not even shown as being connected to the processor.   Might be interesting to see if cutting the MKS_SGEN_L's PCB copper trace for the ONBOARD SD-slot SD-DETECT line would disable the bootloader's ability to update firmware.

**Comment by SharePARTS** [comment]
Thank you for your kind explanation.
I understand.
By default, my printer has a sealed board.  So I have SDcard plugged into the board and uploading firmware via usb connection.  In this environment, I use the SDcard on the LCD, so both are plugged in.
If it's not something that you can modify inside Marlin, let's consider it mechanically possible.

**Comment by ShareEC** [comment]
Thanks for your kind explanation.
I didn't know one SD_DETECT processor pin managed two slots.
Let's approach it the other way around.

**Comment by thisiskeithb** [comment]
It'd be great if manufacturers would standardize LCD controller designs/interfaces *with the same pinouts*.
