### ISSUE TITLE
[BUG] G29 is probing in the wrong position

### ISSUE THREAD

**Issue by rmcbc** [MarlinFirmware/Marlin#16348]
### Bug Description

I'm using bugfix-2.0.x and the problem seems to be  in this commit: Add NOZZLE_AS_PROBE (no probe offsets) (#15929) (https://github.com/MarlinFirmware/Marlin/commit/1c9ccce5209cd1727bf80e632f4f781c651e0c35) developed by @InsanityAutomation 

G29 probes the points in the wrong position.

### My Configurations

[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/4003650/Archive.zip)

### Steps to Reproduce

1. Send G28
2. Send G29

**Expected behavior:**

Probe the 9 points of the bed all around 30 positions from bed limits.

**Actual behavior:**

Is probing the 9 points much more than 30 positions from bed limits (too near the center of the bed)

**Comment by rmcbc** [comment]
Fixed changing the file "G29.CPP"

[G29.cpp.zip](https://github.com/MarlinFirmware/Marlin/files/4006413/G29.cpp.zip)

Please search for "#if ENABLED(NOZZLE_AS_PROBE)"

**Comment by InsanityAutomation** [comment]
Ill go over the action it takes there again, but the theory was the the inset would be honored for everything in the min / max position calculation. Prior it was possible to set points that did not honor configured limits. In reality those couple lines are a bugfix mixed with the feature extension to support lulzbot.

This would be expected behavior since you have 
#define MIN_PROBE_EDGE 30
in youre config. This number is a bit extreme and 5-10 is more common.

**Comment by sjasonsmith** [comment]
@InsanityAutomation, I found a problem causing MIN_PROBE_EDGE to be doubled. I'm testing a fix right now.

**Comment by sjasonsmith** [comment]
@rmcbc, would you be able to test my fix in PR #16367, to verify it solves your problem?

**Comment by rmcbc** [comment]
@sjasonsmith for me your change works. Thanks.

**Comment by dburr** [comment]
Experiencing the exact same problem, and the patch in #16367 solved it for me.

**Comment by boelle** [comment]
seems this one is solved by #16367
