### ISSUE TITLE
[BUG] power loss recovery

### ISSUE THREAD

**Issue by spooky79** [MarlinFirmware/Marlin#16413]
the function does not work, after the power failure and confirmation of resuming printing the printout starts again from the beginning. Does this function work on SKR E3 mini v1.2? on ender 3 .Tested on different versions of marlin
[configurationh.txt](https://github.com/MarlinFirmware/Marlin/files/4014459/configurationh.txt)
[Configuration_advh.txt](https://github.com/MarlinFirmware/Marlin/files/4014460/Configuration_advh.txt)

**Comment by Vertabreak** [comment]
it works on the A10 & A20 but much like run out the resume leaves a gap where the stop/start happens making the print look like garbage i consider both features to be nothing more then a gimmick and not viable real world options. also it only functions from the sdcard prints and the constant writes to the card wear out the card.

**Comment by spooky79** [comment]
on the original board it worked very well :(

**Comment by heriantougm** [comment]
I'm trying to use the latest marlin 2.0.0 and 2.01 using Arduino Mega and Ramps. All runs smoothly for the power loss feature. One problem is when the printer resumes directly homing. This does not matter if the power loss is short. if the power loss is long then the nozzle has cooled and stuck to the object. If directly homing, the object is released because it is carried by the nozzle. Another possibility can damage the nozzles if the object adheres firmly. 

The question is how to change so that after the resume is not homing first but the nozzles are heated first.

**Comment by boelle** [comment]
@spooky79 still an problem?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
