### ISSUE TITLE
Graphic LCD support makes Marlin too big for 128k boards.

### ISSUE THREAD

**Issue by unlimitedbacon** [MarlinFirmware/Marlin#1645]
Without graphic LCD support enabled (for instance, for the RepRapDiscount LCD or the VIKI 2.0), Marlin compiles to about 80 kib. With it enabled, it compiles to about 135 kib. This is just slightly too large to fit on a 128 kib board. With a little bit of optimisation, we could probably get this small enough to fit.

Many boards are moving to 256 kib, but some prefer to use the AT90USB series of MCUs with integrated USB support. Atmel does not make one of these with more than 128k of flash.

**Comment by AnHardt** [comment]
@unlimitedbacon 
You are using a REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER?
Not a REPRAP_DISCOUNT_SMART_CONTROLLER.
The name is just to long and to similar - i know.

To save about 5441 Bytes right now apply #1621, go to dogm_lcd_implementation.h and undefine USE_BIG_EDIT_FONT.

**Comment by AnHardt** [comment]
@unlimitedbacon 
If you have no't updated to Arduino 1.6.1 try that and save another about 3.5K.

With plain Marlin standard Configuration.h just defined in REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
and the above tweaks i'm compiling today to 115,678 bytes.

**Comment by chris-bo** [comment]
Commenting line 9 in ultralcd_st7920_u8glib_rrd.h (#pragma GCC optimize (3)) saves another 10K!
Is there any reason for changing optimizations in this file? I noticed no issues.

**Comment by mr-sneezy** [comment]
Hi, I'm one the Marlin users effected by code size once graphic LCD support is enabled on a recently bought Melzi 2.0 board. In my case it was just by a few bytes... 
I did compile with a late version of Arduino IDE.

There are a few suggestions above now, which one is the least useful to have do you think, or the first one that should be commented out to save bytes ?
Martin

**Comment by AnHardt** [comment]
@mr-sneezy 
The above mentioned #1621 is already in since this morning.
BIG_EDIT_FONT is close to useless, but helps if you need eyeglasses otherwise.

Other changes (1622) to the display-font-language system are pending, but memory consumption will be about the same.

**Comment by AnHardt** [comment]
@chris-bo 
Indeed! I got about -8000 bytes - but only with Arduino 1.6.1.

This has to be tested. Will affect overall timing. Could be critical for, for example, the fast moving deltas.

**Comment by alexborro** [comment]
Increasing the Graphic LCD processing time is waayyy critical!!! Even in
cartesians bots. If you are sure about that, use a conditional #define.

Cheers.

Alex.
Em 19/03/2015 11:03, "AnHardt" notifications@github.com escreveu:

**Comment by AnHardt** [comment]
@alexborro 
I'm far from turning at this wheel. My last message was ought to be warning.

**Comment by AnHardt** [comment]
Hm.
Had a closer look. Somewhere i had seen a warning about ignoring GCC optimization.

With Arduino 1.0.6 i get:
/ultralcd_st7920_u8glib_rrd.h:9: warning: ignoring #pragma GCC optimize

Is upgrading to Arduino 1.6.1 the way to get enough speed for the fast deltas?

Is commenting out the way to get the speed we are used to - but saving 8KB?

How can a test look like?

**Comment by thinkyhead** [comment]
I just recently merged a PR that reduces the menu code by ~6 or 7 KB, so that may also help. We're always looking for more ways to shave off precious bytes…

**Comment by ntoff** [comment]
Mentioned it elsewhere, not sure if it was answered (sometimes github doesn't seem to inform me of responses) but maybe get rid of the animated fan logo? I don't see a reason to have the little spinny fan icon. Apologies if it's already been removed, I'm still using Marlin from a month or 3 ago.

**Comment by Roxy-3D** [comment]
> I just recently merged a PR that reduces the menu code by ~6 or 7 KB, so that may also help. We're always looking for more ways to shave off precious bytes…

If they have the Auto Bed Leveling turned on, we can easily prune 25Kb of code by re-writing the Least Squares Fit algorithm.   It is solving for the general case and we don't need that.

**Comment by thinkyhead** [comment]
@Roxy-3DPrintBoard Do you feel like having a crack at whittling that algorithm down? If we can eliminate the need for the `qr_solve.*` files that would be a nice extra benefit.

**Comment by alexborro** [comment]
@Roxy-3DPrintBoard , that would be nice to optimize the Least Square Fit algorithm to our needs. Do you know somebody who could help on this??

@thinkyhead , we will need to store the algorithm somewhere else.. I think it don't matter if in a separate file or among other stuffs.

Cheers.

Alex.

**Comment by Roxy-3D** [comment]
> @Roxy-3DPrintBoard , that would be nice to optimize the Least Square Fit algorithm to our needs. Do you know somebody who could help on this??

I'm toying with this right now.  It is an interesting problem!   Right now, I'm assuming that a 1 or 2 second delay to do a very accurate Bed Level Correction matrix is acceptable if it can shrink the code footprint significantly.   But I would like to hear confirmation of that.

Incidentally...  I'm starting to come to the conclusion that the current QR_SOLVE.CPP routines do not solve the equations as well as can be done.  There seems to be some error in the coefficients that it produces.  If this is true, this implies that we can get better adhesion when going out to the edges of the build plate with a different approach.

**Comment by alexborro** [comment]
Even 3 seconds are nothing if just once in the print beginning..
Em 24/03/2015 19:36, "Roxy-3DPrintBoard" notifications@github.com
escreveu:

**Comment by brainscan** [comment]
I'd be happy if it took longer than that, it's peanuts compared to the time most jobs take to print. Also if it improves quality an extra few seconds is nothing.

**Comment by Roxy-3D** [comment]
Score!!!  I need to do much more testing.  But it looks like it is possible to get a better solution for the Bed Level Correction Matrix than the QR_SOLVE.CPP package provides.   And at a much reduced code foot print!!!

**Comment by nophead** [comment]
Sounds impressive but by what quality is the result better than a least squares fit? Are you minimising a different quality function?

**Comment by Roxy-3D** [comment]
There are multiple solutions to describe the plane through the sample set of points.   The plane is described by the equation ax+by+cz+d=0.    As you adjust things, the summation of the least square error rises and falls.  There are many peaks and valleys.   The QR_SOLVE.CPP package is not finding the most optimized 'minimum error'.   It is just finding a very good one.    

And in fact, depending upon what you are doing or care about, it is very possible different solutions will work better for you.   If you care about good adhesion at the edges of the print bed, it is possible the 'best' solution for you is not the one with the smallest error.  Instead, it would have the smallest error contribution from those points way out on the edge.

And there is another problem...  When it solves the matrix of equations, it returns an optimized value (for the solution that it found) for d.   Right now, in the code, the Z Offset is being set to what ever is in the Configuration.h file (or being pulled from the EEPROM).   But as it turns out, when doing the Least Squares Best Fit, that number needs to shift a little bit.  The QR_SOLVE package returns the more optimized number but it is being ignored.  The current code just does     current_position[Z_AXIS] = zprobe_zoffset;    It should be using the 'better' number.

**Comment by nophead** [comment]
Ah, I see, thanks for the explanation.

I had also wondered about the validity of setting Z to zprobe_offset. My original implementation uses -d / c for the Z value at the origin.

**Comment by Roxy-3D** [comment]
> I had also wondered about the validity of setting Z to zprobe_offset. My original implementation uses -d / c for the Z value at the origin.

Oh Cool!  I didn't know you did the original implementation!  Right now I'm playing with different data sets and I've found one where it can optimize the least squares fit very well but it has to move d way too much to be usable.   So what that tells me is there has to be some limitation built in to limit how much d can move.   In the very original code it actually used the bed level correction matrix to calculate how much different the numbers were because they were offset from the nozzle.  That isn't being done any more.  I suspect it should be.

But anyway...  I'm having a good time playing with it!   :)

**Comment by nophead** [comment]
I did the original implementation on my own hardware and software: http://hydraraptor.blogspot.co.uk/2011/04/auto-bed-leveling.html. It's done in the host rather than the firmware. I didn't have anything to do with the Marlin version other than point out some other bugs in it that have been fixed.

I am not sure how you can have a least squares plane that is at the wrong height. Surely -d/c must lie close to the of the average height of the points and must at least be between the extremes of the points?

**Comment by Roxy-3D** [comment]
> I am not sure how you can have a least squares plane that is at the wrong height. Surely -d/c must lie close to the of the average height of the points and must at least be between the extremes of the points?

My guess is you have had calculus?   The summation of squared error terms gives you a 2nd order equation to start with.  But even with 4 points (and not the 25 points I'm working with) you have 4 different ways to put a plane through 3 of the 4 points.  Using that as a starting point you can lift (or lower) one corner of the plane and get a more minimal least squares summation.  If you go lift (or lower) a different corner of the plane, you probably can find another minimal least squares summation.  Now repeat that for the other 3 ways you can put planes through 3 of those 4 points.

Expand that logic to 25 points.  There are going to be a bunch of different solutions.   And you don't even have an equation to differentiate to look for places where the first derivative is zero (local peak or valley).  You have to do this by just looking at individual points.  

If this is of enough interest to you, I have some code and data sets you can pull into Microsoft Visual Studio and take a look at it yourself.   But the Reader's Digest version is this:  By starting with  a and b of the ax+by+cz+d=0 set to zero, I can very consistently get better (a smaller) least squares summation of the data set compared to what the current code can do.   

If the current code made use of the d coefficient that QR_SOLVE returns, it would beat the algorithm I currently have 1/2 the time.  However, with that said, I've found some data sets where d has to change so much it is unusable.   That may be why the original author did not use it because (s)he obviously knew what (s)he was doing!   And the amount it can beat my current algorithm by is not very much. 

I'm going to see if I can set the limit on how much d can change, and if it is too much of a shift, go look for another very small least square summation near by.   

And you know the strange thing???  I don't even need more memory in my PrintrBoard!   I've still got 40 Kb of headroom!  :)

**Comment by thinkyhead** [comment]
Rather than using least-squares, one could just take all the squares produced by the grid points and split each one into two nice flat triangles. Get the offset angle of all the triangles and then average the angles together to get the final result. You shouldn't need to do more than two triangles per square.

Or is that pretty close to what is already done?

**Comment by thinkyhead** [comment]
@Roxy-3DPrintBoard You coincidentally mentioned a line which is controversial.

```
current_position[Z_AXIS] = zprobe_zoffset;
```

You will notice that this line appears immediately after the line:

```
current_position[Z_AXIS] = corrected_position.z;
```

So there's talk of just getting rid of the line that uses `zprobe_zoffset`. Does that dovetail with your understanding, or is there some valid reason that odd line is included?

**Comment by nophead** [comment]
@thinkyhead,
  That might be a reasonable heuristic but least squares fit is an algorithm that minimises the larger errors at the expense of more smaller errors. That seems a reasonable criteria for getting the first layer laid down, particularly if the outer probe points match the bounding box of the object. When the probe offset prevents that the parts of the bed that cannot be reached might have a worse Z offset because had they been probed they would contribute greatly to the sum of squares. I.e. points on the outside are very sensitive to the tilt of the plane.

@Roxy-3DPrintBoard,
  Yes I understand basic calculus. I used to win prizes for maths at school but that was a long time ago now!

There may be more than one solution that gives the least sum of squares but there is only one correct minimum value. If you are able to beat the current code and find a lower sum then it must have bugs.

I still don't understand what you mean by solutions with an unusable value of d. a, b and c are the normal vector of the plane and define its tilt. In the normalised form (where a^2+b^2+c^2=1) d is the distance to the origin. Changing d moves the plane up and down along the normal vector. The bounding values of d must be when the plane is above all the points and below all the points. d must always lie between these two extremes because once outside of that range all the squares are increasing.

**Comment by Roxy-3D** [comment]
soon to be replaced!!!

**Comment by nophead** [comment]
I think you misunderstood what I meant by "If you are able to beat the current code and find a lower sum then it must have bugs".

I mean if you can beat QR solve then QR solve has bugs.

**Comment by nophead** [comment]
Regarding d, I think it cannot make sense if the distance from the inclined plane to the origin is bigger than all the Z values from the X Y plane.

Is what you are summing (aXi + bYi + cZi - d)^2 ?

**Comment by nophead** [comment]
Also c should be close to 1, but not actually 1 unless a and b are 0.

**Comment by Roxy-3D** [comment]
Marlin calls QR_SOLVE() with c=1 and fixed.   I kind of disagree with this too because it really is going to end up at something like .999 or .998 with a fairly level bed.

And, Yes, I'm summing the 'error squared' between the plane equation and what is measured.  But the negative numbers caused a bug so I'm re-doing things...

UPDATE:  When I say I'm summing the square of the error between the plane equation and what is measured...  I'm doing that by subtracting the measured Z from the Z predicted by the plane equation.  I chose not to measure the distance in a plane-normal direction because the Z_PROBE doesn't move that way.    Do you have an opinion on this?

**Comment by nophead** [comment]
Yes C will be very close to 1 but then A and B are similarly close to 0 unless your bed is on a massive slant in 3D printer terms. We are talking about small fractions of a mm over something like 200mm.

**Comment by Roxy-3D** [comment]
Yes, but from an error perspective..  Especially because the error is being squared...  Which distance is best to use for the error?   The plane normal direction to the point (which is a little bit shorter) or the vertical distance?

**Comment by nophead** [comment]
The plane normal direction, which I think is (aXi + bYi + cZi - d)^2 where Xi, Yi, Zi are the probed points.

**Comment by nophead** [comment]
Note it is only the distance when a,b and c are normalised, which they aren't if c is fixed at 1. You would need to divide by sqrt(a^2 + b^2 + c^2) if it is not 1.

**Comment by Roxy-3D** [comment]
OK...  Understood...  I'm going to redo things to make my stuff better....    But QR_SOLVE is returning a 'd' constant that is outside of the bonds we both agree should be respected.   (if the bed is tilted too much)

**Comment by Roxy-3D** [comment]
> So there's talk of just getting rid of the line that uses zprobe_zoffset. Does that dovetail with your understanding, or is there some valid reason that odd line is included?

@thinkyhead 

I think there is value in using the coefficients returned by what ever solves the Least Squares Best Fit algorithm.   A much better solution (mathematically) is possible by allowing the offset to be set by the algorithm as part of the solution.  But the algorithm also needs to be sensitive to how much this offset can be adjusted.  The nozzle must be close enough to the surface of the bed to force good adhesion and if that constant is adjusted just for the sake of getting the numbers better for the least square fit it is self defeating.  (And I have some data sets where I skewered the bed enough that the returned 'd' offset is clearly not acceptable.  It was when I was trying to re-level my bed that I discovered that pre-processor issue that was causing the bed topology to mapped wrong)

I'm starting to understand things much better.  This is a really great group of people!  It is helpful to have people that know so much to guide your own thinking!  I expect soon I'll have a solution that takes much less code space and produces at least as good of results as the current code base.  I'll keep you posted!

**Comment by nophead** [comment]
Maybe it is simply broken, like the rest of the levelling was when I first started looking at it. 

"The nozzle must be close enough to the surface of the bed to force good adhesion and if that constant is adjusted just for the sake of getting the numbers better for the least square fit it is self defeating."

The least squares value is a measure of how close the plane is to the measured Z values so I can't see how a lower sum can give a worse extrusion result. Something is wrong with the maths if that happens.

**Comment by AnHardt** [comment]
I believe zprobe_zoffset must be somewhere.
     current_position[Z_AXIS] = zprobe_zoffset + corrected_position.z;
or something like that?

**Comment by Roxy-3D** [comment]
> The least squares value is a measure of how close the plane is to the measured Z values so I can't see how a lower sum can give a worse extrusion result. Something is wrong with the maths if that happens.

Yes.  I agree.  That is good insight.  I need to circle back and figure out why QR_SOLVE is doing that.   

> I believe zprobe_zoffset must be somewhere.

It is.  Inherently, the numbers being sent into the least squares fit algorithm are all going to be offset by that much from zero.

**Comment by nophead** [comment]
In my implementation my probe function subtracts the z offset of the probe from the measured z, so the plane equation I make is the actual plane of the bed, not one floating above it by the probe offset. Then I add -d / c to the z values during the transformation, whereas Marlin just does a rotation, so never uses d.

I can't get my head around whether that is the same but this

```
current_position[Z_AXIS] = corrected_position.z;
// put the bed at 0 so we don't go below it.
current_position[Z_AXIS] = zprobe_zoffset;
```

definitely looks wrong to me as it throws away the rotated version of the current z. 

Also what is the current position at the time it does this? Why does z happen to equal the probe offset?

**Comment by thinkyhead** [comment]
The pending PR #1700 is fixing up all the leveling issues I can find. Give it a scan if you have some time. I will add the `zprobe_zoffset` into the equation. I think the bad line was just supposed to say `+= zprobe_zoffset` instead of `= zprobe_zoffset`.

**Comment by nophead** [comment]
The abs on this line is bogus:
https://github.com/MarlinFirmware/Marlin/blob/9e8427f253158c59ea01fbd3b694200ec7e8a557/Marlin/Marlin_main.cpp#L1120.

I pointed this out before and I thought it got fixed. If the Z coefficient
is negative, the points are in the wrong winding order. To fix it the
normal vector should be inverted, not just its Z coefficient.

**Comment by thinkyhead** [comment]
@nophead Is the solution _only_ to remove the `abs()` or do we need to mess with the normalize function (or its results)?

**Comment by thinkyhead** [comment]
How do you feel about this? Proper?

```
current_position[Z_AXIS] = corrected_position.z + zprobe_zoffset;
```

**Comment by nophead** [comment]
Instead if abs it should be something like this:

```
planeNormal = planeNormal.z > 0 ? vector_3( planeNormal.x,  planeNormal.y,  planeNormal.z)
                                                 :  vector_3(-planeNormal.x, -planeNormal.y, -planeNormal.z);

```

Regarding  zprobe_zoffset, I don't know, its confusing the hell out of me.

The probed values are returned without correcting for the offset. But as far as I can see those values are only used to calculate the plane normal. I don't see how the plane offset from the origin is calculated or corrected for. Presumably this line, but I can't see how it is equivalent to what I did with the d value from the plane equation that I derived from the plane normal.

**Comment by nophead** [comment]
Or perhaps less code with

```
if (planeNormal.z < 0) {
    planeNormal.x = -planeNormal.x;
    planeNormal.y = -planeNormal.y;
    planeNormal.z = -planeNormal.z;
}
```

**Comment by nophead** [comment]
Also there is no need to normalise the two vectors here before crossing them as the result is normalised.
https://github.com/MarlinFirmware/Marlin/blob/9e8427f253158c59ea01fbd3b694200ec7e8a557/Marlin/Marlin_main.cpp#L1117

**Comment by thinkyhead** [comment]
```
vector_3 planeNormal = vector_3::cross(pt1 - pt2, pt3 - pt2).get_normal();
```

?

**Comment by nophead** [comment]
Yes I think that is all it needs followed by the check for negative Z and the three negations.

**Comment by thinkyhead** [comment]
I think the point of the z offset is because the nozzle is above the bed (or below), and it wants to correct the coordinate so it's at the level of the bed.

**Comment by nophead** [comment]
Yes but what happens to the Z information that the nozzle gained? Say all
the points are 1mm high. How does that end up offsetting the Z axis by 1mm?
It only seems to be used to calculate the plane normal, which is just a
direction to rotate to.

**Comment by thinkyhead** [comment]
@nophead Hmm! Well, if it's only used in getting the normal, then it just needs to be consistent. Have you tried it both with and without `zprobe_zoffset` being added and found it makes no difference?

**Comment by nophead** [comment]
I have never used the code in Marlin, only my own Python version, which definitely works.

Adding zprobe_zoffset must offset all Z values by the probe offset but I only offset them by the distance of the plane from the origin. I don't see how the two methods are equivalent.

**Comment by thinkyhead** [comment]
Well, the thing is, not only are these values being used to do the calculations, they also go into `current_position[]` and are passed in `plan_set_position`. So the important thing, I think, is that whatever goes into these variables, it should be the true nozzle position at all times. Otherwise people start their prints and printing starts in the air – or it _could_.

**Comment by nophead** [comment]
So why is the current position changed by the probe offset without it having moved?

I am not saying it is definitely wrong, but having written the first version, I can't understand how this one works.

**Comment by nophead** [comment]
To correct the bed you need to tilt the model by rotating it and also offset it by the difference between the the probed z values and the probe offset. As far as I can see the probed z values are only used to rotate it. I can't see how they influence the offset, which seems to just be equal to the probe offset.

**Comment by thinkyhead** [comment]
@nophead I admit I have not run this code in my head to follow all the effects of these functions. But I feel certain that it's important that the `current_position` be set properly when the process is complete, even if it doesn't matter for the math of leveling. I just want to make sure that we don't see any more printing in the air after leveling because the Z coordinate is incorrect.

**Comment by nophead** [comment]
Well the planner normally keeps track of the current position. When the rotation matrix is set the current position has to be corrected slightly to account for the fact it is now being rotated. The two things I can't understand are why the current position suddenly needs to change by the probe offset. That would imply it gets messed up during probing, but why? The probe is a series of normal moves, why does it mess up the planner's current position?

The other thing is how does the difference between the probed position of the bed and the expected position of the bed get compensated for? Can somebody confirm it is? For example can you put a thick sheet of glass on you bed and have it compensated for automatically? If so where is the code that does that?

**Comment by nophead** [comment]
Does the probing action change Z due to the probe acting as a bottom limit switch?

**Comment by nophead** [comment]
So I think I understand this now. When the probe activates it is seen as the bottom limit and changes the Z position. That means the last point probed sets the offset. That should be OK when your bed is flat as all points would be on the same plane. I don't think it makes sense when doing the grid probe as the best offset should come from the plane equation, not an arbitrary last point probed.

**Comment by Roxy-3D** [comment]
> That should be OK when your bed is flat as all points would be on the same plane. I don't think it makes sense when doing the grid probe as the best offset should come from the plane equation, not an arbitrary last point probed.

Agreed!  But the thing that concerns me is I have data sets where QR_SOLVE is altering 'd' more than is acceptable.   I'm trying to figure that out right now.  That may be why the original author did not use the 'd' value returned by QR_SOLVE and just settled for a number (s)he knew wasn't too far off ???

**Comment by nophead** [comment]
This looks relevant so finding the best plane:
http://www.sbg.bio.ic.ac.uk/~islam/plane.html. It loses me when it starts
talking about eigenvectors. Not sure if it the same as qr_solve, or a
simpler method specific to planes.

**Comment by Roxy-3D** [comment]
I can't read that right now... But I will.   However, I do know that eigen vectors are important for solving linear systems of equations.   The reason is there are enough 0's and 0's in the right place that once you know one correct value, you can keep back substituting to get more and more of the values in the system.

**Comment by nophead** [comment]
I think what the paper says is that you can solve the least squares plane
by differentiating the quality function (which is the square of the plane
equation) with respect to each of the constants, A B C D, in turn and
saying that must be zero at the minimum. That gives n simultaneous linear
equations in n unknowns and then solves those.

I think qr_solve solves a harder problem in that it finds the best solution
for a set of simultaneous equations that don't have an exact solution. Best
being defined as least square of errors.

If that is the case it should be possible to do it with less code than
qr_solve and perhaps get a better result. I am not totally sure about this
though as I thought simultaneous equations cold be solved with matrix
inversion. I vaguely remember writing a program to do this on a Commodore
PET while at school to solve voltages in arbitrary resistor networks and I
certainly didn't know anything about eigenvectors then.

**Comment by alexborro** [comment]
@nophead,  you are correct. The current code just compensate the tilt. The
offset must be adjusted by Z_Probe_Offset.
But once set a working Z_Probe_Offset, you can raise or lower the bed and
the offset should be right.
Em 27/03/2015 17:18, "Chris" notifications@github.com escreveu:

**Comment by thinkyhead** [comment]
Where does the original issue stand? Is graphical LCD alone still enough to make the size too large? We've been able to reduce the code by several K in recent commmits.

**Comment by unlimitedbacon** [comment]
Next week I will try pulling the latest changes, recompiling with Arduino 1.6, and let you know.

**Comment by thinkyhead** [comment]
Here are the build sizes for the current code with Arduino 1.6.1:

```
 51,874 : Default configuration
 95,562 : G3D_PANEL
 95,568 : REPRAP_DISCOUNT_SMART_CONTROLLER
106,960 : REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
+11,398 : Difference of G3D_PANEL vs REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
```

All the LCD options here enable `SDSUPPORT` by default as well.

**Comment by nophead** [comment]
@alexborro,
   Yes any solution that uses a probe separate from the nozzle needs to be told the exact vertical offset between them as well as a reasonably accurate horizontal offset. The issue with Marlin is it appears to only take the height reading from the last point probed. My implementation calculates it at the origin using the plane equation. I think this is more accurate even with 3 points if the bed is not perfectly flat because all three points contribute to the height. It is certainly better for the grid version where calculating a least squares plane through all the points and then ignoring the height of that plane and using the last probed point, which will be a corner, is not going to give a good result when the bed isn't flat.

**Comment by Roxy-3D** [comment]
> If that is the case it should be possible to do it with less code than
> qr_solve and perhaps get a better result. 

I am currently able to get the exact same results as QR_SOLVE with very little code.  I have not compiled it inside the Arduino environment yet, but I'm guessing it is going to weigh in under 1 Kb of code.   

UPDATE:  To get it to conform to the existing calling convention it comes in at 2.5 Kb of code.  That can drop if we don't decide to use the convoluted QR_SOLVE calling convention.

**Comment by alexborro** [comment]
@nophead you are right. The Z position is referenced in homing. So the Z
Offset is applied over this reference. Maybe the right procedure would be
re-reference the Z position with the value returned from the leveling
algorithm -  that plane will become the zero height (Z=0)

@Roxy nice job on that!

Cheers.

Alex.
Em 28/03/2015 06:49, "Chris" notifications@github.com escreveu:

**Comment by thinkyhead** [comment]
I've posted [a couple of comments](https://github.com/MarlinFirmware/Marlin/issues/1682#issuecomment-87336527) after looking at the code from the 14th and the 1st. To sum up, these lines existed in the `set_bed_level_equation_*()` functions at both of those times, and leveling seemed to be more reliable vis-a-vis, having a workable z position at the end:

```
// put the bed at 0 so we don't go below it.
current_position[Z_AXIS] = zprobe_zoffset; // in the lsq we reach here after raising the extruder due to the loop structure
```

The previous line (`current_position[Z_AXIS] = corrected_position.z;`) becomes superfluous, so could be removed – the compiler probably drops it.

**Comment by Roxy-3D** [comment]
About 10 Kb of space can be freed up.   But once again...  I'm fighting GitHub!   :)

Please visit https://github.com/MarlinFirmware/Marlin/issues/1671#issuecomment-87281405

**Comment by mr-sneezy** [comment]
I recently updated to 1.0.3 Dev, and with Full Graphic Display support enabled I get a compile of 119k.
So the changes have helped a lot to keep 128k boards supported.
Thanks,
Martin

**Comment by thinkyhead** [comment]
> I get a compile of 119k

Nice! We've done a lot of code squishing lately. There's a way to set the Arduino compiler to make the code even smaller, but it's great to know that's not needed.

**Comment by boelle** [comment]
closing and it seems to bed fixed
