### ISSUE TITLE
[BUG] Extruder motor doens't work with marlin 2.0.2 (driver A4998)

### ISSUE THREAD

**Issue by bananafell3r** [MarlinFirmware/Marlin#16719]
Hi guys, 

I have an alfawise U10 (motherboard RAMPS PLUS), I installed marlin 2.0.2 but the extruder doesn't work. Do someone have this problem? how I can fix it?

https://drive.google.com/file/d/1pNqSRp-dhhlyftrBJUx9mSIKRULRkVvo/view?usp=sharing

https://drive.google.com/file/d/1HTfZlRiXXVGHAEGYAxCB9Nxd0vStXj4W/view?usp=sharing

**Comment by reloxx13** [comment]
did u heat up the nozzle before moving e ?...

**Comment by bananafell3r** [comment]
Yeah, obviously... And I tried, also the runout sensor doesn't work...

**Comment by bananafell3r** [comment]
My board is exactly 3dymy ramps 1.4 plus

https://reprap.org/wiki/Ramps1.4plus

**Comment by ellensp** [comment]
The page https://reprap.org/wiki/Ramps1.4plus has a circuit diagram that shows same pin out as ramps1.4. But the file pins_RAMPS_PLUS.h moves e0 pins (and others) elsewhere.
Since your e0 isnt working I wonder if there are more than one version of the ramp 1.4 plus...   try  MOTHERBOARD BOARD_RAMPS_14_EFB

**Comment by bananafell3r** [comment]
Yes, the extruder works now.. But the filament sensor doesn't work.. I changed the pin sensor in 11, I am trying now to set the default pin 4.

**Comment by ellensp** [comment]
Either way, it is not a bug in marlin, but just a configuration issue. please close this Bug report.

**Comment by bananafell3r** [comment]
I solved...I close it
