### ISSUE TITLE
Delta kinematics inverted mounted [FR] (feature request title)

### ISSUE THREAD

**Issue by mac7988** [MarlinFirmware/Marlin#17140]
How can I calculate arm length for 3 axis if the delta was mounted like image below?
![image](https://user-images.githubusercontent.com/19393673/76528594-72d15b00-6447-11ea-8dd1-f8eb90dc5e38.png)

Traditionally the delta configuration in on 3 towers. 
![image](https://user-images.githubusercontent.com/19393673/76528755-af9d5200-6447-11ea-9fe9-e167134c51d5.png)

**Comment by ellensp** [comment]
Surly the length is the same. From center of each joint. But your going to need a new kinematic model for that type of machine.

**Comment by mac7988** [comment]
> d

Is this something that is possible to do?

**Comment by ellensp** [comment]
Possible yes... have the resources and the interest to do it.. unlikely.

**Comment by pablopeu** [comment]
The kinematic model is different because you now have angles and the definitions for a delta machine don't

**Comment by sjasonsmith** [comment]
@mac7988 is this request for something which actually exists, or is this just a hypothetical question?

It is already hard enough to find people willing to support Delta kinematics. It is unlikely anybody would ever volunteer to implement this without being directly involved in the project to create the machine. In other words, if this is something you really want, you will likely have to do it yourself.

**Comment by sjasonsmith** [comment]
Given the lack of response to my earlier comment, I am going to close this FR. While this is an interesting thought experiment, I don't see any way this would ever be implemented unless it were contributed by the person creating the printer. There is also no information provided regarding _why_ anyone would use such as design.

Adding new kinematics because they are interesting without practical implementations complicates maintenance without providing any value.
