### ISSUE TITLE
[BUG] SKR 1.4 ERR: MAXTEMP: BED

### ISSUE THREAD

**Issue by trojan-xs** [MarlinFirmware/Marlin#17286]
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4378999/Configuration.zip)

### Bug Description

Right now it says:
**ERR: MAXTEMP: BED
PRINTER HALTED
Please Reset**
Every time I boot it up.
Sometimes it says **MAXTEMP: E1** depending on how I fiddle with the firmware (I tried multiple things to fix this issue, all of them were stupid solutions and I'm to embarassed to post them here so I will not).
Curious thing though, I'm using E0 Not E1 (Maybe something to look into later).
I'm relatively new to the firmware side of 3D printing so please excuse me if I leave anything out or say anything stupid

### My Configurations

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/4379001/Configuration_adv.zip)
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4379005/Configuration.zip)

### Steps to Reproduce

1. Follow Teaching Tech's "[SKR V1.3 Comprehensive guide](https://www.youtube.com/watch?v=GNGN2iSQ5j4)"
2. Instead of LPC1768 (SKR1.3), use LPC1769 for the environment (SKR 1.4 Tubo)
3. Flash the firmware on to your SKR 1.4 Turbo
4. Cry because you've spent 12+ hours trying to fix this issue

**Expected behavior:** [Printer runs Marlin normally]

**Actual behavior:** [The display beeps intermittently and displays "ERR: MAXTEMP: BED, PRINTER HALTED, Please Reset]

**Comment by rado79** [comment]
> "ERR: MAXTEMP: BED, PRINTER HALTED, Please Reset"

Same error appears, if bed thermistor has short circuit.
If you have not tried, unplug bed thermistor and reset again.

**Comment by trojan-xs** [comment]
> > "ERR: MAXTEMP: BED, PRINTER HALTED, Please Reset"
> 
> Same error appears, if bed thermistor has short circuit.
> If you have not tried, unplug bed thermistor and reset again.

The problem is that I've unplugged everything and I'm running the board's power via my PC. Nothing's plugged in apart from the LCD.

**Comment by thisiskeithb** [comment]
> The problem is that I've unplugged everything and I'm running the board's power via my PC. Nothing's plugged in apart from the LCD.

With no thermistors plugged in & the board immediately hitting max temp, something is likely damaged on the board.

**Comment by trojan-xs** [comment]
> > The problem is that I've unplugged everything and I'm running the board's power via my PC. Nothing's plugged in apart from the LCD.
> 
> With no thermistors plugged in & the board immediately hitting max temp, something is likely damaged on the board.

That's weird, everything was working perfectly before I swapped the LCD connectors

**Comment by nogarth** [comment]
I fet same error when i heat my bed up for a print falls over from bed. But if i preheat bed and leave it for a bit it prints ok. Few more trsts tomorrow as i have print running now so gonna test from a cold start tomorrow

**Comment by RFBomb** [comment]
Did you ever resolve this? I am having similar issue.... https://github.com/MarlinFirmware/Marlin/issues/17633

Except it doesn't occur on older firmware (2.0.1)

EDIT: For anyone in future reading this: I resolved my issue, which was similar. I have no idea what the issue was, all I did was recompile the same firmware version using the same config and this time it didn't error out. More details are in my post I link above if needed.

**Comment by mdellen** [comment]
I also get the max temp E1 (SKR 1.4 turbo) after upgrading to the latest bug fix release. Will try to recompile to see if it is persistent. (reverting back to a previous version solves the problem) when I compile the bug fix 2.x with **//#define THERMAL_PROTECTION_HOTENDS** I still get the max temp error on boot?

Flashing back 2.0.1 resolves it, but rebuilding bug fix 2.x (remove .pio and update all) still gives the max temp E1 error, read THERMAL_PROTECTION_GRACE_PERIOD 4000 resolved this in the past but is since depreciated. 

update: moved to 2.0.5.3 (non bugfix, problem remains) Only have 1 extruder so was expecting E0.  moving back to 2.0.1 and all is fine, will recheck my config files.

**Comment by mdellen** [comment]
When compiling the exact same source code today I get the E1 max temp error. When I load the .bin from a few months ago (same source) everything is fine. So it seems something has changed in the libraries and not Marlin itself.

I need to change something in the config but am not able to compile new firmware without getting the error. Tried BTT 2.0.1 branch, 2.0.1, 2.0.4.4 and 2.0.5.2
