### ISSUE TITLE
G29 must require homing of all axes

### ISSUE THREAD

**Issue by gaussgss** [MarlinFirmware/Marlin#1760]
When Z axis isn't homed and bed auto-leveling requested, `G29` produces wrong results.

Tested on commit be593b600b8b9b427656dd27be7fc277aec0a8a5

**Comment by thinkyhead** [comment]
@gaussgss Currently the `G29` command doesn't care if Z is at a known position, just that X and Y have been homed. It probably should prevent using `G29` unless Z has also been homed (especially on deltas).

**Comment by Ziggy2013** [comment]
It's not clear to me why Z must be homed before a G29.  The G29 itself needs to establish where the Z home is a first step before probing. And the point the G29 uses to establish Z Home could be different depending on the type of probing (eg 3 point, 9 point etc)

**Comment by thinkyhead** [comment]
@Ziggy2013 Well, that 's what `G29` is failing to do – establishing a known Z position before probing. If it doesn't get it from a `G28` homing command, then it must establish it when first starting to probe the bed, and I'm not sure it does that.

**Comment by tonnico** [comment]
I don't think that's a good idea to implement the home z in the g29. On Repetier this makes also some trouble. For the transformation you need a fix point from where you can calculate it. If you don't home z and make a g29, the probe will not know where it is.

You can't measure the length of your living room from everywhere. You will go to one wall/edge first.

**Comment by nophead** [comment]
I home to the top and use my probe to find where the bed is, not as a
bottom end stop. I think Marlin is broken because it treats the probe as a
bottom end stop, so whenever it hits it resets the Z home point. At some
point this needs to be fixed so it uses the height information from the
plane equation, which is more accurate.

If you don't a bottom endstop then the probe needs to act as one in G28 but
not G29. I feel yet another horrible global flag being born.

**Comment by Ziggy2013** [comment]
IMHO the G29 should first establish a start "reference" Z = 0 point using the probe.  Where that reference point is on the X/Y plane needs to be set based on the type of probing to be done.  eg a 3 point probe may require a different start Z reference point to a 9 point probe.

If G28 is also going to set that Z "reference" point as well, then the same X/Y reference point as used by the G29 probing needs to be used.  

Need to also keep in mind that not all auto leveling implementations use a separate Z probe.  For example, some implementations use the extruder tip itself to find the Z reference point.  Others use a dockable Z probe sled. In these implementations should G28 always try to find the Z reference point using the extruder or the sled?  

In the older version of Marlin I am using with auto leveling set the G28 only homes X and Y.  The G29 first raises the extruder/probe, moves to the centre of the bed, lowers the probe until it touches the bed to establish a Z reference point.  After that the G29 does its 9 point probing.  This all works very well. I am not sure what adding Z homing to G28 is trying to fix?
.

**Comment by thinkyhead** [comment]
We have a PR pending that establishes a separate `Z_PROBE_PIN` so that the probe can be treated differently from an endstop. I suspected that the logic was being screwed up by the resetting of the Z position every time the probe switch is triggered. I will continue to document and do a full write-up of the program flow during bed leveling, and this should help to reveal where changes need to be made so that probes and endstops can get along together.

Note that in addition to probes that use the nozzle as the probe, there are some that use an NC switch with a floating X gantry, and these could conceivably re-use the Z endstop by applying the right (opposite) logic. (e.g., if the Z axis goes "below" the z endstop it breaks the circuit. Only works with an NO switch as the Z min endstop.)

**Comment by KariVargr** [comment]
I know with the Delta you need to G28 sending G29. i would have to double check but i dont think if DELTA is defined that the received G29 runs a G28 before. this might be a good thing to add for the DELTA mode as for those you always need to home the unit first.

**Comment by TechMasterJoe** [comment]
I honestly think that g29 needs to implement a integrated ver of safe home z before starting where it touches off the bed center and stores that info as a reference just for auto bed leveling. As a plain Z home can be done anywhere with the side-effect of over- or under- comp, with auto bed leveling it's like tossing in a random value for i in a PID never made sense to me.

Honestly think we need a fixed optical endstop that's on the Z axis independent of the bed as a hard reference that we set to a sheet of paper off the center of the bed. I know this sounds like more work, but hey, with a hard-set home the topographical bed map can even tell you direction and how many turns each bed screw is off-by, making bed leveling a breeze.

**Comment by thinkyhead** [comment]
I think that if you issue a `G29` and the axes haven't been homed, it should just call `gcode_G28` directly instead of issuing a message that you need to home first. I think that would be a reasonable _expected behavior_ for this use case.

**Comment by TechMasterJoe** [comment]
agreed

**Comment by Ziggy2013** [comment]
Please keep in mind that the `M206` and `G92` gcode functions also need to be handled if `G28`'s are proposed to be done implicitly with a `G29`.

**Comment by KariVargr** [comment]
I was just looking over the code, to see if there would be a conflict with the `M206` and `G92` by Adding a `G28` to the `G29` command. As far as i can tell (still trying to study the code enough to know where everything is)  `M206` and `G92` do not call, there should be no problem adding a command to call `G28` before running running `G29`.

**Comment by thinkyhead** [comment]
I think the issue is, if you do a `G29` expecting values that you intentionally set with a `G92` (or if offsets were changed using `M206`) then a `G28` could mess that up. Sometimes `G92` can do the job of a `G28` (on such machines as the QuadRap which have no end-stops). But I think that when you do `G92` the axes you set are flagged as "known" so there should be no XY homing if those axes are set (and marked known) by any method. Homing will only occur when axes are "unknown."

**Comment by Ziggy2013** [comment]
More generally the issue is the G29 needs known X = 0 and Y =0 reference
points to be able to probe the bed and calculate the bed plane using the
measured Z probing points. The G29 also needs to measure/calculate an
assumed Z = 0 reference point.  The known X = 0, Y = 0, Z = 0 reference
points then need to be the same during the print otherwise the calculated
plane will not be usable when adjusting the Z to match the bed plane.

In other words G28 homing followed by G92 / M206 offset adjustments should all be ok PRIOR to the
G29 being completed but not after.

**Comment by boelle** [comment]
This issue was moved to MarlinFirmware/MarlinDev#20
