### ISSUE TITLE
[BUG] i2c eeprom hangs on samd51

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#17813]
#17651 removed `eeprom_init` call from byte read/write functions but not to block counterpart (why removed partially?).
This PR causes in SAMD51 a hang when accessing i2s eeprom.

**Comment by p3p** [comment]
`eeprom_init` has been removed from the `eeprom_write_byte` function because you dont really want to reinitialise the i2c/spi peripheral on every byte,

The eeprom code is still being updated but it looks like currently the samd51 platforms new `eeprom_wired.cpp` has the `eeprom_init` call missing from `PersistentStore::access_start()`.

**Comment by GMagician** [comment]
> eeprom_init has been removed from the eeprom_write_byte function because you dont really want to reinitialise the i2c/spi peripheral on every byte,

And why is it needed in block functions? I'm expecting it to be removed even there

**Comment by GMagician** [comment]
> eeprom_wired.cpp has the eeprom_init call missing from PersistentStore::access_start().

no platform but lpc1768 has such call in `PersistentStore::access_start()`

I'm fixing samd51 but wondering if other HALs have the same issue

**Comment by p3p** [comment]
Thinkyhead is rewriting a lot of the eeprom access code across the platforms and there is currently a PR with further updates, I think it was just an oversight that removing `eeprom_init` from `eeprom_write_byte` would require calling `eeprom_init` in `PersistentStore::access_start()` for the PersistentStore implementations that use the old avr `eeprom` functions.

**Comment by GMagician** [comment]
Posted a PR to fix
