### ISSUE TITLE
 linear advance slow prntng

### ISSUE THREAD

**Issue by Crunch69** [MarlinFirmware/Marlin#17981]
Marlin 2,0 bugfix when linear advance 1.5 is compiled printng is very slow 

Attached are the configurations
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/4617441/Configuration_adv.zip)

Marlin 2,0 bugfix using TMC2209 

1. Compile with linear advance activated the printer runs very slow and the stepper motors heat up.
2. Compile without linear advance print speed normal.

**Expected behavior:** [Printer operates with new marlin 2.0 bugfix linear advance 1.5]

**Actual behavior:** [Printer does not operate correctly very slow print speed steppes heat up too hot to touch]

**Comment by XDA-Bam** [comment]
It's not clear to me, what "very slow" means in this context. Can you quantify this? Also, looking at your configs, there's a couple of potential problems:

- Your default extruder jerk of 5 is too low for LA in my experience. I run 15 on an Ender 3 Pro, which should have the same extruder. If the extruder jerk is too low, LA will reduce printing speeds to respect it.
- You are running Junction Deviation with a value of 0.02. If your print is mostly slow in corners and curves: That's why. Try 0.04, maybe even up to 0.08, depending on how stiff your frame is and how much ringing you are willing to accept.
- You are using S-Curve Acceleration with LA. That is not recommended and officially not supported, as far as I know. Deactivate it and check again.

If these config changes do not fix it, please let us know at which release it was still running fine for you (with the exact same config).

**Comment by margaale** [comment]
Sorry to jump in, but why is  scurve acceleration incompatible with LA? I've been using these both settings for a long time now, just asking thou.

**Comment by EvilGremlin** [comment]
LA don't account for SCurve correction, so result is quite unpredictable.

**Comment by rado79** [comment]
> LA don't account for SCurve correction, so result is quite unpredictable.

maybe needs sanitycheck ?

**Comment by qwewer0** [comment]
> maybe needs sanitycheck ?

It has.

**Comment by rado79** [comment]
i have/had both enabled, never saw a warning - or do i misunderstand sanity check?

**Comment by daleckystepan** [comment]
Check is not in stable version yet, only bugfix-2.0.x

**Comment by rado79** [comment]
ok, but i do bugfix-2.0.x update once a week. no sanity check warnings in VSCode.

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4624621/Configuration.zip)

**Comment by qwewer0** [comment]
> ok, but i do bugfix-2.0.x update once a week. no sanity check warnings in VSCode.
> 
> [Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4624621/Configuration.zip)

This is what you should see if you try to compile it with both LA & S-C enabled and `EXPERIMENTAL_SCURVE` is disabled:
`#error "LIN_ADVANCE and S_CURVE_ACCELERATION may not play well together! Enable EXPERIMENTAL_SCURVE to continue."`

**Comment by rado79** [comment]
@qwewer0 yes, disabling `EXPERIMENTAL_SCURVE` shows the warning. thanks for enlightening me.

**Comment by Crunch69** [comment]
XDA-Bam thank you deactivated S-Curve Acceleration changed default extruder jerk to 15
