### ISSUE TITLE
[FR] option to disable stepper Auto-Assignment

### ISSUE THREAD

**Issue by dshield55** [MarlinFirmware/Marlin#18196]
### Description

I think there should be a #define argument to activate/deactivate the Auto-Assignment for Dual X, Dual Y, Multi-Z Steppers section in pins.h. It should continue to be defined by default of course, but I ran into a project where auto-assignments were very troublesome and my options were to either comment out 300 lines (not easy to change or unchange) or delete the whole 300 line section (but then it's gone and troublesome to bring back.) Would have been super helpful if I could have just commented out a define argument and it disables the whole section.

**Comment by sjasonsmith** [comment]
I tend to agree with this. I personally prefer to know exactly how I'm configuring things as opposed to trying to keep track of some internal rules for how things get reassigned.

@dshield55 could you provide some more detail about your exact scenario?
Posting configs will likely be useful, along with your pins file since I'm assuming that will be needed.

I'd like a clear understanding of what you were trying to do that it caused problems.

**Comment by InsanityAutomation** [comment]
It wont auto assign anything that already has pins defined. Auto assignment only kicks in when you tell it to use more than what it has. Explicitly define Z2 and it wont re-assign an E stepper to it. This can be done in the pins file for the board or configuration.h
