### ISSUE TITLE
Auto Z_PROBE_OFFSET_FROM_EXTRUDER

### ISSUE THREAD

**Issue by lcfm1** [MarlinFirmware/Marlin#1835]
You can do this?

Theoretically, if I correctly input `MANUAL_Z_HOME_POS`, and manually expose position z-probe relative to hotend spending several measurements where the sensor will be triggered, I can get `Z_PROBE_OFFSET`.

**Comment by thinkyhead** [comment]
If you also have a Z endstop which is accurately set, then yes, you could automatically determine the distance from the Z probe to the Z position of the hot-end. It will also depend on having some point on the bed which you know to be at a good height.

**Comment by jbrazio** [comment]
@thinkyhead Why is this marked as a [open] feature request ? This seems a support question.

**Comment by thinkyhead** [comment]
@jbrazio My interpretation of this issue is that @lcfm1 is asking for us to write code implementing a new command which could automate the process of determining the distance from the nozzle tip to the probe. But in practical terms I don't think it's possible. It's also unnecessary, since a probe is expected to be at a fixed position, not movable.
