### ISSUE TITLE
UBL -Probe gets inactive

### ISSUE THREAD

**Issue by ircmgr** [MarlinFirmware/Marlin#18458]
There is an issue with UBL enabled. When i am doing a mesh level ( from LCD ) or a create cold mesh ( pla / abs "hot" mesh has the same behaviour ) it starts probing and after a while probe gets inactive and nozzle hits the bed hard.

Things tried :

* change the GRID_MAX_POINTS_X ( tried with values 10 ,4 ,5 )
* changed NOZZLE_TO_PROBE_OFFSET (tried 0,0,0 and the accurate ones)
* Z_PROBE_LOW_POINT ( from 0 to -7 , not going further it ll break my structure) 

Expected behavior : probe all points and give the mesh 
Actual behavior : Starts probing and after a while the probe gets inactive , probing continues slamming the bed but probe is inactive , even by putting a metal piece under it when high enough nothing triggers. 

After resetting probe is active again. Normal homing procedure runs as expected and prints start . the failure is while trying to configure UBL 

* Running on latest bugfix/2.0 branch

[config.zip](https://github.com/MarlinFirmware/Marlin/files/4866072/config.zip)

**Comment by boelle** [comment]
please attach the 2 config files in a zip file instead and remove the long config file text

just as the template told you to

**Comment by ircmgr** [comment]
> please attach the 2 config files in a zip file instead and remove the long config file text
> 
> just as the template told you to

done

**Comment by shitcreek** [comment]
Did it return an error message? What exactly do you mean by 'after a while'? Like after a couple probe points? Does it fail at the same probe point each time?
Have you checked your cables and connections?
Disable the motors (**M18**) and move the print head around and see if if you can trigger the probe manually from all areas of the bed - if it fails then it maybe be a kinked/loosed wire.

**Comment by ircmgr** [comment]
No it doesn't return an error. It is random point where it stops but always above point 14 in a 10x10 grid (100 points). If i reset on the last position an put my finger under the probe it will trigger so no cable faults.
If i manually move to any place it triggers as well. 

When this happens it ll start probing it ll reach a probe point number ( random above 14) and it ll keep probing there . Every time z goes below the low point it ll increase the probe point number and log the low point value in the mesh. But the head wont move! So if the issue starts at point 20 (assume somewhere close to center) then all points 21-100 will be probed at the same x/y  and in the end all these will have the low point value

**Comment by thinkyhead** [comment]
Whenever there are homing or leveling issues, we now ask everyone to follow a standard procedure to gather more information so that we're not just taking stabs in the dark. Here is the boilerplate:

- Download Marlin `bugfix-2.0.x` to test with the latest code.
- Enable `DEBUG_LEVELING_FEATURE` and `M114_DETAIL` and re-flash the firmware.
- Connect to your printer from host software such as Cura, Printrun or Repetier Host.
- Send `M502` and `M500` to ensure your Configurations are applied.
- Issue the command `M111 S247` to enable maximum logging.
- Perform a `G28` to do your standard homing procedure.
- Do a `G29` to probe the bed. This will also enable bed leveling.
- Copy the log output into a **.TXT file** and attach it to your next reply.

Repeat this procedure, if needed, to demonstrate inconsistencies. From these logs we should hopefully get a better idea of what's going on with your machine.
