### ISSUE TITLE
[FR] Add menu item to bed leveling menu to use G35

### ISSUE THREAD

**Issue by KyleLampkin** [MarlinFirmware/Marlin#18489]
It would be nice to have the G35 tramming feature added to the bed leveling menu so that you don't need to connect with a pc or write a gcode program.

**Comment by boelle** [comment]
could you please remove  half the post... i think when you read your own post you will get a smile on your face

**Comment by Tannoo** [comment]
Add to all bed leveling menues or just ABL?

**Comment by KyleLampkin** [comment]
I would think just the ABL and possibly UBL since you need a probe of some kind to make it work!

**Comment by InsanityAutomation** [comment]
The menu item probably makes sense where the G34 menu is. I added this to my existing PR #18737 where I was adding another menu right next to it.

**Comment by NetTecture** [comment]
I just was getting bugfix today and - I have a menu item, but it does nothing. Is that work in progress? Because - why have it in a LCD menu when I need to connect a terminal ANYWAY to see the output and get some use out of it. This shoudl be able to run either full  in menu, or - be removed from the menu, if one asks me.

**Comment by thisiskeithb** [comment]
Implemented in https://github.com/MarlinFirmware/Marlin/pull/20000
