### ISSUE TITLE
[BUG] Extruder issue: recommended steps/mm for BMG are for 1/16 microstepping 

### ISSUE THREAD

**Issue by Chris0812** [MarlinFirmware/Marlin#18622]
[Config.zip](https://github.com/MarlinFirmware/Marlin/files/4908299/Config.zip)

### Fixed
# two realizations
1. The 415 steps/mm for BMG and clones is for 1/16 icrostepping setting. I was using it as the full-step base value so far, making my extruder motor running at 16x the speed, it was supposed to.
2. The SD6128 that were meant for digipot Vref setting might be slightly messed up by me, as I used them until now at -what I thought to be- 1/32 steps...which was clearly not the case.

maybe delete the stuff below, as it might cause more confusion than help anyone?

### Bug Description

After upgrading to Watterott TMC2209 on my SKR 1.3 or SKR1.4, the extruder doesn't work: 
The extruder is screeching and skipping steps like it does in lin.advance or with way too low current. But even with 1000mA current setting.
Steps/mm are off when extruding but as written below, most likely a loosing step problem.

Drivers and board are properly modified as described by Watterott's knowledge base.
Side note: X,Y,Z work perfectly silent and with the correct microsteps.

### What I tried so far
- Tried different steppers, drivers (SD6128, A4988), cables and Z,E0,E1 driver positions: 
Always only the Extruder motor not working.
- upped the power to 1500mA 
- tested motor without any attachments: steps/mm setting are correctly applied on the motor
- compiled about 10 different  Firmwares with following changes to the stock version, at least the ones that even remotely are contributed to motion, extrusion and UART:

-- setting drivers to standalone
-- disabling volumetric extrusion
-- uart with hybrid Threshold and spread cycle de-/activated

- older Gcodes, to exclude recently changed Slicer settings

### My Configurations

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/4908299/Config.zip)

### Steps to Reproduce

1. Load Firmware with my config (with adjusted E steps)
2. Place any driver on E0 
3. Use extruder motor 
4a. Try retraction and extrusion in printing scenario
4b. try extruding with a host software at over 300mm/min

**Expected behavior**
Audible movement but nothing out of the ordinary

**Actual behavior**
Wrong extrusion values contradictory to the actual E step/mm set
Retracts not possible, only screeching

#### my Ideas
- I can relatively safe exclude the volumetric vs. linear extrusion possibility
- Somehow a bad link between the set and applied Feedrates (mm/min to mm/s?)
- messed up my Power supply along the way during change to SKR1.4? although, at least voltage is stable and reaches the board.
- I am overlooking something extremely obvious

**Comment by AnHardt** [comment]
> Load Firmware with my config (with adjusted E steps)

Without configuring max-speeds, accelerations, jerk-speed for your extruder it's completely random if your extruder can work or not.

**Comment by thisiskeithb** [comment]
I don’t think this is a Marlin bug since you have to modify your driver [as described here](https://github.com/MarlinFirmware/Marlin/issues/14683#issuecomment-513269551). There’s also some additional information in Watterott’s [TMC2209 Notes section](https://learn.watterott.com/silentstepstick/pinconfig/tmc2209/).

I’ve done the above mods on Watterott TMC2209s (and some other hackery to get the DIAG signal working since Watterott moved the pin location) and can confirm they work with Marlin.

**Comment by Chris0812** [comment]
I think, I can actually exclude the drivers themselves as I adjusted the Hardware accordingly. Will change the title, as soon, as I can pin the problems a little more down...
Set the Extrusion back to linear instead of volumetric, hoping this might help - it doesn't

**Comment by thisiskeithb** [comment]
What is the status of this? I can't tell what's being asked anymore or if your issue has been resolved.

**Comment by shitcreek** [comment]
Closing because this appears to be a case of user error.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
