### ISSUE TITLE
[2.0.x] CR-10S No media/No SD-card detected. [SOLVED!]

### ISSUE THREAD

**Issue by JalteJKR** [MarlinFirmware/Marlin#18864]
I have a CR-10S that I recently updated to Marlin 2.0.5.3 (I used the stock CR-10S configuration). But now the printer won't register the SD-card and the "Init. sd card" option is gone, so I can't do it manually either.

Here are my configuration files:
[Configuration-Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/5002705/Configuration-Configuration_adv.zip)

![115688015_666454990882037_7249644442061444496_n](https://user-images.githubusercontent.com/50962246/88952194-5ec3b400-d297-11ea-9169-5b8e640e7756.jpg)

**Comment by ellensp** [comment]
There where many SD card issues with 2.0.5.3  please use bugfix or at lease latest release 2.0.6

**Comment by boelle** [comment]
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by JalteJKR** [comment]
Thanks for the answers, I will try and update to 2.0.6, and if that doesn't work then I will try the bugfix. I will report back once I've tried 👍

**Comment by sjasonsmith** [comment]
@JalteJKR have you resolved this?

**Comment by Jimmy8881** [comment]
@JalteJKR on your configuration_adv
try changing:
 //#define SDCARD_CONNECTION LCD
to   #define SDCARD_CONNECTION ONBOARD

**Comment by JalteJKR** [comment]
Hello again, sorry that I never reported back, but I had a lot of issues updating marlin since I kept getting a "file name or extension too long" error. I have finally come around that and have successfully updated to marlin 2.0.x bugfix yesterday... But the problem is still there.

I will try doing what @Jimmy8881 suggested when I come home today, and I'm actually pretty confident that will fix the problem after looking it up in the code :)

![image](https://user-images.githubusercontent.com/50962246/98212370-c5fe9d80-1f43-11eb-812c-8253a875cace.png)

_This time I WILL report back!_

**Comment by JalteJKR** [comment]
It finally works!

Many many thanks to @Jimmy8881 for the solution 👍

**Comment by djardi** [comment]
This is not a complaint; I am very happy with Marlin and grateful for people's work. I am adding a comment in the hopes of bumping this issue to a higher priority. This is a significant problem for anybody with a Creality CR-10S printer. When you install Marlin 2.0.x, the SD card reader is disabled. I experienced this problem first with the branch of Marlin that I downloaded from TH3D and then with Marlin 2.0.x downloaded from github. Until I found this solution, I thought that I was going to have to choose between using old firmware or losing access to the SD reader. The fix is incredibly easy (alter one line of code in the Configuration_adv.h file as described above). This completely fixes the problem.

Unless this creates another problem that I am not aware of, it could be quickly fixed by a github volunteer who can edit the configuration file examples (Creality --> CR-10S --> CrealityV1 --> Configuration_adv.h). This would be a great service for those of us who own this printer.

Thanks for considering this change to Marlin!
