### ISSUE TITLE
is there a way to have an emergency stop button ?

### ISSUE THREAD

**Issue by jfpion** [MarlinFirmware/Marlin#190]
it could be useful when something goes wrong to have an emergency stop button which stop immediatly the moves and go up a few mm

could save some bed

if by the same occasion an resume button could be added to restart at the stop point it would be great

thank you

**Comment by beebenutz** [comment]
If your firmware has Watchdog, you could wire a momentary switch in parallel with one of your thermistors. A press of this button would result in the thermistor being shorted, resulting in  a halt of all functions and processes until manually reset. A resume wouldn't be possible with this method.
![20180303_104701](https://user-images.githubusercontent.com/37024014/36937439-808016f6-1ed0-11e8-89b7-0efb4b16e989.jpg)

**Comment by thinkyhead** [comment]
@beebenutz — Did you sign up to Github today just to post on this 5-year-old issue? _Thanks!_

That is a very roundabout way to call `kill()`, when you could just wire a switch to an endstop plug and add code to call `kill()` directly in response to a press.

**Comment by beebenutz** [comment]
I did sign up to post on this 5 y.o. thread. I didn't think knowledge had an expiration date! 

I wouldn't describe a direct method for completing a task as "very roundabout". The code for calling kill is already implemented within the thermistor watchdog which acts directly from a press.

**Comment by thinkyhead** [comment]
You'll have to forgive us. We have been experiencing a lot of troll activity, and we are thus highly suspicious of shiny new accounts doing unusual things.

Anyway, since we're here I'll elaborate on my opinion that this is "roundabout."

While certainly this method would work, it presupposes that:
- The firmware is not easily changed (it is).
- Wiring a switch in series with a thermistor is a good idea (it would be better not to).

The result of this modification would be:
- With recent Marlin the switch is ignored unless heating is started (maybe desirable).
- Resistance may be increased and noise introduced, altering the reported temperature.
- On press the machine would report `MINTEMP ERR` (hackish).

As a software person I tend to favor the software change that implements the desired feature formally, and in full. It would be my advice to anyone seeking to add such a switch –and who stumbles onto this page– to follow the methods outlined in more recent topics. Namely, connect a switch to an unused digital pin and add code to call `kill(PSTR("USER HALT"))` in response to the switch.

**Comment by beebenutz** [comment]
I forgive you. I am not a troll. 

Upon reading your last response I feel as though the presupposes have been preassumed. 

- I had not presupposed that the firmware was difficult to change. I supposed that the firmware already had code which would enable the task at hand, and it does. 

- I had not presupposed that adding a switch in series would be a good idea, for it would have obvious potential to cause incorrect resistance which would certainly cause incorrect temperature readings. I, instead stated as well as provided an accurate hand drawn wiring diagram that the proposition was to wire a switch in parallel with the thermistor, which would cause no inaccuracies. I supposed the only part I presupposed was that a software person could interpret a wiring diagram.

- It is correct that Marlin monitors temperatures while heating functions are or have been activated within a set amount of time, however the recommended MINTEMP and MAXTEMP functions are constant. In the latest Marlin dummy thermistors have also been implemented to allow testing. 

- On press the machine would report MAXTEMP triggered kill () called. The end game is a kill command being sent, which stops the machine as requested by the thread originator.

- I feel that instead of monitoring for trolls on this forum, you have seemingly become one yourself. I have not had someone try to discredit me so much without actually understanding the concept of what was being proposed. It is very unfortunate. 

- If anyone stumbles across this thread, look out for trolls, and keep a big stick!
