### ISSUE TITLE
K factor calibration tool (nozzle hitting the bed)

### ISSUE THREAD

**Issue by tiagomaricate** [MarlinFirmware/Marlin#19003]
Even if I but the Z offset, when the bed rises it always hit on the nozzle. After that, the nozzle touches the bed, and the print starts, but as the nozzle is too close, no line is printed.

I tested putting higher values for Z offset and the result is always the same.

I have a Robo R2 printer.

**Comment by boelle** [comment]
did you read the template????

Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by sjasonsmith** [comment]
I'm going to go ahead and close this, since it didn't follow the template and there isn't enough information to act upon.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org/)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
