### ISSUE TITLE
2.0.6.1 TFT_LVGL_UI_FSMC can't display pictures

### ISSUE THREAD

**Issue by diver197** [MarlinFirmware/Marlin#19219]
can't display pictures, only text，Maybe the picture was not read successfully
![a50b7c2b5cb518eb921096f26ae6bfc](https://user-images.githubusercontent.com/8023774/91836336-33a8f780-ec7d-11ea-9e1b-fdccc5f6b2ae.jpg)
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5155481/Configuration.zip)

**Comment by rhapsodyv** [comment]
Did you put the `assets` folder in the SD root?
The `assets` folder is generated in the build folder together with the firmware.

**Comment by diver197** [comment]
The relevant data has been written in flash, I read the code, it is estimated that there is no picture read

**Comment by rhapsodyv** [comment]
Do you board have SPI Flash?

Chip W25Qxx 

LVGL requires spi flash.

**Comment by thisiskeithb** [comment]
What is `BOARD_YL3V_V1`? That board doesn't exist in the main Marlin codebase.

**Comment by diver197** [comment]
Yes, the files in SD card on the screen are also written into flash

**Comment by diver197** [comment]
> What is `BOARD_YL3V_V1`? That board doesn't exist in the main Marlin codebase.
If you draw but directly on the screen, you can display it,
![a50b7c2b5cb518eb921096f26ae6bfc](https://user-images.githubusercontent.com/8023774/92068755-57ce1b00-edda-11ea-8706-d36761293eb4.jpg)

**Comment by diver197** [comment]
![96a6352001d1e02511c0b7bc1dc5f53](https://user-images.githubusercontent.com/8023774/92068817-7cc28e00-edda-11ea-9342-21bf0c34ace0.jpg)

**Comment by rhapsodyv** [comment]
Which flash?

There’s the prog flash. And the spi flash. That is a separated chip.

Seems your board don’t have a spi flash.

**Comment by rhapsodyv** [comment]
The board must have a chip like this. Without this chip, lvgl will not work.
![CD7B7D53-9B28-46D8-8802-CAB75A557F65](https://user-images.githubusercontent.com/81722/92069086-e745e080-ed7e-11ea-8bb3-db66f4669b1c.jpeg)

**Comment by thisiskeithb** [comment]
Which motherboard are you using? `BOARD_YL3V_V1` doesn't exist in Marlin.

**Comment by diver197** [comment]
#define HAS_SPI_FLASH                          1
#define SPI_FLASH_SIZE                 0x4000000  // 16MB
#if HAS_SPI_FLASH
  #define W25QXX_CS_PIN                     PA4
  #define W25QXX_MOSI_PIN                   PA6
  #define W25QXX_MISO_PIN                   PA7
  #define W25QXX_SCK_PIN                    PA5
#endif
![c8c03bf6da85e44e64fb784021f35c6](https://user-images.githubusercontent.com/8023774/92069153-4a656080-eddb-11ea-90db-2cfa0d8cc4e7.jpg)

**Comment by diver197** [comment]
![1](https://user-images.githubusercontent.com/8023774/92069428-e8f1c180-eddb-11ea-90cc-8918b4923aec.PNG)
![16043bf283569c72d6b8ebadc6c9a92](https://user-images.githubusercontent.com/8023774/92069516-235b5e80-eddc-11ea-94ac-763765bb3c41.jpg)

**Comment by rhapsodyv** [comment]
I think is because the current code fixes the spi flash to spi 2.

But your spi flash pins seems the spi 1.

We don’t have any other board similar to yours right now.

**Comment by thisiskeithb** [comment]
Closing since `BOARD_YL3V_V1` is not a valid/supported board.

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
