### ISSUE TITLE
[BUG] can’t flash SKR 1.3 

### ISSUE THREAD

**Issue by joneggg** [MarlinFirmware/Marlin#19367]
Hello, when trying to flash skr 1.3, it gives this:

![075EFFDF-1D16-4456-A544-9827049ECC23](https://user-images.githubusercontent.com/71187057/93005559-e7f72780-f573-11ea-8127-098e601031bc.jpeg)

Windows 10, Latest VSCode, latest platformio, github desktop, printerface and cura works good 

If I try to put sdcard to PC, PC don’t see sdcard

can this be repaired somehow?

**Comment by thisiskeithb** [comment]
Copy the firmware to your SD card instead of uploading it. This is not a Marlin bug.

<hr>

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
