### ISSUE TITLE
[FR] change M112 command

### ISSUE THREAD

**Issue by wzaburko** [MarlinFirmware/Marlin#19451]
I mount my first 3d printer from scrach.
On every stupid problem my printer say "System halted".
Probing feil - system halted
Heating feil - temp. drop because I open door - system halted
Homing feil - system halted
and lots of another stupid problem.

Every in this case i must restart manually, connect to octoprint, heat and waste time. 
On each stupid problem is M112 Emergency stop. 

Why?
Probing fail is reson to emegency stop?
I think M112 is not good in case of problem to debug.

Make warings with alarm with choice (continue, retry, cancel)
1. Heatings problem with alarm sound - warnings on screen (with options continue or cancel). If no rection shutdown.
2. Another problem with short sound  - retry/cancel on screen

**Comment by sjasonsmith** [comment]
These are treated as emergency stops because they risk severe damage to your printer or their surrounding environment.
Under normal circumstances you should never be encountering these. Rather than changing how this behaves, I suggest you seek to solve the electrical and mechanical problems on your printer causing these failures in the first place.
