### ISSUE TITLE
[BUG] Anet A8 fail compile in Arduino IDE 

### ISSUE THREAD

**Issue by Boia11** [MarlinFirmware/Marlin#19586]
### Bug Description

Compiling of Marlin firmware 2.0.7 for Anet A8 failed in Arduino IDE 1.8.13

### My Configurations

Configuration files it's the example configuration for Anet A8: 
 - [Configuration.h](https://github.com/MarlinFirmware/Configurations/blob/release-2.0.7/config/examples/Anet/A8/Configuration.h)
- [Configuration_adv.h](https://github.com/MarlinFirmware/Configurations/blob/release-2.0.7/config/examples/Anet/A8/Configuration_adv.h)
### Steps to Reproduce

1. Install Arduino IDE 1.8.13
2. Install [Anet A8 Board](https://github.com/SkyNet3D/anet-board) 
3. Download latest marlin firmware and configuration zip
4. Unzip firmware
5. Copy and paste Anet/A8 example configuration
6. Open Marlin.ino
7. Select "Anet V1.0" from board selector
8. Verify and Compile

**Expected behavior:** Compiled succesfull

**Actual behavior:** Failed compiling with error:
```
avr-gcc: error: CreateProcess: No such file or directory

exit status 1

Errore durante la compilazione per la scheda Anet V1.0.
```

**Comment by ellensp** [comment]
This is a Arduino IDE on Windows issue. Windows has a hard coded unchangeable max path/fork limit of 32K characters. Arduino IDE is written badly, when it attempts to link all the .o files together to form the final .bin file on large projects, such as Marlin, it generate one very long command that can easily exceed the windows limit.

There are a number of tricks to shorten the path under windows. 
Move marlin to root of drive, rename it to m
Delete unused parts of marlin such as unused HAL directories and unused display types. But this require in depth knowledge of how marlin works to know what is safe to remove.

Ultimately it is far better to use PlatformIO on vscode instead of Arduino IDE
PlatformIO only complies and links the code you need for your system, this avoids the Windows limitation. It also produces smaller binaries and is faster.
