### ISSUE TITLE
[BUG] Setting SKR Pro 1.1 causes Fans to disappear

### ISSUE THREAD

**Issue by Borillion** [MarlinFirmware/Marlin#19806]
### Bug Description

Setting #define E0_AUTO_FAN_PIN PE5 on SKR Pro 1.1 causes Fans to disappear

```
Marlin$ git branch -vv
  2.0.x        0a0f211cb [origin/2.0.x] Fix SAMD Serial name macro (#19765)
* bugfix-2.0.x 637582944 [origin/bugfix-2.0.x] Apply home offsets to probing, Z Safe Homing (#19423)

```

### My Configurations

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5398306/Configuration.zip)

### Steps to Reproduce

#define E0_AUTO_FAN_PIN PE5
Build  and Flash

**Expected behavior:**
Fans 0,1,2 be available in temperature menu

**Actual behavior:** [What actually happens]
Fans 1,3  are made available in temperature menu

#define E0_AUTO_FAN_PIN -1 (Default) 
![image](https://user-images.githubusercontent.com/954851/96388173-f8df1e00-115b-11eb-8c71-f9b1040b4bfe.png)

#define E0_AUTO_FAN_PIN PE5
![image](https://user-images.githubusercontent.com/954851/96387901-570b0180-115a-11eb-9fd1-a0dca3d4463b.png)

**Comment by thisiskeithb** [comment]
`PE5`/`FAN1_PIN` is the "second" fan and when you set it as `E0_AUTO_FAN_PIN`, it won't be controllable because it is controlled by your hotend temperature.
https://github.com/MarlinFirmware/Marlin/blob/6375829448eebe01b2835689aac69b73b63ebfd8/Marlin/src/pins/stm32f4/pins_BTT_SKR_PRO_common.h#L234-L240

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
