### ISSUE TITLE
[BUG] Freezing print randomly, auto-clicking and steep-skipping (Extruder) → New Ender 3 with the 4.2.2 board

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#19810]
# Ender3 with the 4.2.2 board randomly stops during prints

All was working fine but suddenly started stopping during the prints. 
Everything was on (motors/fans) and hot (hot end/bed). The LCD screen was normal like I was printing.

I pressed the main button and suddenly started printing normally. I'm using the last marlin bugfix (#19765 0a0f211)

My Marlin2 files [link](https://gofile.io/d/2U2R8u)

It is my first issue that I post here in Github so take it easy and sorry if I did something wrong 

Update 1 → I noticed a "click" sound that happens sometimes (the same sound when u click the button). And, apparently, it is auto-clicking because I left it on the "info screen" and after the 'auto-click', so I came nearby, It was on the "options screen".It happens a lot now

Update 2 → My extruder started steep-skipping (Extruder) due to low torque. I checked the Vrefs and was all Ok.  I made a downgrade to "[Ender-3_4.2.2_Firmware_ Marlin2.0.1 - V1.0.1.bin](https://drive.google.com/drive/folders/1sQ9TnIfssNy42rfK-DcJtLlkd30sUy6V)" by the official Creality website. It increased the Extruder torque a little, but not enough to work properly
Obs.: Keeps "auto-clicking" 

Update 3 → I asked the seller for their .bin file for the printer and it stopped all problems (auto click and freezing). If needed I upload it here later.
Obs.: Stopped "auto-clicking" ande Freezing but still Estep skipping.

**Comment by BuzzDaClown** [comment]
Following

**Comment by ghost** [comment]
I noticed a "click" sound that happens sometimes (the same sound when u click the button). And, apparently, it is auto-clicking because I left it on the "info screen" and after the 'auto-click', so I came nearby, It was on the "option screen".

#Edit: The "auto-click" happens mostly at 35 minutes

**Comment by Nu-hin** [comment]
@kiritokunsama

The "click" sound problem also happened to me, and, according to Reddit to numerous users of Ender 3, Ender 3 Pro and Ender 5 with stock mainboards and with custom ones. 

As suggested [here](https://www.reddit.com/r/ender3/comments/ejgv3x/ender_3_ender_5_pushing_button_by_itself_while/), this can be connected to an electric leakage.

In my case I could radically solve it by detaching my complete LCD module from the printer base, so that metal parts (LCD case and printer base) don't touch.

**Comment by Nu-hin** [comment]
Exactly the same problem with pausing prints started happening to me since yesterday, when I upgraded my Ender 3 Pro (4.2.2 board) from stock firmware to 6375829448eebe01b2835689aac69b73b63ebfd8.

It pauses on longer prints, randomly, sometimes 5 minutes between pauses.

Hotend and bed stay heated, and the nozzle stays in the plastic, making an ugly blob.

When I press the knob, the print instantly resumes.

I also noticed that a screen during these pauses shows a couple of weird characters, where printed filename used to be. After pushing the knob, the filename is displayed again.

I am printing from SD card, and I have checked the Gcode for anything suspicious - could not find anything.

**Comment by ghost** [comment]
Exactly, I think there is another problem, but I'm still working on it.

**Comment by Nu-hin** [comment]
@kiritokunsama Do you print from SD card? Have you tried replacing it? I had exactly the same symptoms as you described, then I replaced the poor SD card which came with the printer with a more expensive Samsung one. Since then I have completed five 7-8 hour prints and never run into this issue again.

**Comment by sjasonsmith** [comment]
I'm labeling this with Safety and LCD labels, since it seems it is waiting for a user-interaction through the LCD button?

I thought I was reading about a completely hung printer, but that seems not to be true if it resumes eventually.

**Comment by ghost** [comment]
> @kiritokunsama Do you print from SD card? Have you tried replacing it? I had exactly the same symptoms as you described, then I replaced the poor SD card which came with the printer with a more expensive Samsung one. Since then I have completed five 7-8 hour prints and never run into this issue again.

I've tried other SD cards but still the same here.

**Comment by ghost** [comment]
> I'm labeling this with Safety and LCD labels, since it seems it is waiting for a user-interaction through the LCD button?
> 
> I thought I was reading about a completely hung printer, but that seems not to be true if it resumes eventually.

Actually, it freezes completely the printer (the motion).

**Comment by Nu-hin** [comment]
@kiritokunsama I think what's important is that it reacts to the main button, as you wrote:

> I pressed the main button and suddenly started printing normally.

For me it was the same.

**Comment by ghost** [comment]
> @kiritokunsama I think what's important is that it reacts to the main button, as you wrote:
> 
> > I pressed the main button and suddenly started printing normally.
> 
> For me it was the same.

I agree, and the "auto-click" acts like someone pressed the main button.

**Comment by ghost** [comment]
Updated the post.

**Comment by ghost** [comment]
Freezing SOLVED. Just Updated again to the newer version

**Comment by rhapsodyv** [comment]
I'm closing this, as the user said the it's fixed when updating new newer version.
