### ISSUE TITLE
[BUG] printer halted when trying to move any axis

### ISSUE THREAD

**Issue by brayden1658** [MarlinFirmware/Marlin#20039]
every
[marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5497976/marlin.zip)

 time I try to home or move it just says printer halted. I have an SKR pro 1.1 board with tmc2130. have tried multiple configurations and versions but nothing had working on older marlin 2.0 but lost files. and thought I would upgrade. I have included my files.

**Comment by sjasonsmith** [comment]
This issue is being closed because it is incomplete. When reporting an issue, please be sure to follow all instructions at the top of the template, including debugging steps, and leave the sections headings intact.

For reference, these are the instructions included in the template:

### Before Reporting a Bug

1. Test with the `bugfix-2.0.x` branch to see whether the issue still exists.

2. Get troubleshooting help from the Marlin community to confirm it's a bug and not just a configuration error. Links at https://github.com/MarlinFirmware/Marlin/issues/new/choose

### Instructions

1. Fill out every section of the template below.

2. Always attach configuration files, regardless of whether you think they are involved.

3. Read and understand Marlin's Code of Conduct. By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/MarlinFirmware/Marlin/blob/master/.github/code_of_conduct.md
