### ISSUE TITLE
[BUG] EEPROM size error & I2C port setting

### ISSUE THREAD

**Issue by EYHJ59** [MarlinFirmware/Marlin#20124]
**Bug Description**

1. EEPROM size error

If I use external eeprom(not flash eeprom emulation), eeprom size error is occurred.
Because of size error, default values are loaded when rebooting.
i.e settings.reset() is called when reboot.

I think two points have bugs.

1) for loop in settings.cpp line 1570
             // MBL is disabled - skip the stored data
            for (uint16_t q = mesh_num_x * mesh_num_y; q--;) EEPROM_READ(dummyf);

            this for loop is changed to
            for (uint16_t q = GRID_MAX_POINTS_X * GRID_MAX_POINTS_Y; q--;) EEPROM_READ(dummyf);

2) for loop in settings.cpp line 1619
            // Skip past disabled (or stale) Bilinear Grid data
            xy_pos_t bgs, bs;
            EEPROM_READ(bgs);
            EEPROM_READ(bs);
            for (uint16_t q = grid_max_x * grid_max_y; q--;) EEPROM_READ(dummyf);

            this for loop is changed to
            for (uint16_t q = GRID_MAX_POINTS_X * GRID_MAX_POINTS_Y; q--;) EEPROM_READ(dummyf);

2. I2C port setting
In MarlinCore.cpp, void setup() has no port init for I2C.
Before SETUP_RUN(settings.first_load()), I2C port setting must be added.
(ex. 
 #if ENABLED(I2C_EEPROM)
  digitalPinHasI2C(PIN_WIRE_SDA);
  digitalPinHasI2C(PIN_WIRE_SCL);
 #endif
)

Expected Behavior
           After change for loop, eeprom size error is not occurred.
           And after add I2C port setting, external eeprom is working good.

**Comment by sjasonsmith** [comment]
This issue is being closed because it is incomplete. When reporting an issue, please be sure to follow all instructions at the top of the template, including debugging steps, and leave the sections headings intact.

For reference, these are the instructions included in the template:

### Before Reporting a Bug

1. Test with the `bugfix-2.0.x` branch to see whether the issue still exists.

2. Get troubleshooting help from the Marlin community to confirm it's a bug and not just a configuration error. Links at https://github.com/MarlinFirmware/Marlin/issues/new/choose

### Instructions

1. Fill out every section of the template below.

2. Always attach configuration files, regardless of whether you think they are involved.

3. Read and understand Marlin's Code of Conduct. By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/MarlinFirmware/Marlin/blob/master/.github/code_of_conduct.md
