### ISSUE TITLE
Z-Axis set DIR and check_endstops

### ISSUE THREAD

**Issue by tonnico** [MarlinFirmware/Marlin#2022]
What is the reason for check_endstops is in TEST Z-Axis? Not like X and Y?
https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/stepper.cpp#L539

**Comment by thinkyhead** [comment]
The flag `check_endstops` is also examined before checking X and Y endstops.

But really, I think there should be a single `inline void update_xyz_endstops()` function and then that flag should only be checked once, instead of once for XY and then again for Z – although I'm sure the compiler consolidates those two checks into one test-and-branch, since `check_endstops` isn't marked as `volatile`.
