### ISSUE TITLE
[BUG] Microstepping does not work at all

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#20408]
1. Flash with FW
1b. optional Init/Save
2. Start a print
3. microstepping does not work

**Expected behavior:**

Expected it to step as needed to adjust Z offset and make the hot-end lower or father than expected

**Actual behavior:**
No movement even if offset if changed and saved until print is stopped and restarted

**Comment by thisiskeithb** [comment]
This issue is being closed because it is incomplete. When reporting an issue, please be sure to follow all instructions at the top of the template, including debugging steps, and leave the sections headings intact.

**This includes attaching your configuration files, regardless of whether you think they are involved.**

For reference, these are the instructions included in the template:

### Before Reporting a Bug

1. Test with the `bugfix-2.0.x` branch to see whether the issue still exists.

2. Get troubleshooting help from the Marlin community to confirm it's a bug and not just a configuration error. Links at https://github.com/MarlinFirmware/Marlin/issues/new/choose

### Instructions

1. Fill out every section of the template below.

2. Always attach configuration files, regardless of whether you think they are involved.

3. Read and understand Marlin's Code of Conduct. By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/MarlinFirmware/Marlin/blob/master/.github/code_of_conduct.md
