### ISSUE TITLE
cold mesh -> fine tune = head will dip down below the bed and crash into it

### ISSUE THREAD

**Issue by SquirrelAssassin** [MarlinFirmware/Marlin#20723]
Every time I do a cold mesh on the marlin screen, I start with a cold mesh -> then fill in the gaps -> then do a fine tune.  The fine tune every time will raise up then lower down below the bed causing the head to crash into the build plate, then raise up just to get back to where it should be.  It should just raise up a bit .... move to the next point .... then lower back down to just the place it should be for the next spot.   How do we stop big dip downward that is not needed?

So far the only way I found is to raise the Z end stop just to the right position where I can still fine tune it in the negative.  And this only works because the Z end stop lever is long enough to give some play room.

**Comment by sjasonsmith** [comment]
Is this a delta? If so, there were some recent changes in bugfix-2.0.x to resolve an issue like this.

This issue is being closed because it is incomplete. When reporting an issue, please be sure to follow all instructions at the top of the template, including debugging steps, and leave the sections headings intact.

For reference, these are the instructions included in the template:

### Before Reporting a Bug

1. Test with the `bugfix-2.0.x` branch to see whether the issue still exists.

2. Get troubleshooting help from the Marlin community to confirm it's a bug and not just a configuration error. Links at https://github.com/MarlinFirmware/Marlin/issues/new/choose

### Instructions

1. Fill out every section of the template below.

2. Always attach configuration files, regardless of whether you think they are involved.

3. Read and understand Marlin's Code of Conduct. By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/MarlinFirmware/Marlin/blob/master/.github/code_of_conduct.md
