### ISSUE TITLE
[Bug] Anycubic Predator - Temperature presets collide on filament reload after runout during print

### ISSUE THREAD

**Issue by GunnardVS** [MarlinFirmware/Marlin#20782]
When filament runs out during printing, the reload routine automatically lets the extruder unload the remaining filament (I assume this to be expected behavour, just wanted to mention it for compete coverage).
On loading the new filament, heating seems to be confused between presets.
The preset for preheating for PLA is set to 185°C.
The print temperature was set to 195°C.
The actual heating for filament exchange during the print platoed at 185°C, while Marlin was waiting for the temperature to reach 195°C.
It failed with a "heating failure" error, demanding a reset of the printer - the print progress got lost.

**Comment by sjasonsmith** [comment]
This issue is being closed because it is incomplete. When reporting an issue, please be sure to follow all instructions at the top of the template, including debugging steps, and leave the sections headings intact.

For reference, these are the instructions included in the template:

### Before Reporting a Bug

1. Test with the `bugfix-2.0.x` branch to see whether the issue still exists.

2. Get troubleshooting help from the Marlin community to confirm it's a bug and not just a configuration error. Links at https://github.com/MarlinFirmware/Marlin/issues/new/choose

### Instructions

1. Fill out every section of the template below.

2. Always attach configuration files, regardless of whether you think they are involved.

3. Read and understand Marlin's Code of Conduct. By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/MarlinFirmware/Marlin/blob/master/.github/code_of_conduct.md
