### ISSUE TITLE
MBL on I3 Mega, Special menu showing ABL

### ISSUE THREAD

**Issue by ntangle** [MarlinFirmware/Marlin#21140]
Compiling current release of marlin, and using the example configuration.h for the i3 Mega. Enabled the TMC2208 but not BLTouch. Reading through the config, it should enable Manual Mesh Levelling. However when compiled and loaded onto the machine, there are no Manual Mesh levelling options in the Special Menu. It just shows Auto Bed Levelling option with no hot end Z movements that can be controlled by the LCD.

It should pick it up from the Marlin/src/lcd/extui/lib/anycubic_i3mega. I tried to 'cut' out the other special menu but when I then skip from first to second point the machine makes a grinding noise and does not move. 
I am inserting the mesh points using a saved M503 and taking the G29's
[anycubic_i3mega_lcd.cpp.txt](https://github.com/MarlinFirmware/Marlin/files/6015087/anycubic_i3mega_lcd.cpp.txt)

**Comment by Baton34** [comment]
Its because PROBE_MANUALLY disabled if enabled MESH_BED_LEVELING:
https://github.com/MarlinFirmware/Marlin/blob/b8cf818dac851f6d57de49f6f45cdfe2da884a00/Marlin/src/inc/Conditionals_LCD.h#L791-L793
And if PROBE_MANUALLY disabled Mesh leveling options are disabled in Special menu:
https://github.com/MarlinFirmware/Marlin/blob/c0673dbdf14eb7cd74bfdc0417cc8290b98fc00a/Marlin/src/lcd/extui/lib/anycubic_i3mega/anycubic_i3mega_lcd.cpp#L247
You can replace `#if ENABLED(PROBE_MANUALLY)` by `#if ENABLED(MESH_BED_LEVELING)` and options will appear.
