### ISSUE TITLE
[BUG] (Marlin Adds 5mm extra to the Position after homing and then reduze to nozzle Z Offset

### ISSUE THREAD

**Issue by Liriel-666** [MarlinFirmware/Marlin#21584]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

After homing the Noozle Drive 10 mm High like i set but the Firmware Add 5mm more without any reasen and then drive down the Nozzle  Z offset.
that means it set z 0 throughthe BL touch then drive up 10mm like i set then extra 5mm and then the down which is the offset between BLtouch 0 and nozzle.
Then the Display show Z 10 and when i drive down to z0 it hangs in the air and have 5 mm more to drive down

I dont Find any clue where this extra 5mm are from!

Marlin 2.0x Bugfix from 10.4.2021 on a MKS Robin Nano V3 (rev 3) with bltouch.
tried TFT_COLOR_UI and TFT_LVGL_UI and on github build from 4.4, 8.4 and 10.4

On the Older Github of the MKS Firmware it doesnt happens.

Configuration Files:
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/6290932/Marlin.zip)

Video of the Problem
https://youtu.be/E4oiSbcdM9E

### Bug Timeline

on my github downloads from 4.4, 8.4 and 10.4

### Expected behavior

After homing the Noozle Drive 10 mm High like i set but the Firmware Add 5mm more without any reasen and then drive down the Nozzle  Z offset.
that means it set z 0 throughthe BL touch then drive up 10mm like i set then extra 5mm and then the down which is the offset between BLtouch 0 and nozzle.
Then the Display show Z 10 and when i drive down to z0 and it should put the nozzle on the Surface.
That would be normal

### Version of Marlin Firmware

bugfix 2.0.X

### Printer model

Anet A8

### Electronics

MKS Robin Nano V3

### Add-ons

3d Touch (bltouch clone)

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by thinkyhead** [comment]
Whenever there are homing or leveling issues, we now ask everyone to follow a standard procedure to gather more information so that we're not just taking stabs in the dark. Here is the boilerplate:

- Download Marlin `bugfix-2.0.x` to test with the latest code.
- Enable `DEBUG_LEVELING_FEATURE` and `M114_DETAIL` and re-flash the firmware.
- Connect to your printer from host software such as Cura, Printrun or Repetier Host.
- Send `M502` and `M500` to ensure your Configurations are applied.
- Issue the command `M111 S247` to enable maximum logging.
- Perform a `G28` to do your standard homing procedure.
- Do any moves needed to reveal problems. Take notes.
- Copy the log output into a **.TXT file** and attach it to your next reply.

Repeat this procedure, if needed, to demonstrate inconsistencies. From these logs we should hopefully get a better idea of what's going on with your machine.
