### ISSUE TITLE
[BUG] Bed Leveling Z-axis of evil

### ISSUE THREAD

**Issue by Arogen** [MarlinFirmware/Marlin#21637]
I've been finding a lot of inconstancy with the Z-axis in trying to set my BLTouch.  For example I use babysteps to find a value for the probe offset Z value that works, and right away trying to use it again on the same gcode it is printing up in the air again.  

[Marlin_bug.zip](https://github.com/MarlinFirmware/Configurations/files/5999580/Marlin_bug.zip)

### Steps to Reproduce
Here is a specific reproducible example of what I think is behind all this:

Set the Probe Z offset set to 0
Turn off Bed Leveling
Home the Z axis
screen says Z is at 0.00
Raise the Z axis 2.00 mm
screen says Z is at 2.00
Turn on Bed Leveling
screen says Z is at 1.24mm (assume this is from applying the mesh)
Turn off Bed Leveling
screen says Z is at 2.07mm

As a shortcut, you can just turn Bed Leveling on then off and see the Z is now 2.07

**Expected behavior:**

When the Bed Leveling is turned off again, the Z height would register as 2.00 like it was before it was turned on.

**Actual behavior:**
After the Bed Leveling is turned on and off again, the Z height changes from 2.00 to 2.07 even though nothing was done to cause Z movement..

#### Additional Information
Hardware:  Ender 3 Pro, SKR Mini v2, TFT 35
Firmware: Marlin bugfix stream downloaded and set up today.
Config files and a video uploaded.

**Comment by thinkyhead** [comment]
Whenever there are homing or leveling issues, we now ask everyone to follow a standard procedure to gather more information so that we're not just taking stabs in the dark. Here is the boilerplate:

- Download Marlin `bugfix-2.0.x` to test with the latest code.
- Enable `DEBUG_LEVELING_FEATURE` and `M114_DETAIL` and re-flash the firmware.
- Connect to your printer from host software such as Cura, Printrun or Repetier Host.
- Send `M502` and `M500` to ensure your Configurations are applied.
- Issue the command `M111 S247` to enable maximum logging.
- Perform a `G28` to do your standard homing procedure.
- Do a `G29` to probe the bed. This will also enable bed leveling.
- Do any other moves needed to reveal problems. Take notes.
- Copy the log output into a **.TXT file** and attach it to your next reply.

Repeat this procedure, if needed, to demonstrate inconsistencies. From these logs we should hopefully get a better idea of what's going on with your machine.
