### ISSUE TITLE
[BUG] BLTOUCH doesn't deploy and Error:Probing Failed/endstops hit:  Z:"value"

### ISSUE THREAD

**Issue by ThePsyk8** [MarlinFirmware/Marlin#21896]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

At the first start I set z-offset, after I do autohome from Pronterface or from printer and it works. M48 also works.
The problem is when I want to do the automatic bed levelling, the bltouch doesn't deploy at first probe and I receive an error: Error:Probing Failed. Otherwise BLTOUCH makes some probes and at a certain point it stop working and I receive an error:
STOPPED or endstops hit:  Z:"value".
If I start a print from SD or slicer, it starts but when the BLTOUCH gives the error, the print continues without compensating.

https://user-images.githubusercontent.com/65788763/118170632-9cf72200-b42a-11eb-8662-52a99a59122f.mp4

### Bug Timeline

From Marlin 2.0.7.2

### Steps to Reproduce

- Power on printer;
- Home all axis;
- Set z-offset;
- Once all axis are homed, send a G29 command from Pronterface/printer;

### Version of Marlin Firmware

Marlin-bugfix-2.0.x

### Printer model

Alfawise U30 (motherboard: V08)

### Electronics

STM32F103VE_longer (V08)

### Add-ons

BLTOUCH

### Your Slicer

IdeaMaker

### Host Software

Pronterface

### Additional information & file uploads
[M111 S247.txt](https://github.com/MarlinFirmware/Marlin/files/6476682/M111.S247.txt)

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6474403/Configuration.zip)

**Comment by ellensp** [comment]
Whenever there are homing or leveling issues, we now ask everyone to follow a standard procedure to gather more information so that we're not just taking stabs in the dark. Here is the boilerplate:

- Download Marlin `bugfix-2.0.x` to test with the latest code.
- Enable `DEBUG_LEVELING_FEATURE` and `M114_DETAIL` and re-flash the firmware.
- Connect to your printer from host software such as Cura, Printrun or Repetier Host.
- Send `M502` and `M500` to ensure your Configurations are applied.
- Issue the command `M111 S247` to enable maximum logging.
- Perform a `G28` to do your standard homing procedure.
- Do a `G29` to probe the bed. This will also enable bed leveling.
- Do some of the moves that revealed problems before. Take notes.
- Copy the log output into a **.TXT file** and attach it to your next reply.

Repeat this procedure, if needed, to demonstrate inconsistencies. From these logs we should hopefully get a better idea of what's going on with your machine.

**Comment by ThePsyk8** [comment]
[M111 S247.txt](https://github.com/MarlinFirmware/Marlin/files/6476684/M111.S247.txt)

Thanks

**Comment by ThePsyk8** [comment]
Hello,
Is there a solution?
Thanks
