### ISSUE TITLE
[BUG] expected primary-expression before '(' token in types.h

### ISSUE THREAD

**Issue by johnco1126** [MarlinFirmware/Marlin#22037]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Compile fails due to "expected primary-expression before '(' token [92,36]" error in types.h
Trying to compile in VSCode, but keep getting this error. Tried 2.0.8.2 and bugfix-2.0.x.

### Bug Timeline

New

### Expected behavior

Expected to compile without failing

### Actual behavior

Compile fails

### Steps to Reproduce

Attempt to compile in vscode
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/6594910/Marlin.zip)

### Version of Marlin Firmware

2.0.8.2 or 2.0.debug

### Printer model

FLSUN SuperRacer

### Electronics

Stock BOARD_BTT_SKR_V1_3

### Add-ons

Pt1000

**Comment by thisiskeithb** [comment]
This is a configuration issue. I'd recommend pulling down a fresh copy and porting your settings over since you seem to have a mix of settings from older & newer versions of Marlin.

The main issue is that you're trying to use `HOMING_FEEDRATE_MM_M` as `Z_PROBE_FEEDRATE_FAST`, which won't work since it's an array.

Use something like this instead:

```cpp
#define Z_PROBE_FEEDRATE_FAST (4*60)
```

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
