### ISSUE TITLE
[BUG] G12 misses documentation for XYZ

### ISSUE THREAD

**Issue by dwery** [MarlinFirmware/Marlin#22103]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

G12's documentation doesn't explain what the code is doing with XYZ params
```
/**
 * G12: Clean the nozzle
 *
 *  E<bool>          : 0=Never or 1=Always apply the "software endstop" limits
 *  P0 S<strokes>    : Stroke cleaning with S strokes
 *  P1 Sn T<objects> : Zigzag cleaning with S repeats and T zigzags
 *  P2 Sn R<radius>  : Circle cleaning with S repeats and R radius
 */

```
```
  const bool seenxyz = parser.seen("XYZ");
  const uint8_t cleans =  (!seenxyz || parser.boolval('X') ? _BV(X_AXIS) : 0)
                        | (!seenxyz || parser.boolval('Y') ? _BV(Y_AXIS) : 0)
                        | TERN(NOZZLE_CLEAN_NO_Z, 0, (!seenxyz || parser.boolval('Z') ? _BV(Z_AXIS) : 0))
                      ;

```

### Version of Marlin Firmware

n/a

**Comment by slowbro** [comment]
<snip>

However, it looks like otherwise it is specifying to stay at the current location for each param XYZ.. i.e. X = stay at the current X instead of moving to the usual `NOZZLE_CLEAN_START_POINT` X, etc.

Edit; no, I was wrong. It looks like it's the opposite of that.

By default, it looks like the command treats X and Y as a `true` boolean value, i.e. it will move those axes to get to the cleaning spot. If you specify `X0` or `Y0` it will not move those axes and instead just do the cleaning in place for that axis. For `P2`, a circle, it needs to move X/Y to get to the start of the circle, which is dependent on the middle for calculating the moves around the radius; not moving would make the moves not behave as expected. If you were to do a `G12 P2 X0 Y0` it would throw an error.

For `Z`, same thing kind of, but it's affected by NOZZLE_CLEAN_NO_Z, too.

**Comment by thinkyhead** [comment]
Added:
```
 *  X, Y, Z          : Specify axes to move during cleaning. Default: ALL.
```
