### ISSUE TITLE
[BUG] SKR 2 Marlin 2.0.9.1 Serial 1 Undefined Issue

### ISSUE THREAD

**Issue by rennwaffen** [MarlinFirmware/Marlin#22636]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

The compilation almost completes until it gives me the following error: 

`Compiling .pio\build\BIGTREE_SKR_2\src\src\sd\cardreader.cpp.o
Linking .pio\build\BIGTREE_SKR_2\firmware.elf
c:/users/suren/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: .pio/build/BIGTREE_SKR_2/src/src/module/stepper/trinamic.cpp.o: in function `HardwareSerial::begin(unsigned long)':
C:\Users\suren\.platformio\packages\framework-arduinoststm32\cores\arduino/HardwareSerial.h:120: undefined reference to 
`Serial1'
c:/users/suren/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: .pio/build/BIGTREE_SKR_2/src/src/module/stepper/trinamic.cpp.o: in function `_GLOBAL__sub_I_stepperX':    
C:\Users\suren\Downloads\RW Factory Mk. V/Marlin\src\module\stepper/trinamic.cpp:999: undefined reference to `Serial1'  
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\BIGTREE_SKR_2\firmware.elf] Error 1`

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/7049141/Configuration.zip)

I haven't been able to compile successfully once. I watched the SKR 2 basics video, but to no avail. Please advise. 

### Bug Timeline

Started on the first compile

### Expected behavior

Successful compilation followed by installation of the new firmware on the printer. 

### Actual behavior

Failure to compile.

### Steps to Reproduce

1. Load Configuration.h and Configuation_adv.h
2. Set environment in platformio to BIGTREE_SKR_2
3. Compile

### Version of Marlin Firmware

2.0.9.1 (Latest)

### Printer model

RW Factory (Basically a CoreXY Ender 5)

### Electronics

SKR 2 w/ TMC 2209 drivers. 

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Additional information & file uploads

I can't even load it onto the printer for more info.

**Comment by rennwaffen** [comment]
Kind of resolved? The issue was in the BTT SKR 2.0 pins file which I copied into the bugfix version. I then tried using the raw file from the bugfix version and it worked. The issue was that the X, Y, Z, Z2, and E0 serial hardware code was uncommented, so I commented them out. I'm not sure what effect that will have, however. It's possible I uncommented them myself and completely forgot about it.

  //#define X_HARDWARE_SERIAL  Serial1
  //#define X2_HARDWARE_SERIAL Serial1
  //#define Y_HARDWARE_SERIAL  Serial1
  //#define Y2_HARDWARE_SERIAL Serial1
  //#define Z_HARDWARE_SERIAL  Serial1
  //#define Z2_HARDWARE_SERIAL Serial1
  //#define E0_HARDWARE_SERIAL Serial1
  //#define E1_HARDWARE_SERIAL Serial1
  //#define E2_HARDWARE_SERIAL Serial1
  //#define E3_HARDWARE_SERIAL Serial1
  //#define E4_HARDWARE_SERIAL Serial1

**Comment by thisiskeithb** [comment]
<details><summary>Because you're trying to manually set slave addresses in your config:</summary>

![image](https://user-images.githubusercontent.com/13375512/130854681-8ff79e71-ddfe-45f4-afe0-4b34354693b5.png)

</details>

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by rennwaffen** [comment]
> This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

I was getting errors when not manually setting slave addresses.
