### ISSUE TITLE
[BUG] SD printing stops when click Printing menu

### ISSUE THREAD

**Issue by a0s** [MarlinFirmware/Marlin#22786]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

Printing from SD hangs if press on "Printing" menu at printer's screen.

### Expected behavior

Printer shouldn't stop printing

### Actual behavior

Printing stops

### Steps to Reproduce

0. Upload big file to SD over Octoprint.
1. Open Octoprint and start printing from SD.
2. Disconnect Octoprint
3. Click on Printing menu at printer's screen.

### Version of Marlin Firmware

67d82ff228789408f7f32e6c9af3108c989c0c90 at bugfix-2.0.x

### Printer model

Sapphire Plus

### Electronics

mks nano 1.2

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by thisiskeithb** [comment]
Which UI are you using? Please attach your config.

**Comment by a0s** [comment]
@teemuatlut  I am using TFT_LVGL_UI
My config [config.tar.gz](https://github.com/MarlinFirmware/Marlin/files/7184833/config.tar.gz)

**Comment by sk8board** [comment]
I have the same printer, same board, but use TFT_COLOR_UI without OctoPrint. The problem I am having is once the printer starts printing, I can press on menu but the UI does not respond. 

Therefore, the menu to pause the print does show so I cannot pause the print.

I have used the latest bugfix (Dec-30-2021) without any difference to the problem.

**Comment by sk8board** [comment]
I found the cause of the problem is I did not set my screen settings in the config before compiling the firmware.

When I start printing, the M502 code will restore default config settings, which would erase the learned screen settings when learned from screen calibration, then the screen would not know how to respond to touch because the firmware did not have default screen settings.

Make sure your config has values for your screen X and Y positions. Example:

`#define TOUCH_CALIBRATION_X -17045
  #define TOUCH_CALIBRATION_Y 11689
  #define TOUCH_OFFSET_X        507
  #define TOUCH_OFFSET_Y        -17`
