### ISSUE TITLE
[BUG] BABYSTEP_ZPROBE_GFX_OVERLAY layout fail with DWIN_MARLINUI_LANDSCAPE

### ISSUE THREAD

**Issue by aalku** [MarlinFirmware/Marlin#22969]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

BABYSTEP_ZPROBE_GFX_OVERLAY layout fails with DWIN_MARLINUI_LANDSCAPE
![image](https://user-images.githubusercontent.com/12587056/137601592-9c5b8f6e-d932-46fd-ad20-1b2559696bc3.png)

### Bug Timeline

I think DWIN_MARLINUI_LANDSCAPE is a new feature so bug is new.

### Expected behavior

The icons should be better placed arround the screen.

### Actual behavior

The icons are overlapping with the text and the "progress bar" or whatever that rectangle is.

### Steps to Reproduce

1. Enable DWIN_MARLINUI_LANDSCAPE.
2. Enable BABYSTEP_ZPROBE_GFX_OVERLAY.
3. Build and install on an Ender 3 v2 or other printer with same screen (Icons updated on screen flash).
4. Enter menu "Configuration" -> "Probe Z Offset".

### Version of Marlin Firmware

Marlin bugfix-2.0.x (Oct 16 2021 22:47:50)

### Printer model

Ender 2 v2

### Electronics

Stock electronics, rotated screen.

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/12587056/137601890-a6c56e87-ff47-4a9f-90f4-99715b1460df.png)

**Comment by ellensp** [comment]
DWIN_MARLINUI_PORTRAIT mode isn't much better
![portrait](https://user-images.githubusercontent.com/530024/138040429-704c06d1-52d5-4905-861a-c0d1d7fb43d6.png)
Text to large, icons obscuring both ends of the number

**Comment by ellensp** [comment]
been talking a look at this in landscape mode
the lines in question that draw the icons are
```
DWIN_ICON_Show(ICON, ICON_UpArrow, LCD_PIXEL_WIDTH - 10 - (48*2), arrow_y - dir);
      DWIN_ICON_Show(ICON, rot_up, LCD_PIXEL_WIDTH - 10 - 48, arrow_y);

```
in Marlin/src/lcd/e3v2/marlinui/ui_common.cpp
the ICON_UpArrow is missing and nether seems to not be respecting their X position 
just as a test I switched it up a little
```
WIN_ICON_Show(ICON, rot_up, 480 - 48, 48 + arrow_y);
      DWIN_ICON_Show(ICON, ICON_UpArrow, 480 - (48*2), arrow_y - dir);
```
now rot_up and ICON_UpArrow show, but both are in the same (incorrect ) X position but on top of each other as was desired for the test
it is ignoring the X parameter. 480 - 48 and 480 - (48*2)

so this issue is elsewhere

**Comment by aalku** [comment]
Looking at the photos we posted it seems like there is a limit based on portrait mode width.

**Comment by ellensp** [comment]
I added some debugging to Marlin/src/lcd/e3v2/common/dwin_api.cpp
void DWIN_ICON_Show(bool IBD, bool BIR, bool BFI, uint8_t libID, uint8_t picID, uint16_t x, uint16_t y) {
```
  SERIAL_ECHOLNPAIR_F("raw x: ", (double)x);
  SERIAL_ECHOLNPAIR_F("raw y: ", (double)y);
  NOMORE(x, DWIN_WIDTH - 1);
  NOMORE(y, DWIN_HEIGHT - 1); // -- ozy -- srl
  SERIAL_ECHOLNPAIR_F("nomore x: ", (double)x);
  SERIAL_ECHOLNPAIR_F("nomore y: ", (double)y);
```

So it print out the raw X and Y as it was received by the function, and then again after it has passed through the NOMORE macro

The result is 

> raw x: 384.00
> raw y: 162.00
> nomore x: 271.00
> nomore y: 162.00

This is where the X is being truncated

The issue is that DWIN_WIDTH and DWIN_HEIGHT are swapped here.

still looking for the root cause

**Comment by ellensp** [comment]
This fixes it.  On a second review I think this will be fine.

```DIFF
diff --git a/Marlin/src/lcd/e3v2/common/dwin_api.cpp b/Marlin/src/lcd/e3v2/common/dwin_api.cpp
index d89b22a7aa..68b033bc67 100644
--- a/Marlin/src/lcd/e3v2/common/dwin_api.cpp
+++ b/Marlin/src/lcd/e3v2/common/dwin_api.cpp
@@ -23,6 +23,11 @@
 
 #if EITHER(HAS_DWIN_E3V2, IS_DWIN_MARLINUI)
 
+#if ENABLED(DWIN_MARLINUI_LANDSCAPE)
+  #define DWIN_WIDTH  480
+  #define DWIN_HEIGHT 272
+#endif
+
 #include "dwin_api.h"
 #include "dwin_set.h"
```

**Comment by ellensp** [comment]
But give this a try, see if anything else breaks. I have to call it for now.

**Comment by ellensp** [comment]
If you cant read DIFF file that it simply says 

edit Marlin/src/lcd/e3v2/common/dwin_api.cpp

above the line #include "dwin_api.h" incert the following
```CPP
#if ENABLED(DWIN_MARLINUI_LANDSCAPE)
  #define DWIN_WIDTH  480
  #define DWIN_HEIGHT 272
#endif

```

**Comment by aalku** [comment]
I can read diff :) I don't think I can try it today. Thank you for your help!

**Comment by aalku** [comment]
UI still needs refinement but it's not that bad anymore. Thank you!
![image](https://user-images.githubusercontent.com/12587056/138531793-faddf5d5-da3e-4d0f-be79-72d2e7457563.png)
