### ISSUE TITLE
[BUG] LCD is slow, and becomes unresponsive during print on BTT SKR e3 DIP

### ISSUE THREAD

**Issue by matthew-goulart** [MarlinFirmware/Marlin#23001]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

After updating the firmware to the latest commit on bugfix-2.0.x (occurs on master as well) (as of Oct 20th, 8PM EST 2021), the LCD attached to my BTT SKR Mini E3 DIP suffers from slow performance and even _stops_ working for short periods. When not printing, the LCD is very slow to respond to commands, sometimes requiring 3-4 seconds before an encoder rotation is registered. During printing, the LCD responds once every 10-15 seconds at best. This is probably the same issue as #19477. I do have a version of the bugfix-2.0.x branch from over 6 months ago that works just fine. I will try to find the exact commit number and report back.

### Bug Timeline

New issue, after flashing current bugfix-2.0.x branch

### Expected behavior

LCD works as it has in the past, with no discernable slow downs.

### Actual behavior

The LCD is very slow when not printing, and unusable when printing.

### Steps to Reproduce

1. Flash the latest bugfix-2.0.x (or master) branch on an SKR MINI E3 DIP board, using the `STM32F103RC_btt_USB` env and `#define CR10_STOCKDISPLAY`
2. Attempt to use the LCD

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

Ender 3

### Electronics

SKR MINI E3 DIP, stock LCD

### Add-ons

4 x TMC2208 in UART

### Bed Leveling

No Bed Leveling

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

**Comment by thinkyhead** [comment]
Note that the display automatically throttles to prevent stuttering when the planner might be in danger of starvation. If you are printing very detailed G-code with a lot of small segments the throttling will be more pronounced. If the display is unresponsive but printing is not stuttering, that is one possible scenario.

Anyway, since you were able to locate some older version that worked better, maybe you can find the most recent version that works well for you and then we can compare the older version to the current one and see whether there are any obvious changes to the motion handling or the screen throttling that could be contributing to this new problem.

**Comment by matthew798** [comment]
I found that the cause of this issue is the usb mass storage feature of my board. When connect usb to my computer, and data is transferring in either direction, the lcd becomes unuseably unresponsive. Id consider this an acceptable limitation, so no issue for me anymore.
