### ISSUE TITLE
Z_PROBE vs. Z_MIN

### ISSUE THREAD

**Issue by tonnico** [MarlinFirmware/Marlin#2362]
Hi all,

i have no idea why we have a Z_PROBE_PIN and a Z_MIN_PIN. I guess this will make some confusion.

I run autobedleveling with my Z_MIN-Endstop. Anyone how can tell me the advantage of this?

**Comment by linchunguang** [comment]
Motor self-locking function

**Comment by tonnico** [comment]
Can you explain?

**Comment by Roxy-3D** [comment]
> i have no idea why we have a Z_PROBE_PIN and a Z_MIN_PIN. 

Some people home their Z to the Max position and also have a Z Probe.   There are advantages to this.  If you print things that fill the entire Z build envelope, you don't have to raise the nozzle prior to engaging the Z probe.  You have plenty of room.   If you just use the Z Probe to home, you have to give up what ever your Z probe raises prior to engagement in the Z direction.

**Comment by tonnico** [comment]
I understand to have a probe and a z max endstop. But not a probe and a z min endstop.

**Comment by Wackerbarth** [comment]
I think that the intention was to allow either a probe or a Z_MIN end-stop rather than having both at the same time.

The distinction has to do with how they are used in various places within the code.  For example, the end-stop would be available during operation, but the probe would not. The different names are used to control the (convoluted) code of how the sensor is used under various conditions.
