### ISSUE TITLE
Full Graphics LCD no longer displays Z position (dev Branch)

### ISSUE THREAD

**Issue by WheresWaldo** [MarlinFirmware/Marlin#2369]
I am not sure when this happened, it is working in 1.0.0 and 1.0.2. The Full Graphics LCD in 1.0.3 dev behaves in a way that does not display the Z height. As expected when starting up the display for X, Y and Z all show ----.-. When you issue a <b>G28</b> command to home all axis the display will show first the X axis of 000.0 when home, then the Y axis of 000.0 when home. Upon moving to the middle of the build plate to home the Z axis, the LCD correctly displays X and Y locations, after homing Z the LCD panel still displays ----.- for the Z location. Any subsequent command such as <b>G29</b> or any other command that requires moving along the Z axis completes as expected but the display still shows ----.- for Z height.

I am not sure if this is a consequence of fixes to <b>ABL</b> for <b>Z_OFFSET</b>.

Just tested with <b>Development</b> Branch and it behaves the same way.

**Comment by ntoff** [comment]
I'm pretty sure it's probably because they've now made it so that if the steppers are deactivated, it now shows ---.-- because the position is now somehow unknown due to it being able to jump to the next full step.

Try turning off the options to disable the steppers when not in use and reflash.

**Comment by AnHardt** [comment]
@ntoff 

~~~> I'm pretty sure it's probably because they've now made it so that if the steppers are deactivated~~~

~~~The opposite is the case.~~~
EDIT: Sorry overlooked the `if`.
Yes, we deactivate the display now for an axis, where we do not know the exact coordinates.
Yes, we do not now the exact position, when the steppers where switched off.
No, we did not change the default behavior for switching off the motors. By default they are NOT switched off.

```
#define DISABLE_X false
#define DISABLE_Y false
#define DISABLE_Z false

// @section extruder

#define DISABLE_E false
```

This change, to show --- when the motors were disabled, enabled us to find and fix a bug with `M84` (`DEFAULT_STEPPER_DEACTIVE_TIME`) where all steppers where shut down instead of respecting the `DISABLE_?` settings.

@WheresWaldo 
Please check your `DISABLE_?` settings.

**Comment by ntoff** [comment]
>The opposite is the case.

Opposite? You just repeated what I said, how's that opposite?

**Comment by AnHardt** [comment]
@ntoff 
The steppers are NOT deactivated! Furthermore they are not deactivated by error anymore.

**Comment by AnHardt** [comment]
@ntoff 
Sorry overlooked the 'if'.

**Comment by WheresWaldo** [comment]
I am going to comment and close, that is exactly what it was #define DISABLE_Z
