### ISSUE TITLE
[FR] MPC Tuning - Menu

### ISSUE THREAD

**Issue by ETE-Design** [MarlinFirmware/Marlin#23996]
Now that MPC Tuning is introduced, it would be great to have an Menu on LCD just like PID Tuning.
So if PID Temp is activated PID Tuning is in the Menu structure, and when MPC is activated MCP Tuning is in the menu structure instead.

**Comment by thisiskeithb** [comment]
See https://github.com/MarlinFirmware/Marlin/pull/23984

**Comment by ETE-Design** [comment]
@thisiskeithb But #23984 dosen't involve a LCD Menu like PID does? 
You have to send external command, or make a custom command, would it be better to have it under "Temperature" like PID is? Or am I missing something?

**Comment by GMagician** [comment]
@ETE-Design, please note that PID may be still present because of Bed or chamber

**Comment by tombrazier** [comment]
> would it be better to have it under "Temperature" like PID is?

That's where I would be inclined to put it. It's certainly where I would look for it as a user.

> PID may be still present because of Bed or chamber

So both PID and MPC will be in one menu but that seems okay to me. That menu already gets a whole block of options for every heater. It's mostly just a matter of the options being MPC ones rather than PID ones.

**Comment by tombrazier** [comment]
Just added this to #23984.
