### ISSUE TITLE
Floating equality test 

### ISSUE THREAD

**Issue by zeryabmoussaoui** [MarlinFirmware/Marlin#2403]
In Marlin_main.cpp, on the function prepare_move() , the following condition  : 

 if( (current_position[X_AXIS] == destination [X_AXIS]) && (current_position[Y_AXIS] == destination [Y_AXIS])) {

may be never verified because all values are represented in float.

References :  

http://www.cygnus-software.com/papers/comparingfloats/comparingfloats.htm
https://isocpp.org/wiki/faq/newbie#floating-point-arith
http://www.boost.org/doc/libs/1_36_0/libs/test/doc/html/utf/testing-tools/floating_point_comparison.html

**Comment by thinkyhead** [comment]
This function is often called after one or more assignments like `destination[i] = current_position[i]`. Otherwise these values tend to come from the parser, so any values parsed from G-Code will also match equivalent G-Code. But, if the values don't exactly match the planner may try to perform micro-moves, and it may see these moves as so small (less than a half micro-step) that it throws them away. It's not really a bug, per se, but it will affect the feedrate on moves without XY, so perhaps we should gather some statistics on how often this test fails when it should not.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
