### ISSUE TITLE
Delta auto-leveling issues on development 7/9

### ISSUE THREAD

**Issue by skhameneh** [MarlinFirmware/Marlin#2408]
Last night I configured development for my delta hoping to fix some auto-leveling issues with prior versions of Marlin.  Everything is looking promising and I like the latest code refactors in the dev branch, but I'm having an entire new set of issues.

1) G29 won't do anything unless I enable enable Z_PROBE_ALLEN_KEY, unfortunately my z_min is attached directly to the print head (no retractable probe).  G29 results in the print head coming close to the bed and "Error:Z-Probe failed to retract!".

2) G28 works flawlessly, much better than prior versions.  Running G29 without homing results in an error as expected.  Running G29 after G28 causes all axis to reverse before moving the probe down, causing the belts to grind.  Is this a config issue?

I appreciate any help and would be more than happy to do some code edits (and testing).

Thanks,

Shawn

**Comment by thinkyhead** [comment]
@skhameneh Sorry for your current `G29` troubles. It sounds like Marlin might not have the best support for non-servo and non-allen-key probes on Delta machines right now. Also, Z isn't _supposed_ to raise up in cases where Z is homed to a Z max endstop, but it might be trying to do that anyway due to `Z_RAISE_BEFORE_PROBING`, so you might try setting that to 0.

Meanwhile, I have a debug branch that I will be patching up with the latest code, and as soon as I have that ready you can grab it and give it a test run. All it does differently is print lots of position information to the serial console, but from that we should be able to see where it's getting confused.

I'll let you know when my debug branch is patched up – should be pretty soon!

**Comment by thinkyhead** [comment]
Ok, this can be used to get more debug output…
https://github.com/thinkyhead/Marlin/tree/debug_G29

**Comment by skhameneh** [comment]
Thanks, here's a nice long debug output.  I'll need to skim through it myself.

It appears the Z_RAISE_BEFORE_PROBING is causing the reversing issue like you said :+1: , I'll adjust that and see if it fixes it.

https://gist.github.com/skhameneh/39561f13d8d95079ba25

**Comment by skhameneh** [comment]
Why was this closed?  To my knowledge, it's not resolved.

**Comment by AnHardt** [comment]
Just a test if you are still around. ;-)

Thanks for the log. Sadly i can't find the error.
Is your sensor connected/configured as a Z_MIN_endstop or a Z_MIN_probe?
Is your printer doing the moves to deploy the allen_key?
What is the output of M119 in mid air.

A link to your Configuration.h & Configuration_adv.h may be helpful.

**Comment by AnHardt** [comment]
Maybe related to https://github.com/MarlinFirmware/Marlin/issues/2722

**Comment by max-232** [comment]
a possible dirty solution? https://github.com/MarlinFirmware/Marlin/issues/2722#issuecomment-154162669

**Comment by thinkyhead** [comment]
We should be at a much better place with `RCBugFix` at this time. Now is the time to test it, because we're trying to get another release candidate out to the world, and it would be great to have all known issues cleared up.
