### ISSUE TITLE
[BUG] Markforged_XY option has problem to make small circles round 

### ISSUE THREAD

**Issue by Marek-zl** [MarlinFirmware/Marlin#24086]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

1) Markforged_xy there is problem with motor direction, I can not find the right setting. Motor is going all the time in wrong dirrection. With all settings like true and false direction or change pins on motor. No right possition.
2) the circles are not circles are on left and right side smaller, sides of the circle are more like cube. With size of the circle, it is more less dissapier. 

### Bug Timeline

new

### Version of Marlin Firmware

02010000 

### Electronics

BTT octopus pro v1

### Bed Leveling

No Bed Leveling

### Your Slicer

Prusa Slicer

### Host Software

Other (explain below)

### Additional information & file uploads

![40x40mm detail](https://user-images.githubusercontent.com/104358877/165148647-c46646ee-180f-4d89-8d55-7ade753f8783.jpg)
![40x40mm](https://user-images.githubusercontent.com/104358877/165148662-644da624-d2ea-44b5-883f-889ebd86efd0.jpg)

**Comment by rondlh** [comment]
That's odd, which slicer do you use? Could you show us the slicer preview?

**Comment by Marek-zl** [comment]
Prusa slicer, for this model. I tried also G2 instruction for circle and has the same result.
![slicer_prusa](https://user-images.githubusercontent.com/104358877/165355241-e83f4599-eead-4416-8e99-903c7c4581e2.JPG)

**Comment by rondlh** [comment]
Thanks, the preview looks fine. 
Markforged_XY has some racking issues that are most obvious when changing X direction. You could try moving X left and right 10mm and see if it affects the Y position. A lose Y belt could be the cause.

**Comment by Marek-zl** [comment]
I tried almost everithing. First of all I was testing mechanical parts, belts too ofcourse. There is not issue in mechanic. 

The X is moving smooth and holding possition. If I move 10 mm x or Y it is 10 mm so the callibration of the axis is good. 

The problem with "no circle" is groving when the circle is smaller. There has to be I think some calculation problem in planner. 

There is also problem with direction of the axis, in planner.

**Comment by rondlh** [comment]
If you can post your gcode, I will have a go at it...

**Comment by Marek-zl** [comment]
G2 I20 J20 or G2 I10 J10 for fast test it is just to draw a circle I use pen instead nozzle.  attached is also gcode for this callibration test print. 
[kalibrace4040pr10_43m_0,20mm_205C_PLA.zip](https://github.com/MarlinFirmware/Marlin/files/8570988/kalibrace4040pr10_43m_0.20mm_205C_PLA.zip)
![20220427_120225](https://user-images.githubusercontent.com/104358877/165494767-c836c977-35ae-444a-b177-788de7e30aa5.jpg)

**Comment by rondlh** [comment]
Note that in the gcode, there is no G2 command...

**Comment by rondlh** [comment]
I printed the gcode on an i3 style printer, the result is a nice small circle, so the gcode is fine.
![Circle](https://user-images.githubusercontent.com/77279634/165530255-62585157-630f-4ef2-8bbd-dab444252547.jpg)

Then drew some circles on a Markforged system: G2 I5 J5 (D=14mm), G2 I10 J10 (D=28mm), here the results with a 25mm coin. This shows the problem quite clearly, the left and right side are flat.
![Circle+Coin](https://user-images.githubusercontent.com/77279634/165526642-91436762-8d46-460b-8906-3da406e21a44.jpg)

About what you said "Markforged_xy there is problem with motor direction".
I don't have that problem. First make sure your Y-direction is correct, then adjust the X-direction if needed.

**Comment by Marek-zl** [comment]
yes, I printed the G-code on ender with no problem. But on Markforged_xy style printer is this issue with flat circle. 

The direction of the axis: Y is ok, no problem. but X is oposit, if I change direction in FW or wiring on motor than motor is in good direction but not is not working in Markforged_XY possitionning. 

I tried to change some +- in planner, I am not programmer I did it on blind. but I after this is was working.

Now I use bugfix 2 of FW version without any changes in planner. First would like to fix the circle problem, after this the problem with dirrection. 

![plannner2](https://user-images.githubusercontent.com/104358877/165548645-ff390e59-baaf-4c38-94c9-4a501af9314f.JPG)
![plannner](https://user-images.githubusercontent.com/104358877/165548657-8aed4094-febf-43b6-806f-8c82f09e7b9f.JPG)

**Comment by descipher** [comment]
I don't think it would be a planner movement issue since the X/Y lengths are equal in the print. G2 is and arc command so the arc reference point must be off center.
```
      if (r) {
        const xy_pos_t p1 = current_position, p2 = destination;
        if (p1 != p2) {
          const xy_pos_t d2 = (p2 - p1) * 0.5f;          // XY vector to midpoint of move from current
          const float e = clockwise ^ (r < 0) ? -1 : 1,  // clockwise -1/1, counterclockwise 1/-1
                      len = d2.magnitude(),              // Distance to mid-point of move from current
                      h2 = (r - len) * (r + len),        // factored to reduce rounding error
                      h = (h2 >= 0) ? SQRT(h2) : 0.0f;   // Distance to the arc pivot-point from midpoint
          const xy_pos_t s = { -d2.y, d2.x };            // Perpendicular bisector. (Divide by len for unit vector.)
          arc_offset = d2 + s / len * e * h;             // The calculated offset (mid-point if |r| <= len)
```

**Comment by descipher** [comment]
It appears to be the plan_arc call, it looks like it cannot do arcs on CORE_XY. What are you using to slice?

**Comment by rondlh** [comment]
I've been digging in the code a bit, generating some debug output. 
I can see that the G2 function creates a nice circle, and the circle is converted to steps and directions correctly and stored in the motion buffer.
 If there is any issue, then this happens afterwards.

**Comment by descipher** [comment]
Can't be arcs, there was no G2 in the gcode test sample provided.

**Comment by Marek-zl** [comment]
the problem is there also in normal G1 "arc" segments. in Markforged_xy where the position depends on two steppers. For this reason I thought that problem is in planner. seems that movement of the x asix is not complet, cos the flat segments of the circle.

**Comment by descipher** [comment]
@rondlh Can you do a 10mm box and then a circle in the center with a 5mm radius so we can see what the errored movements look like from a reference point? I don't have a a corexy to test on.

**Comment by rondlh** [comment]
@descipher 
Something like this?
```
G0 X0 Y0
G1 X0 Y10
G1 X10 Y10
G1 X10 Y0
G1 X0 Y0
G2 I5 J5
```
Please note that Markforged is _not_ the same as Corexy. 
This plotted on a Markforged_xy:
![Circle3](https://user-images.githubusercontent.com/77279634/165671059-99d3cd5e-56a1-480d-b51c-692995fc870b.jpg)

**Comment by descipher** [comment]
Perfect! Thanks. Now we can measure and analyze the coordinate results.
Immediately we can see X and Y are not equal. Y is greater than X

**Comment by descipher** [comment]
Question: Is BACKLASH_COMPENSATION enabled by chance?

**Comment by Marek-zl** [comment]
not in my case, will test it.

**Comment by descipher** [comment]
Based on the box being 10mm x 10mm  Y should actually be Y - 1mm and X should be X + 1mm.
Very odd.

**Comment by descipher** [comment]
This looks wrong.
planner.cpp:2097
```
    steps_dist_mm.a      = (da - db) * mm_per_step[A_AXIS];
```
If the steps da and db are equal then it will calculate 0 mm per step.

**Comment by rondlh** [comment]
> Question: Is BACKLASH_COMPENSATION enabled by chance?

Nope, it's not compatible with Markforged

**Comment by descipher** [comment]
Ok, that will need to be sanity checked.

**Comment by rondlh** [comment]
> Ok, that will need to be sanity checked.

It's there already, I played around with it a bit, and got an error.

**Comment by descipher** [comment]
@rondlh Ok, sorry missed it.

**Comment by rondlh** [comment]
> This looks wrong. planner.cpp:2097
``` steps_dist_mm.a      = (da - db) * mm_per_step[A_AXIS];```
> If the steps da and db are equal then it will calculate 0 mm per step.

da = X-steps, db=Y-steps.
A move in Y will also move the position of X (but not the other way around, Markforged_XY)
So if by chance the Y movement causes the required movement in X then there are no more steps needed for X.
![Markforged](https://user-images.githubusercontent.com/77279634/165848744-82a1f27e-d7d8-4147-9b30-f8a8131ff135.png)

**Comment by rondlh** [comment]
> @rondlh Ok, sorry missed it.

I checked it again, and it seems that backlash compensation is actually possible. I previously got a error saying that it was only possible on the Z-axis. But if I see the condition for this error than it looks like that you can use it on X or Y, but not on both. 

```
#if ENABLED(BACKLASH_COMPENSATION)
  #ifndef BACKLASH_DISTANCE_MM
    #error "BACKLASH_COMPENSATION requires BACKLASH_DISTANCE_MM."
  #elif !defined(BACKLASH_CORRECTION)
    #error "BACKLASH_COMPENSATION requires BACKLASH_CORRECTION."
  #elif EITHER(MARKFORGED_XY, MARKFORGED_YX)
    constexpr float backlash_arr[] = BACKLASH_DISTANCE_MM;
    static_assert(!backlash_arr[CORE_AXIS_1] && !backlash_arr[CORE_AXIS_2],
                  "BACKLASH_COMPENSATION can only apply to " STRINGIFY(NORMAL_AXIS) " on a MarkForged system.");
  #elif IS_CORE
    constexpr float backlash_arr[] = BACKLASH_DISTANCE_MM;
    #ifndef CORE_BACKLASH
      static_assert(!backlash_arr[CORE_AXIS_1] && !backlash_arr[CORE_AXIS_2],
                  "BACKLASH_COMPENSATION can only apply to " STRINGIFY(NORMAL_AXIS) " with your CORE system.");
    #endif
  #endif
#endif
```

**Comment by descipher** [comment]
Yes only one makes sense.

**Comment by descipher** [comment]
'target      - target position in steps units'

``` 
   if (da < 0) SBI(dm, X_HEAD);                  // Save the toolhead's true direction in X
   if (db < 0) SBI(dm, Y_HEAD);                  // ...and Y
```
da = X db =Y

```
_populate_block(block_t * const block, bool split_move,  const abce_long_t &target ...
```

If target is {100,100,0} and position is {0,0,0}

```  int32_t LOGICAL_AXIS_LIST(
    da = target.a - position.a,
    db = target.b - position.b,
```

steps are now set
da=100-0
db=100-0

block updated to
``` 
block->steps.set(NUM_AXIS_LIST(ABS(100 + 100), ABS(100), ABS(0) ...
```
da=100-0
db=100-0

```   
  #elif ENABLED(MARKFORGED_XY)
    steps_dist_mm.a      = (100 - 100) * mm_per_step[A_AXIS];
    steps_dist_mm.b      = 100 * mm_per_step[B_AXIS]; 

```
Looks wrong.
I am missing something?

**Comment by descipher** [comment]
Based on the formula:

![image](https://user-images.githubusercontent.com/10734527/165857634-639b3491-e6cd-4c8e-9a82-2ebfc6a8b2c2.png)

I would think this is better:

steps_dist_mm.a    = (da + (da - db)) * mm_per_step[A_AXIS];
steps_dist_mm.a = 100 * mm_per_step[A_AXIS];

**Comment by rondlh** [comment]
> steps_dist_mm.a = (da + (da - db)) * mm_per_step[A_AXIS];

This is the same as: steps_dist_mm.a = (2 * da - db) * mm_per_step[A_AXIS];
This is not according to the give kinematics.

I feel the issue might be coming from a rounding error or perhaps the minimum amount of steps that is handled in a segment. Even a small circle results in a minimum of 72 segments (MIN_CIRCLE_SEGMENTS in configuration_adv.h).
Below a picture of the positions calculated for: G2 I5 J5 circle. This looks fine, and also the resulting calculation in steps and directions are correct. The problem is introduced afterwards.

![Circle](https://user-images.githubusercontent.com/77279634/165893938-ea78f555-44f9-4782-a3ae-4e5fa6f873bb.png)
![circle2](https://user-images.githubusercontent.com/77279634/165895759-ad66d52c-5bee-47f3-8e4f-d531b6a89737.png)

**Comment by rondlh** [comment]
I've have a closer look at the steppers and found them to be running smoothly and constantly. So I don't believe the problem is on the software side, rather it's on the mechanical side. Racking is an issue for Markforged kinematics. If I look at the above picture I get the impression that the X-axis is sticking a bit. I have a closer look and the initial resistance against movement in the X-direction is a bit on the high side. This would explain the results, which shows that the carriage is not responding to small X-movements, until the force is enough and the friction is reduced (static friction > dynamic friction).

**Comment by descipher** [comment]
That's possible but less likely with two systems having exactly the same result. Also wouldn't you see faults in a more distributed way? If racking is the cause would you see it more by printing strait X lines repetitively.

**Comment by rondlh** [comment]
I think the main problem is sticking of the X-axis, and perhaps racking could also be a factor. I'm willing to do some tests if you have any suggestions...

**Comment by descipher** [comment]
If it's loosing steps due to racking then try printing X_AXIS only with 10 x 100mm lines and measure them. 
Then do Y individually. If the lines all measure exactly 100mm then it almost rules out a step loss due to racking alignment.

**Comment by descipher** [comment]
I did log the output step values on the simulator, based on the actual output results the axes movement formulas are correct.

**Comment by descipher** [comment]
The part that got me was the move formula distances are signed and based on direction.

**Comment by descipher** [comment]
One thought that came up for me is what if the X/Y axes moves were not in perfect sync. Y moves need X to move in perfect sync. One step out of sync and its not going to be pretty ... lol

**Comment by descipher** [comment]
If you suspect really small movement you could do 3 mm lines as an alternative.

**Comment by rondlh** [comment]
It's definitely not losing steps, that would show up very fast, and destroy any print. I think its a bit of flexibility in the belts, frame, and gantry that causes the carriage to stay behind about 0.5mm in the X-direction because of the carriage X-friction. In the pictures you can see that it catches up once it starts moving (dynamic friction < static friction), but for some reason it stays behind after it stopped moving for a bit. If I disconnect the carriage from the belt and push the carriage manually I can clearly feel this.
I also was thinking of out of sync pulses, but that would create nice ellipses, there would be no straight sections.
1 step out of sync is not going to show up. I use 200 steps per mm, typical is 80 steps per mm for X and Y, so 1 step would only be 12.5um. I've printed huge parts on this printer, print area is 40x40x40cm.
I not 100% clear about the test you propose... a bunch of 3mm lines along the x-axis?

**Comment by descipher** [comment]
Interleaved with y e.g. x y x y x y x y, if it's racking the flex effect may show up on the print.

**Comment by Marek-zl** [comment]
My last test 
Correction for X stepper direction

 #elif ENABLED(MARKFORGED_XY)
    if (da - db < 0) SBI(dm, A_AXIS);              // Motor A direction  (- instead +)
    if (db < 0) SBI(dm, B_AXIS);                   // Motor B direction
  #elif ENABLED(MARKFORGED_YX)

#elif ENABLED(MARKFORGED_XY)
      ABS(da - db), ABS(db), ABS(dc) // - instead +
    #elif ENABLED(MARKFORGED_YX)

  #elif ENABLED(MARKFORGED_XY)
    steps_dist_mm.a      = (da + db) * mm_per_step[A_AXIS]; // + instead - 
    steps_dist_mm.b      = db * mm_per_step[B_AXIS];
  #elif ENABLED(MARKFORGED_YX) 

This help me to correct X stepper 

Backlash

#define BACKLASH_COMPENSATION
#if ENABLED(BACKLASH_COMPENSATION)
  // Define values for backlash distance and correction.
  // If BACKLASH_GCODE is enabled these values are the defaults.
  #define BACKLASH_DISTANCE_MM { 0, 0, 0 } // (linear=mm, rotational=°) One value for each linear axis
  #define BACKLASH_CORRECTION    1.0       // 0.0 = no correction; 1.0 = full correction

If I put some different value than 0 in distance is going to error 

Last circle in 5 mm diam is on picture.

![220430091950442](https://user-images.githubusercontent.com/104358877/166096295-c3306075-3ca1-4a7f-826c-1f71ee98c206.jpg)

**Comment by descipher** [comment]
https://github.com/MarlinFirmware/Marlin/blob/3bcbd3259f8d1ff3fc262b2ede83efd873863d5f/Marlin/src/module/planner.cpp#L2063-L2065

This calculation is correct, it is not currently used anywhere else in the code. I did verify its value output using logging.

**Comment by descipher** [comment]
We would need line numbers to know where the discussion references are from.

**Comment by descipher** [comment]
Any chance you could run a 10mm or more diameter, 5mm may not show the fault as well.

**Comment by descipher** [comment]
@Marek-zl  I think you are the right track, I think the issue is the direction calculation failing at the Y 0 crossing points, just can't tell if its correct yet. Kind of looks like the circle you printed has the fault on the lower side now.

**Comment by Marek-zl** [comment]
10mm circle. Result is horrible. the problem is significant on left and right side. If circle is smaller is going to be more square

![220430175223254](https://user-images.githubusercontent.com/104358877/166112850-4e546003-c527-40e6-b791-80cdf2effcfc.jpg)

**Comment by descipher** [comment]
Inverse side from what @rondlh experienced. Looks like only negative X and negative Y directions are impacted in the last print.
There are odd and even sizes within infill cross hatching which could be direction related.

**Comment by descipher** [comment]
https://github.com/MarlinFirmware/Marlin/blob/3bcbd3259f8d1ff3fc262b2ede83efd873863d5f/Marlin/src/module/planner.cpp#L1962-L1967
```
 #elif ENABLED(MARKFORGED_XY) 
   if (da < 0) SBI(dm, A_AXIS);                   // Motor A direction 
   if (db < 0) SBI(dm, B_AXIS);                   // Motor B direction 
 #elif ENABLED(MARKFORGED_YX) 
   if (da < 0) SBI(dm, B_AXIS);                   // Motor B direction 
   if (db < 0) SBI(dm, A_AXIS);                   // Motor A direction 
```
@Marek-zl Could you please test this.

**Comment by descipher** [comment]
I may have the da db switched around though, hard to tell what MARKFORGE_XY means in respect to the belts A or B. We will fix that up once this is sorted out.

**Comment by Marek-zl** [comment]
result

![220430210010304](https://user-images.githubusercontent.com/104358877/166119163-b3c2f46a-e555-46a4-9c91-148bf0a7e843.jpg)

**Comment by descipher** [comment]
LOL, if you move X manually does Y move?

**Comment by descipher** [comment]
![Markforge_on_cart](https://user-images.githubusercontent.com/10734527/166128720-07273f67-ac71-4151-b9e7-e96263cf2443.jpg)

I did some tests on a cartesian frame with MARKFORGE_XY enabled. It works correctly without odd flat areas on the sides. Of course it is skewed at 45 degrees but that's expected due to X moving negative to hold it's position. I did have to modify the code for it to operate correctly in XY format. You may be experiencing a racking issue where the axes need to be adjusted to square and or belt tension needs to be set equal. Just used a pencil to track the move, it was a little loose but not an issue.

https://github.com/MarlinFirmware/Marlin/blob/a1d4942f760fa1d589af11d378a938fba6f45cd2/Marlin/src/module/planner.cpp#L825
```
  block->decelerate_after =  block->step_event_count - decelerate_steps; <-this makes sure the steps are set equally at each end of a segment. 
```
https://github.com/MarlinFirmware/Marlin/blob/a1d4942f760fa1d589af11d378a938fba6f45cd2/Marlin/src/module/planner.cpp#L1962-L1964
```
  #elif ENABLED(MARKFORGED_XY)
    if (da - db < 0) SBI(dm, A_AXIS);              // Motor A direction
    if (db < 0) SBI(dm, B_AXIS);                   // Motor B direction
```
https://github.com/MarlinFirmware/Marlin/blob/a1d4942f760fa1d589af11d378a938fba6f45cd2/Marlin/src/module/planner.cpp#L2015-L2016
```
  #elif ENABLED(MARKFORGED_XY) 
    ABS(da - db), ABS(db), ABS(dc)
```

**Comment by Marek-zl** [comment]
I think that if there problem with belts, has to be problem print something. I have fine surface on prints, no problem to print cubes, the problem is just on circle. 
I can try to play around with belts, but I do not think that problem is there.

**Comment by descipher** [comment]
```
block->decelerate_after =  block->step_event_count - decelerate_steps;
```
This is important for syncing steps across the axes , did you try it?

**Comment by Marek-zl** [comment]
no, where it is?

I tried 0,1mm steps to test belt tention, manualy stepping x y and seems it is quite good. 

![220501172420642](https://user-images.githubusercontent.com/104358877/166152850-a375ff5c-4cc3-46d0-96d1-c2affc4542d8.jpg)

**Comment by rondlh** [comment]
@Marek-zl 
>if (da - db < 0) SBI(dm, A_AXIS); // Motor A direction (- instead +)
Changing the sign doesn't do much, it's just a matter of definition of the positive Y-direction. Changing the sign will mirror the print in the Y-direction, that's all.

> I tried 0,1mm steps to test belt tention, manualy stepping x y and seems it is quite good.
This kind of zigzag line is quite useful, it would show the problem I expect my printer has (on the mechanical side, sticking of the X-carriage, perhaps a bit of racking). To really test this the 0.1mm steps should be made slowly to allow the carriage to come to a complete stop before doing the next step. This can be done manually or insert some G4 (dwell). Several zigzags would be needed. The problems are in the change of direction.

In my case, I will reduce the friction on the X-carriage as much as possible. I found that the carbon fiber guide rods and PETG bearing have a bit too much static friction. I will work on this and do some more test, but I currently do not have access to the printer because of the labor day break.

For Markforged_XY, there seems to be a bit of confusion still...
da just means delta on stepper A.
Stepper A is linked to the X-axis. If you make steps on motor A then the carriage X-position will change, but not the Y-position. 
Stepper B is linked to the Y-axis, but moving Y affects the X-position too. So you will have to take corrective actions on X to keep it's position, or to make it go where you want it to go. I'm convinced that the Marlin math and stepper signals are correct.

**Comment by descipher** [comment]
> @Marek-zl
> 
> > if (da - db < 0) SBI(dm, A_AXIS); // Motor A direction (- instead +)
> > Changing the sign doesn't do much, it's just a matter of definition of the positive Y-direction. Changing the sign will mirror the print in the Y-direction, that's all.
>

That's true however this must be consistent across the code.
e.g. needs to be insync with 

https://github.com/MarlinFirmware/Marlin/blob/3bcbd3259f8d1ff3fc262b2ede83efd873863d5f/Marlin/src/module/planner.cpp#L2063-L2065

**Comment by descipher** [comment]
> no, where it is?

https://github.com/MarlinFirmware/Marlin/blob/a1d4942f760fa1d589af11d378a938fba6f45cd2/Marlin/src/module/planner.cpp#L825

> I tried 0,1mm steps to test belt tention, manualy stepping x y and seems it is quite good.

![166152850-a375ff5c-4cc3-46d0-96d1-c2affc4542d8](https://user-images.githubusercontent.com/10734527/166155565-8b553136-b7d0-46b4-b76e-7f1e4e009a3b.jpg)

Yes you have an issue. It is not transitioning at 90 degrees.

**Comment by Marek-zl** [comment]
block->decelerate_after = accelerate_steps - plateau_steps --- Is doing nothing in the result

I gues that if this problem is on belt, it has to looks different. Belt is pulling until is on the top of the circle. 

When problem with belts has to be circle broken in the point where motor changing dirrection. But it is not this case, flat part start before top of the circle, so before belt changing dirrection. 

On picture is circle made of the  normal G-code 

![test](https://user-images.githubusercontent.com/104358877/166157689-75bcc8d8-cbc2-4451-a36f-b7d41c238e0f.jpg)

this circle is with G2 
with this setting 

// G2/G3 Arc Support
//
#define ARC_SUPPORT                   // Requires ~3226 bytes
#if ENABLED(ARC_SUPPORT)
  #define MIN_ARC_SEGMENT_MM      0.01 // (mm) Minimum length of each arc segment (0,1)
  #define MAX_ARC_SEGMENT_MM      0.1 // (mm) Maximum length of each arc segment (1,0)
  #define MIN_CIRCLE_SEGMENTS    72   // Minimum number of segments in a complete circle
  //#define ARC_SEGMENTS_PER_SEC 50   // Use the feedrate to choose the segment length
  //#define N_ARC_CORRECTION       25   // Number of interpolated segments between corrections (25)
  //#define ARC_P_CIRCLES             // Enable the 'P' parameter to specify complete circles
  //#define SF_ARC_FIX                // Enable only if using SkeinForge with "Arc Point" fillet procedure

![Test_001_segment](https://user-images.githubusercontent.com/104358877/166158013-7135268f-c80e-47ec-a14e-5c823f9f64a4.jpg)

**Comment by descipher** [comment]
> Belt is pulling until is on the top of the circle.

Not really, look at the movement trace I did on the Cartesian frame. That represents the actual motor movements. With the image horizontally mirrored to match your moves the right XY idle point belt transition is approximately at 60 degrees and thats where X starts to go in the negative direction from a stand still.

**Comment by rondlh** [comment]
I did some more tests and solved some issues on my IDEX Markforged_xy printer. I found that the X-carriage was sticking a bit causing the artifacts that I showed above. After making some adjustments (new bearings, tighter belts) I got some nice results. I attached the STL and Gcode (Cura 5 beta 1) too for reference. Note that the gcode does not use the G2 command, but it uses straight line approximations in the same ways as G2 does. This looks quite satisfactory in my view.
Markforged systems will always have some inaccuracy because of racking, friction and belt flexibility, I believe that is what the people here are experiencing. So please make sure your belts are tight and friction is at a minimum. For testing you can use tiny steps (0.1mm) in the X- and Y-direction, forwards and backwards to see of the carriage follows that accurately. In my case I could see that some steps were not visible in carriage movement, but after some more steps suddenly the carriage started moving.
![Circle test](https://user-images.githubusercontent.com/77279634/167297846-84b93a10-0ebc-462e-9d22-a88dce5321e8.jpg)
[Circle_test STL GCODE.zip](https://github.com/MarlinFirmware/Marlin/files/8647022/Circle_test.STL.GCODE.zip)
