### ISSUE TITLE
[FR] Include Date In Bugfix Release

### ISSUE THREAD

**Issue by rq3** [MarlinFirmware/Marlin#24174]
### Is your feature request related to a problem? Please describe.

The "nightly" bugfix releases all have the same name. It would be tremendously helpful if the name included the date, or even better, the time, of the release. So that "bugfix-2.0.x.zip" would look like "bugfix-2.0.x_051422.zip", or if bugfixes are released muliple times per day, "bugfix-2.0.x_051422_HHMMSS.zip", where HHMMSS is 24 hour time.

For folks trying to do testing of new features in Marlin, it is very aggravating to have to go through file compares or the like to determine if a new bugfix is actually new.

Having the same file name for what is actually a different file seems like bad practice. And the addition of a simple time stamp to the file name would fix this.

### Are you looking for hardware support?

No

### Describe the feature you want

Time stamps included in the bugfix name.

**Comment by thisiskeithb** [comment]
> For folks trying to do testing of new features in Marlin, it is very aggravating to have to go through file compares or the like to determine if a new bugfix is actually new.

The date is already included and is bumped by [this cron job](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/workflows/bump-date.yml). Simply check the commit history or `Marlin/Version.h` or `Marlin/src/inc/Version.h` for an updated date. Since those are bumped daily if there were changes made to bugfix.

If you have `LCD_INFO_MENU` enabled, you can also find the date on your LCD screen.

>  So that "bugfix-2.0.x.zip" would look like "bugfix-2.0.x_051422.zip"

We can't change the name of zip files downloaded from branches on Github because that would require us to rename the branch every single time a change is made and that is not possible.
