### ISSUE TITLE
[BUG] fatal error: ../inc/MarlinConfig.h: No such file or directory

### ISSUE THREAD

**Issue by Mech131** [MarlinFirmware/Marlin#24299]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When compiling BIGTREE_SKR_2_F429, receive error:

```
                 Compiling .pio\build\BIGTREE_SKR_2_F429\src\src\gcode\feature\trinamic\M569.cpp.o
In file included from Marlin\src\gcode\feature\runout\../../../feature/../module/stepper/../../feature/../lcd/../feature/pause.h:37,
                 from Marlin\src\gcode\feature\runout\../../../feature/../module/stepper/../../feature/../lcd/marlinui.h:48,
                 from Marlin\src\gcode\feature\runout\../../../feature/../module/stepper/../../feature/tmc_util.h:25,
                 from Marlin\src\gcode\feature\runout\../../../feature/../module/stepper/trinamic.h:35,
                 from Marlin\src\gcode\feature\runout\../../../feature/../module/stepper/indirection.h:44,
                 from Marlin\src\gcode\feature\runout\../../../feature/../module/stepper.h:47,
                 from Marlin\src\gcode\feature\runout\../../../feature/runout.h:31,
                 from Marlin\src\gcode\feature\runout\M412.cpp:28:
Marlin\src\gcode\feature\runout\../../../feature/../module/stepper/../../feature/../lcd/../feature/../libs/nozzle.h:24:10: fatal error: ../inc/MarlinConfig.h: No such file or directory
   24 | #include "../inc/MarlinConfig.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\BIGTREE_SKR_2_F429\src\src\gcode\feature\runout\M412.cpp.o] Error 1
```

### Bug Timeline

Marlin 2.1

### Expected behavior

I expected the firmware to compile

### Actual behavior

It threw an error

### Steps to Reproduce

1. Configure firmware for Board BTT SKR 2 Rev B Dual Z
2. Compile firmware using BIGTREE_SKR_2_F429

### Version of Marlin Firmware

2.1

### Printer model

Ender 5 Plus

### Electronics

BTT SKR 2 Rev B Dual Z

### Add-ons

None

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Other things to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.
- [ ] Log output from the host. (`M111 S247` for maximum logging.)
- [ ] Images or videos demonstrating the problem, if it helps to make it clear.
- [ ] A G-Code file that exposes the problem, if not affecting _all_ G-code.

### Additional information & file uploads

[ZIP of Config & Config_adv](https://drive.google.com/file/d/1rdPEsYdv8hifOmDwr8c8pvSoEPr5w5Dg/view?usp=sharing)

**Comment by thisiskeithb** [comment]
You configs are not the latest version since they are missing several settings/things are moved around, but they build against the latest `bugfix-2.1.x` fine.

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server
