### ISSUE TITLE
[BUG] Compilation errors for BTT SKR V2 board for BTT TFT 35 display

### ISSUE THREAD

**Issue by NightingaleUQ** [MarlinFirmware/Marlin#24322]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When compiling firmware for the **BigTreeTech SKR (v2) mainboard** with the **STM32F407 microcontroller** I receive compilation errors when I `#define REPRAP_DISCOUNT_SMART_CONTROLLER` for use with my **BigTreeTech TFT35 E3** display.

At first, the compilation errors occur due to no definitions of the SPI pins on my mainboard. Fixing them will lead to other errors pertaining to display size not defined and later a linking error for `MarlinUI::touch_calibration_screen()`. It seems that whenever I either `#define` the variable the compiler needs or comment out preprocessor macros there's always something else to fix.

Could you please look into this for me?

### Bug Timeline

Not sure, but I also had errors on v2.0.9.3

### Expected behavior

I expected the code to successfully compile and link

### Actual behavior

The code does not compile and link (see bug description)

### Steps to Reproduce

In `Configuration.h`:
1. `#define MOTHERBOARD BOARD_BTT_SKR_V2_0_REV_B`
2. `#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`

### Version of Marlin Firmware

bugfix-2.1.x branch, commit ec7cc59818455af49b21651e6e0e9acf909e9864

### Other things to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.
- [ ] Log output from the host. (`M111 S247` for maximum logging.)
- [ ] Images or videos demonstrating the problem, if it helps to make it clear.
- [ ] A G-Code file that exposes the problem, if not affecting _all_ G-code.

### Additional information & file uploads

[config.zip](https://github.com/MarlinFirmware/Marlin/files/8880387/config.zip)

**Comment by thisiskeithb** [comment]
You have `TOUCH_SCREEN` enabled. You do not enable that setting with these displays because they are really separate computers/G-code senders connected via serial. For "Marlin Mode", enabling `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` & a serial port is enough.

See the readme in [BigTreeTech's TFT firmware repo](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware#table-of-contents) for full instructions.

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server
