### ISSUE TITLE
Cancel hot end idle time out on Start Print rather than E motion

### ISSUE THREAD

**Issue by eric-the-eye** [MarlinFirmware/Marlin#24341]
### Is your feature request related to a problem? Please describe.

https://github.com/MarlinFirmware/Marlin/issues/19610

### Are you looking for hardware support?

No

### Describe the feature you want

Using high printing temperature filaments and high bed temperatures often takes longer to achieve before idle time out is cancelled by E motion. Would be better to have idle time out cancelled on start of new print.

**Comment by thisiskeithb** [comment]
Have you tested current code/[`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip)? Marlin now checks the planner to see if the printer is truly idle instead of just the extruder. See: 

- https://github.com/MarlinFirmware/Marlin/pull/21535

Otherwise, increase your `HOTEND_IDLE_TIMEOUT_SEC` value to something longer than the default `(5*60)` (five minutes).
