### ISSUE TITLE
[Marlin does not install] (Prusa MK3S with BTT002, Marlin does not install)

### ISSUE THREAD

**Issue by mikoducky** [MarlinFirmware/Marlin#24393]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I tried recently to update to Marlin 2.1, but got freezing menus when I removed the SD card. This got worse until the controller would not even boot.

I tried stepping down to 2.0.9.4. Marlin does not even attempt to flash.

I went to 2.0.9.3. Same issue.

Marlin 2.0.9.2 is the last version to work flawlessly with my setup.

Using visual code studio to build using platform IO AND auto marlin builder. The versions after 2.0.9.2 added a BTT002_VET6 version, which also does not work. Besides that, VS studio complains of some vscode issues, which I'm too stupid to understand.

I'm using the config and config_adv files from your guthub here: https://github.com/MarlinFirmware/Configurations/tree/release-2.0.9.4/config/examples/Prusa/MK3S-BigTreeTech-BTT002

### Bug Timeline

2.0.9.3

### Expected behavior

Marlin would update properly.

### Actual behavior

Marlin did not flash to the controller.

### Steps to Reproduce

1. Have an MK3S with a BTT002 board.
2. Compile any Marlin after 2.0.9.2.
3. Flash to printer.
4. ???
5. Non-profit.

### Version of Marlin Firmware

2.0.9.2

### Printer model

Prusa MK3S

### Electronics

BTT002 controller with 2207 drivers

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
This is a hardware issue since flashing is handled by the bootloader and is not something Marlin has control of.

Also, I just flashed `bugfix-2.1.x` (645c7dc) to a BTT002 and it updated fine.

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server
