### ISSUE TITLE
E3D Cyclops 

### ISSUE THREAD

**Issue by stanrob** [MarlinFirmware/Marlin#2500]
Hi,
I just bought a E3D Cyclops nozzle and I need tout help to set Marlin setting to use it.
It is a single nozzle with two extruder motor (mixing extruder) 
I didn't find anything to do tgis by myself si if someone know how can I do it will be awsome 
Thank's

**Comment by AnHardt** [comment]
Same as #1613.

**Comment by stanrob** [comment]
You closed this issue but I don't have my answer. I don't find the soution in #1613 topic

**Comment by AnHardt** [comment]
@stanrob 
Closing this one and pointing to an other means.
We already have an issue with the same topic. Continuing this issue here will split the available information to different places.

The original poster of #1613 at least gave a partial solution.
MagoKinbra advertised his branch.

Please make further comments in #1613 .
