### ISSUE TITLE
[BUG] not homing at 0,0

### ISSUE THREAD

**Issue by Th3w0lver1n3** [MarlinFirmware/Marlin#25004]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Board- mks gen v1.4
Optical endstops
Bltouch
When my printer homes it doesn't register the home position as 0,0 it registers it as 210,320, and consequently only partially uses the print bed because the max spot is somewhere in the middle of the bed. 
How do I fix this in the marlin code?

### Bug Timeline

New

### Expected behavior

Should home to 0,0

### Actual behavior

Homes to 0,0 but reads 210,320

### Steps to Reproduce

Press auto home

### Version of Marlin Firmware

V 1.1.9

### Printer model

Folgertech ft-6 with vqrious upgrade

### Electronics

Upgraded optical endstops

### Add-ons

N/a

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

Pronterface

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

N/a

**Comment by ellensp** [comment]
No configs. 
This is what happens when you home to max positions. 
Homing sets to a known position, not always 0,0 can be any known position 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
