### ISSUE TITLE
Z-probe wizard gives radically different results based on current z-probe offset.

### ISSUE THREAD

**Issue by jwalton** [MarlinFirmware/Marlin#25222]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

If you set your z-probe offset to -1.5mm and run the z-probe wizard, then set the z-probe offset to 0mm and run the z-probe wizard, you'll get two different results that differ by 1.5mm.

### Bug Timeline

Unknown

### Expected behavior

Z-probe wizard should ignore the existing z-probe offset.

### Actual behavior

Z-probe wizard does not ignore the existing z-probe offset.

### Steps to Reproduce

1. Set z-probe offset to 0
2. Run z-probe wizard, get result x
1. Set z-probe offset to -1.5
2. Run z-probe wizard, get result x-1.5.

### Version of Marlin Firmware

bugfix-2.1.x (33e5aad364)

### Printer model

Creality Ender 5 Pro

### Electronics

5.2.2 silent mainboard

### Add-ons

CRTouch

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/10383752/Config.zip)

**Comment by AustinTylerDean** [comment]
I have a similar issue, though may be different.
I use the Z Offset Wizard, determine that the delta is -1.9mm. Click Done, then Save.
Use the wizard AGAIN, find a delta of -.25, Done, then Save.
Z Offset value now shows -.25 instead of -2.15, resulting in having to zero out your SW Z Offset every time before you use the wizard.
Hoping these are the same things, it would certainly be a huge fix in my book.

**Comment by NeoIsrafil** [comment]
Honestly, i'm thinking nozzle to probe offset is badly broken.  Certain things take it into account, certain things dont, it may have to do with the change to  the way marlin handles the z clearance deploy probe, z clearance between probes, etc.  it may also have to do with something entirely different.  I'm just speculating.  I do know that when i have anything in nozzle to probe offset for z it does weird things, the z clearance also does weird things, its needing a z probe low point of -4 to even trigger the second time it tries to touch off, because it jumps up 30mm or so after the first and i have no idea where its getting that command from.

Has anyone found a workaround?  I'd like my printer working :(

**Comment by dynek** [comment]
@AustinTylerDean I'd need to check it again but I have to zero out the value before running the z-offset probe wizard, because it will actually **add** delta each time.

**Comment by AustinTylerDean** [comment]
It seems to me that the reading should be absolute. So if you are already
at -1.15 and you go .2 lower from a second calibration, the moment you
click out of the adjustment, the value should be -1.35. and it clearly
doesn't work like that. Do you agree with my expectation?

**Comment by dynek** [comment]
@AustinTylerDean your reasoning is correct. Simple put, the Z-Offset should be set to the value discovered during calibration.

Just made a test:

```
Send: M851 Z0
Recv: ok
Send: M851
Recv:   M851 X45.00 Y8.00 Z0.00 ; (mm)
```

Running Z Probe Wizard that ends up displaying:
> Z-0.80
> Probe Z Offset-0.80

Saving data, M851 now shows Z-0.80 👍 
But if I now re-run the Z Probe Wizard, I will find out the same value (-0.8) but it will add it to previous value.
It ends up displaying:
> Z-0.80
> Probe Z Offset-1.60

And value stored is -1.60 and now the nozzle hits the bed.

**Comment by mashuptwice** [comment]
The same seems to happen with babystepping. I have an exponentially growing error in the offset, started at -1.7mm and now I am at +7.490mm!

**Comment by vito30x** [comment]
> Honestly, i'm thinking nozzle to probe offset is badly broken. Certain things take it into account, certain things dont, it may have to do with the change to the way marlin handles the z clearance deploy probe, z clearance between probes, etc. it may also have to do with something entirely different. I'm just speculating. I do know that when i have anything in nozzle to probe offset for z it does weird things, the z clearance also does weird things, its needing a z probe low point of -4 to even trigger the second time it tries to touch off, because it jumps up 30mm or so after the first and i have no idea where its getting that command from.
> 
> Has anyone found a workaround? I'd like my printer working :(

Got the same Problem here. This happen after updating to Marlin 02010300.

**Comment by vito30x** [comment]
Is there any fix done yet?

**Comment by inspectionsbybob** [comment]
I am seeing the same thing that my Z-offset keeps growing after every reset.

Everything is stable and works for days and days.  But if I have to reset the printer due to a failed print, or something else, the Z-offset ALWAYS is off, and needs to be made larger (more negative).
