### ISSUE TITLE
Append comments to "Inverted extruder on second print after power on and stop"

### ISSUE THREAD

**Issue by sppmg** [MarlinFirmware/Marlin#25233]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I use ``Marlin-2.1.1``, it happen same problem in #18153.
#18153 locked, so I create new issue, can you move to #18153 or just unlock it and let me append it ?

I think the problem is start gcode by slicer, e.g. Cura .
My start gcode is:
```
M220 S100
G28 ;Home
G1 Z15.0 F6000 ;Move the platform down 15mm
;Prime the extruder
;G92 E0
G1 F200 E10 ; <------ Problem here , it will unload filament.
G92 E0
G1 F1500 E-6
```
(I know it's bad, because I did not research gcode at setting time.)
After use serial console and M114 to report position, I discover G28 will not zeroing E axis.
**So when printing is non-first and gcode using ``absolute extrusion mode``, extruder will invert to unload filament.**
(Cura default use absolute extrusion mode.)

And maybe add this information (about not zeroing E axis) to G28 [document](https://marlinfw.org/docs/gcode/G028.html) will be good.

### Bug Timeline

old

### Version of Marlin Firmware

2.1.1

### Printer model

diy

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
> ;G92 E0

You have commented out [`G92 E0`](https://marlinfw.org/docs/gcode/G092.html) which resets the extruder back to zero.

If you want to use relative mode for your print, then use [`G91`](https://marlinfw.org/docs/gcode/G091.html) instead of [`M82`](https://marlinfw.org/docs/gcode/M082.html).

This is not a bug with Marlin, but with your slicer's start script.

---
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server
