### ISSUE TITLE
[FR] Add standard peripheral serial port defines for all motherboards. Makes config file easier for users.

### ISSUE THREAD

**Issue by ellensp** [MarlinFirmware/Marlin#25265]
### Is your feature request related to a problem? Please describe.

Users seem to easily get confused as to what serial port numbers to use.

Developers and support people know to look at board manufacturers pin diagram or to look at circuit diagrams, , But they don't always name the UART port used, sometimes it is IO pins, which the user is not expected to be able to translate.

   

### Are you looking for hardware support?

no

### Describe the feature you want

Add the following defines per board.  

CONTROLLER_USB_SERIAL_PORT
CONTROLLER_TFT_SERIAL_PORT
CONTROLLER_LCD_SERIAL_PORT
Any others?

Then you can have #define SERIAL_PORT CONTROLLER_USB_SERIAL_PORT
and #define LCD_SERIAL_PORT CONTROLLER_LCD_SERIAL_PORT

Without the user having to worry about what port they are on
While still allowing for numeric settings for customization, for users that know what they want.

**Comment by Roxy-3D** [comment]
This makes a lot of sense...

**Comment by EvilGremlin** [comment]
+1, thinking about it for a long time
probably HMI_SERIAL_PORT, not LCD
and ESP_SERIAL_PORT

**Comment by ellensp** [comment]
HMI_SERIAL_PORT may be technically correct, but no one, including myself, knows what that means!

Perhaps WIFI_SERIAL_PORT, yes most are ESP modules for now, but may not be in the future..

**Comment by Bob-the-Kuhn** [comment]
Along similar lines ...

How about adding info to configuration.h indicating which LCDs use SERIAL_PORT and which use LCD_SERIAL_PORT.

**Comment by ellensp** [comment]
There are no LCD types in marlin config that use SERIAL_PORT, only those that need LCD_SERIAL_PORT

**Comment by EvilGremlin** [comment]
It's naming hell. TFT refer to what? DWIN is TFT alright. Unless they have TN models which i doubt. 
Maybe
BOARD_USB_SERIAL_PORT
BOARD_5PIN_SERIAL_PORT
BOARD_EXP_SERIAL_PORT (for creality 10-pin mostly)
BOARD_WIFI_SERIAL_PORT

**Comment by ellensp** [comment]
It doesn't really matter, what ever we come up with thinkyhead will change it, 

So for now I say we use temporary names

OPAL_PORT    for usb
JADE_PORT    tft port    
RUBY_PORT   for wifi
ONXY_PORT  for exp

Then a simple search and replace can be done for the final name that passes thinkyhead scrutiny.

**Comment by EvilGremlin** [comment]
For now i vote fot BOARD_#PIN_SERIAL_PORT, numbers can be 3,4,5 and 10. And wrong serial error must link to doc explaining stuff (including referencing datasheets etc)

**Comment by ellensp** [comment]
Well if your not going to be serious.

**Comment by EvilGremlin** [comment]
?? i'm quite serious about that naming with pin count. It's representative of board connectors, no matter silkscreen labels and devices plugged.

**Comment by Roxy-3D** [comment]
This is a good idea and we need to work through the issues.

**Comment by Roxy-3D** [comment]
One question I have that could use some discussion is this:     

If a board has multiple serial ports available, should they all be enabled by default?   Or should just one be enabled unless the user specifies multiple are desired?    And if only one is enabled, my thinking is it should be the USB Serial port that has hardware support (assuming that exists).

**Comment by The-EG** [comment]
At least one case of not wanting all available serial ports enabled comes to mind: Creality v4.2.x boards have a UART in the EXP port. This is so that the DWIN screen (ie. Ender 3 v2) can be used, but you obviously can't use that UART if you are using something else, like a `CR10_STOCKDISPLAY`. 

I also really like this idea. This was one of the hurdles for me when upgrading to the BTT Octopus board, and trying to get the above DWIN screen working. I had no idea that the UART numbers were actually labeled as RXn/TXn on BTTs pin diagrams until *after* I had stumbled upon the correct UART number and then made the connection. I got it working by just trying numbers until it worked.

I also think the most helpful and easy to understand approach, for the ***average user***, would be to name them as they are on the board/documentation. I believe that's also what the original intent with the changes here was.

With the Octopus you'd end up with something like:
```c++
#define CONTROLLER_USB_SERIAL_PORT -1
#define CONTROLLER_TFT_SERIAL_PORT 1
#define CONTROLLER_CAN_SERIAL_PORT 1
#define CONTROLLER_RPI_SERIAL_PORT 2
#define CONTROLLER_WIFI_SERIAL_PORT 3
```

You can argue all you want about what RPI and WIFI should be called, but in reality a user looking at either of those is going to see things like this:
![image](https://user-images.githubusercontent.com/7342077/214435720-83c583c3-5a0b-4c3d-9c45-c56c60ffbe28.png)

**Comment by Roxy-3D** [comment]
The BTT Octopus board is a good example to use.  I have a BTT octopus board and its serial ports have to be messed with to get it to work reliably with PronterFace.    We should probably have a couple of other 'problem' boards that we check our thinking against.   Maybe one of the Creality boards too?
