### ISSUE TITLE
[BUG] At the M503 command, the M900 paremtr is not complete.

### ISSUE THREAD

**Issue by radek8** [MarlinFirmware/Marlin#25381]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I have a printer with 2 hotends.
The printer prints the parameters on Command M503.
In earlier versions, Marlin reported the parameter:
   M900 T0 K0.1000
   M900 T1 K0.1000
In the current version, only:
M900 K0.1000

### Expected behavior

   M900 T0 K0.1000
   M900 T1 K0.1000

### Actual behavior

M900 K0.1000

### Steps to Reproduce

Command M503

### Version of Marlin Firmware

VERSION 02010200

### Printer model

Endar3

### Electronics

SKR V1.4 Turbo

### Add-ons

BTT TFT35 E3 V3

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/10726981/Config.zip)

**Comment by thisiskeithb** [comment]
> #error "Your Configuration_adv.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration_adv.h."

This config was not tested with the current `bugfix-2.1.x` because it does not build.

Also, you did not enable `DISTINCT_E_FACTORS` and you only have one extruder enabled, so `M503` is going to only output one K value:

https://github.com/MarlinFirmware/Marlin/blob/4c136c3dad1284d7c1ece2238c8413f8f97f8392/Marlin/src/gcode/feature/advance/M900.cpp#L147-L158

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
