### ISSUE TITLE
[BUG] Icons and some text are missing on ender-3 v2 neo

### ISSUE THREAD

**Issue by Andlix** [MarlinFirmware/Marlin#25464]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I think it is the same problem as #23860.
When I update to version 4.2.2, all icons and some text are missing.

I build with the configuration for Ender-3 v2 neo, with tag release-2.1.2.

I thought that the resources for the display didn't fit, so I updated them from https://github.com/mriscoc/Ender3V2S1/tree/Ender3V2S1-Released/display%20assets. However, that made everything worse, both the delivered firmware and version 2.1.2 no longer worked. I tested the stock version and Giadej.

The display is a DACAI.

### Expected behavior

Icon and all text are displayed.

### Actual behavior

Icon and some text are not displayed.

### Version of Marlin Firmware

2.1.2

### Printer model

Creality Ender 3 v2 neo

### Electronics

Stock electronics

### Bed Leveling

None

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/10891441/Configuration.zip)

**Comment by Andlix** [comment]
Now I take the files from "Configurations\config\examples\Creality\Ender-3 V2\LCD Files", now I see the icons, but the text in menu is missing.

**Comment by Andlix** [comment]
Finally I found a proper configuration.
If I find the time, I'll create a pull request for MarlinFirmware/Configuration  in the next few days.

**Comment by ThomasToka** [comment]
@Andlix could you please share your findings? Thx

**Comment by Fido789** [comment]
@Andlix Yes, it would be very helpful to share a proper configuration.

**Comment by chtaube** [comment]
I've ran into the same display issue with my Ender-3 v2 Neo and my "solution" was to build the firmware based on @mriscoc release at https://github.com/mriscoc/Ender3V2S1

The travel limits (endstops) on my E3v2Neo where slightly different, and I'm using a dual gear extruder with a different feedrate, that's why I've modified and compiled my own firmware based on his release. But apart from that no modifications where necessary.

The DACAI display can be reflashed with the stock firmware. It's in included in his release, too.

**Comment by loop0** [comment]
I have the same issue with my ender 3 v2 neo, I built the latest marlin 2.1.2.1, I reflashed my display with the configurations for DACAI display from release 2.1.2.1. I get the icons but the text on the menus won't show. Would you care to share your solution @Andlix? Thanks

**Comment by JaxGM** [comment]
Hi! I'm having the same issue. I was able to find this in the Configuration repo: https://github.com/MarlinFirmware/Marlin/issues/23621 However, I haven't been able to find the results of this in the most recent release but I hope someone else may find this helpful! 😊

I have also tried to flash the contents of the ender3v2/lcd/private folder but it says the folder is too large.




![IMG_7882](https://github.com/MarlinFirmware/Marlin/assets/131479022/b120400a-e5d7-4a3b-8d6e-783b25935d5e)
![IMG_7881](https://github.com/MarlinFirmware/Marlin/assets/131479022/bc301242-acdd-41ae-a77d-da9040a199e7)

**Comment by JaxGM** [comment]
I'd thought I'd share the entirety of my research in the hopes this helps someone else. The issue seams to be from the screen being of a different variety. This issue is not localized to to this exact models; the [Ender 3 v2 has a similar issue](https://www.reddit.com/r/MarlinFirmware/comments/xjz9vz/glitched_marlin_ui_when_compiling_for_ender_3_v2/) of a seemingly similar root.

If you want to revert back to the original Creality firmware for the Ender 3 v2 NEO, here they are: (I, admittedly, have done this a few time myself)

- https://www.creality.com/pages/download-ender-3-v2-neo
- https://www.reddit.com/r/ender3v2/comments/ur1ew9/dacai_screen_stock_firmware/

**Comment by JaxGM** [comment]
Inseam to have found a solution! Thanks to the amazing u/Soneliem on Redit, I have learned that the Pro firmware by mriscoc on GitHub should solve the problem. [Github Link](https://github.com/mriscoc/Ender3V2S1) | [Redit Link](https://www.reddit.com/r/ender3v2/comments/14sh1zp/marlin_dacai_screen_bug/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=1&utm_term=1)

Let me know if this works for anyone else here! Best of luck to all of you!

**Comment by HyperDX** [comment]
Thanks! This firmware works flawlessly. All icons and texts are visible :).
