### ISSUE TITLE
ENDSTOP_INTERRUPTS_FEATURE breaks BLTouch on Creality boards, possibly all STM32

### ISSUE THREAD

**Issue by EvilGremlin** [MarlinFirmware/Marlin#25747]
z_min_probe is stuck triggered with interripts, i think it's better to disable them at least for creality boards (including dropins)

**Comment by thisiskeithb** [comment]
How many reports have we seen with this issue? Were they using genuine BLTouches or clones?

**Comment by EvilGremlin** [comment]
Couple so far, one in dicsord, other in local forum. Clone or not doesnt matter - it fails in force_sw too. Fixing configs should be stopgap until someone get to actual issue

**Comment by ellensp** [comment]
From a user that just disabled ENDSTOP_INTERRRUTS and it started to work
"its a ender 3 pro, stock mobo, 4.2.2, 256k i think? though it may be 512k but im flashing with 256k anyways because i got it recently. BLTouch is plugged into the BL Touch port on the mobo"
BLTOUCH looks genuine

**Comment by thisiskeithb** [comment]
> it fails in force_sw too

Something is really broken if `BLTOUCH_FORCE_SW_MODE` is now causing BLTouches to fail.

**Comment by EvilGremlin** [comment]
??? 
it doesn't

**Comment by silycr** [comment]
Using Z_Min Endstop with 3dTouch on Tronxy X5S-2e stock board (Chitu cxy-v5-180409) STM32F1. Works both EN and DISABLED `ENDSTOP_INTERRRUPTS` 
EN `BLTOUCH_FORCE_SW_MODE` can not detect 3dTouch. DISABLED can be sensed. Possible 3DTouch issue. Will test with genuine BLTouch Classic.

**Comment by bellertm1** [comment]
Hardware: Ender3 Pro and Ender5 Pro, Official Creality BLTouch and STM32F103RE 4.2.7 board
Software: tried 2.1.X Bugfix,   Release 2.1.1,  and 2.0.9.5 all with 512 Flash 
Settings Tried and Adjusted:
- #define BLTOUCH_FORCE_SW_MODE
AND
- #define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
AND
- // Force the use of the probe for Z-axis homing
  #define USE_PROBE_FOR_Z_HOMING
AND
 - The BLTouch probe uses a Hall effect sensor and emulates a servo. */
#define BLTOUCH
AND
//#define ENDSTOP_INTERRUPTS_FEATURE

Have tried every variation with same result - after homing, Bed & Extruder heat up and print time shows in progress through completion and Extruder never moves (EEPROM_CHITCHAT shows "Stopped"). Prints reliably as long as BLTouch is not enabled (same for Ender 3 Pro and Ender 5 Pro with same hardware configurations.

**Comment by EM-III** [comment]
My Genuine BLTouch 3.1 plugged into the BLTouch port on my 4.2.2 creality board worked fine with 1.9.x. I struggled upgrading to 2.1.x. The BLToouch seemed to work but Z kept offsetting more and more. After hours of searching fixes that didn't work I discovered if I commented out, i.e.  //#define USE_ZMIN_PLUG then the BLTouch worked and the z-offset didn't change.

**Comment by thinkyhead** [comment]
> I discovered if I commented out `USE_ZMIN_PLUG` then the BLTouch worked…

When `USE_ZMIN_PLUG` is enabled and `Z_HOME_DIR` is set to -1, it's possible that the `Z_MIN_PIN` is being monitored, even when `Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN` is disabled and `USE_PROBE_FOR_Z_HOMING` is enabled.

It may also be possible that `USE_ZMIN_PLUG` combined with `ENDSTOP_INTERRUPTS_FEATURE` causes the pin interrupt to be inappropriately enabled.

So we should look at the way these settings all interact in the current codebase and figure out where the problem is.

What is your combination of these settings @EM-III ?

**Comment by thinkyhead** [comment]
I think I may have patched your issue @EM-III … But, we still need to investigate the cause of the original issue, if that didn't also get solved by the latest endstops patch.

So if anyone has the ability to test the latest code to see if the BLTouch / STM32 / Endstop Interrupt conflict is still happening, we can start to delve into that and consider possible causes. Generally this kind of issue involves a timer or interrupt conflict, so that would be my first area of inquiry. I have a couple of spare BLTouch probes and some loose STM32 boards, so I can hook up an ST-Link and get down with some direct debugging, if the issue isn't clear just by looking at the datasheets and our endstop interrupt code.

I have other tasks to deal with today, but we can start gathering information. First, does the issue still exist? And, what are the steps to reproduce it? …preferably with one of the boards I have handy here. Of course, the larger question is whether it's an unavoidable conflict, so endstop interrupts just have to remain disabled, or is it actually solvable?

So, let's gather all the data we can about which pins and timers and interrupts are involved, and then we'll be at a good starting point to start into testing, experiments, and debugging.

**Comment by EM-III** [comment]
> What is your combination of these settings @EM-III ?

```cpp
//#define USE_ZMIN_PLUG
#define Z_HOME_DIR -1
#define Z_MIN_PROBE_PIN PB1 <-- BLTouch 3.1 is plugged into the 5 pin port on the 4.2.2 board.
//#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
#define USE_PROBE_FOR_Z_HOMING
//#define ENDSTOP_INTERRUPTS_FEATURE
```

**Comment by EvilGremlin** [comment]
Sounds like return of that dumb bug with preprocessor going blind.

**Comment by thisiskeithb** [comment]
> Sounds like return of that dumb bug with preprocessor going blind.

I remember trying to track this down and could never confirm that it was a real issue.

...Or it was a very short-lived bug.

I enable `ENDSTOP_INTERRUPTS_FEATURE` where I can on my builds / forks that I support and it seems to work fine without causing issues, but I may not be running the perfect set of hardware to reproduce it.

**Comment by thinkyhead** [comment]
I suspect this is all set and can likely be closed.
