### ISSUE TITLE
[BUG] Laser Menu not working when LASER_SAFETY_TIMEOUT_MS is enabled

### ISSUE THREAD

**Issue by Fusseldieb** [MarlinFirmware/Marlin#26013]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When LASER_SAFETY_TIMEOUT_MS is enabled, the laser does **not** fire in the Laser Menu using the LCD. It doesn't matter which value is set. Commenting LASER_SAFETY_TIMEOUT_MS out makes it work normally again.

### Bug Timeline

Since LASER_SAFETY_TIMEOUT_MS was introduced, others do report the same

### Expected behavior

Laser should fire.

### Actual behavior

Laser doesn't fire. Actually, it seems to trigger the PWM pin ever so slightly since the "LASER" LED on the PSU itself lights up, but it doesn't burn ANYTHING at all.

### Steps to Reproduce

1. Reference the machine XY as you would normally
2. Go into the LCD Menu and choose "Laser Menu"
3. Choose "Fire laser". It will trigger the PWM ever so slightly but nothing is being burned.

### Version of Marlin Firmware

Marlin 2.1.2.1

### Printer model

Custom "K60" Laser

### Electronics

SKR 1.4 Turbo, Fysetc 12864 Mini LCD

### Add-ons

-

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

For the time being, I'll leave the "feature" disabled (commented out).

**Comment by cbagwell** [comment]
Same issue extends to using software such as Lightburn and the Focus button to turn on the diode laser while focusing.  It shuts off because of safety timeout without movement.

If we wanted to be more GRBL-like in this case, we would disable the safety feature while in "M3 I" mode.  Thats what mode Lightburn goes into when focusing (well, just M3 on GRBL).  

And of course we could also temp disable safety feature for the duration the laser toggle menu lasts.

I disabled the safety feature for same reason.
