### ISSUE TITLE
Sainsmart 2004 I2C LCD line break

### ISSUE THREAD

**Issue by borisz94** [MarlinFirmware/Marlin#26287]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Sainsmart 2004 I2C LCD line break not correct. Long lines overflow and move to other places on the display (images). This happens in all languages.

### Version of Marlin Firmware

Marlin 2.1.x bugfix

### Electronics

Megatronics V2.0

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Images.zip](https://github.com/MarlinFirmware/Marlin/files/12641317/Images.zip)
[configuration files.zip](https://github.com/MarlinFirmware/Marlin/files/12641318/configuration.files.zip)

**Comment by ellensp** [comment]
Himm...  this seems rather similar to https://github.com/MarlinFirmware/Marlin/issues/26148 
 which was meant to be fixed with https://github.com/MarlinFirmware/Marlin/pull/26154

Images from images.zip
![1694886338343](https://github.com/MarlinFirmware/Marlin/assets/530024/c6f06216-4ea9-4b69-a8d0-43e7138302e8)

![1694886338351](https://github.com/MarlinFirmware/Marlin/assets/530024/40299e17-cade-4f92-bb73-82ff3496a3bd)

![1694886338356](https://github.com/MarlinFirmware/Marlin/assets/530024/fa1a986a-6a2c-4f3a-b65b-18a42bf4ccb3)

![1694886338362](https://github.com/MarlinFirmware/Marlin/assets/530024/80632f19-a901-4f8c-8fd2-9c8bbed8cee4)

**Comment by ellensp** [comment]
These error does not seem to be happening in current bugfix
Update your bugfix code and try again.

**Comment by thisiskeithb** [comment]
> which was meant to be fixed with #26264

You had it right the first time 😄 This was fixed in https://github.com/MarlinFirmware/Marlin/pull/26154.

https://github.com/MarlinFirmware/Marlin/pull/26264 is a PR for `.editorconfig` changes.

**Comment by ellensp** [comment]
fixed failed cut and paste.

**Comment by borisz94** [comment]
Thanks.  The new version really solved the problem.  Sorry for the new bug report, but I couldn't find the solution in the search engine.
