### ISSUE TITLE
[BUG] Blank screen with Hybrid Threshold

### ISSUE THREAD

**Issue by jokingradio** [MarlinFirmware/Marlin#26384]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When Hybrid Threshold is enabled my screen stock on blue screen when disable everything work /skr3 tmc 2209ez  lcd 2004A /bugfix-2.1.x

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

prusa mk2.5 (X and printhead bear)

### Electronics

skr 3

### Add-ons

tmc 2209

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[config.zip](https://github.com/MarlinFirmware/Marlin/files/13229937/config.zip)

**Comment by thisiskeithb** [comment]
Some comments after reviewing your config:

- Disable `MK3_FAN_PINS` since that doesn't do anything on the SKR 3.
- Disable `SOFTWARE_DRIVER_ENABLE` since there are dedicated Enable pins on the SKR 3.
- Change the `*_RSENSE` values to `0.11` since `0.22` are specific to the Einsy Rambo this config was originally setup for for.
