### ISSUE TITLE
[BUG] (Z OFFSET not responding)

### ISSUE THREAD

**Issue by kbritt02** [MarlinFirmware/Marlin#26766]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I'm running a CR touch on an Ender 3. I have an upgraded board 4.2.7. I wanted to add more mesh points and upgraded Marlin to Marlin-bugfix-2.1.x I'm now having an issue with the Z probe being set not working. It is not adjusting at all. I tried saving and reloading as well as tuning while printing, and nothing seems to fix this. Do you have any suggestions on a fix?

### Version of Marlin Firmware

Marlin-bugfix-2.1.x

### Printer model

Ender-3 

### Electronics

board 4.2.7

### Other add-ons

CR Touch

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/14151781/Configuration.zip)

**Comment by steljwagh** [comment]
I have the exact same 4.2.7 board and I just installed the lastest fw. Can you give more details about the steps you follow in the menu? Because my z-offset settings are working fine from the prepare / z-offset menu.

I have however an issue after automatic leveling, the printer gets stuck in the menu without saving the new mesh. I'll investigate later and maybe open a bug for that.

**Comment by kbritt02** [comment]
The first thing I did after flashing was to auto-home the Z-axis and activate the probe. Then, I jogged the Z-axis until it initiated and further jogged it until the nozzle touched the paper placed under it and had a little resistance. I recorded the number and inputted it in the Z-probe offset and saved it. Next, I initiated a bed level process and tried to print. However, I noticed that the printer was about 10mm off the printer bed. I tried to adjust the Z-axis with babysteps until the proper squish was there, but the Z-axis did not respond to any adjustment.

**Comment by steljwagh** [comment]
I have no issues at all with the latest firmware, just flashed the latest firmware.

Setup z-offset, with use of all possible resources in the menu.
Did a bed-level (although I had to do it from octoprint, because bedleveling doesn't save from printer menu anymroe)
Started print and tried to alter z-offset from tuning menu (working)

Are you sure your gcode is not messing with your printer settings?

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
