### ISSUE TITLE
[BUG] SD Card is detected but doesn't start printing or heating

### ISSUE THREAD

**Issue by Hydra99o** [MarlinFirmware/Marlin#26913]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I've flashed the latest marlin bugfix 2.1.x to my ANYCUBIC CHIRON, when i try to start a print via SD card using the lcd menu i can see the files in the SD card files menu , after selecting a file it takes me to the status screen as usual but it doesn't do anything, it shows the file name but wont start printing
Note: It prints fine with USB and i can also start a print from SD card using Pronterface the problem only occurs when trying to print using the stock Chiron LCD 
Also in Pronterface log it says SD Card ok "echo:SD card ok"
this bug doesn't exist in previous versions of marlin 

### Bug Timeline

NEW BUG

### Expected behavior

I expect it to start heating and printing after selecting a file form the menu 

### Actual behavior

it wont start printing

### Version of Marlin Firmware

Bugfix 2.1.x

### Printer model

Anycubic Chiron

### Electronics

stock Trigorilla_14

### LCD/Controller

ANYCUBIC LCD CHIRON

### Other add-ons

no add-ons except a direct drive extruder 

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

### Host Software

Pronterface

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/14760774/Configuration_adv.zip)

**Comment by mechano** [comment]
Yes same as mine, with Kingroon machines with Kingroon 1.3 board. It's an MKS Robin Nano 1.2 clone with GD32F303 chip.

**Comment by Matsavol** [comment]
I'm having similar symptoms on my Longer LK1 running on bugfix-2.1.x fimware 5/23/2024. Here are some interesting details I have noticed:
- I'm using the TFT_COLOR_UI. (In case UI has something to do with this.)
- Firmware compiled with VS Code using STM32F103VE_longer environment.
- If SD card is inserted when turning on the printer Marlin boots up and I can browse the files on SD card . Trying to start the print from SD card fails. Going back to SD card file list shows a corrupted list. Releasing and attaching media fixes the file system but I still cannot start the print.
- If SD card is inserted when when turning on printer and first thing I do is Refreshed file list I can start print from SD card normally.
- If the print had failed to start it can be fixed with following sequence: Release media, Attach media, Refresh file list and then print can start normally. (Key here is that I must do the Refresh file list, even when the file list did show up correctly without it.)
- If printer is turned on without SD card and later on SD card is inserted and media attached print starts normally from SD card without need to Refresh file list.
- If print had failed to start, removing SD card and trying to refresh file list without SD card shows empty file list. After inserting SD card back and Attach media file list gets populated correctly. Print fails to start unless Refresh file list was performed before selecting the file to start print. 
- The "#define ONBOARD_SDIO" must be added to Configuration.h file. Without it Marlin crashes and goes to boot loop during power up. This happens only if compiled without "maple" environment. (With "maple" environment boot loop doesn't happen but there are some other issues with stepper motor control during printing that it is not an option.)

**Comment by SMH17** [comment]
This bug is still present. This issue should be reopened.

**Comment by carloslockward** [comment]
Im experiencing this bug aswell. Kingroon KP3S with Marlin compiled from the tagged `2.1.2.4` release. Please re-open.

**Comment by SMH17** [comment]
If you use FSCM and an STM32 based motherboard the issue may be caused by [this ](https://github.com/MarlinFirmware/Marlin/issues/27460).
