### ISSUE TITLE
[BUG] Negative Z_MIN_POS Setting with Auto-Leveling Causing Part Thickness/Z-Height Too Large

### ISSUE THREAD

**Issue by Platypidus** [MarlinFirmware/Marlin#26932]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

If the Z_MIN_POS setting (under travel limits after homing category, line 1706) is set to a negative value (eg. -1), this negative value is essentially added to the total thickness of your part in the Z-Axis. The problem is only present with auto-bed leveling (mesh) enabled. I have often set this value to -1 since I assumed it would simply allow me to move the nozzle slightly below the bed surface, which can be useful at times. If there is an intentional link between this Z_MIN_POS variable and the Z-height of the printed part, this should at least be clarified, but it really seems like a bug. I fixed the issue by reverting to the default 0.

### Bug Timeline

I noticed this same issue several years ago on older Marlin versions.

### Expected behavior

I expected setting Z_MIN_POS to -1 in the firmware would simply allow me to manually, or in custom g-code, move the print head slightly below the bed surface. I expected parts to still be printed starting from a z-height of 0...

### Actual behavior

I was able to move the nozzle below the bed surface, but with auto bed leveling enabled, it also caused my parts to be 1 mm too thick. At first I thought I had my Z steps/mm incorrect. When I corrected the steps/mm for this issue, my parts were too thin under a certain height, and too thick over a certain height - due to it simply being offset by 1 mm.

### Steps to Reproduce

1) Set Z_MIN_POS (code line 1706 in Marlin 2.1.2.1 configuration.h file) to -1 instead of default 0.
2) Enable auto-bed-leveling (I think any type, but I use Bilinear auto-bed leveling.
3) Print part and observe that the thickness in the Z-Axis is ~1 mm thicker than the gcode asked for.

### Version of Marlin Firmware

Marlin 2.1.2.1

### Printer model

Creality Ender 3 S1 Plus

### Electronics

stock

### LCD/Controller

LCD from Ender 3 S1 non-plus (non-touch)

### Other add-ons

none

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin_2.1.2.1_Config_Files.zip](https://github.com/MarlinFirmware/Marlin/files/14847729/Marlin_2.1.2.1_Config_Files.zip)

**Comment by thisiskeithb** [comment]
If you want to move below Z min, disable `MIN_SOFTWARE_ENDSTOP_Z` instead of setting a negative `Z_MIN_POS`.

<hr>

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
