### ISSUE TITLE
[BUG] (Bltouch probing in the same spot nomater the NOZZLE TO PROBE OFFSET

### ISSUE THREAD

**Issue by PDynia26** [MarlinFirmware/Marlin#27462]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Hi, I have a problem that no matter what I change in NOZZLE_TO_PROBE_OFFSET no matter if its { 0, 0, 0 }, or { -48, -4, 0 }, or { 4, 67, 0 } when I load it to my printer and start auto homing it keeps homing the the same spot far to the right, when I want it to probe in the middle. Am I doing something wrong ? I will attach Configuration.h and Configuration_adv.h files

### Version of Marlin Firmware

2.1.2.4

### Printer model

Ender 3

### Electronics

SKR MINI E3 V3.0

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/user-attachments/files/17285145/Marlin.zip)
Configuration.h and Configuration_adv.h

**Comment by ellensp** [comment]
NOZZLE_TO_PROBE_OFFSETis saved to eeprom on first start
Any additional changes to NOZZLE_TO_PROBE_OFFSET in Configuration.h are ignored

You have to force an eeprom update  using gcode or a display
Or enable EEPROM_INIT_NOW  so that every time you upload the eeprom is reset to Config files

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
