### ISSUE TITLE
Russia has banned and blocked Discord:    Russian users can get top priority by posting in this thread.

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#27465]
Discord is Marlin's primary user support mechanism.     Because Russia has banned and blocked Discord within Russia, all of our Russian users are left with no support.

I don't expect we will get many problems reported by our Russian users.  After all...   They are a very smart and independent bunch of people.     But with that said...

If you are Russian....   And you need help with a Marlin issue....     Please post your problem here.   I will make sure it gets the attention it deserves.

**Comment by thisiskeithb** [comment]
I don't think we need a dedicated Issue for this since we have several other resources for users including places to ask for help:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube

Similar to users in China, Russians are using VPNs to get around blocks and can still access Discord.

**Comment by Roxy-3D** [comment]
Ok...    Especially with the links you just provided, it won't be too hard for the affected users to find support.   

Thank You for the links!

**Comment by thisiskeithb** [comment]
Support links are also available in the README: https://github.com/MarlinFirmware/Marlin?tab=readme-ov-file#marlin-support
