### ISSUE TITLE
Thermal runaway : Upgraded to 1.1.0 RC3 from ~6 months older version.

### ISSUE THREAD

**Issue by AndKe** [MarlinFirmware/Marlin#2840]
My bed bottom-insulated 30x30cm aluminium is heated by ~140W  a while after heating up , the temperature is allowed to dip, and the sluggish heating takes some time, more than the default
THERMAL_PROTECTION_BED_PERIOD = 20
so it trigged thermal runaway.
this was regardless using (tuned) PID's or no PID.
I increased it from (unrealistic for my setup) 20s  - to 120s  - maybe you should consider a higher default.

**Comment by thinkyhead** [comment]
Sounds like a good idea, though probably 120 seconds would be too far the other way for a default. (The defaults are meant for your average 12V 20x20 bed.)

Meanwhile, if your bed's temperature is falling after initial heating and remaining below temperature for _over 20 seconds_, you might also try increasing your `THERMAL_PROTECTION_BED_HYSTERESIS` to give a little more room for the initial dip. You could also play with `BED_LIMIT_SWITCHING` and `BED_HYSTERESIS` to try and change the margin where bed heating enables/disables. Another option, `MAX_BED_POWER` might also benefit from adjustment. Instead of heating the bed so fast that it overshoots and cools, lowering the bed power may actually get you closer to the target, even though initially it heats more slowly.

Ideally, you want to keep tuning parameters until that 20 second margin for `THERMAL_PROTECTION_BED_PERIOD` is a realistic prospect.
