### ISSUE TITLE
[FR] Endstop self-test at startup

### ISSUE THREAD

**Issue by AnHardt** [MarlinFirmware/Marlin#2947]
Add a endstop selftest during startup.
Throw an error if the endstops at both ends of an axis are triggered at the same time.
If an endstop, not probe, is triggered, back up a few mm to see if it's untriggered then - if not, throw an error.

**Comment by KiteLab** [comment]
#2965

**Comment by bradanlane** [comment]
Thanks for linking to the existing FR. I didn't see that when I did a quick search. Feel free to close this issue as a duplicate.

**Comment by thinkyhead** [comment]
I will see about integrating this concept pretty soon. There might be complications to work out, such as which direction to "back off" when you don't know which end you're at.

**Comment by AnHardt** [comment]
@thinkyhead 
Have you had a look into https://github.com/AnHardt/Marlin/pull/15?
if min- and max- endstops are mounted in parallel to the same pin it's cought by a construct like

```
+   #if HAS_X_MIN && HAS_X_MAX
+      if ((READ(X_MIN_PIN)^X_MIN_ENDSTOP_INVERTING) && (READ(X_MAX_PIN)^X_MAX_ENDSTOP_INVERTING)) {
+        endstop_test_error('X');
+      }
+    #endif
```

before any movement starts.

When all endstops are connected to the same pin, but only one per axis, we don't know what axis to move to free the endsop.

In that (rare?) case, do not activate the test.

Maybe the description (https://github.com/AnHardt/Marlin/pull/15/files#diff-8270513bcf2a548cd418cdfe123f27d3R348) can be further improved.

**Comment by thinkyhead** [comment]
I will look more closely at your number fifteen. But of course, after the release. (I sound just like a broken record.)

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.

**Comment by AnHardt** [comment]
@jbrazio 
Super idea to direct feature requests to MarkinDev the day it is discussed to remove the repository (#3656). Please reopen.

**Comment by jbrazio** [comment]
@AnHardt we have to work with the tools in place, issues have being closed for a couple of weeks now, all of them with the same message.

**Comment by AnHardt** [comment]
@jbrazio 
But the situation has clanged today (#3656). And now you are touching my FRs, so i have a right to complain.

**Comment by boelle** [comment]
should this not be closed with remark that the feature should be submitted as a PR from the OP ?

**Comment by thinkyhead** [comment]
I do love this idea. It should be in 1.1.1, at least. In the meantime I will do my usual thing, grab the original branch, rebase onto the latest code, clean it up a bit, and post a PR as a placeholder with "Don't Merge" tagged on it where we can discuss the Exhibit A.

**Comment by jbrazio** [comment]
Maybe a bit more fancy..

I would suggest this: When doing a `G28` the endstop trigger values are stored in EEPROM, when booting if the current endstop status is in a triggered state the robot gives a warn to the user that something maybe wrong and ask click to continue.

Because when booting the robot can be already homed, thus the user will click to confirm everything is ok.

Every time we `G28` the triggers are saved using `eeprom_update()` instead of `eeprom_write()`, `update()` only writes to the address if the byte being written is different from the one stored.

@AnHardt @thinkyhead what do you think ?

**Comment by thinkyhead** [comment]
I tend to favor the simplest approach with the least code/storage required – thinking of those 64M boards. That would be an endstop self-test at startup that throws an error message and calls `kill()`. It won't catch every endstop mis-configuration, necessarily. It would have been especially useful to catch instances where `DISABLE_MIN_ENDSTOPS`/`DISABLE_MAX_ENDSTOPS` were wrong, but now that those settings are gone it will mainly catch instances where the INVERTING or PULLUPS settings are wrong.

I suppose the test could be added to the main endstop-updating function, rather than `G28` in particular, and rather than just being a startup test.

**Comment by bradanlane** [comment]
The simple case I've encountered more than once is having both MIN and MAX Z report "closed". 

This happens wihh the delta printers when a wire breaks on a Z-probe mounted to the effector. With all of the motion of the effector it can be easy to break a wire. This results in the Z-min reporting "closed". G28 will move until Z-max is "closed". Then G29 will attempt to auto-level the bed and both are reporting closed and bad things happen.

**Comment by thinkyhead** [comment]
@bradanlane Well with the new configuration, endstop plugs that you're not using will just be ignored and treated as open. And the Z probe will also be ignored when not in use. (Plus, the probe is not treated as an endstop on deltas anyway.)

**Comment by bradanlane** [comment]
I may not have been clear. With some of the delta printers, the Z-probe wires run right to the effector. Therefore there is are two Z endstop - one each for min and max. If the wire breaks at the effector, then there is a condition where both min and max report "closed" for the Z axis.

**Comment by thinkyhead** [comment]
@bradanlane Marlin won't treat the wires connected to "min" as an endstop if you configure it as a probe. But I get your point. If the probe and any max endstop is triggered, that's bad on a delta. So we should include probes in the self-testing.

**Comment by boelle** [comment]
+1 for this one

**Comment by thinkyhead** [comment]
It will certainly help to abort bed probing when the probe is found to be triggered at unexpected times, such as just before starting the probe. I keep running into this in my development on the MakerArm prototype, whose probe is triggered when retracted.

**Comment by AnHardt** [comment]
Just use and/or extend '_TRIGGERED_WHEN_STOWED_TEST'

**Comment by thinkyhead** [comment]
Maybe. Allow me to describe. This is a case where the probe must be deployed manually. If it hasn't been unscrewed then it sits in a position where an opto endstop is triggered. Thus, when you do `G28 Z` or `G29` it immediately assumes it has hit the bed. In the case of `G29` it keeps raising the Z axis by the 'clearance' distance at every point.

Since this probe can't deploy or stow on its own, I'm not sure the "triggered-when-stowed" test is appropriate. There's no "deploy" or "stow" for it. And also, the test I'm proposing would apply universally — to every type of probe. If any probe is triggered before the probe move even begins the procedure should abort. So it needs to do a direct test of the appropriate pin.

I'm thinking, at the start of `probe_pt` would be the best place to test it.

**Comment by AnHardt** [comment]
Prepared a test. #5229 
Maybe kill() is a bit to hard reaction? 
It's a serious configuration error if the probe is triggered then.

**Comment by thinkyhead** [comment]
@AnHardt Oh, gosh, no, I don't want to see a `kill()`, but `G29` should abort.

**Comment by boelle** [comment]
@thinkyhead maybe put this on the 1.1.1 milestone?

seems like a good feature

**Comment by slowbro** [comment]
Is this solved by `VALIDATE_HOMING_ENDSTOPS` (https://github.com/MarlinFirmware/Marlin/pull/11912) or `DETECT_BROKEN_ENDSTOP` (https://github.com/MarlinFirmware/Marlin/pull/18424)?
