### ISSUE TITLE
Improvement: Get rid of the numerous number to string conversions

### ISSUE THREAD

**Issue by AnHardt** [MarlinFirmware/Marlin#2955]
Get rid of the numerous number to string conversions.
All together they now use a lot of memory. itoa(), ltoa(), dtostrf() with a bit of wrapping do the same, using less space and are not slower than the most of the now used functions.
A consistent naming also would be a big step forward.

**Comment by thinkyhead** [comment]
One tip I heard recently for best AVR performance is to make your own number-to-string functions. So I think we probably get some benefit from them. But yeah, we don't really need so many, do we?

So, we will first need to audit all the code that calls (or uses) these functions. Then decide which of them can be combined and made simpler.

I noticed that in some firmware — most notably **Matt Roberts' RepRap Firmware** — the code avoids using `float` values as much as possible. The GCode parser even stores all float parameters in `long` values (simply multiplying by 10000 to maintain 5 digits to the right of the decimal). Then it converts these values only as needed.

Meanwhile, the GCode parser in that firmware also smartly gets all parameters first as it scans the input, instead of calling `strchr` repeatedly. I'm sure it outperforms the parser in Marlin by an appreciable factor.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
