### ISSUE TITLE
Speed relative extrusion rates?

### ISSUE THREAD

**Issue by bradanlane** [MarlinFirmware/Marlin#2999]
While investigating an under extrusion issue on my printer, I found the following research:

http://www.extrudable.me/2013/04/18/exploring-extrusion-variability-and-limits/

It nearly perfectly describes my issue.

In summary, it states that "**under extrusion increases with print speed**."

This may be something to consider for Marlin. Then again, if this is wandering into the "over-reaching" territory, it may be better left to post processing.

Thoughts?

**Comment by Sungod3000** [comment]
its an excellent test, that should be replicated more often. 
im having issues with these underextrusion patterns as well. it mostly shows on top level infill when the lines are thicker towards the perimeter when the print speed slows down and the pressure builds up.

im not sure that if marlin is the place for that to be corrected especially since some slicers (slic3r, craftware) are implementing features that take this pressure build up into account.

i recently bought the bondtec extruder which reduced these patters quite a bit just by having more controll over the filament. but even with this there will always be pressure build up at some speeds.

**Comment by thinkyhead** [comment]
@bradanlane The `ADVANCE` feature is supposed to obviate this issue, but from what I have heard it's not working right now. Fixing `ADVANCE` is a big item on my list. Currently gathering information to make sure I fully understand the concept and the code.

Meanwhile, have you tried the "ADVANCE" feature in the latest Slic3r? It accomplishes in GCode what Marlin tries to do in real-time.

**Comment by bradanlane** [comment]
Re: Slic3r

I had undesirable results with slic3r for a number of the prints I've had to work on so I've been bouncing from KISSlicer to Cura and now trying three more slicers. 

I was not clear on my ADVANCE would be setup so I took the kludge approach and just added a new thermistor profile. It worked well (even though I knew it would need to be re-applied with every update to Marlin).

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
