### ISSUE TITLE
Melzi board

### ISSUE THREAD

**Issue by JurgenNijrolder** [MarlinFirmware/Marlin#3020]
I connected a Melzi board. with th old software from 2011 everything was almost perfect, bur wir
th thenew sofstware it looks like the pright pin-numbers are not compiled..i selected the melzi board in the file "Marlin"

the led is not blinking, the temperature's show 0 graden ( i selected sensor 6 ). and nothing is moving.

I think it is a small problem, but I didn't find it.

please someone help.

greetings. jurgen

**Comment by thinkyhead** [comment]
I'm not sure when support for Melzi was formally added to Marlin. But there have been very few changes needed in a long time. Usually that indicates that a pins file is in good shape. But maybe Melzi hasn't been getting enough testing with Marlin.

If you're using the latest stable release, 1.0.2-1, you should select the board using this line in `Configuration.h`:

``` cpp
#define MOTHERBOARD BOARD_MELZI
```

…or…

``` cpp
#define MOTHERBOARD BOARD_MELZI_MAKR3D
```

Did you also update your configuration files? It may be easier to start with fresh configuration files from the 1.0.2-1 release, then make the same modifications from your old configurations.

if you were thinking of picking up one of the release candidates, I would recommend waiting for `1.1.0-RC4` (or using `RCBugFix`), only because there are still a few annoying bugs in `RC3` that need to be patched.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
