### ISSUE TITLE
Watchdog function on GT2560

### ISSUE THREAD

**Issue by valdemar4eg** [MarlinFirmware/Marlin#3032]
Dear all,
Could somebody, please, explain in more details how does WATCHDOG works on geeetech gt2560 (mix on Arduino Mega 2560)? My printer quite often crashes in the middle of the print with all heaters on. So I would like to use all safety features available on Marlin.

These comments in the code are not clear to me.

``` cpp
#ifdef USE_WATCHDOG
// If you have a watchdog reboot in an ArduinoMega2560 then the device will hang forever, as a watchdog reset will leave the watchdog on.
// The "WATCHDOG_RESET_MANUAL" goes around this by not using the hardware reset.
// However, THIS FEATURE IS UNSAFE!, as it will only work if interrupts are disabled. And the code could hang in an interrupt routine with interrupts disabled.
//#define WATCHDOG_RESET_MANUAL
#endif
```

Thank you in advance

**Comment by thinkyhead** [comment]
I think the comments try to explain too much, and aren't very helpful.

I suggest using `USE_WATCHDOG` as a general safety feature, so Marlin can reset the machine if the Arduino hangs for any reason. `WATCHDOG_RESET_MANUAL` is an alternative method to catch a hang condition, that won't reset the machine but just leave it frozen until manually reset.

The AVR manuals state that the built-in watchdog timer is not necessarily reset when you reboot the board. For this reason, under some conditions the Arduino could keep rebooting repeatedly. This really depends on the code that the Arduino is running. Marlin calls `wdt_reset` frequently, so there's no reason for Marlin to keep rebooting due to this feature unless something is very wrong.

The alternative method, `WATCHDOG_RESET_MANUAL`, uses a custom interrupt routine to catch a hung condition. As long as Marlin keeps calling `wdt_reset` the interrupt will never fire. But if anything goes wrong, after 4 seconds Marlin will try to invoke `kill` and turn off the heaters.

**Comment by thinkyhead** [comment]
P.S., I suggest you try `RCBugFix` to get the most reliable performance right now. Perhaps you can try doing a long print and see how it does. The Arduino shouldn't hang at all, of course, so that's what we want to mainly avoid. Check for loose connections, as always. If the board does hang, hopefully in the latest code it can at least turn off the heaters before it gives up the ghost.

**Comment by Blue-Marlin** [comment]
> The alternative method, WATCHDOG_RESET_MANUAL, uses a custom interrupt routine to catch a hung condition. As long as Marlin keeps calling wdt_reset the interrupt will never fire. But if anything goes wrong, after 4 seconds Marlin will try to invoke kill and turn off the heaters.

If the hung is not in an interrupt. What is the problem with WATCHDOG_RESET_MANUAL.
Never. Never! Never define WATCHDOG_RESET_MANUAL!

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
