### ISSUE TITLE
Printing client

### ISSUE THREAD

**Issue by NervenCid** [MarlinFirmware/Marlin#3145]
Hello:

I'm new on github, and i making my thesis project on 3d printing, i want to understand how marlin comunicates, send a receive to the clients...

Where can i find documentation about this?

Thank you

**Comment by jbrazio** [comment]
Marlin uses serial protocol and [g-code](http://reprap.org/wiki/G-code).

**Comment by Roxy-3D** [comment]
> Where can i find documentation about this?

We don't have as good of documentation as we should (or want to) have.   But that issue aside....

The source code is the ultimate documentation.  It defines EXACTLY what the behavior is going to be.  Can you read C code?  If so,  you can dig in.

**Comment by NervenCid** [comment]
Hello again:

Thank you for your answers, i have been reading about G-code, and i know that this code is what the arduino really receives from the client (i guess), i have been exploring some source files of the firmware but i couldn't find the file which is responsible of the serial comunication.

Thank you

**Comment by Blue-Marlin** [comment]
loop() https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/Marlin_main.cpp#L736
get_command() https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/Marlin_main.cpp#L794
process_next_command() https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/Marlin_main.cpp#L5662

**Comment by thinkyhead** [comment]
The protocol between a host and Marlin (or any firmware) is pretty straightforward. The host sends GCode as plain text, each command a single line. Marlin replies "ok" as soon as it processes the command. Marlin may send other replies that hosts can use. Those aren't documented well, but all the firmware out there has to send the same replies. The language.h file in Marlin includes almost all the messages that Marlin sends.

Hosts may send extra information on each command line during a print session so that Marlin can do error checking and the host can re-send on error. See the bottom part of https://github.com/MarlinFirmware/Marlin/wiki/DNE-G-Code-in-Marlin for a description of the "N" and "*" parameters. The best place to find documentation on GCode and specific GCode commands is at http://reprap.org/wiki/gcode

**Comment by jbrazio** [comment]
@NervenCid if you feel your question has been answered please close this ticket.

**Comment by NervenCid** [comment]
Hello:

Thank you for your answers and sorry for my delays, i see that you don' t use delays in your code...

But for example in pseudocode if i send for example this:

serial.send("G1 X50 Y50;")

Marlin is capable for understand? or i need to send each character

and what is the format or data type in which Marlin receives/send data?

Thanks and sorry for my english

**Comment by jbrazio** [comment]
Marlin will understand because ";" is the start of a comment. A standard "move nozzle to XY" is just "G1 X10.5 Y5.3".

**Comment by jbrazio** [comment]
I understand your question, the final char is usually a `\n` for each command.

**Comment by NervenCid** [comment]
Thnak you for your answer...

I will try to work in that

I will close this issue, but: can i reopen it? or i must open a new one

**Comment by jbrazio** [comment]
If the topic is the same I would to keep this one open.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
