### ISSUE TITLE
Missing Chinese translation

### ISSUE THREAD

**Issue by jbrazio** [MarlinFirmware/Marlin#3350]
We need your contribution to translate the following missing messages:

``` cpp
#define MSG_BED_Z
#define MSG_ERR_MINTEMP_BED
#define MSG_HEATING_COMPLETE
#define MSG_BED_HEATING
#define MSG_BED_DONE
```

Have a look on the file [language_en.h](https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/language_en.h) for the original English translation.

**Comment by liangruiben** [comment]
```
#define  MSG_BED_Z             热床Z
#define  MSG_ERR_MINTEMP_BED   热床最小温度错误
#define  MSG_HEATING_COMPLETE  加热完毕
#define  MSG_BED_HEATING       加热热床
#define  MSG_BED_DONE          热床加热完毕 
```

**Comment by thinkyhead** [comment]
Also needed…

``` cpp
#define MSG_LEVEL_BED_HOMING                "Homing XYZ"
#define MSG_LEVEL_BED_WAITING               "Click to Begin"
#define MSG_LEVEL_BED_DONE                  "Leveling Done!"
#define MSG_LEVEL_BED_CANCEL                "Cancel"
. . .
#define MSG_HOME_OFFSETS_APPLIED            "Offsets applied"
```

**Comment by jbrazio** [comment]
@thinkyhead what is the encoding used by the LCD for CN chars ?

**Comment by AnHardt** [comment]
@jbrazio 
There is no. There is no way to map some thousand symbols to 128.  What we have is a very special selection of symbols mapped one by one to the strings.

**Comment by jbrazio** [comment]
Then this one will be a hard one to kill..
So you mean that hex values on the file is kinda of "custom mapping", nothing like big5 not utf8 ?

**Comment by jbrazio** [comment]
@AnHardt Then this one will be a hard one to kill..

**Comment by liangruiben** [comment]
``` cpp
#define MSG_LEVEL_BED_HOMING                "归位 XYZ"
#define MSG_LEVEL_BED_WAITING               "单击开始"  or 点击开始
#define MSG_LEVEL_BED_DONE                  "矫平完成!"  or 调平完成
#define MSG_LEVEL_BED_CANCEL                "取消"
. . .
#define MSG_HOME_OFFSETS_APPLIED            "偏移补尝"   or 应用偏移补尝
```

**Comment by jbrazio** [comment]
Thank you @liangruiben.
But we're having another issue, we do not have "all" the Chinese charset available on the LCD.

**Comment by liangruiben** [comment]
”全部“
I don't know how to help you.

**Comment by CONSULitAS** [comment]
@liangruiben 
please look at https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/language_cn.h#L36
- The characters/symbols used are from `DISPLAY_CHARSET_ISO10646_CN`.
- Find https://github.com/MarlinFirmware/Marlin/search?utf8=✓&q=DISPLAY_CHARSET_ISO10646_CN
- leads you to https://github.com/MarlinFirmware/Marlin/blob/cf9a171aa92a4f43f0f61309c7145e46233b1c7c/Marlin/dogm_lcd_implementation.h#L72
- https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/dogm_font_data_ISO10646_CN.h has all chinese characters Marlin knows
- You find https://github.com/MarlinFirmware/Marlin/tree/RC/Marlin/fonts with https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/fonts/ISO10646_CN.fon which contains the pictures.
- There is a batch for it in https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/fonts/make_fonts.bat
- read the realm

So we have to
- use a character defined in dogm_font_data_ISO10646_CN.h
- or define a new one in dogm_font_data_ISO10646_CN.h and use it then
  - paint with Fony.exe
  - save and create new `.h` file
  - use new character in language_cn.h
  - BUT:
    
    > Currently we are limited to 256 symbols per font.

Since we all can not read any chinese it is impossible for us to do this work. Sorry.

**Comment by liangruiben** [comment]
好的，明天我会尝试操作，现在我需要睡觉了，我这边的时间是早上4点
Ok, tomorrow I'll try to operation, I need to sleep now, the time is 4 o 'clock in the morning on my side

**Comment by liangruiben** [comment]
paint with Fony.exe
fony.exe那里可以下载，我用的是WINDOWS 7 X64
Fony. Exe can download there, I am using WINDOWS 7 X64

**Comment by CONSULitAS** [comment]
Please make a `>` before your citations. Tutorial: https://guides.github.com/features/mastering-markdown/

Fony should work on your system.

**Comment by liangruiben** [comment]
好的，没有问题，我会尽快给你弄好，请原谅我需要时间学习
Ok, no problem, I'll give you as soon as possible repair, please forgive me I need time to study

**Comment by jbrazio** [comment]
@liangruiben did you had any luck updating the language file ?

**Comment by liangruiben** [comment]
Where can I download Foxy.exe

**Comment by liangruiben** [comment]
OK, I found FONT.EXE downloaded

**Comment by Blue-Marlin** [comment]
Do you mean Fony.exe (http://hukka.ncn.fi/?fony) what was used for the fonts?

https://github.com/MarlinFirmware/Marlin/tree/RC/Marlin/fonts

**Comment by boelle** [comment]
So we are still stuck with missing china?

**Comment by Blue-Marlin** [comment]
No.
We are missing an update of the Chinese language files.

**Comment by Blue-Marlin** [comment]
Even that is not the full truth.
We got a PR 'UTF-8 language translation supports #4704' that would make updating the Chinese language files much easier and this includes an update of the Chinese language files.
But:
The result on the screen is currently too poor to consider a merge.
While simplifying the update for Chinese considerably, it complicates update process for all languages a bit.
It's outdated now.

**Comment by thinkyhead** [comment]
> It's outdated now.

…and @yhfudev has been too busy to follow up with patches.
We might just have to abandon that PR for the time being.

**Comment by yhfudev** [comment]
@thinkyhead The current UTF-8 patch is a big change into the source code, and the most changes are related to the language files which cause the problem of 'outdated'.

I would suggest a two-step merging for the UTF-8 patch if you need more time to consider the merging and avoiding the 'outdated' problem. That would be easier for the two branches to be merged later.

First step is to merge the language files, which won't impact the current source code, to be shared with two branches.

``` C++
// define a macro in the language_en.h
#define _UxGT(a) a
```

and

``` C++
// use _UxGT() to define the strings for all of utf-8 language files
#define WELCOME_MSG                         MACHINE_NAME _UxGT("已就绪.")  //" ready."
#define MSG_SD_INSERTED                     _UxGT("存储卡已插入")  //"Card inserted"
...
```

for those non-utf8 files, we don't need to change anything, except asking the language maintainers to prepare two version files -- one for current solution and another one is for UTF-8. So that we can update the UTF-8 branch without worrying about the conflicts until merging.

And for the side benefit, you may also want to see a normal language, not a martian language, right?

The second step is continue to update the UTF-8 branch according to feedback, and share the same language files with the main branch.

**Comment by thinkyhead** [comment]
All good. And don't forget, there's still the issue of the messed-up vertical position of some glyphs.

**Comment by thinkyhead** [comment]
Attempting to resurrect the UTF-8 support by @yhfudev with #5441.

**Comment by boelle** [comment]
i think this one should have the 1.1.2 milestone on it.

it has gon a bit dead for a few months and i think we will get a very hard time finding any good chinamen that also speaks english as good as chinesse
