### ISSUE TITLE
How to modify last G28?

### ISSUE THREAD

**Issue by karabas** [MarlinFirmware/Marlin#3652]
On deltas after print finishing endscript sends G28. I want to modify G28 exactly for this condition. What can be used as condition for IF statement? End_of _file?

**Comment by thinkyhead** [comment]
@karabas What do you want to do instead of `G28`? Why not remove `G28` from the end of the GCode and put in the GCode you would prefer?

If you need to intercept the end-of-file and do something extra, you will need to add code to the `get_sdcard_commands` function in `Marlin_main.cpp`.

There's no way to detect "end of file" within Marlin when host printing.

**Comment by karabas** [comment]
Some people use  many slicers simultaniusly and wont edit end-Gcode every time. For big deltas parking of head after finishing is important to prevent drop down to model. Yes End-Gcode scrypt is most logical and easy solution.

**Comment by thinkyhead** [comment]
@karabas The idea of Marlin is not to be too smart, but to faithfully execute commands as-given. If you can do something with the existing commands, even if it requires editing your slicer's end-gcode, that is preferable to modifying Marlin itself. Of course, most of us don't put `G28` at the end of our GCode because on Cartesian machines the head and/or gantry will crash into the print.

**Comment by WZ9V** [comment]
@karabas - The dropping is due to turning off the motors in the end G-Code.  If you remove the command to power down the steppers which almost every slicer does by default then G28 will hold at the top.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
