### ISSUE TITLE
When does EEPROM get set to defaults?

### ISSUE THREAD

**Issue by edwilliams16** [MarlinFirmware/Marlin#3938]
If I use the same version of Marlin and change a parameter - say the xyjerk setting - in Configuration.h and upload the modified firmware, then the parameter loaded into memory does not change as the old value in EEPROM over-rides it.  M502 will bring the value in from Configuration.h and M500 will then stuff it into EEPROM.  Although a potential trap for the unwary, I see this is a feature not a bug.
   What I'm unclear about is what happens when I change firmware versions.  Are any of the old EEPROM settings kept?  Are they wiped and null until an M500 is done, or are the new "factory default" settings pushed into EEPROM -- or what?

**Comment by KevMags** [comment]
All settings stored in EEPROM stay there until EEPROM is erased via Arduino or M500.

**Comment by KevMags** [comment]
In the LCD menu, Restore Failsafe writes firmware values to EEPROM.

**Comment by edwilliams16** [comment]
You didn't really address my specific question.  What happens when you change Marlin versions?  
Is the data stored in key/value pairs or the like, or at addresses chosen by the compiler? What happens to parameters present in one version and not in the other?

**Comment by KevMags** [comment]
Uploading Marlin firmware does nothing to the EEPROM.  None of the default parameters get pushed into EEPROM.  On a cleared EEPROM the EEPROM stays "empty" unless you push a value into it.  The old values stay in the EEPROM unless cleared or overwritten by M500. The values stored in the EEPROM for such items as e-steps and accel will be used with the new firmware.   From what I can tell (and I'm not the sharpest knife in the drawer) the major EEPROM addresses used in all of the firmware versions are the same.  Items not used in the new firmware will be ignored and newer feature parameters (if changed via USB or LCD and stored) will be stored in unique addresses (chosen by Marlin) that don't conflict with older firmware.   I always clear the EEPROM before uploading new or modified firmware since any value stored in an EEPROM address will override firmware settings.

Edit: I'm not sure that the new features don't use older addresses that may have values stored in them so that is why I always clear before upload.

**Comment by Blue-Marlin** [comment]
```
/**
 * configuration_store.cpp
 *
 * Configuration and EEPROM storage
 *
 * IMPORTANT:  Whenever there are changes made to the variables stored in EEPROM
 * in the functions below, also increment the version number. This makes sure that
 * the default values are used whenever there is a change to the data, to prevent
 * wrong data being written to the variables.
 *
 * ALSO: Variables in the Store and Retrieve sections must be in the same order.
 *       If a feature is disabled, some data must still be written that, when read,
 *       either sets a Sane Default, or results in No Change to the existing value.
 *
 */

#define EEPROM_VERSION "V23"
```

**Comment by edwilliams16** [comment]
To make sure I understood the IMPORTANT/ALSO comments.  Is it saying that if the EEPROM version number is changed, the default values are written into the EEPROM, but leaving unknown/disabled feature values either unchanged or sensible.  Or is KevMags correct and the the EEPROM is untouched even if you change EEPROM Version?

  One context of all this is that there's a fork of Marlin supporting a digipot in the Rigidbot. This firmware allows you to set the stepper currents.  The question is if these get set appropriately (I think writing into EEPROM in the digipot itself), can it get screwed up on switching to mainstream Marlin.

**Comment by thinkyhead** [comment]
> the default values are written into the EEPROM

⬆️  Actually, not quite, as it turns out.

Whenever the version number stored in the EEPROM is different from the Marlin's current EEPROM version number (as when you flash a newer version of Marlin where the EEPROM has been changed) Marlin will use the "factory settings" instead of the values in EEPROM.

In other words, whenever you send `M501` (`Config_RetrieveSettings`) Marlin checks the EEPROM version for a match. If it doesn't match, Marlin will do `M502` (`Config_ResetDefault`) instead.

So, to answer the original question:

> When does EEPROM get set to defaults?

Issuing `M502`, `M500` is the only guaranteed way to store the factory settings to EEPROM.

**Comment by KevMags** [comment]
Well obviously I am full of bad information.  Sorry .

**Comment by edwilliams16** [comment]
Got it.   It works exactly how I hoped it would!  Thanks for your patience.
