### ISSUE TITLE
hard to navigate code

### ISSUE THREAD

**Issue by Sgaggino** [MarlinFirmware/Marlin#4116]
I am not a skilled programmer, but whenever i want to look up for something it`s really hard to keep track of all the redirections related to #defines, #ifdef, etc. I think it could be better to modularize the code. The setup has to be something separated from the working code itself.

**Comment by paulusjacobus** [comment]
That's because the Arduino environment is meant for hobbyist/school
education. It's not a full professional development environment. Having
said that, the Open Source community has pushed this far to the bleeding
edges of what it can do. I suggest to read the books from Simon Monk
("*Programming
Arduino Getting Started with Sketches"). *He is brilliant in explaining how
it works and how to squeeze out the few more bytes and processing power
through coding tricks. These are all applied in marlin but you won't
understand it unless you get the deep explanation. Enjoy reading! It's very
well written for novices.

**Comment by Roxy-3D** [comment]
> I think it could be better to modularize the code. 

It is planned.   But the top priority is to get a very stable branch of the code published so we can take our time cleaning up the code.

**Comment by Sgaggino** [comment]
@paulusjacobus I will read about that.
@Roxy-3D I understand your point, but i am seeing that there are lot of electronic platforms and it's getting difficult to port because of the complexity of the code (i guess). I don't mean to modularize everything, but if only we can select a planner regardless of the firmware it could be beneficial. See... right now there's GRBL and TINYG (getting traction), maybe on the future we'll have more planners to choose. Even tho, which parts do you think ar most unstable? Do you think i could help on some topics?
