### ISSUE TITLE
RC7 Experimental filament change display error

### ISSUE THREAD

**Issue by WZ9V** [MarlinFirmware/Marlin#4526]
On RC7 after doing a filament change from the tune menu using a XXL LCD, the screen is not completely cleared prior to re-displaying the info screen.  On the third line of the display, the letters "to" remain on the screen between % and SD and the letter "e" remains between % and the timer.  There should be white space in those three places.

The actual function worked as expected and is a nice addition.  I'll try the M600 embedded in g-code version next.

**Comment by thinkyhead** [comment]
Interesting. The screen should always be cleared in-between displays, because the `lcd_goto_screen` function always sets `lcdDrawUpdate = LCDVIEW_CLEAR_CALL_REDRAW`. But maybe the `lcd.clear()` function isn't actually doing anything…?

To help debug this, please modify the `lcd_implementation_clear` function in `ultralcd_impl_HD44780.h` and check the output in your host console:

``` cpp
static void lcd_implementation_clear() {
  lcd.clear();
  SERIAL_ECHOLNPGM("Called lcd.clear()");
}
```

The message should appear every time you switch screens.

**Comment by WZ9V** [comment]
I'll try that tonight.  It is just my best guess that it is the clear, it could be elsewhere.  You agree with what my instincts say is the best place to look first.

**Comment by WZ9V** [comment]
lcd.clear is not called after the screen saying

CHANGE FILAMENT
Wait for print 
to resume

so some of the test from the third line shows through on the info screen.

**Comment by WZ9V** [comment]
@thinkyhead - I don't know how to create a pull request but I did this in ultralcd.cpp and it's working now.

`static void lcd_return_to_status() { 
    lcd_implementation_clear();  // add this line
    lcd_goto_screen(lcd_status_screen); 
  }`

Sorry the code was formatted correctly in the IDE.

**Comment by thinkyhead** [comment]
Very strange. Your solution is fine, but I would rather find the root cause as to why the screen is not being cleared based on the clear flag. Were you able to determine any pattern as to which screens are clearing properly versus which are not? Or maybe there is a bug where `lcdDrawUpdate` is being set to something else after it is set to `LCDVIEW_CLEAR_CALL_REDRAW`. I will have to keep looking.

**Comment by WZ9V** [comment]
No idea, but it does seem contained to the last screen before switching back to the info screen.

**Comment by thinkyhead** [comment]
Well, I decided to go for the simplest solution and clear the screen explicitly in `lcd_goto_screen` instead of setting the flag to do it on the next loop. I'll merge that pretty soon.
