### ISSUE TITLE
UBL Z Offset Diagram

### ISSUE THREAD

**Issue by MrExo3D** [MarlinFirmware/Marlin#4548]
@Roxy-3D Let me know if this diagram is accurate for UBL
![ubl-diagram](https://cloud.githubusercontent.com/assets/10480179/17457894/97ebaae8-5bd2-11e6-8535-215d79d4919d.jpg)

**Comment by Roxy-3D** [comment]
I started by saying I think your diagram is correct.   I changed my mind just because in the tiny wording you say (should be a negative value).    

That is the geometry and positioning I have been using when I need to calculate an offset in the code.    And from your diagram, you can see how somebody might need to have an Z-Offset even if they accurately set the Z_PROBE_OFFSET_FROM_EXTRUDER number.   The way you have it drawn, if the Z-Home is done in it's current position, we will end up with the nozzle a little too close to the bed because the probe will be triggering below the dashed zero line.   So, a small POSITIVE z_offset will bring things up a little bit so the rest of the tracking system works.

If the probe is going to trigger below the dashed line, the Z_Offset should be positive because we want the nozzle slightly higher than what the probe is indicating at the place we home Z.
