### ISSUE TITLE
BugFix from today does not raise z between probing points

### ISSUE THREAD

**Issue by funbobby2001** [MarlinFirmware/Marlin#4559]
# define Z_PROBE_TRAVEL_HEIGHT 5  // Raise between probing points.

z axis does not move at all between probings (grid)
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/405598/Configuration.h.txt)

**Comment by thinkyhead** [comment]
We just fixed a "bug" in the behavior of `do_probe_raise` so your settings will need to be updated. The height options are now nozzle-relative, as with other literal coordinates.

Since your Z probe is 9mm below the nozzle, your nozzle is already at Z=9mm above the bed when the probe triggers. A raise to Z=5mm will therefore do nothing. If you want a raise of 5mm over the trigger-point, you should now set your `Z_PROBE_TRAVEL_HEIGHT` to 14.

Unfortunately we cannot sanity-check this with the pre-processor, because it cannot compare floating point values, and `Z_PROBE_OFFSET_FROM_EXTRUDER` usually has a decimal.
