### ISSUE TITLE
Feature request: add ability to use G38.2 command (CNC) 

### ISSUE THREAD

**Issue by Bob-the-Kuhn** [MarlinFirmware/Marlin#4677]
Some CNC programs are now automatically adding the G38.2 commands to the gcode files.  It would be nice to have this implemented in Marlin.

**Comment by Roxy-3D** [comment]
Do you want it to do the probe?  Or do you want all the output the command generates?  What exactly are you trying to accomplish?

**Comment by thinkyhead** [comment]
RepRap GCode doesn't use the full GCode specification, but is more "inspired by" GCode, so we won't be implementing any codes with decimal points. The feature request is fine, but should be restated as a request for "**a command to automatically establish the tool height from the build surface using the nozzle (or tool) as a conductor or switch.**"

As it happens, you can use a probe for homing with `G28` and that works for any situation where you have already established the distance from the probe to the nozzle. Many machines, particularly deltas, have taken to using the nozzle itself as the probe by placing it on a spring-loaded gantry with a simple switch mounted above. Some machines do pass current through the nozzle to use it as the switch. Take a look at the [Prusa i3 MK2](https://www.youtube.com/watch?v=JqH41K2vq0g) for example.

Marlin does not currently support CNC features or in-place tool-changing, so that would need to be established first to make G38.2 (or equivalent) viable.

**Comment by Bob-the-Kuhn** [comment]
I like how it was restated except it sounds like it's just for the Z axis.  I'd like this to be available for the X, Y and Z axis.  

Maybe something like  "**command(s) to automatically establish the tool location from the build origin along an axis using the nozzle (or tool) as a conductor or switch**."

   Bob

**Comment by thinkyhead** [comment]
> available for the X, Y and Z axis

You're talking about something which pertains very well to CNC, but not so much to 3D printing, at least not at the RepRap level. That said, we have a thread going already on the subject of implementing [more general CNC style support](https://github.com/MarlinFirmware/Marlin/issues/3208) within Marlin. I think you would do well to jump on that topic, look at what has already been discussed, and put in your 2¢.

**Comment by Bob-the-Kuhn** [comment]
I see you've already added this request to the **more general CNC style support** thread.  Thanks

That thread seems to be almost exclusively aimed at laser engraving.  I don't mind bothering them.

I'm puzzled about your G28 comment.  As best I can tell G28 will do a two stage move to the origin unless Z_SAFE_HOMING is enabled and the Z probe signal activates.  Is there something similar for the X & Y axis?

   Bob

**Comment by Bob-the-Kuhn** [comment]
Attached are the modified files implementing G38.2 and G38.3 commands on Marlin 1.02

  Bob
[Marlin_G38.zip](https://github.com/MarlinFirmware/Marlin/files/468480/Marlin_G38.zip)

**Comment by thinkyhead** [comment]
I'd personally rather you used the tools for making PRs provided by Github rather than asking me to do the work for you. My time is very limited right now, and it's not cheap.

**Comment by Bob-the-Kuhn** [comment]
I've created a pull request for this feature request.

**Comment by thinkyhead** [comment]
Your pull request didn't go to the [right place](https://github.com/MarlinFirmware/Marlin/pulls) (the `RCBugFix` branch). Keep trying.

**Comment by Bob-the-Kuhn** [comment]
Pull request 4845 was just created to implement the G38.2 and G38.3 commands.

https://github.com/MarlinFirmware/Marlin/pull/4845
