### ISSUE TITLE
analogRead or extend Temperature::isr?

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#4696]
I need to add support for reading (yet another) analog sensor to Marlin. I notice analogRead is avoided, and I presume this is because it eats up too much time if you call it directly. So, is the ADC reading code in `Temperature::isr` the proper way to do it, and should I just add my new sensor there?

Also, the pin I want to use is defined (in the code of a Marlin fork) simply as "A3" – presumably from `fastio.h`. If I want to implement this for more than one board, how do I translate A3 to the specific pin number like we use in the pins files?

**Comment by Roxy-3D** [comment]
analogRead() looks like this:

``` cpp
int analogRead(uint8_t pin)
{
    uint8_t low, high;
#if defined(__AVR_ATmega1280__) || defined(__AVR_ATmega2560__)
    if (pin >= 54) pin -= 54; // allow for channel or pin numbers
#elif defined(__AVR_ATmega32U4__)
    if (pin >= 18) pin -= 18; // allow for channel or pin numbers
#elif defined(__AVR_ATmega1284P__) || defined(__AVR_ATmega644P__)
    if (pin >= 24) pin -= 24; // allow for channel or pin numbers
#else
    if (pin >= 14) pin -= 14; // allow for channel or pin numbers
#endif
#if defined(__AVR_ATmega32U4__)
    pin = analogPinToChannel(pin);
    ADCSRB = (ADCSRB & ~(1 << MUX5)) | (((pin >> 3) & 0x01) << MUX5);
#elif defined(ADCSRB) && defined(MUX5)
    // the MUX5 bit of ADCSRB selects whether we're reading from channels
    // 0 to 7 (MUX5 low) or 8 to 15 (MUX5 high).
    ADCSRB = (ADCSRB & ~(1 << MUX5)) | (((pin >> 3) & 0x01) << MUX5);
#endif
    // set the analog reference (high two bits of ADMUX) and select the
    // channel (low 4 bits).  this also sets ADLAR (left-adjust result)
    // to 0 (the default).
#if defined(ADMUX)
    ADMUX = (analog_reference << 6) | (pin & 0x07);
#endif
    // without a delay, we seem to read from the wrong channel
    //delay(1);
#if defined(ADCSRA) && defined(ADCL)
    // start the conversion
    sbi(ADCSRA, ADSC);
    // ADSC is cleared when the conversion finishes
    while (bit_is_set(ADCSRA, ADSC));
    // we have to read ADCL first; doing so locks both ADCL
    // and ADCH until ADCH is read.  reading ADCL second would
    // cause the results of each conversion to be discarded,
    // as ADCL and ADCH would be locked when it completed.
    low  = ADCL;
    high = ADCH;
#else
    // we dont have an ADC, return 0
    low  = 0;
    high = 0;
#endif
    // combine the two bytes
    return (high << 8) | low;
}
```

A to D conversions always takes a bunch of time.   (as you know!)   The heart of the routine is here:

``` cpp
    // start the conversion
    sbi(ADCSRA, ADSC);
    // ADSC is cleared when the conversion finishes
    while (bit_is_set(ADCSRA, ADSC));
```

If you can kick off the start of the conversion with the sbi() and do other useful work for a while....
When you wait for the conversion to complete with a:

``` cpp
    while (bit_is_set(ADCSRA, ADSC));
```

you won't have wasted a bunch of processing cycles!  I don't know what analog value you are trying to watch.  But for temperature things, it might make sense to kick off a new conversion at the very end of the idle() routine because it might be done with the conversion by the time you get back into the idle() routine.   (or the manage_inactivity() )      If it isn't done, well, there maybe very little harm done waiting for it to finish because the only reason you are back in idle() is because you ran out of work to do.  (My guess is this isn't strictly correct...  But I'm trying to suggest a possible path forward...)

**Comment by Roxy-3D** [comment]
>  If I want to implement this for more than one board, how do I translate A3 to the specific pin number like we use in the pins files?

I think the digital pin numbers for the analog pins are bigger than the normal digital I/O pin numbers.   If you want, I can put a wire on A3 on my Mega2560 board and get you the digital pin # (using M43 in the devel_ubl branch).   But for the Analog Library stuff, I suspect you want to use the A3 symbol.   (I have switches on Aux-3 analog lines I'm using for debugging UBL.  The digital I/O pin numbers are 64 and 65 and are connected to A11 and A12)  The 64 and 65 numbers are kind of unexpected because none of the documentation I've seen for the Mega2560 has digital numbers that high.   But for sure...  I'm reading values from those pins.

The ideal scenario is you can kick off a conversion with the sbi() and then get an interrupt when it finishes.   But I don't know if that is possible and if it is possible I don't know how to do it.  If that can be done, you could always have the 'current' value of the thing you are watching because the ISR could kick of the next conversion before it leaves.   And when the CPU enters the ISR it could store the converted value in a Global Variable that anybody anywhere could access.

But if your question is how to map this to different processors....  I'm guessing the logic at the front end of analogRead() is the answer:

``` cpp
#if defined(__AVR_ATmega1280__) || defined(__AVR_ATmega2560__)
    if (pin >= 54) pin -= 54; // allow for channel or pin numbers
#elif defined(__AVR_ATmega32U4__)
    if (pin >= 18) pin -= 18; // allow for channel or pin numbers
#elif defined(__AVR_ATmega1284P__) || defined(__AVR_ATmega644P__)
    if (pin >= 24) pin -= 24; // allow for channel or pin numbers
#else
    if (pin >= 14) pin -= 14; // allow for channel or pin numbers
#endif
#if defined(__AVR_ATmega32U4__)
    pin = analogPinToChannel(pin);
    ADCSRB = (ADCSRB & ~(1 << MUX5)) | (((pin >> 3) & 0x01) << MUX5);
#elif defined(ADCSRB) && defined(MUX5)
    // the MUX5 bit of ADCSRB selects whether we're reading from channels
    // 0 to 7 (MUX5 low) or 8 to 15 (MUX5 high).
    ADCSRB = (ADCSRB & ~(1 << MUX5)) | (((pin >> 3) & 0x01) << MUX5);
#endif
```

**Comment by thinkyhead** [comment]
Reading the actual source code is a good way to get insights! I would do more of that, but I'm so busy it's crazy. So it looks like the `Temperature::isr` is where I would add support for another sensor, since it already does the kick-off now, read later strategy.

**Comment by Roxy-3D** [comment]
> So it looks like the Temperature::isr is where I would add support for another sensor, since it already does the kick-off now, read later strategy.

I think I would try that.   If you do that...  Your temperature reading for the sensor will always be one reading behind.  But temperature changes so slowly, I doubt it matters.   (You would at most points in time have a conversion in process.  But instead of waiting for it to complete so you have the latest and most correct value, you would be using the 'last' value that got converted.  )

At: https://www.arduino.cc/en/Reference/AnalogRead  it says that the conversion process takes .1 ms to read an analog input.  That doesn't seem that bad.  It may not be worth all the complexity to kick off a conversion and then come back later to read it.

**Comment by thinkyhead** [comment]
> Your temperature reading for the sensor

It just needs to read a resistor integrated into a tool-head to identify the tool, so that won't be a factor. In the long run it will be supplanted with an i2c interface that passes more info.

**Comment by madhunm** [comment]
Is there a possibility to add code that changes the analog reference value from AVCC to the internal 1.1 reference when TEMP_SENSOR 147 is selected?

With the current AVCC reference, the current resolution is ~9 degrees. This defeats the purpose of using a high resolution sensor like a PT100.

With the reference set to the internal 1.1V reference, the resolution will become ~1.5 degrees.

From the 2560 datasheet, setting ADMUX.REFS1 = 1 and ADMUX.REFS0 = 0 will set the reference to the internal 1.1V reference

**Comment by thinkyhead** [comment]
@madhunm Do we have a separate feature request for that change? I'm closing this issue as it is resolved related to my project.

Would we need to have a new `thermistortable_147.h` if we alter the reference voltage?
