### ISSUE TITLE
can't compile 1.1.0-RC7

### ISSUE THREAD

**Issue by alejandro-anv** [MarlinFirmware/Marlin#4808]
I've compiled 1.1.0-rc6 without problems but when I try to compile RC7 I receive the following error:

For testing I've used all default configuration. Just download and compile.

```
/tmp/ccRleP5V.ltrans0.ltrans.o: In function `process_next_command()':
ccRleP5V.ltrans0.o:(.text+0x351c): relocation truncated to fit: R_AVR_7_PCREL against `no symbol'
collect2: error: ld returned 1 exit status
exit status 1
Error compilación en tarjeta Arduino/Genuino Mega or Mega 2560.
```

Tested with Arduino 1.6.8 and 1.6.11 (linux)

**Comment by thinkyhead** [comment]
Just like #4788. Please keep an eye on that issue. It seems to be a spurious internal compiler problem. Try moving the `process_next_command()` function to the end of `Marlin_main.cpp`, or shuffling other functions around. Eventually the compiler will magically be able to compile it without any other changes to the code. I recommend you start with the current `RCBugFix`, where we have already shuffled some functions around.

**Comment by alejandro-anv** [comment]
Thank you: Just moved the declaration of codenum:

uint16_t codenum = 0; // define ahead of goto

a few lines up and it compiled ok.

**Comment by alejandro-anv** [comment]
I was testing moving instructions and couldn't compile... 

Can you test if you can compile with this settings?

[config_anv.zip](https://github.com/MarlinFirmware/Marlin/files/480800/config_anv.zip)

**Comment by thinkyhead** [comment]
Helpful Tip # 1: You no longer need to redefine these to reverse the encoder:

``` cpp
#define BTN_EN2 31   //ANV: invertido
#define BTN_EN1 33
```

Instead you should enable one of these:

``` cpp
//#define REVERSE_ENCODER_DIRECTION
//#define REVERSE_MENU_DIRECTION
```

Helpful Tip # 2: You're defining `DELTA_RADIUS` more than once.

**Comment by thinkyhead** [comment]
Helpful Tip # 2: You're defining `DELTA_RADIUS` more than once. Don't do that.

**Comment by thinkyhead** [comment]
As I suspected, it does seem to be a compiler/linker issue. The linker doesn't like the `NOZZLE_CLEAN_FEATURE` for some inexplicable reason. I've tried various tricks to get it to compile with that feature enabled, but nothing seems to work. You can see for yourself, if you comment out line 2787 of `Marlin_main.cpp` it will compile…

``` cpp
  //Nozzle::clean(pattern, strokes, objects);
```

While `RC7` won't compile with your configuration, `RCBugFix` compiles just fine. So you should update to `RCBugFix` if you want to keep using the nozzle cleaning feature.

**Comment by Roxy-3D** [comment]
Would it make sense to make a branch that is ready to compile but won't?   Because with that, the Arduino people could probably chase down the problem and figure out what the problem is.

Is there anybody here that has a good working relationship with the Arduino group that could pass along the link to that branch and get it resolved?

**Comment by thinkyhead** [comment]
It's a longstanding issue with certain kinds of branching vs. jumping optimization. It can probably also be worked-around by setting compiler/linker flags instructing it to use jumps instead of trying to use branches where possible.

The basic issue is that the compiler tries to be predictive about how close together code segments will be, but it gets it wrong in some cases, and this is only discovered when the linker tries to apply the branch distance and discovers that it's too large — usually by only a few bytes. If branch code and jump code was the same size, the linker could cleverly substitute a jump, but there's a slight size difference so it just bails out.

In some forums the word is that jumps are actually smaller and faster on AVR, so it might make sense to apply different compiler flags anyway.

**Comment by boelle** [comment]
since this is invalid and a dublicate why not close?
