### ISSUE TITLE
UBL on CoreXY

### ISSUE THREAD

**Issue by MrExo3D** [MarlinFirmware/Marlin#4809]
@Roxy-3D I finally got my machine behaving to the point where i was able to run a G29 P1
I noticed some funny actions.. such as long pauses (30-40 seconds) once in a while
also when it does a large raise.. it seem to get higher each time, up to the point it was raising up like 200mm and i had to shut it down.

looking forward to testing your latest release :) eta?

**Comment by Roxy-3D** [comment]
> looking forward to testing your latest release :) eta?

I think it will be this weekend some time.  I'm reading too many stories about stupid stuff on Yahoo.  So it seems I never get a full day of debugging done. 

I certainly believe you that you are seeing some long pauses, but that doesn't make any sense.   If you see that in the new version we can add some print outs that will isolate exactly what is causing that.   For all practical purposes, I don't do any thing different for CoreXY's than a normal Cartesian machine.  That might be wrong.   I got bit on that with M48 and Delta's.   For the longest time I didn't have a Delta so I couldn't fix it and make M48 work.  (M48 now works on Delta's!!! )   There may be something like that going on with CoreXY's.

**Comment by MrExo3D** [comment]
M48 works :)

**Comment by kmbecker13** [comment]
I also saw this behavior where the bed would drop (+Z direction) rarely during G29 P1, but i also was having some other issues with my endstops ([see 4796](https://github.com/MarlinFirmware/Marlin/issues/4796)) at the time so i didn't really worry about it.

It was a very rare event and only happened maybe 2-3 times out of 40 attempts at doing the G29 P1, haven't been able to track down a root cause yet.

**Comment by MrExo3D** [comment]
@Roxy-3D check out this video.. let me know your thoughts.. ive noticed the Z doing several up down motions between layers..

https://www.youtube.com/watch?v=_t9lsUzMkio

**Comment by Roxy-3D** [comment]
@adamfilip  Was it actually changing layer heights each time it did that?   If so, that will be much easier to track down and fix.   The reason I'm asking is the walls of that box you were printing is thicker than one perimeter and it was doing it each time at the same spot.    

If that really is happening each layer change, I know exactly where to look to get the problem fixed!   When I rewrote the mesh_buffer_line() routine to be faster, I moved the Z-Correction up to a higher level.  It used to be done down in the planner.buffer_line() routine.  That was a good place for it because every request funneled together there.   The problem is, at that low of a level a lot of information was lost.    

In the case of the new mesh_buffer_line() it knows when it is doing a horizontal or vertical (Y-Axis) move, and drastically less floating point operations are needed in those cases.  But to do less floating point operations, the Z-Correction has to be done at a higher level where that knowledge is available.  

If this funny up and down is happening when it is trying to change layers, it is probably happening with a G1 Z   command and is not associated with any X & Y move.   That will make it much easier to find.

**Comment by Blue-Marlin** [comment]
For me it looks like: retract, lift, sweep, go to new position - generated from the slicer.
Our FWRETRACT has no sweep.

**Comment by MrExo3D** [comment]
using simplify3D to slice.. I dont have any Lift during retraction applied..

**Comment by MrExo3D** [comment]
I was doing a test print of a single wall box, not spiral

**Comment by Roxy-3D** [comment]
> I was doing a test print of a single wall box, not spiral

OK!  That helps to know...  I'll start digging in.   I'm also going to add some verbose debug code to G26 so I can get this other issue figured out:   https://github.com/MarlinFirmware/Marlin/issues/4828#issuecomment-248664190

**Comment by thinkyhead** [comment]
Please post the GCode for examination and testing.

**Comment by MrExo3D** [comment]
Here is the gcode
[TW_Calibration_Cubes.txt](https://github.com/MarlinFirmware/Marlin/files/486249/TW_Calibration_Cubes.txt)

**Comment by MrExo3D** [comment]
Noticed that the revised code with the switch from MAP M to O isnt working for me
M still works.. O does not

also the notes still reference using M

**Comment by Roxy-3D** [comment]
That comment was in regards to G29, right?   The 'O' parameter should work better in G29 now.   I did not find any problems in G26 with its 'M' conversion.

Adam, I'm not convinced the Z-Offset issue is totally correct yet.   You are probably best off setting that to 0.0 and getting the Z_PROBE_OFFSET_FROM_EXTRUDER exactly correct for right now.   But if you have time to investigate and see if it is correct, please let me know what you find.    In the mean time, the Z-BabyStepping should work to fine tune the start of a print.

**Comment by MrExo3D** [comment]
Got it working
https://www.youtube.com/watch?v=y6L8fQW-RkQ

I cant set travel speeds higher then 100mm/s it seems to bind or run into a cpu limit or something else.
getting some weird vibrations/resonating in the rails as well.

and yes i was referring to G29

**Comment by Roxy-3D** [comment]
I really like that printer!   The only problem is I can't see the Z-Axis going up and down as it crosses Mesh Lines in those videos.   And for UBL debugging, that makes things difficult.    

On the travel speed higher than 100mm/s, do you see the Z-Axis moving back and forth very fast?  If your mesh has big corrections in neighboring cells, is it possible your speed is being limited by how fast the Z-Axis can change direction and accelerate the opposite direction?    On my really bad piece of glass, I did notice an issue with that.   But my Z-Axis is painfully slow.  And I had one Mesh Point that was constantly forcing a change in direction of the Z-Axis as the nozzle got near it.   I ended up editing the Mesh point to be not perfectly correct just so it wouldn't kill my print speed in that part of the bed.

**Comment by Roxy-3D** [comment]
> I cant set travel speeds higher then 100mm/s it seems to bind or run into a cpu limit or something else.

I just realized something.   Make sure you think everything is printing correctly before you make this change.   But right now, there is extra debug code.  It is doing the Z Correction the old way, and the new way.   And then making sure the two numbers are very close to the same.   That could be impacting your max speed.    

In Mesh_buffer_line.cpp you will see this code block a number of times.   If you delete each occurance of it, the code will run faster and you should be able to go faster than 100mm/s.     But that code is in there to verify that the new (and faster) mesh corrections are creating the same results as the old code did.

``` cpp
//
// debug code to use non-optimized get_z_correction() and to do a sanity check
// that the correct value is being passed to planner.buffer_line()
//
z_optimized = z0;
z0 = blm.get_z_correction( next_mesh_line_x, y);
if ( fabs(z_optimized - z0) > .01 && !isnan(z0) )  {
debug_current_and_destination("!HORIZONTAL z_correction()");
SERIAL_ECHOPAIRPGM("  next_mesh_line_x=", next_mesh_line_x);
SERIAL_ECHOPAIRPGM("  y=", y);
SERIAL_ECHOPAIRPGM("  z0=", z0);
SERIAL_ECHOPAIRPGM("  z_optimized=", z_optimized);
SERIAL_ECHOPAIRPGM("  err=",fabs(z_optimized-z0));
SERIAL_ECHO("\n");
}
```

**Comment by MrExo3D** [comment]
Thanks I will try that :)

**Comment by MrExo3D** [comment]
System has been working well recently :)

**Comment by MrExo3D** [comment]
Before UBL enabled.
![before ubl](https://cloud.githubusercontent.com/assets/10480179/19410767/0be3f07e-92c2-11e6-9d84-86d29a95b7c2.jpg)

After without any finetuning. pretty good
![after g29](https://cloud.githubusercontent.com/assets/10480179/19410771/1af4037e-92c2-11e6-9b9f-e3372cfac14b.jpg)
