### ISSUE TITLE
Prusa i3 1.5 Rework not really auto leveling

### ISSUE THREAD

**Issue by 2pcu** [MarlinFirmware/Marlin#4870]
Hi All,

I'm already using my printer for a half year but my auto leveling is not really auto leveling and want some help if possible.

When I do a G29 all works fine and printer is checking 4 points and showing me the Z axis offset for hits/checks 4 points. I use a inductive sensor. 

I'm thinking that even the bed is not 100% even the auto leveling will fix this difference but when he's printing some places of the bed is printing well but other places it's just drops the plastic. Can somebody tell my how I can configure that Z axis auto correct the little difference? 

I'm using the Marlin_Prusa_i3_rework_1.5.zip firmware which can be found on reprap-3d website. 

Does maybe somebody now how to fix this ? 

Thanks in advance,

Topcu

**Comment by thinkyhead** [comment]
Prusa's latest (MK2) firmware is using mesh leveling these days. If their 1.5 firmware is using planar leveling, that has the same limitations as all planar leveling, in that the bed needs to be perfectly flat, because it only compensates for the tilt.

In the main Marlin branch, we're just on the verge of making the "nonlinear" leveling (also called "bilinear", and basically the same as "mesh" leveling) that is currently limited to DELTA available on regular Cartesians. Meanwhile, we have only a manual form of mesh leveling.

We don't support third-party forks, so I suggest you ask Prusa Research for support on that. They may have a newer version of their firmware that does what you want.
