### ISSUE TITLE
Mechanical resolution vs software stepping 

### ISSUE THREAD

**Issue by Aggebitter** [MarlinFirmware/Marlin#4928]
I'm in the making of a closed loop stepper controller. When I did some testing earlier I started to wonder about how Marling is doing its stepping vs the mechanics. When a move is running the smoothest ride is to do as many microsteps you can, but on Hold/Stop/Start/Direction change a fullstep gains the most torque.

So by combining microstep moves with biggest microstep we can accept at start/stop we would get the most out of the stepper driver and motor. It evens gets better if we take into calculation that we actually hit the peak torque 200 times per revolution. I'd love to know what step that was. Well I kind know if I home the printer at a full step (one of the things i try to implement i my controller)  

How is stepping done in Marlin? Is each step the same as the vector distance without the "max" torque mentioned above ? 

If so, we can take some mechanical resolution limits in to the loop and tweak the steps to gain the max torque with in the mechanical limits or am I just thinking wrong ?

Example: 
Fullstep, 200 steps/rev, 20 tooth GT2 pulley gives 40mm/rev and a mechanical resolution of 0.2 mm 
Do the same with 1/4-steps and we get 0.05 mm ! well we are printing plastics ;-)

**Comment by thinkyhead** [comment]
Marlin accelerates and decelerates the step rate as-needed during movement according to the configuration. The acceleration and jerk values determine the acceleration behavior. It uses look-ahead to determine whether to accelerate/decelerate over multiple moves.

Marlin uses the micro-stepping as set at the stepper driver level - with one stepper pulse per micro-step. Marlin cannot do a "whole step" without doing N individual micro-steps. For example, it always requires 80 step pulses per mm when using 16x micro-stepping with a 40mm pulley, and always requires 160 steps pulses per mm when using 32x micro-stepping with a 40mm pulley.

**Comment by Aggebitter** [comment]
This is exactly  what I'm thinking of. Do the combining of knowledge of what puls was a full step we could do a calculation that keeps the best torque step inside the mechanical limit we set. 

At 80 steps/mm the resolution is 0.0125mm and at 160 steps/mm it is 0.00625. That is about the thickness of a human hair.  Way more than even a well built printer can do just by looking at the extrusion of filament. The stretching on belts and mechanical slack is greater than this.  

My studies of papers regarding this gives around 10% increase i torque at the full step movement and around 30% in holding torque. but it has one more even more interesting feature. The full step is at a higher accuracy mechanical. We can even get that proof by not adding any current at all to the phases and that position the stepper will rest at is a full step 

I'm not trying to prof anything here. I'm trying to analyse if I should implement it in my closed loop stepper code

**Comment by thinkyhead** [comment]
It's always going to be a trade-off between torque, speed, and accuracy. One simple way to mitigate changes in load is to add a little bit of friction intentionally to an axis - not so much that it take a lot of torque to accelerate the mass, but just enough so that slowing down and changing speed are nearly "free" because it brakes on its own.

Better torque is generally achieved using smaller pulleys also. If you were to use full stepping, theoretically, you would need to gear down and/or use small pulleys to get acceptable resolution. The smallest possible on a 5mm stepper shaft is probably 8mm diameter, yielding ~24mm per revolution, or 0.12mm per-step resolution, which is not ultra-fine. But 0.06mm resolution (2x microstepping) is certainly acceptable. At 400 steps/revolution, loss of steps might possibly be noticeable to a less expensive encoder.

**Comment by stecor7001** [comment]
Hello all, sorry to revive an old thread, but I think I am hitting the same issue,and others may too; 

I will start with a few basic points: Microstepping vs holding torque
Full step :100%
Half step 50%
Quarter step 38%
......
16nth step: 9.8%
32nth step:4.91%

Since 1/16 and 1/32 step are common,  to simplify, let's focus on 1/16 only.

The holding torque  varies per microstep as follows:
 100% when the rotor position corresponds to one of the 200 (or 400) native steps
70% when the rotor is halfway between native steps (200 positions)
38% for each quarter step which does not fall on the full step or half step positions (200x4 -200 full step - 200 half step positions) 400 positions
20% for each eigtht step not falling on the above positions (8x200 - 200 f step - 200 half step -400 q step) 800 positions 
Down to 9.8 - 10% for 16/th steps positions (1600 positions, same logic as above)

So, while microstepping, the holding torque varies between 100 and 10% of the nominal value, depending on where the physical rotor position is related to the actual motor step position. Further, as you can see, the low tq positions are the major contributors 1600 positions w 10% tq, 800 positions with 20% tq = 2400 positions out of 3200 total rotor positions.

There are undeniable benefits to microstepping such as low noise and lower vibrations, however one drawback is that, for nearly 67% of the positions (where the torque is low) to motor does not do its job - or rather it's crippled to something like 14% holding tq. This results in vibration patterns (if a force is to be overcome, the rotor would move until nearing one of the higher torque positions, then oscillate until equillibrium is met). Friction does help with dampening, but is suboptimal.

I propose adding an additional parameter - resolution - which helps with the above as follows: resolution defines the minimum number of microsteps to be performed. In other words, even though we're microstepping at 1/16 step, the rotor position would move either one full step, or a half step, or a quarter step. Personally, i think resolutions below 1/2 step are misleading and result in rotor oscillation rather than repeatable moves. 

E.g. 200 step/ rev motor
1/16 microstepping
16t gt2.5 belt
Results in 80(micro)steps per mm. Now as discussed above, some 50% of these steps provide only 10% tq.

What I am proposing is adding a new parameter - resolution. Resolution could be: 5 steps/mm, in which case tq would be 100% and every actual move is a multiple of 16 microsteps. Basically, each move puts the rotor in one of its native positions, while retaining microstepping and its benefits.

Or, resolution could be 10 steps/mm when tq varies between 100% and 50% and the minimum move is 8 microsteps (halfstepping using microstepping). And so on so forth. Personally, I would not use more than quarter-stepping (1/2 preferably) as this yields unpredictable moves, and oscillation around the home position.

Adding this parameter would allow flexibility in choosing tq variance while retaining the benefits of microsteping (noise, vibration reduction). Please let me know what you think.

Thank you.
Stefan

**Comment by thinkyhead** [comment]
> Adding this parameter would allow flexibility in choosing tq variance

I was out of the loop last October, so missed this. I like the concept, but I'm not sure whether the effects would be measurable (or, on the firmware side, desirable). It would be an interesting addition to try out.

I hope to hit the planner and stepper code soon to attempt some other optimizations. At the same time I don't mind playing around with this concept.

My initial caveat comes from the fact that stepping is simply a matter of timed pulses. All you're proposing is to change the timing of the pulses, not the number, and inserting a "pause" at each larger (or full) step. I anticipate that the resonances would only differ, but would not be eliminated. As for holding torque, again, since the pulses are coming at a fast pace during an active print job, this kind of change would only matter for direction changes.

Note also that in terms of acceleration, you're talking about doing some number (perhaps 16) intermediate steps very fast, outside the acceleration, always at fastest pace, which is not substantially different from doing an instant move. There may be a slight dampening, but this is only due to the extra time inserted between pulses — which is what the stepping interrupt already does.

Obviously it's hard to come to any conclusions without testing. Hopefully I'll be able to get into that stepper/planner work soon and play around with the idea.

**Comment by boelle** [comment]
@Aggebitter 

Please post your question either on discord: https://discord.gg/n5NJ59y or on facebook: https://www.facebook.com/groups/2080308602206119/ 
The issue list is for bugs and feature requests only
Please close this issue once you have posted it on one of the 2 links
Thanks :-D
