### ISSUE TITLE
Is the use of USE_WATCHDOG safe?

### ISSUE THREAD

**Issue by Sebastianv650** [MarlinFirmware/Marlin#4970]
Most likely I get the meaning of the following comments regarding the watchdog from Configuration_adv wrong:

``` cpp
// If you have a watchdog reboot in an ArduinoMega2560 then the device will hang forever, as a watchdog reset will leave the watchdog on.
// The "WATCHDOG_RESET_MANUAL" goes around this by not using the hardware reset.
//  However, THIS FEATURE IS UNSAFE!, as it will only work if interrupts are disabled. And the code could hang in an interrupt routine with interrupts disabled.
```

For me, this means the use of the watchdog is unsafe: If `USE_WATCHDOG` is enabled and `WATCHDOG_RESET_MANUAL` isn't, the ArduinoMega will hang forever (until a power cycle). If `WATCHDOG_RESET_MANUAL` is also enabled it will only work depending on the interrupt enabled/disabled state.

I guess this feature is safe in some way, because it's enabled by default. Maybe someone understanding this feature could add some words, why it is good to have it enabled even when there is a power cycle necessary if the watchdog resets the board?

**Comment by thinkyhead** [comment]
It means to say that `WATCHDOG_RESET_MANUAL` is "unsafe" because it traps the watchdog timeout in a loop inside an interrupt, and doesn't reset the board as usual, which would put everything into a well-defined state. `WATCHDOG_RESET_MANUAL` does call `kill()` and it does turn off interrupts. So it might be "safer" now compared to when that comment was originally written.
