### ISSUE TITLE
After changing MARLIN firmware getting some lines on model. Please help

### ISSUE THREAD

**Issue by Shrikant888** [MarlinFirmware/Marlin#5236]
![p](https://cloud.githubusercontent.com/assets/22236971/20379059/0fe97faa-acc0-11e6-9af2-958cd478c532.jpg)

**Comment by emartinez167** [comment]
I think you have already been asked to post those questions in the reprap
forum. This is not a user support forum. All you are going to achieve is
piss everyone here.

**Comment by Shrikant888** [comment]
I have closed the all issues now help me..

**Comment by emartinez167** [comment]
I think you just don't understand. Go and SEARCH in the reprap forum. Put effort in actually reading and learning like everybody else here, instead of expecting someone else to do it for you.

Again, go to the reprap forum and read their documentation, and post your questions there. Google is a nice tool too.

@thinkyhead put it very simply. This is not an end user support forum, but a place to contribute to the Marlin firmware or post errors RELATED to the firmware, not user issues.

I am afraid you are going to make some people very upset if you insist.
