### ISSUE TITLE
How to use a paste extruder with Marlin? 

### ISSUE THREAD

**Issue by bellbonnar** [MarlinFirmware/Marlin#5300]
i would like to import the code from 0x7d website for the solder paste dispenser into marlin if anybody could explain in some detail i would be gratefull

thanks ]
alex

**Comment by thinkyhead** [comment]
Basic support for a paste extruder called `BARICUDA` is already in Marlin. First enable `BARICUDA` and then you can test. You may follow the advice on the 0x7d website on not using SD or an LCD, if that turns out to be important. But as far as I know, the LCD and SD card should not harm performance that much.

The codes to use for controlling the air valve are these:

```cpp
 * M126 - Solenoid Air Valve Open. (Requires BARICUDA)
 * M127 - Solenoid Air Valve Closed. (Requires BARICUDA)
 * M128 - EtoP Open. (Requires BARICUDA)
 * M129 - EtoP Closed. (Requires BARICUDA)
```
