### ISSUE TITLE
Documentation for multiextruders

### ISSUE THREAD

**Issue by alexxy** [MarlinFirmware/Marlin#5458]
From config file its not clear what is the logic of multi extruder offsets, distance in what direction will be calculated?

And it seems it behave differently if i set it via M218

**Comment by ekozan** [comment]
//#define EXTRUDER_OFFSET_X {0.0, 20.00}
//#define EXTRUDER_OFFSET_Y {0.0, 0.00}

It's the same axis direction of the printer but in relative coordinate

**Comment by alexxy** [comment]
So formula for second extruder coordinates are

E2_X = CURR_X - EXTRUDER_OFFSET_X[1]
E2_Y = CURR_Y - EXTRUDER_OFFSET_Y[1]
E2_Z = CURR_Z - EXTRUDER_OFFSET_Z[1]

Or something different?

I'm asking because i dont see this behavior.

**Comment by ekozan** [comment]
first is 0,0 second is 0+X and 0+Y

**Comment by alexxy** [comment]
what about Z?

**Comment by landodragon141** [comment]
The Z will always be equal because they are generally mounted together on the X or Y axis.

**Comment by alexxy** [comment]
Not for switching extruder

**Comment by landodragon141** [comment]
What do you mean by switching extruder?

**Comment by alexxy** [comment]
Its extruders like dondolo that uses servo to switch head

**Comment by landodragon141** [comment]
Well in that case X Y and Z will always be ~equal since the hot ends "should" be in the same place when active. These values are mostly intended for multi hotends that are fixed so that marlin knows where they are relative to each other. You could use those values to fine tune but I recommend doing as much tuning physically as you can. One thing you could do to test calibration is print two thin squares (just a couple layers) one on top of the other using the two extruders. That will help you calibrate X and Y. I may be preaching to the choir but I hope this information is helpful.

**Comment by thinkyhead** [comment]
You can also `#define HOTEND_OFFSET_Z { 0.0, z2 }` in the case of switching extruder.

(It's `HOTEND_OFFSET_*` in the newer code.)
