### ISSUE TITLE
G0 on Z without specified Feedrate

### ISSUE THREAD

**Issue by martindb** [MarlinFirmware/Marlin#5503]
The mpcnc project uses Marlin as the firmware to run this CNC multitool machine. There are users that generate their g-code with estlcam software, and this g-code use `G0` without feedrate specified in the first lines of the programs. We were using Marlin 1.1.0-RC7 without problems.

With RC8, Arduino starts to reset when executing the `G0` over `Z`. If you put a feedrate on those first moves, all is working.

Does Marlin have to limit these movements as specified in `default_max_feedrate` for each axis, in particular for Z?

**Comment by thinkyhead** [comment]
The reset may be due to the Z axis failing to move, or trying to move too quickly and eating up all the CPU.

The speed of the Z axis _should_ be constrained by the max feedrate (`DEFAULT_MAX_FEEDRATE`) and max acceleration (`DEFAULT_MAX_ACCELERATION`) values for the Z axis, which prevent it from moving or accelerating at excessive rates. But it's possible the acceleration and jerk behave differently enough in RC8 that your settings need to be adjusted.

I suggest you start by cutting the `DEFAULT_ZJERK` value in half (use `M205 Z` or the LCD controller). If that doesn't fix the issue, try setting lower max feedrate (`M203 Z` or the LCD) and max acceleration (`M201 Z` or the LCD) until the problem goes away.

If you find values that work, save them to EEPROM with `M500` and set them as your `DEFAULT_MAX_FEEDRATE` and `DEFAULT_MAX_ACCELERATION` values for Z.

HTH

**Comment by martindb** [comment]
Thanks! I've lowered DEFAULT_MAX_FEEDRATE for Z and no more resets with G0 without explicit feedrate.
