### ISSUE TITLE
How does ENSURE_SMOOTH_MOVES behave with SLOWDOWN?

### ISSUE THREAD

**Issue by cfelicio** [MarlinFirmware/Marlin#5507]
Hi All,

I noticed #define SLOWDOWN is enabled by default, and if I enable ENSURE_SMOOTH_MOVES, what happens in a scenario where the buffer is getting empty? Would both work at the same time? Should I disable one option if I enable the other?

Or are we talking about 2 different buffers / issues here?

Cheers! :-)

**Comment by Blue-Marlin** [comment]
`ENSURE_SMOOTH_MOVES` is already history in RCBugFix.
Since the planner buffer isn't drained that suddenly as before, `SLOWDOWN` has a realistic chance to work.

If you want to stay with RC8 - both of the options do about the same, but `ENSURE_SMOOTH_MOVES` is a. adjustable and b. a bit more powerful, but therefore less smooth. With `ENSURE_SMOOTH_MOVES` you can adjust the minimal time for all planed moves. With `SLOWDOWN` the moves time gets gradually longer, depending on how empty the buffer is.

**Comment by Sebastianv650** [comment]
Additionally to what has already been said, it's safe to enable both at the same time.

**Comment by cfelicio** [comment]
thanks for clarifying! :)
