### ISSUE TITLE
Unnecessary OCR1A setting in trapezoid_generator_reset()?

### ISSUE THREAD

**Issue by Sebastianv650** [MarlinFirmware/Marlin#5536]
Maybe it's a bug (without consequences) or I don't get the meaning..

Inside trapezoid_generator_reset(), which is called on each new block, we [set the OCR1A register]( https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/stepper.h#L360). But on every possible following path insider the stepper ISR, Marlin will set the OCR1A register a second time.
Or there was the initial intention to do a return after a trapezoid_generator_reset(), so that the stepper ISR is called after the time for initial_rate?
Or are I missing something?

I found this because with my PR for the unified stepper ISR, I forgot to change this register set but it had no bad impact at all.

**Comment by thinkyhead** [comment]
I'm not sure of the exact logic. Let's see… So, the `trapezoid_generator_reset()` method is only called when a block is first popped off the queue. If `Z_LATE_ENABLE` is enabled `OCR1A` may be overridden by that logic. Later, after steps have been taken in the current ISR, if accelerating or decelerating, `OCR1A` will be set from `calc_timer`, otherwise it will be set to `OCR1A_nominal`.

I think you are correct, that it does not need to be set in `trapezoid_generator_reset()`.
