### ISSUE TITLE
LIN_Advance Support Question

### ISSUE THREAD

**Issue by psavva** [MarlinFirmware/Marlin#5636]
I have enabled LIN_Advance, and it's absolutely awesome to see such a big leap in the quality improvements in my test prints.

@Sebastianv650 I need some advice on the K value.
I started at 75 and worked my way up to 200.

I can't seem to get a good value for my printer. 
I have built a custom printer called the WeldingRod Bot.  You can find it on thingiverse...

It has a long Bowden tube with a RepRapDiscount Hexagon Hotend.

Here are some photos of my test prints.

![img_20161230_204836](https://cloud.githubusercontent.com/assets/1454758/21571022/f510eeda-ced3-11e6-9948-30b33919f921.jpg)

K=75
![img_20161230_204402](https://cloud.githubusercontent.com/assets/1454758/21571044/1812d114-ced4-11e6-8017-98be6757a30f.jpg)
![img_20161230_204412](https://cloud.githubusercontent.com/assets/1454758/21571049/261647b4-ced4-11e6-9192-432ca656339f.jpg)
![img_20161230_204430](https://cloud.githubusercontent.com/assets/1454758/21571051/2b96fdbe-ced4-11e6-997a-dc32c176c1f6.jpg)

K=90
![img_20161230_204525](https://cloud.githubusercontent.com/assets/1454758/21571057/395559be-ced4-11e6-87e3-3ee7d16bbf7e.jpg)

![img_20161230_204539](https://cloud.githubusercontent.com/assets/1454758/21571066/426334fe-ced4-11e6-8dee-5e6243570c69.jpg)

![img_20161230_204551](https://cloud.githubusercontent.com/assets/1454758/21571069/4a9bff20-ced4-11e6-90e6-b4cbe66620e5.jpg)

K=150
![img_20161230_204608](https://cloud.githubusercontent.com/assets/1454758/21571078/5af4bb96-ced4-11e6-8d19-61a6d4b37088.jpg)
![img_20161230_204616](https://cloud.githubusercontent.com/assets/1454758/21571083/61448670-ced4-11e6-83f5-2998730f46e0.jpg)
![img_20161230_204621](https://cloud.githubusercontent.com/assets/1454758/21571086/68c7496e-ced4-11e6-9de6-c22a7485d7e0.jpg)

K=200
![img_20161230_204646](https://cloud.githubusercontent.com/assets/1454758/21571091/737da40c-ced4-11e6-9172-ffa82338b061.jpg)
![img_20161230_204653](https://cloud.githubusercontent.com/assets/1454758/21571095/7a6eae50-ced4-11e6-9e5d-00fe2879939a.jpg)
![img_20161230_204722](https://cloud.githubusercontent.com/assets/1454758/21571100/80cdd208-ced4-11e6-9aa0-47941609c06e.jpg)

Lin_Advance disabled
![img_20161230_191444](https://cloud.githubusercontent.com/assets/1454758/21571104/916a29ea-ced4-11e6-8634-0223f5404090.jpg)
![img_20161230_191522](https://cloud.githubusercontent.com/assets/1454758/21571110/9e5ec75a-ced4-11e6-8eb6-1d68bc4d1ee4.jpg)
![img_20161230_191548](https://cloud.githubusercontent.com/assets/1454758/21571114/a9a6c180-ced4-11e6-8215-e8212ea8707c.jpg)

Yoda printed with Lin_Advance enabled at K=90
![img_20161230_191601](https://cloud.githubusercontent.com/assets/1454758/21571132/cc994924-ced4-11e6-9b53-f0985e69f1ff.jpg)
![img_20161230_191615](https://cloud.githubusercontent.com/assets/1454758/21571136/d4b4d9de-ced4-11e6-901a-012fb6710405.jpg)
![img_20161230_191646](https://cloud.githubusercontent.com/assets/1454758/21571158/15e3981e-ced5-11e6-8f8f-b4b527b44fd5.jpg)

**Comment by Sebastianv650** [comment]
Do you get a nice clean cube when you print it slow without LIN_ADVANCE? Just to be sure your esteps/mm value is good.

It's interesting to see that the difference between the K values seems to be not that clear on a bowden system. There might be other effects inside the tube (friction due to buckling and others) that are not covered by the advance algorithm.
Based on the given pictures, I would say the cubes look nicer with increasing K value, where K=200 is the best (compare corners and gaps in top infill). I would try another one with 300 and 400, just to see what will happen.

**Comment by m0n5t3r** [comment]
I had a similar problem with underextrusion and it was because of E-steps being slightly off after moving from direct drive to bowden

Also, you may have to go higher, depending on the filament: using RC from a few days ago, on a ~60cm bowden the formula in Configuration_adv.h gives me 528 for ngen and 282 for PLA; 528 is definitely too much for ngen, the corners come out rather rounded at 60mm/s, and if I increase the speed (say, 150%, so 90mm/s in theory) they don't look like corners any more 

I am running with 350 now when I print ngen, and it seems to work fine at low-ish speeds (60-70mm/s); for flexible filaments I disable it completely (same for weird ones like {brass,bronze}fill or wood).

**Comment by psavva** [comment]
I will firstly try with a slow speed print a cube.
Say around 30mm/s should be ok? 

I'll try adjust jerk and acceleration to get the best results. 

My esteps for my extruder are given by the manufacturer of the drive gear.
http://www.reprap.me/mk8.html

**Comment by Sebastianv650** [comment]
@psavva 20-30mm/s for perimeters and top/bottom solid infill should be great to see if you printer is in a well calibrated state (without ADVANCE-things). For K calibration prints, I recommend a medium-high print speed. Sadly that's hard to give in numbers, because it depends on your extruder and hot end. On most printers, it's around 8mm³/s - you see it depends on the line width and layer height what that means in print speed. For a usual line width of around 0.5mm and 0.25mm layer height that means around maximum 65mm/s.

**Comment by billyd60** [comment]
Really stupid question. Does Lin_Advance have to also be enabled in the LCD menu anywhere (like firmware retract) or just uncomment the function in .h and go?

**Comment by psavva** [comment]
I managed to get the test cube look very similar to a good print with LIN_ADVANCE, by adjusting acceleration, jerk and max velocities without Lin_Advance

I will retune with Lin_Advance and see if I can get the full awesomeness of if it :)

Thank you for your advice and support.
