### ISSUE TITLE
RC7 Full Graphic Smart Controller problem

### ISSUE THREAD

**Issue by DaniDiaz71** [MarlinFirmware/Marlin#5720]
I've installed a new Full Graphic Smart Controller on my Prusa i3 (Hephestos by BQ), but after several minutes printing display shows like this:

![img_20170118_165703](https://cloud.githubusercontent.com/assets/8013962/22072675/5fef9b24-dda3-11e6-99e7-3013a80feb07.jpg)

At the beginning display shows OK, like this:

![img_20170118_162619](https://cloud.githubusercontent.com/assets/8013962/22072069/6302e55c-dda1-11e6-9215-628cb6de2b8e.jpg)

I use IDE 1.6.13 and U8glib 1.19.1, it could be solved at RC8?

In this directory you'll find all configuration files: 

[https://drive.google.com/open?id=0B2i6OYnHCL_gMGRJRlNybGdFTzg](url)

Thanks and BR.

  Daniel.

**Comment by ghost** [comment]
Probably not, but it never hurts to run the lastest firmware.

I belive it is a bad display. See #5542, surprisingly hasn't been closed.
There is also this #5703.

**Comment by DaniDiaz71** [comment]
Yes, it seems to be the same problem, i'm going to buy a new one.

Thank you very much ;-)

**Comment by willthiswork89** [comment]
my new one started doing it again too. I'm started to unconvince my self that the LCD is the issue.... i

**Comment by ghost** [comment]
@willthiswork89, try:
- Re-downloading and installing the LCD drivers ([U8glib](https://github.com/olikraus/u8glib)).
- Check and/or replace the ribbons.
- Check for bent or broken pins.
- If your cables are longer than standard, they should be shielded to prevent interference.
- Maybe the interface card (if you have one) is bad.
- Maybe there is a bad I/O pin. Only fix is to replace the controller.

I say all of this because I have the same LCD and have had no issues with it over several different Marlin firmware versions. I do not believe at all that it is a software issue (aside from drivers)
My printer stays powered up most of the time.  (Sorry for the fuzzy picture)
![win_20170119_11_27_58_pro](https://cloud.githubusercontent.com/assets/12885062/22120240/2f947a78-de3c-11e6-942a-20db6694013b.jpg)

**Comment by psavva** [comment]
@DaniDiaz71 based on the conclusions, please can you close this incident

**Comment by DaniDiaz71** [comment]
Done! Thank you :)

**Comment by DaniDiaz71** [comment]
Finally my problem was a ribbon cable bad contact, I unplugged both cables and plugged it again and now it's working fine.

**Comment by Roxy-3D** [comment]
> Finally my problem was a ribbon cable bad contact, I unplugged both cables and plugged it again and now it's working fine.

I would replace the ribbon cable.  Just because it is making a good connection right now...   I wouldn't trust it...
