### ISSUE TITLE
Marlin 1.1.0-RC8 auto bed leveling G28 travelling out of bed and crashing

### ISSUE THREAD

**Issue by stiivik** [MarlinFirmware/Marlin#5741]
Hi

I am using MarlinRC8, ramps 1.4 board and Anet A8 printer. If I use G28 X Y everything is fine and working and if i use G28 it travels out of bed. Settings should be correct, but apparently they are not as this is crashing beyong max position on X and Y axis. I can't find the mistake. I enabled debugging and logged both commands, I will also post Configuration file. Using the same settings on old Marlin 1.0.2-1 and it's working correct. Is there something I missed or what could it be?

Thanks!

[G28 X Y.txt](https://github.com/MarlinFirmware/Marlin/files/725046/G28.X.Y.txt)
[G28.txt](https://github.com/MarlinFirmware/Marlin/files/725045/G28.txt)
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/725047/Configuration.txt)

**Comment by FHeilmann** [comment]
When you do G28, when exactly is it going out of bed?

**edit:** Can you also upload your old configuration please.
I found one configuration for the Anet A8 online where the XY steps/mm were 100. Your configuration has that set for 200 which would explain your issue. After homing X and Y the printer attempts to go to `(121.00, 162.00, 5.00)` but since the steps/mm are set twice as high than they should be the head will, in fact, travel to `(242.00, 324.00, 5.00) which causes it to crash.`

**edit2:** found another and I'm quite certain now. Change

`#define DEFAULT_AXIS_STEPS_PER_UNIT   { 200, 200, 400, 90 }`

to 

`#define DEFAULT_AXIS_STEPS_PER_UNIT   { 100, 100, 400, 90 }`

and don't forget to close the issue if that helps.

**Comment by stiivik** [comment]
Climbed out of bed to test it and it works perfectly. Tried G29 after it and works. Thank You!
