### ISSUE TITLE
Remember Last Toolchange Used?

### ISSUE THREAD

**Issue by sarf2k4** [MarlinFirmware/Marlin#5797]
I would like to ask about the toolchange command, how long does marlin remembers if I were to give it T1 command to use extruder 2?

I know that the last toolchange used such as T1 might reset after some time but after power loss or reset it surely goes back to T0 by default.

Is it possible to implement an eeprom variable to remember last toolchange command so that after reset/power loss it will stay that way?

I am using a multi-material jig and sometimes after print the last filament loaded was extruder 2, after power loss/reset, it will move extruder 1 instead of extruder 2.

Currently I had to include a toolchange command to revert back to extruder 1 loaded into the nozzle at the end gcode script.

**Comment by Bob-the-Kuhn** [comment]
What you propose is doable but ...   Automatically writing to the EEPROM is discouraged because you can literally wear it out.

I think the better approach is to put the tool change command in your slicer's start script.

**Comment by sarf2k4** [comment]
simplify3d does that everytime, but on power loss/reset, it will go back to extruder 1, but the one loaded is actually extruder 2, unless putting several micro switches to detect the current extruder that is loaded on the teflon tube of each extruder, but having the micro switch on them will make it even more complex.

Unless there are some other methods to retain the last used tool/extruder

**Comment by Bob-the-Kuhn** [comment]
I didn't answer one of your original questions.  The only thing that changes the active extruder is the tool change command or going through reset.   Reset always selects extruder 0.  Reset occurs on power up and whenever you disconnect/connect to the printer.  There is no timeout on which extruder is selected.

Since "simplify3d does that everytime" then the correct extruder will be selected before the print starts.

I guess I'm not understanding why you want to save the last used extruder.  How would that change/improve your print setup process?

**Comment by sarf2k4** [comment]
Sorry, I don't want to raise unhealthy argument, I'm trying my best to clarify what I want to address.

If for example the loaded extruder is extruder 2, and we don't know the current selected extruder, doing the toolchange script to swap the extruder filament would caught someone off guard if the owner of the printer doesn't even know if the printer had a reset or power failure before they started to use the printer. 

Another would be that, the user had power outage during printing/crash/thermal runaway and had to reset while the one loaded is extruder 2, got to manually retract the loaded filament same way as the toolchange script would do.

**Comment by Bob-the-Kuhn** [comment]
I'm running a single nozzle so I have not experienced what you're trying to improve.

I'm going to just leave it as "I don't understand".

**Comment by token47** [comment]
The problem is that the filament from extruder 2 is going through the Y splitter. If the printer resets and on the next print simply loads filamento from extruder 1 they will crash inside the splitter. It should remember that extruder 2 was the last one used so when trying to use 1 next, it would unload the filamento from 2 and load from 1. Unless he puts a microswitch on each filament to see which one is being used, there is no way to know which one is loaded unless it remembers from last use.

The multi-material is key here (multiple motors on one hotend).

**Comment by Bob-the-Kuhn** [comment]
I take it that you can't see which filament is loaded within the splitter.

How about automatically unloading both on power up / reset?  If you change **card.checkautostart(false);**  to **card.checkautostart(true);** in Marlin_main.cpp then the g-code file auto0.g will automatically be executed on reset and power up.

**Comment by thinkyhead** [comment]
I understand your proposal makes some sense for your setup, and maybe some commercial printer will want to use this kind of scheme. Of course just because the last tool was T1 doesn't necessarily mean the filament has also been loaded. It would be better if there was a sensor that could detect this.

**Comment by sarf2k4** [comment]
What if, by using a microswitch that is driven by a servo arm? I dont know
how marlin handles the servo everytime it resets, does it do like z probe
movement?

Let's say i have a z probe arm at position 90 for retract and position 12
for deploy, on my end it goes to somewhere in around position 40 then goes
to retract position afterwards

**Comment by thinkyhead** [comment]
An optical switch in the filament path would be my recommendation.
