### ISSUE TITLE
Thermal protection not triggering

### ISSUE THREAD

**Issue by Pipshag** [MarlinFirmware/Marlin#5916]
I just broke my thermistor on Heater 0 and found a bug that is possibly a safety issue. 

On RC6 I get an ERR: MAXTEMP error as soon as the printer powers on but on f9e4717 the printer powers on very happily with a temp reading of 100C on the LCD (but it shows 1100C in OctoPrint). Might this be case of the value being too great to be picked up as unsafe?

My configuration is located here https://github.com/Pipshag/Marlin/tree/BOWDEN_IDEX_RCBugFix

```
#define THERMAL_PROTECTION_HOTENDS
...
#define HEATER_0_MINTEMP 5
#define HEATER_0_MAXTEMP 400
```

**Comment by ghost** [comment]
Broken should result in MINTEMP error not a MAXTEMP error.

I tested this on mine by pulling the thermistor plug. LCD reported -15C.
Octoprint reported -14.8C.
My settings:
```
#define HEATER_0_MINTEMP -10
...
#define BED_MINTEMP -10
```
and
```
#define HEATER_0_MAXTEMP 255
...
#define BED_MAXTEMP 130
```
and
```
#define THERMAL_PROTECTION_HOTENDS // Enable thermal protection for all extruders
#define THERMAL_PROTECTION_BED     // Enable thermal protection for the heated bed
```
When I set the hotend to 1C, I got:
```
Err: MINTEMP
PRINTER HALTED
Please reset
```
Just as expected.
I am running RCBugFix.

**Comment by Roxy-3D** [comment]
@Tannoo   Thank You!

**Comment by ghost** [comment]
Np. I didn't think there was an issue, I just thought I would try it because it's been a while since I had a broken thermistor. (Usually the bed for me).

**Comment by Pipshag** [comment]
So I understand, the checks don't trigger before we try to actually heat the tool. Reflashed and tried once again and it works just as you tested. It went against my better judgement to start heating with a defective temperature sensor.

I'm not really certain that this behavior is better than just shutting down with an error. Sure, aids in troubleshooting but are we never seeing a case where it might be bad?

On RC6 I got what I expect if my temperature is reading above normal, 1100C - an ERR.
Running latest (referenced above) boots up happily with T:1100.0.

**Comment by ghost** [comment]
>So I understand, the checks don't trigger before we try to actually heat the tool.

Correct

Above normal? It should throw a MAXTEMP error if it goes past the MAXTEMP value. That can be tested also by setting the MAXTEMP to a lower temp, like a few deg above ambient and set the hotend to a few deg higher than the MAXTEMP.
You should get the MAXTEMP error.

**Comment by Pipshag** [comment]
In this case I have a value of 1100C (TOOL 0) on startup. The machine boots, runs and operates until I try to set a temperature on TOOL 0. I am just now printing something with TOOL 1 while TOOL 0 is showing 1100C (100C on the display).

What you are describing is totally correct. What I referred to as "normal" was the ambient temp, or whatever the temperature would actually be.

**Comment by ghost** [comment]
hmmm... what thermistor do you have setup? When mine breaks, it goes low, not high.

**Comment by Pipshag** [comment]
It's a PT100. There might be a false contact and not a total break.

**Comment by ghost** [comment]
If you unplug it from the board, does it go high also?

**Comment by Pipshag** [comment]
Yes, I unplugged both sensors from the amplifiers and got the same temp reading (1100C).

**Comment by ghost** [comment]
Going to have to leave this one for the pros. Sorry. I'm at a loss.

**Comment by Blue-Marlin** [comment]
There are two main failures with resistance based temperature sensors:
* shortcut  -> ~0 Ohm -> ~0 Volt at the ADC -> low ADC reading
* break -> infinite Ohm -> ~ VCC Volt at the ADC -> high ADC reading

Depending of the __T__ emperature __C__ oefficient of the resistor the ADC readings have to be interpreted differently.
* __P__ ositive __TC__ -> high temperatures high resistance -> low ADC values (f.e. PT100 without amplifier)
* __N__ egative __TC__ -> high temperatures low resistance -> high ADC values (f.e. normal thermistors)

-> a broken wire results in a MINTEMP_ERROR with a Thermistor but a MAXTEMP_ERROR with a PT100 (without amplifier). 

-> the temperatures you can usually read on the display when a error occurs is determined by the first and last line of the table that is correlating ADC value and temperature (thermistortables.h).

(If there is an amplifier it depends on, if the amplifier is inverting or not)
(The relative new delay for the errors, until really heating, is made for the fu**ing high temperature thermistors (66) witch would come up with a MINTEMP_ERROR at room temperature otherwise. )
