### ISSUE TITLE
#G26 UBL Mesh Validation

### ISSUE THREAD

**Issue by aaronthomaswebster** [MarlinFirmware/Marlin#5929]
devel-UBL
Crazy thing happening. After I G28 and G29  I run G26 to validate the mesh my bed heats properly but my hot end does not.  The hot end never gets to the temperature shown on the LCD no matter what I set it to. It always seems to hang 10° lower than set.

**Comment by Roxy-3D** [comment]
That is strange.   What happens if you just do a G28 and then tell the printer to go to your temperature and wait?    The G26 command uses the standard calling convention to set bed and nozzle temperature that the rest of Marlin uses:
```cpp
//
// Now turn on the hotend (nozzle) and wait for it to come up to 
// temperature.

  thermalManager.setTargetHotend( hotend_temp , 0 );
  while( abs(thermalManager.degHotend(0)-hotend_temp) > 3 ) {
  	if ( G29_lcd_clicked() ) {
		strcpy( lcd_status_message, "Leaving G26    "); // We can't do lcd_setstatus() without having it continue;
  		while ( G29_lcd_clicked() )			// Debounce the switch
			idle();
            	lcd_setstatus( "Leaving G26     ", true);	// Now we do it right.
		return 1;
	}
	idle();
  }
```
Can you experiment a little bit and see if you can get a little more information?   And...   You do know that G26 has a default nozzle temperature of 205 C. Right?
