### ISSUE TITLE
Screen issue with i2c 2004 lcd display

### ISSUE THREAD

**Issue by nielsnl68** [MarlinFirmware/Marlin#5939]
Hi, 
i have hooked up an i2c lcd display to follow the print process.  Using the dcf8574t
Sadly the shown result is not displayed correctly.  For example the temperature indications are in correct and not shown correctly. And the x y z values are not shown at all. 

I have already been looking into it for some time and i know where it displays the values but when i try to add lcd.print (T1); \  then i get a one digid value instead a 2 or 3 digid value. 

See attatched image.
![20170302_224109](https://cloud.githubusercontent.com/assets/4739151/23528267/85a8071c-ff99-11e6-84c4-70f4966405bb.jpg)

**Comment by nielsnl68** [comment]
Nobody else has this issue?

**Comment by thinkyhead** [comment]
It does appear, only the first digit is coming through on each individual call to `lcd.print`. This sounds like it could be caused by a program error, but it could also be caused by some mis-configuration (of the `u8g` interface to the display) where the character mapping is not correct, or where the display is expecting more bits to come through per-character. At the outside, it could be caused by bad timing to the display, but this seems to me the least likely.

I note that the string "RigidBot ready." comes through fine. And, it happens to use the `lcd_print` function to print that line instead of the (more direct) `lcd.print` function. So it's possible that replacing all the `lcd.print(char*)` calls with `lcd_print(char*)` will solve the issue for your situation. I'm not sure whether that's a universal solution, but it may be.

I believe that the only time `lcd.print` is used rather than `lcd_print` is when printing numerical values. And it should continue to be used for printing single characters.

**Comment by nielsnl68** [comment]
Thanks Scott,

You are totally right i modified the code and it works now. Should I add a
PR  for this?

**Comment by nielsnl68** [comment]
Is this now fixed?
