### ISSUE TITLE
reporting actual position

### ISSUE THREAD

**Issue by FloydPerfect** [MarlinFirmware/Marlin#6037]
M114 reports the actual position. If you issue a position command (G0 .. G1 ), M114 immediatly reports after the position that was set in the command, even if the unit is still moving. I woud need to know when the position is reached. Is there a way to query the actual position of the head ? Maybe a M114.1 ?

**Comment by Blue-Marlin** [comment]
M400

**Comment by FloydPerfect** [comment]
You made my day.
Sending the position command. Next command M400. It reports Ok, when the position is reached.

Thanks

**Comment by Bob-the-Kuhn** [comment]
See PR #6039

**Comment by FloydPerfect** [comment]
Smoothieware has a command M114.1 that reports the "real time position".

[](url)http://smoothieware.org/supported-g-codes

**Comment by Bob-the-Kuhn** [comment]
The change has been merged into Marlin.  M114 now waits until the move has completed before reporting.

**Comment by thinkyhead** [comment]
What's the use case for `M114` where it needs synchronization? Would it be sufficient if we skip synchronize and simply apply the same equations to produce stepper counts that correspond to the reported current position?

It seems that some touch screens are using `M114` to ask the firmware for the current position. As you can imagine this is causing some really bad print artifacts and now this is coming back on us.

I'm thinking that as an alternative to `M114.1` (to keep the parser slightly leaner for the tiny platforms) we simply make `M114` not synchronize by default (old behavior), and also report only the cartesian position by default. However, if you issue `M114 D` to ask for more detail (a current option) then `M114` will include the synchronize before it gives the longer report with additional information.

**Comment by AnHardt** [comment]
I'd vote for a auto-position-reporting similar to the auto-temperature-reporting. It should return the current planner position. Then there is no need, for the host/display to send a M114 to get a (synced) position report. During printing that would be as useless as the positions on the nativ Marlin displays. But during manually preparing a job, where the g-codes are sent one by one, waiting for the response, where the planer-buffer is always empty, that would be as sufficient as the native Marlin display.

**Comment by thinkyhead** [comment]
Hosts that are sending g-code of course don't need `M114` reporting since they have access to the g-code. The LCD never needed to use `M114` because the firmware was controlling the LCD. Serial LCDs that want to display XYZE and are implemented through ExtUI have access to those variables directly and so they don't need to use a g-code either. PanelDue uses `M408` to get a full status which includes position.

It would ultimately be fine for tiny hosts (touch LCDs) to use `M114` if it can be determined that `M114` is not hooked into any host software or entrenched use-case where it requires synchronization by default. And if we are permitted to remove the default synchronization behavior then it will fix the problem for those cases where users are not able or aware about updating the LCD that is using it.

Auto-reporting of the position is fine too, and it could be appended onto the temperature auto-report when they are both enabled to save on bandwidth. (`M408` with an auto behavior would be better here.) But, then hosts and the LCD firmware have to be updated to adopt the new protocol. Since that will take some weeks or months it would be nice to have the `M114` patch as an interim solution.

In the meantime, we can offer non-sync default as an optional behavior of `M114` and enable that behavior —or throw a sanity error— when we detect that Marlin is being built with one of these LCDs.

**Comment by thinkyhead** [comment]
See #17032 for a proposed approach that preserves the output (for the most part) while keeping motion constant. The only time it could be incorrect is when changing steps-per-mm or changing compensation features in-between moves, which are not normal activities.
