### ISSUE TITLE
Using Z probe as a limit switch as well?

### ISSUE THREAD

**Issue by gcormier** [MarlinFirmware/Marlin#6146]
Venturing out of charted waters for me personally....

I have a nozzle Z probe working quite well. Is it possible to have it also function as a limit switch, so if it's ever triggered (should never happen, other than probing operations), it would stop printing?

(I've been seeing all the sweet UBL merges, and I want to try it out. My plate is mounted on springs, so I want to change that to a rigid mounting so the nozzle probe doesn't have inconsistent results)

**Comment by Roxy-3D** [comment]
> (I've been seeing all the sweet UBL merges, and I want to try it out. My plate is mounted on springs, so I want to change that to a rigid mounting so the nozzle probe doesn't have inconsistent results)

It should be OK to stay on springs.   I typically home (and probe) once in the center of the bed.   And if the height isn't exactly right as it is printing the skirt, a double click drops you into Z-BabyStepping where you can quickly get things perfect.

If you have a Z-Probe...   You shouldn't need to make any hardware changes to bring up UBL.

**Comment by gcormier** [comment]
The issue is that the edges of the beds seem to have more give then the center of the bed, so I'm worried it will skew my resulting grid that Marlin uses. I could tighten the heck out of them to make them even stiffer I suppose?

**Comment by Roxy-3D** [comment]
No...   I wouldn't do that.    I guess it depends on your Z-Probe.   But most of them are very gentle (unless you drive the nozzle into the bed).   I doubt you will see much deflection based on the probe pressing down on the bed.

But here is the thing...   It just doesn't matter.    The probe is used to help automate the mesh generation process.   Even if the edges of the mesh are off because the bed was deflecting a small amount...   It won't hurt you.   When you do the G26 P C O3.5  to validate the mesh, you will see that the edges need improvement.   And with the Mesh Validation Pattern still on the print bed, you can edit those mesh points up or down.    You might add an extra iteration of G26 mesh validation followed by a G29 P4 R.   But you are going to get to where you want to be pretty quickly.

My startup GCode for the Slic3r doesn't even have a G29 in it.   The system loads the mesh and its active.   I home in the center of the bed and everything is alive and well.   Up until a week or so ago...  All of my machines had spring mounted beds.    I need that because its easy to make a firmware mistake and crash the nozzle into the bed.   But now I'm on a machine with solid mount for the print bed...  So no more nozzle crashes are allowed!

**Comment by gcormier** [comment]
Hmmm. Okay, I will have to check it out :)

Where is the best place to read up on UBL? Is there any Github issue that has steps to follow? Or somewhere documented? :) Dare I ask. Do you think it's ready for testing/playing with yet or should I give it a few more weeks?

**Comment by Roxy-3D** [comment]
There are bullet point lists in some of the UBL threads telling you the steps...   If you follow those lists, you will get a perfect mesh very quickly and will see very good results.    One thing that is important is get your Z_PROBE_OFFSET_FROM_EXTRUDER set very accurately.   That affects everything down stream in the process.    Make sure you can home (preferably in the center of the bed) and that you can print a calibration cube with no bed leveling active.   If you can do that...   Then just follow the bullet point list and you should get good adhesion across your entire bed.

> Dare I ask. Do you think it's ready for testing/playing with yet or should I give it a few more weeks?

I now have it running on all my printers and have been using it for 6 months.   I just started using it on my super nice gMax printer.   I was hesitant to do firmware development on that printer because I didn't want to do anything to damage it.    And doing firmware development, does result in the occasional nozzle crash.   But I am not that worried about that issue any more.   I'm now doing all my development work on that printer.    

As a 'Best Practice', if you enable UBL's bed leveling...   Tell it to home with a G28 but manually trigger the probe with the nozzle 4 or 5 inches above the bed.   Then tell it to automatically probe the mesh and keep triggering the probe with the nozzle well away from the bed (and keep a finger on the reset button).    If things work reasonably that way....   You should be ready to do it for real.

**Comment by Bob-the-Kuhn** [comment]
On one of the original questions ...

If you enable **Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN** (and disable **Z_MIN_PROBE_ENDSTOP**) and enable **ENDSTOPS_ALWAYS_ON_DEFAULT** (in Configuration_adv.h) then your nozzle/probe will act like an always on endstop.

You may have to re-define your Z_MIN_PIN to the one used by the probe.

**Comment by gcormier** [comment]
@Bob-the-Kuhn Awesome! So I can just have the same pin doing both functions? And it will ignore that endstop for probing operations?

**Comment by Bob-the-Kuhn** [comment]
It'll use the Z_MIN_PIN for both probing and homing.

**Comment by ghost** [comment]
@Bob-the-Kuhn 

Sorry for highjacking the ticket. I do not have found the option ENDSTOPS_ALWAYS_ON_DEFAULT in my tree. had it changed? I plan to use an microswitch for autoleveling. Both will be connected to z endstop pin, which is defined as 19 in my case.

**Comment by thinkyhead** [comment]
![image](https://user-images.githubusercontent.com/698003/39887262-656ecbac-5457-11e8-8b96-8bed760e29cc.png)
