### ISSUE TITLE
add a debug level to print when mouvements are finished

### ISSUE THREAD

**Issue by Cdriko** [MarlinFirmware/Marlin#6269]
Hello
For experimental purpose, I want to synchronize a python script on my computer with movements on the reprap.

For example if the program send "G1X25Y34F500" I need to do a calculus to know how long the program need wait before sending another sequence (or do anything else).
Experimentally it does work well because I think that the time of serial transmission count in the total time.

I tried M114 but this command give the "official" position (at the end of all current gcodes) but not the real one.

It would be great if it could be possible to set a debug level  for made that the machine return a message when all gcodes are finished processed.

**Comment by Bob-the-Kuhn** [comment]
In the last month or so the M114 command was changed so that it waits for all movements to be completed before reporting.  Will that do?

The counts in the M114 report gives the true location after you've done a G28.  The counts are relative to the 0,0,0 location.

On my machine I get the following after a power up.  I home in the +Z direction so G28 sets Z to Z_MAX_POS which is 200.
```
11:44:17.832 : N21 M114*20
11:44:17.848 : X:0.00 Y:0.00 Z:0.00 E:0.00 Count X:0 Y:0 Z:0
11:44:49.694 : N32 G28*34
11:44:52.070 : X:0.00 Y:0.00 Z:200.00 E:0.00 Count X:0 Y:0 Z:39702
11:45:14.181 : N41 M114*18
11:45:14.196 : X:0.00 Y:0.00 Z:200.00 E:0.00 Count X:0 Y:0 Z:39702
```
