### ISSUE TITLE
g29 probing above the printer

### ISSUE THREAD

**Issue by rareik** [MarlinFirmware/Marlin#6387]
Hello I have no idea what is going with this printer.  
when I use the G29 command it does some weird stuff.  
it starts it bed leveling 60 mm above the bed and continues to move up as it probes. I have pasted a video below. 
https://www.youtube.com/watch?v=7M2KmxTnUFE

**Comment by Bob-the-Kuhn** [comment]
I think the probing going higher is because your probe is always reporting TRIGGERED.   What's happening is the units always starts probing at a safe distance from the bed (assuming your config is correct) and then checks if the probe is triggered.  When the probe triggers it backs up to the higher of the safe height or the amount of Z_CLEARANCE_DEPLOY_PROBE (could be Z_CLEARANCE_BETWEEN_PROBES).  Since the probe is already triggered when the probe starts it'll raise by the set height, go to the next point, raise again, ...

If you do a M119 before and after G28 I'll bet it says the probe is triggered.

This is usually because the Z_MIN_ENDSTOP_INVERTING (or the Z_MIN_PROBE_ENDSTOP_INVERTING) flag is set incorrectly.  Other causes are bad cabling, connected to wrong pin, ...

Easiest way to see what it is to lower the head until you get close to the bed and then SLOWLY lower the head & do M119 commands until either the nozzle touches the bed of M119 starts saying OPEN.  If it starts saying open then just flip the flag.  If it always says triggered then you'll have to troubleshoot your wiring & pin definitions.
