### ISSUE TITLE
RCBugFix weird LCD screen at start up

### ISSUE THREAD

**Issue by cormier8** [MarlinFirmware/Marlin#6426]
Hi,

I'm using a VELLEMAN K8400 dual haeds 3d printer with RCBugFix.

Works fine, but I've a strange LCD screen at startup (see picture) :

![dscn5272_](https://cloud.githubusercontent.com/assets/5839816/25306037/2c0b8cfa-2786-11e7-806b-cb70c3473ee8.jpg)

temperatures and positions are reported correctly, but temperature tags are replaced by '\', there is a 'i' just before 'Z', and a '\" before SD ...

If I click on the knob, the tags are OK and the bug don't come back anymore.

So I think it's a LCD initialization problem and I'm looking for a command to add in setpup().

I explored ultralcd.h and .cpp, but I did'nt find any suitable command.

Any idea ?

**Comment by cormier8** [comment]
got it !

In file ultralcd_impl_HD44780.h, line 533, there is a '/*' which make lines 533 to 541 commented :

    /*    <- line 533
    lcd.clear();

    lcd_set_custom_characters(
      #if ENABLED(LCD_PROGRESS_BAR)
        false
      #endif
    );
    //*/ <- line 541

so, the lcd_set_custom_characters(...) is not executed and the custom characters are not restored after bootscreen, wich explain wrong tag and weird status screen.

**Comment by thinkyhead** [comment]
I'll have to check and see whether that is intentional or not, and how it got in.

**Comment by thinkyhead** [comment]
Actually it was an intentional patch, meant to hide the change of character set on the boot screen, (which looks glitchy). For some reason on my own unit the character set is changing. But I think it's because I have an SD card inserted, and this causes an extra init of the screen.

So, I will reinstate this code, but add a small delay to hide the glitch.
