### ISSUE TITLE
inline keyword has no effect in code size

### ISSUE THREAD

**Issue by trivalik** [MarlinFirmware/Marlin#6521]
Any idea how this should be? I removed several "inline" in the Marlin_main.cpp. But not effect.

**Comment by JustAnother1** [comment]
inline tells the compiler to not create a  callable code peace for that, but to put the code everywhere this function is called. So if a inline function is just called once then the code size will be about the same with or without the inline. If the inlined function is called from thousands of places then the code size will grow with inline enabled. inline is usually used to speed up the code. instead of calling a function the functions code is executed. This saves a few instructions due to the skipped function call.

Does this answer your question?

**Comment by thinkyhead** [comment]
In fact, `inline` only _suggests_ to the compiler that it can put the function inline. The compiler may or may not do so. And if you leave off `inline` the compiler may still decide to inline the function anyway.

**Comment by trivalik** [comment]
Sure, you are alright with that. Sorry.
