### ISSUE TITLE
Changing configuration at runtime

### ISSUE THREAD

**Issue by mathiascg** [MarlinFirmware/Marlin#6635]
Hi, I'm making a modification to my 3D printer to be able to change the hot end for another tool that doesn't require temperature control. Therefore I'd like to know if it's possible to change some definitions in the configuration file at runtime (such as disabling max temp/min temp errors, cold extrusion protection, etc), so as to be able to change the tool without re-compiling the code. Thanks!

**Comment by tcm0116** [comment]
>  I'd like to know if it's possible to change some definitions in the configuration file at runtime

Currently, no. This would have to be accomplished by building two versions of the firmware and then loading the proper one when you change the tool head.

This feature is something I've been rolling around in the back of my mind as I'm in the process of upgrading my printer to support multiple tool heads as well, and I'd rather not have to re-load firmware when changing the tool head. However, it will require a significant amount of effort to get working due to the heavy use of the C pre-processor, so I wouldn't expect to see it working any time soon.
