### ISSUE TITLE
v1.1.0 might have broke retract un-hop ?   

### ISSUE THREAD

**Issue by Squid116** [MarlinFirmware/Marlin#6652]
I have been running RC8 for a while with no issues and upgraded to 1.1.x when it was released.

This PR seems to be causing me grief, it never unretracts: https://github.com/MarlinFirmware/Marlin/commit/94ffb58da7d85f82c6a48917c2cf739f53f5e846

Even if you do nothing between retract and unretract, it doesn't ever unhop.  My c++ is a little rusty but I think hop_height should be set after the hop is performed, not before:

```
hop_height = current_position[Z_AXIS];
// Pretend current position is lower
current_position[Z_AXIS] -= retract_zlift;
```

should be:

```
// Pretend current position is lower
current_position[Z_AXIS] -= retract_zlift;
hop_height = current_position[Z_AXIS];
```

**Comment by Roxy-3D** [comment]
We need to get all bug fixes (and not necessarily all new features) crossed over from BugFix-v1.1.0 to v1.1.0

Right now... you are better off running BugFix-v1.1.0

**Comment by Squid116** [comment]
@Roxy-3D the same problem exists in RCBugFix, BugFix-v1.1.x and v1.1.x but it was never in RC - which is what I have been running.  I can't see how any branch including 94ffb58 would work.

**Comment by Roxy-3D** [comment]
OK.  Let's change the title and see if we can get some people to weigh in.   

How do we find the commit that caused it?

**Comment by FHeilmann** [comment]
It may be the commit that "broke" it was a result of the discussion I started in #5486
FWIW, my machine hops and unhops flawlessly with a firmware including 94ffb58 

regarding your code suggestion, I don't know why @thinkyhead chose to do it this way, but it works as expected.
What it does is, save the current z-height, and then lower the current z-position by z-hop. That way, 

```
 SYNC_PLAN_POSITION_KINEMATIC();
// Raise up to the old current_position
 prepare_move_to_destination();
```
will actually lift the nozzle until current_position[Z_AXIS] is equal to hop_height again.

Later, when unretracting, the hop is only undone when the z-position hasn't changed between the retract and the unretract.
The reason this was implemented is because G-Code, assuming a z-hop of e.g. 0.4mm, that does something like

```
G10 ; retract
G0 Z0.2 ; move nozzle to height of first layer
G11 ; unretract
```
would drive the nozzle into the bed with the original code because the z-height of the nozzle changed. My original discussion was started because this happened when I tried to put firmware retraction into G-Code generated by Simplify3D using simple REPLACE operations, which resulted in the above G-Code at the start of the print, resulting in my nozzle being driven into the bed every time. Check your G-Code if it does something like that. 
If it doesn't an exact G-Code sequence that exhibits the erroneous behavior would be helpful.

**Comment by Squid116** [comment]
Take this (extreme) example:

```
G28
M207 S8.00 F4800.00 Z10.00
G0 Z0.1
G10
G0 Z0.2
G11

G10
G0 Z0.3
G11
```

I'd expect the nozzle to be atZ=0.3 (the last of the G0 commands), however mine is ~20mm above the bed.

**Comment by FHeilmann** [comment]
yes, I see the problem, slicers with activated "retract between layer changes" will cause problems here.
The unhop doesn't happen because of the considerations outlined in my previous post and the discussion I linked. We'll have to find some sort of solution here.

Just for kicks, disable that feature in your slicer and see if that solves your problem (i.e. generate G-Code which has no Z-Moves between retract and unretract)

**Comment by Squid116** [comment]
I just deleted the  `&& hop_height == current_position[Z_AXIS]` and everything is back working as expected.

The only way I can see this being an issue is if you LOWER z while retracted.
```
G28
M207 S8.00 F4800.00 Z10.00
G0 Z10
G10
G0 Z3 //lower than before the retraction
G11 //crash!

```
I guess it is good to safe guard against a crash, but I don't see the scenario coming up in normal use.

**Comment by FHeilmann** [comment]
Yes, I agree, but instead of deleting it I'd suggest changing  ```&& hop_height == current_position[Z_AXIS]``` to ```&& hop_height <= current_position[Z_AXIS]```

which should solve your problem and keep the nozzle from crashing into the bed. I'll submit it as a pull request right away.

**Comment by Squid116** [comment]
@FHeilmann Agreed that would be a safe solution.

FWIW Even with retract on layer change disabled, Cura can be in a retracted move when the layer changes.  (it isn't retracting because of the layer change, but happens to change layer during a retraction).

**Comment by FHeilmann** [comment]
See #6656

**Comment by VanessaE** [comment]
Well that would certainly explain why my Z offset went all wonky after enabling FW retract today (because I enabled Z hop also).  :stuck_out_tongue_closed_eyes:

**Comment by Squid116** [comment]
Just referenced on https://github.com/MarlinFirmware/Marlin/commit/fee696db5d293d9a93997e25facc6448f6ee4abf

@thinkyhead This has been reverted and now I see the problems again.

As an aside - has unit/integration testing been considered for v2?  It really helps to be solve problems like this, I have plenty of experience (albeit not arduino/c++) in the field, I'd be happy to help out.

**Comment by thinkyhead** [comment]
A lot of reform was done to firmware retraction, so these issues should be well sorted out by now in the bugfix branches.

> has unit/integration testing been considered for v2? It really helps to be solve problems like this, I have plenty of experience (albeit not arduino/c++) in the field, I'd be happy to help out.

It's a pretty motley crew around here, most of whom hardly even understand git, and for the most part they don't seem too interested in adopting formal procedures. So, what are you proposing?

**Comment by thinkyhead** [comment]
@Squid116 We're increasingly interested in being able to make a build of Marlin that includes unit tests to make sure all functions are returning sane values. But, as you can imagine, this is not as straightforward in an embedded universe as it is in a "modern application." I'd be interested to see what unit tests would look like when applied in this milieu.

**Comment by Squid116** [comment]
@thinkyhead I'll see if I can put together a PR with some thoughts, covering (part of) a feature.  There are definitely challenges in the way it is written being embedded, but there are ways around that, namely mocking frameworks.  Unit testing purists will be up in arms and suggest that the design is wrong and you should never need to mock -  but in a more pragmatic approach a mocked test is better than no test.

My c++ is rusty, so it might take me a while get something together but I'll see what I can do.  I might create a separate issue about choosing a mocking framework? as that is a decision that everyone would need to be comfortable with.

**Comment by thinkyhead** [comment]
I look forward to your thoughts and ideas, even if only in rough form.

For AVR-only, were you aware that Ultimaker made a desktop environment where Marlin can be embedded and run? https://community.ultimaker.com/topic/10523-ultimaker-simulator-getting-started/ I'm not sure how useful it would be. I assume we want to exercise all the HAL code as much as we can too.
