### ISSUE TITLE
Missing ; in gcode.h

### ISSUE THREAD

**Issue by DaveAhrendt** [MarlinFirmware/Marlin#6849]
Compile error on line 230 in gcode.h when TEMPERATURE_UNITS_SUPPORT is defined.
Offending line is:
        return input_temp_units == TEMPUNIT_K ? PSTR("Kelvin") : input_temp_units == TEMPUNIT_F ? PSTR("Fahrenheit") : PSTR("Celsius")

**Comment by Roxy-3D** [comment]
So...   If GCC can have 1327 different ways to optimize the code,  how about they add an option to put in missing semi colons on your source file?  It knows where the semi colon is supposed to be.  It told you where the problem was.  How about the compiler just fixes the problem?

**Comment by Tannoo** [comment]
More of a travis test is needed for EVERY option.

**Comment by DaveAhrendt** [comment]
The ; is still missing on line 230 in 1.1.2 build

**Comment by Bob-the-Kuhn** [comment]
This was just fixed in bugfix-1.1.x via PR #6915.

**Comment by thinkyhead** [comment]
> More of a travis test is needed for EVERY option.

I'd like to see that, but it has to be done without significantly impacting the build time. If we wanted to methodically test every possible option on every possible board, with every possible LCD controller, it would make the Travis test time ridiculously long. So we have been selective. The best way to add more tests is to still maintain a small number of test builds, but enable a greater number of options under each build.

The other thing we don't have in the bundle is a helper script that allows us to test intentional build failures, but I'm sure that could be added.

**Comment by Roxy-3D** [comment]
> I'd like to see that, but it has to be done without significantly impacting the build time.

110% agreed....

**Comment by boelle** [comment]
@DaveAhrendt is the problem gone?

**Comment by DaveAhrendt** [comment]
As far as I know, yes.  I moved on to RRF on Duet some time ago so I’ve not kept up with Marlin.

**Comment by boelle** [comment]
dare i ask why you got the Duet?

**Comment by DaveAhrendt** [comment]
Really needed 32 bit for my larger delta and at the time Marlin 2.0 was not really ready for use.
I also really appreciate the “gcode for everything” approach of Duet and RRF.  Never have to recompile
to make changes.  Just edit a config file and reboot and you’re done.

**Comment by thinkyhead** [comment]
I've been using the Duet Wifi and RRF on the E3D Toolchanger beta, and it's pretty cool. I'm told the browser-based UI isn't as good as OctoPrint. I will have to try OctoPrint next!
