### ISSUE TITLE
1.1.2 G33 Bed Radius implausible

### ISSUE THREAD

**Issue by novio8** [MarlinFirmware/Marlin#6924]
Hi,
I'm struggling with `G33`,
when I send `G33` I get message `M665 Bed radius implausible`

I've increased or lowered
```cpp
#define DELTA_PRINTABLE_RADIUS 130
```
but I'm always getting `M665 Bed radius implausible`

If I run Delta Calibration from LCD
I can only run set Delta Hight and X,Y Z separately
and not Auto Calibration

I'm stuck
Any advice will be most welcome

Regards
Mario

**Comment by oldmcg** [comment]
If you have probe offset from nozzle, use this in your configuration.h if not already (all one line)

```cpp
#define DELTA_CALIBRATION_RADIUS ((DELTA_PRINTABLE_RADIUS) * 0.869 - HYPOT(X_PROBE_OFFSET_FROM_EXTRUDER,Y_PROBE_OFFSET_FROM_EXTRUDER))
```

Also, if you have probe offset from nozzle, wait for pending change from @LVD-AC.

Then, if you use EEPROM after recompile/upload make sure to do M502, M500 so the new settings you compiled are used instead of what was previously saved in EEPROM.  This bites me regularly.

**Comment by novio8** [comment]
thanx oldmcg,
I already find the same solution, a little more brutal: I'v just reduced calibr. ratius to 60
```cpp
#define DELTA_CALIBRATION_RADIUS 60
```
and now it seems to work, or I just don't get error message anymore
And I'm beaten every time I recompiling/uploading and forgetting that EEPROM holds
old memories
Regards
Mario

**Comment by LVD-AC** [comment]
That is why you can change this as well with e.g. `M665 B60`

**Comment by LVD-AC** [comment]
This issue can be closed!
