### ISSUE TITLE
Delta G33 Auto Level, Bed not leveled

### ISSUE THREAD

**Issue by novio8** [MarlinFirmware/Marlin#6997]
I have latest Marlin 1.1.3 I enabeled
delta Calibration wit fixed Z probe. I run G33 P7, everything goes well
M500, but the Bed is not leveled if I check it manually, about a millimetre 
or so in the center from the corners
Am I doing something wrong or ?

Please advise
Mario

**Comment by oldmcg** [comment]
Is your Z-probe in the nozzle or offset from the nozzle?  If offset from nozzle then you need pending PR #6850 from @LVD-AC, but that is for bugfix_1.1.x branch, not 1.1.3.  I recommend switching to bugfix_1.1.x branch, and if you have XY offset probe then manually apply the #6850 changes if you are able to do that.

My experience with G33 (with #6850) is that I still need UBL to compensate, but not nearly as much tilt shown in the bed in the UBL mesh due to G33 corrections.

**Comment by novio8** [comment]
My Z-probe's offset is only in Y direction. I'll try and apply 6850 changes. 
If I understand you correctly you still use UBL as your  Bed Leveling procedure.
I did not try UBL yet, Is there anythin specific fo Deltas, or anything else
as I'm getting frustrated wit AutoCalibration. I'v  returned to Marlin 1.1.2 and manually
calibrated the Bed, but I would really like to have AC, but don't wanna loose another 
4 days.

**Comment by LVD-AC** [comment]
Or you can use my rep https://github.com/LVD-AC/Marlin-AC; PR #6850 with the eccentric probe fixes is already merged in 1.1.3 there.

**Comment by novio8** [comment]
thanks, but that is just what I did. I upgraded from 1.1.2 to 1.1.3 and than my troubles started.
Maybe I made a mistake when I was editing new configuration file 1.1.3, I double checked new
configuration file ageinst the one from 1.1.2 and everything seems OK

**Comment by oldmcg** [comment]
For delta and specficially UBL on delta, stick with bugfix_1.1.x branch for now.  I just added another round of UBL on delta improvements a few days ago in bugfix_1.1.x.  

To do UBL bed leveling on delta, after G33 all done and saved, run G29 P1 to auto-probe, then G29 P2 to manually probe (with nozzle and paper and dial on the LCD) the few points the probe can't reach because it is offset from nozzle, then run G29 P3.15 (not yet documented) to extrapolate all the remaining mesh points, save it to eeprom with G29 S0, then give G26 a try to print a one-layer pattern to see how well it sticks to the bed.

**Comment by LVD-AC** [comment]
??? most of PR #6850 was already merged in 1.1.2-AC, 1.1.3-AC only has an extra small bug fixed in the LCD menu

**Comment by novio8** [comment]
thanks for UBL routine, I'll try it.
by staying on bugfix branch you mean  https://github.com/LVD-AC/Marlin-AC.
so if I just take config file from 1.1.2 to 1.1.3 it shoul work, if it works in 1.1.2

**Comment by LVD-AC** [comment]
https://github.com/LVD-AC/Marlin-AC is Marlin 1.1.3 with #6850 included
Latest bugfix-1.1.x you find at https://github.com/MarlinFirmware/Marlin/tree/bugfix-1.1.x but you will have to merge #6850 yourself (or wait until @thinkyhead finds the time to do it)

**Comment by novio8** [comment]
I downloaded https://github.com/LVD-AC/Marlin-AC is Marlin 1.1.3 with #6850 included
and I'll try again

**Comment by GibaHC** [comment]
With the stable 1.1.4, is the UBL working for deltas ? The UBL documentation on the site is from 1.1.2 and could not clarify that. 
I am currently using ABL bilinear after g33 auto calibration, but I can't print large objects. The mesh can't compensate far from the middle. Maybe UBL is a step forward.

**Comment by Roxy-3D** [comment]
UBL should be working in 1.1.4 for Delta's.   It should be able to compensate for a Cup & Bowl problem on a Delta bed.

**Comment by GibaHC** [comment]
Today I tried the UBL. Manage to get a nice flat middle bed, but the 5cm away from the center I got some problems. Probably because I couldn't probe  manually the points that are unreachable for auto probing. I'll give another try as soon as my screen arrives. 

When configuring the UBL, I had to set 3 points in bed for eventual 3 point mesh. Nothing hard, but ... if the size of the bed is already set in config, why aren't they calculated instead of user declared?

**Comment by oldmcg** [comment]
Regarding the 3-point for UBL on delta, I have changes pending to make that automatic, removing the #defines from configuration.h, but have to wait for 32-bit merge to get that in.  

Realistically I would not choose to use the 3-point leveling feature of UBL.  I use a 11x11 grid and let it auto-probe anytime I change the glass.  G29 P1 to probe, then G29 P3.14 to interpolate all the unprobeable points.  Much better than using 3-point.

Oh, and set UBL_MESH_INSET to zero -- just make sure your DELTA_PRINTABLE_RADIUS and probe X/Y offsets are correct, and it won't try to move outside that.

**Comment by Roxy-3D** [comment]
The 3-Point 'Leveling' or tilting of the mesh is included in UBL just for completeness.  3-Point was the original bed leveling.   So just from that perspective it should be included.  But if you are going to tilt the mesh, a 3x3 or 4x4 grid will give you results you can have more confidence in.  (That would be G29 J3)

**Comment by oldmcg** [comment]
I don't think my G29 J3 for delta changes made it in before the freeze.

**Comment by GibaHC** [comment]
I'am still validating and correcting the edges. But I found out that my effector tilt changes next to the edges. This problem lead to reading errors of the Allen key probe. In fact, all the mesh reading os the probe where shifted by the y probe offset in the wrong direction, comparing with a mesh entirely done by manually probing the bed with the nozzle and paper. 

Ex: with the nozzle at x 0 y 84 the probe is at x 0 y 65, and the z height it reads is set for the I 7 J 12 point instead of I 7 J 14 (15x15 mesh). Probing with the nozzle resulted in a bigger printable flat area in the middle.
