### ISSUE TITLE
Compile Error PlatformIO

### ISSUE THREAD

**Issue by Grogyan** [MarlinFirmware/Marlin#7105]
PlatformIO reports compile errors of 
Missing binary operator before "("

Way I tested this is to open up a fresh copy of Marlin 1.1.3 in PlatformIO
Adjust the temperature sensor from 1 to 2 in Configuration.h this is so the Linter actually shows that there are compile errors
Eg
#if ENABLED(SWITCHING_EXTRUDER)
The "ENABLED" part appears to be unsupported, producing, Missing binary operator before "("  error

**Comment by p3p** [comment]
The linter errors, as far as I can tell, are a problem with the PlatofrmIO linter, The project compiles successfully. I'm unsure why the linter can't see the macros.h file, perhaps it is unable to parse preprocessor stringification (stringified?) macros correctly, I'm not sure there is anything we can do about them but I could be wrong.

**Comment by Grogyan** [comment]
It will need to be addressed shortly as 32bit support via PlatformIO is just around the corner as the baseline compiler methinks. 
But it also fails the same regardless of board

**Comment by Roxy-3D** [comment]
It would seem we should spend some time and get all the lint errors to go away...

**Comment by thinkyhead** [comment]
Linters operate on each file individually, so if a given single file can't compile as a standalone unit, the linter will miss some symbols. This is also true of any `.h` files. Marlin has some careful ordering of headers and config files, as enforced by `MarlinConfig.h`. For most files to compile within the linter, they must at least have `MarlinConfig.h` explicitly included.

A file like `Configuration.h` is only ever **included** — it is not compiled by itself. And so it has been scrubbed of any `#include` lines. To make the linter happy, it should be safe to add any of the includes that appear before `Configuration.h` in `MarlinConfig.h`.

The new file layout will be favoring `.h` files and retaining the same basic compilation units, rather than (for example) putting every gcode handler into a separate `.cpp` file. Linters won't like it. But this is for expediency. In future, gcode handlers may be in individual `.cpp` files. But this will require exposing all the globals of `Marlin_main.cpp` and various other changes.

The code organization continues to evolve. We can keep in mind ways to make it more linter-friendly as we go forward.

**Comment by Phr3d13** [comment]
Can this be closed?

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by boelle** [comment]
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by GadgetAngel** [comment]
How did you fix this problem? Atom/PlatformIO will generate a firmware.hex file but I get all these errors from LINT how do I fix this

![compile_errors_with_MarlinV2 0_with_ATOM_PlatfromIO](https://user-images.githubusercontent.com/33468777/69637682-27757700-1027-11ea-8ca9-815a3a62860d.png)

Please re-open this or tell me how to fix the errors.

**Comment by jicefrost** [comment]
I got same trouble(( Just install atom and PlatformIO and same mistakes as on skreen above

**Comment by Vertabreak** [comment]
fairly sure the use of atom was deprecated in favor of platformio on vscode.
warnings should in general be disregarded only real errors are a problem and prevent compile.
marlin auto build is also a great option.

**Comment by thinkyhead** [comment]
The [Auto Build Marlin](https://marketplace.visualstudio.com/items?itemName=MarlinFirmware.auto-build) extension in VSCode is the way of the future.
![image](https://user-images.githubusercontent.com/698003/76157101-0adae780-60ca-11ea-8582-b286aeb8ac29.png)

**Comment by jicefrost** [comment]
Same to me. Tried to use visual code - get no warnings and errors and compile good. Problem solved. Sad that the atom be like this(

**Comment by thinkyhead** [comment]
Atom really should get a rewrite. But then it would just end up being VSCode.
