### ISSUE TITLE
G29 in a DELTA printer doesn't work

### ISSUE THREAD

**Issue by ihouses** [MarlinFirmware/Marlin#7159]
Hello,

I am trying to make work the G29 command in a delta printer. I am using a induction probe. 
I can calibrate the printer and measure the hight using the menu option without problem.

When I execute G29 (after G28) the noozle comes down a bit and later on does a movement that brings it out of the printer are, something like smashing the lateral part of the printer. No idea what is the problem here. I am using the last version of the marling 1.1.x bug_fix. I attach the config.h (renamed to .txt)  just in case can be userful.

Thanks!
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/1105813/Configuration.txt)

**Comment by Roxy-3D** [comment]
It is not required...  But it is a good idea to turn on

#define Z_SAFE_HOMING   and to set the Z-Home location to the center of the bed.   This helps for a number of reasons.  One of them is it minimizes how far any bed location is from the home location.

You also want to turn off:

//#define MIN_SOFTWARE_ENDSTOP

with UBL.   The reason is you probably need to allow the nozzle to go below 0.000 mm to accurately track the bed.   At least in some locations of your bed.

But here is something else confusing about your message.   With UBL turned on...  UBL's G29 doesn't do anything unless you give it some more parameters.   

My suggestion is you make sure you can print small objects reliably at the center of the bed with no bed leveling active.   Do that first.   And only after you can do that, turn on the bed leveling.    

Otherwise, you will be fighting too many problems at once and you won't know where the root cause of the problem is.
