### ISSUE TITLE
EEPROM_CHITCHAT PROGMEM usage comment in Configuration.h

### ISSUE THREAD

**Issue by fiveangle** [MarlinFirmware/Marlin#7203]
The claim [here in Configuration.h](https://github.com/MarlinFirmware/Marlin/blob/bugfix-1.1.x/Marlin/Configuration.h#L994-L997) is ~1700bytes are saved, but I'm seeing just 86bytes (no change in SRAM usage):

```
#if ENABLED(EEPROM_SETTINGS)
  // To disable EEPROM Serial responses and decrease program space by ~1700 byte: comment this out:
  #define EEPROM_CHITCHAT // Please keep turned on if you can.
#endif
```

Could it be compiler efficency improved so much as to make this comment moot ?

**Comment by thinkyhead** [comment]
A very outdated comment. I think it was confused with `DISABLE_M503` since it doesn't remove any code.

Try `DISABLE_M503` to save `PROGMEM` instead. I found that it saves ~2740 bytes with default config on my test, useful to get Marlin down to an even smaller size.

The PR below exposes `DISABLE_M503` as a user-facing config option.

**Comment by fiveangle** [comment]
DISABLE_M503 behavior Confirmed and saved 3084 bytes on my AT90USB system - huge help for not a lot of functionality loss (just 501, 500 back and forth and remember what changes you've made).  And the Printrbot rides again - thanks Scott !
