### ISSUE TITLE
[FR] Configurable pause before probing

### ISSUE THREAD

**Issue by DjDemonD** [MarlinFirmware/Marlin#7283]
Hi all,

I now market and sell an open-source piezo Z-probe. More details can be found online at reprap forum, just see the general forum main page, I won't leave any spam here.

What we are interested in is having a configurable pause before a probing dive takes place. RRF already has this as DC42 and T3P3 are making a nozzle contact probe based on piezo like we do, and the M558 command now has an R (recovery) parameter which is pause (in seconds) after positioning over a probing point before diving to probe. A value of 0.2sec is usually enough. It allows mechanical noise to settle before probing and reduces/eliminates false triggers from this very sensitive probe.

These things are becoming quite popular now as they are by far the most convenient and accurate z-probe available.

Would you consider implementing it for the benefit of the now hundreds of people using piezo z probes? I know you don't use M558 so it would have to be an option in configuration_adv, "recovery time before probing move" or something like that?

Kind regards
DjDemonD/Simon
Precisionpiezo.co.uk

**Comment by teemuatlut** [comment]
Would you be able to make it into a pull request?
The added feature itself sounds simple enough but as none of the Marlin developers have the module, it would be difficult to test it out before pushing it online. Or would you be willing to send out a test unit?

**Comment by DjDemonD** [comment]
I would happily make it into a pull request but I haven't forked Marlin and amended the code, so I'm not sure how I would do that?

I can ship a test unit out to someone to try.

**Comment by teemuatlut** [comment]
I'd be happy to help. It seems like an interesting approach to implementing a z-probe. I can also make sure it works with the TRAMS platform as well.

**Comment by DjDemonD** [comment]
Okay PM? me your details and I'll sort something out for you.

**Comment by teemuatlut** [comment]
GitHub removed private messages a few years back.
Can I instead email you at precisionpiezo (at) yahoo.com ?

**Comment by DjDemonD** [comment]
yes thats fine

**Comment by FHeilmann** [comment]
Marlin already has facilities that can be used for this via the `PROBING_FANS_OFF` and `PROBING_HEATERS_OFF` options. I am going to forego the M558 G-code here since all you need is a delay that can be adjusted via the configuration:

In configuration_adv.h specify your delay in miliseconds, i.e.:

```C
#define PAUSE_BEFORE_PROBING
#ifdef PAUSE_BEFORE_PROBING
  #define PAUSE_BEFORE_PROBING_DELAY 200
#endif
```

In Marlin_main.cpp [@2043](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/Marlin_main.cpp#L2043)
change:
```C
  #if QUIET_PROBING
    void probing_pause(const bool p) {
      #if ENABLED(PROBING_HEATERS_OFF)
        thermalManager.pause(p);
      #endif
      #if ENABLED(PROBING_FANS_OFF)
        fans_pause(p);
      #endif
      if (p) safe_delay(25);
    }
  #endif // QUIET_PROBING
```
to:

```C
  #if QUIET_PROBING
    void probing_pause(const bool p) {
      #if ENABLED(PROBING_HEATERS_OFF)
        thermalManager.pause(p);
      #endif
      #if ENABLED(PROBING_FANS_OFF)
        fans_pause(p);
      #endif
      #if ENABLED(PAUSE_BEFORE_PROBING)
        if (p) safe_delay(PAUSE_BEFORE_PROBING_DELAY);
      #else
        if (p) safe_delay(25);
      #endif
    }
  #endif // QUIET_PROBING
```
and, to enable the whole block, in [Conditionals_post.h@655](https://github.com/MarlinFirmware/Marlin/blob/e68b7afc52792ef7e97dbefc19c82d5b4902744e/Marlin/Conditionals_post.h#L655)
change 

```C
#define QUIET_PROBING (HAS_BED_PROBE && (ENABLED(PROBING_HEATERS_OFF) || ENABLED(PROBING_FANS_OFF)))
```
to
```C
#define QUIET_PROBING (HAS_BED_PROBE && (ENABLED(PROBING_HEATERS_OFF) || ENABLED(PROBING_FANS_OFF) || ENABLED(PAUSE_BEFORE_PROBING)))
```


that should do it. However I have just typed this out hastily and there may be a bug or two to fix, but you get the idea. Do this to your own local copy of marlin, and if it works we (you or me or whoever) can submit it as a pull request for the main devs to consider

**Comment by DjDemonD** [comment]
Thank you that's very helpful, no further action required then.

So whats required to get this into the latest version?

**Comment by FHeilmann** [comment]
You're welcome, also, nice effort, this would probably work a lot better than my current nozzle microswitch design so I'll be watching out for your results :)

**Comment by FHeilmann** [comment]
If you need any more testers let me know, I'd be eager to put one these on my CoreXY too.

**Comment by DjDemonD** [comment]
We are past the testing stage with Piezo module and piezo kits, but we have some new ideas in the pipeline and some coding help might be needed.

**Comment by inventabuild** [comment]
Sorry, but the above does not work to delay the reading of the Piezo Board information on the RAMBO Board.  I tried numbers as high as "#define DELAY_BEFORE_PROBING 10000" and as soon as my hot end finishes homing x and y and starts homing z the Piezo sensor triggers the Piezo Board's blue light and z min is triggered causing the hot end to rise immediately.

If the delay was working my hot end should travel down for a designated number of seconds (or wait for designated number of seconds before traveling down) before allowing z min to trigger.  Neither of those is happening.  Marlin zip file attached.
[Printer_2_Marlin-src_1.1.9.34.zip](https://github.com/MarlinFirmware/Marlin/files/3935886/Printer_2_Marlin-src_1.1.9.34.zip)

**Comment by inventabuild** [comment]
Never mind I see this is designed to only run after G29.  I can control my G28 by running G28 X0Y0 first then running G28 Z0.

**Comment by inventabuild** [comment]
In parting, because it's after midnight here, I'll mention I think it would be better to have a delay that allows the hot end to start traveling downward for x millisec before accepting input from the probe.  I noticed that after running G28 X0Y0 from pronterface, pausing then running G28 Z0, the probe still triggers right away.

However if, after running G28 X0Y0, I run G91, G1 +Z10, G1 -Z10, I wait for the moves to finish then run G29 I can get the probe to tap the bed.  However, I cannot guarantee this will work every time as there is obviously more noise in the printer's mechanisms when starting the hotend in its travel downward (acceleration) than after it is already traveling smoothly (velocity).

So I would appreciate it if you would add the ability to delay probe triggering for x millisec after the hotend starts it's downward travel for both G28 Z0 and G29.

**Comment by DjDemonD** [comment]
Hi. Not a marlin dev, but I am one of the originators of the piezo probe. If the level of mechanical noise in your machine is such that the probe triggers despite being set (on the piezo pcb) for a lower sensitivity, and despite using temporary settings to set jerk to 0, and reduce acceleration to a very low setting, then delay before probing even after the z movement begins, isn't going to help. It was mainly to reduce the effect of ringing from xy movement before commencing a probing dive. With temporarily low acceleration and jerk, the inertia of the probing dive shouldn't trigger the probe. If the mechanics of your printer are this noisy then, start there. I have an unber-bed setup on one machine, so sensitive I can blow on the bed and trigger it, but with low jerk/accel it probes normally.
