### ISSUE TITLE
Mesh Level stuck in LOOP

### ISSUE THREAD

**Issue by ZhuDaHai** [MarlinFirmware/Marlin#7491]
### Bug Report
- Description: Marlin 1.1.4 Mesh Level restarts after completing. Cannot exit loop
- Expected behaviour: Once Mesh level is completed, it should return to the menu. It does not, I just restart Mesh leveling again
- Actual behaviour: Mesh leveling begins again after finishing. Cannot break out of loop
- Steps to reproduce: Start Mesh leveling. You can't end it
 Attach a ZIP of `Configuration.h` and `Configuration_adv.h` by dropping here.

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1220196/Configuration.zip)

**Comment by oysteinkrog** [comment]
Mesh leveling or UBL?
Could you try UBL instead?

**Comment by fiveangle** [comment]
> Mesh leveling or UBL?

Configuration.h shows MBL with BLTouch for homing.  It should not be doing that so we want to fix it (rather than switching to another levelling system).  My printer is being converted to Re-ARM so can't test this myself.

Can you enable bed levelling debug, rerun the process, then upload a zip of the resulting terminal output ?  This will hopefully show what is happening when you (should) get the end.

**Comment by ZhuDaHai** [comment]
Here's some more clues. About 30% of the time, Mesh Leveling completes properly and returns to the main screen. The other 70% of the time it loops back into Mesh Leveling Mode.
However, I've done Mesh Leveling with Debug enabled 3 times and it has not looped. Grrr. Some maybe a timing issue or uninitialized variable?
Anyway, here the the debug output from a (successful) Mesh Leveling process. I'll keep trying to get it to loop with debug on.
[Mesh Level Debug - No Loop.zip](https://github.com/MarlinFirmware/Marlin/files/1221067/Mesh.Level.Debug.-.No.Loop.zip)

**Comment by EddieFerg** [comment]
I'm seeing the same behavior as ZhuDaHai posted at the top, but with Marlin 1.1.5
I'm using:
#define MESH_BED_LEVELING
#define LCD_BED_LEVELING
After adjusting Z on the final point and pressing the knob, it Homes XYZ, then displays "Click to Begin".  I'm now stuck in the Mesh creation loop and can't exit.
This issue is repeatable on my printer.
However, with #define DEBUG_LEVELING_FEATURE enabled & issuing M111 S34, Bed Leveling upon completion exits to the Main Menu as expected 50% of the time.  
So my observations are close to what ZhuDaHai sees, and it would appear to be a timing issue.

[Mesh Level Debug - Stuck in Loop.txt](https://github.com/MarlinFirmware/Marlin/files/1294936/Mesh.Level.Debug.-.Stuck.in.Loop.txt)

**Comment by fiveangle** [comment]
You say it happens with debug enabled 50% of the time, so it would be useful to have the debug output for an instance when it exhibits the problem.

**Comment by EddieFerg** [comment]
Added Debug text file "Mesh Level Debug - Stuck in Loop.txt" to my comment above.  
This is a Bed Level that did not return to the Main Menu upon completion.

**Comment by OutsourcedGuru** [comment]
You should probably ignore me since I've not really looked into this much.

Line 41 in [mesh_bed_leveling.cpp](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/mesh_bed_leveling.cpp) calls a reset after doing the sampling. That reset() sets the status attribute to none. If whatever called the routine is looking at status then this could be why it's looping.

**Comment by thinkyhead** [comment]
Moving discussion to #7912
