### ISSUE TITLE
I need a working config for Auto Bed Leveling

### ISSUE THREAD

**Issue by CatsForThrones** [MarlinFirmware/Marlin#7689]
I tried so much now to get my bed leveling working. Does anybody has a config file which works for an induction probe to do bilinear auto bed leveling?

**Comment by guiseco** [comment]
What kind of problem do you have ?

**Comment by Tannoo** [comment]
Please follow the template that you deleted. It will help us help you.


Thank you for submitting your feedback to the Marlin project.
Please use one of the templates below to fill out this box.

------------------------------------------------------------
### Feature Request
Please put [FR] in the issue title: `[FR] Add-on that goes 'ping'`

------------------------------------------------------------
### Compile Error
When I compile with `FEATURE_X` I get an error:
```
Paste_the_error_text_here
```

------------------------------------------------------------
### Bug Report
- Description: ---
- Expected behaviour: ---
- Actual behaviour: ---
- Steps to reproduce:
  - Do this
  - Do that

Attach a ZIP of `Configuration.h` and `Configuration_adv.h` by dropping here.

------------------------------------------------------------
### Bug Report Tips
- When troubleshooting, use `M502` followed by `M500` to reset EEPROM to defaults.
- Use `DEBUG_LEVELING_FEATURE` with `M111 S247` for detailed logging of homing/leveling.
- Format text with: **bold**, _italic_, `code`.
- Format C++ with three backticks, plus "cpp":
```cpp
void my_function(bool do_it) {
  // Hold this spot
}
```

**Comment by CatsForThrones** [comment]
I already posted a detailed issue. ( https://github.com/MarlinFirmware/Marlin/issues/7652 )
However I thought now that it may be easier just to get a config which works for probing and ABL and then adapt it to my printer.

**Comment by Tannoo** [comment]
Well, just configure it for your printer. That will be faster.

**Comment by CatsForThrones** [comment]
Not really becuase whatever I change The problem I have stays, so I thought I try a working config. So if somebody has a **Working Config.zip for an Induction Probe** give it to me pleaaaase.

**Comment by Tannoo** [comment]
Download and try the latest `bugfix-1.1.x`.

**Comment by Tannoo** [comment]
If you tried to run my configs, you would likely get compile errors.

**Comment by CatsForThrones** [comment]
Thanks for every help, I got it mostly fixed now. Therefore I will close this :)
