### ISSUE TITLE
upgrading from 1.1.5

### ISSUE THREAD

**Issue by novio8** [MarlinFirmware/Marlin#7937]
Hi,
I have Delta Kossel XL. I want to upgrade from 1.1.6
just by copying mh configuration.h and configuration.adv.h
to new 1.1.6. 
Any reason not to ?
Regrds
Mario

**Comment by Festivejelly** [comment]
Have a look at the release notes here: https://github.com/MarlinFirmware/Marlin/releases

**Comment by psavva** [comment]
The configuration files change in both format and content.

You need to use the new config files always, and port any changes you made to the config in order to have a good configuration.

You can use a diff tool to help you understand what changes you made when comparing the new config file and your modified config file.
