### ISSUE TITLE
Dual Z axis Homing with 2 end stops

### ISSUE THREAD

**Issue by barsamgr** [MarlinFirmware/Marlin#809]
Hello,

I have setup a 3D printer which uses 2 steppers for the Z axis.  Everything is working perfectly but I have a little issue that I was trying to figure out if I can automate it at every homing process.  The issue is that sometimes the left and right leads of the Z axis are miss-aligned and I have to align them manually (usually I have a difference of max 0,05mm). Most of the times I do not check it because I am lazy to do it.
So I was thinking if there is a way to add a second end stop (I already have a Hall-O type endstop at the Z min which is very accurate so homing is perfect each an every time when the left and right leads are aligned), and home each stepper separately.  I had this idea while I was Building/setting up a delta printer and I saw how the homing is behaving.  The idea is the same. Move both steppers to min and stop each one separately when the relevant endstop is triggered.

Do you thing that is it possible to do something like that? I could try to code it my self, but I have no idea where to start.  If someone can guide me maybe I could manage it.

**Comment by boelle** [comment]
at least this assume that the bed is perfect level with the end stops...

if just one of the endstops are a micron higher or lower than the other the X axis will never be parallel with the bed

also to consider is how much gain there is adding the feature compared with the effort and code  needed to add the feature...

**Comment by thinkyhead** [comment]
Manual or automated bed leveling will compensate for out-of-alignment Z ends. But in general these ends should be adjusted mechanically before doing any other bed leveling compensation, including when adjusting the bed screws.

**Comment by boelle** [comment]
what i do on my mendel90 is that at one end of the bed i have 2 pillars that are not adjustable.... i lower the nozzle to  8mm between the middle of the pillars and then i use a short lenght of smooth rod to know that i'm at excatly 8mm. then i go to left and right corners and adjust to excatly 8mm... it takes some back and forth.

once i got this right i go to the 2 remaining corners and adjust the pillars to get excatly 8mm also.

just because i like to be precise i repeat the whole thing again with a 0.05mm feeler blade

not sure if the same idea could be usefull in this case? but at least to make it automatic / semiatutomatic it requires individual drivers for each Z and a touch probe

**Comment by AnHardt** [comment]
@barsamgr 
This feature is in Marlin since Mar 24 2015.
https://github.com/MarlinFirmware/Marlin/commit/0ce35766855c53c95df9d7e065f774534937df96
