### ISSUE TITLE
[help] Follow z-height with extruder or camera

### ISSUE THREAD

**Issue by Hywelmartin** [MarlinFirmware/Marlin#8449]
Feature Request

I have a delta and a spare stepper E1 output that that could be used for a new axis to follow print hight. my plan was to mount the my camera and a swivelling extruder on this axis.. but I need help to code this

**Comment by thinkyhead** [comment]
This is not a straightforward thing to do at all. Changes would need to be made all the way down to the Stepper::ISR. My suggestion would be to enable `Z_DUAL_STEPPER_DRIVERS` which will automatically assign the extra Z stepper to your next unused E stepper driver. Then build your camera rig to use exactly the same Z raise mechanism as your machine, or otherwise gear it so that the same number of steps results in the same amount of movement.

**Comment by Hywelmartin** [comment]
If it was an cartesian printer that seems like an solution, but on an delta printer? I tough that this feature [Z_DUAL_STEPPER_DRIVERS] sends the same information to driver module X and E1..

**Comment by AnHardt** [comment]
Marlin is made for 4 independent axes (XYZE or ABCE). 
Wanting more means a more or less complete rewrite.
So - no way.

**Comment by Hywelmartin** [comment]
@AnHardt That was already clarified , thank you for your time spent..

But what happens if I enable the Z_DUAL_STEPPER_DRIVERS feature when running delta kinematics, as I mentioned before, Will the A(X) stepper and the E1 move the same?

I can try that myself, but if anybody knows it's less of an hassle ....

**Comment by thinkyhead** [comment]
Yeah, sorry. `Z_DUAL_STEPPER_DRIVERS` is not possible on DELTA. Here's another concept:

Implement your camera rig as E1. Add to your G-code something akin to this:
```gcode
T1 ; Select camera rig (E0)
M83
E0.2 ; Raise by 1 layer or so
M82
T0 ; Back to E0
```
This won't work completely without a code tweak to preserve the E positions for T0/T1 separately, because internally Marlin has only one E position. But it will make it possible to move the camera axis between layers. You just need to enable `DISTINCT_E_FACTORS` and supply the correct `STEPS_PER_UNIT` for E1.

**Comment by Hywelmartin** [comment]
I have to look in to that next week. My main use for this is not camera but extruder( sort of flying to reduce bowden tube length) but the camera will tag along

**Comment by Hywelmartin** [comment]
Closing this one
