### ISSUE TITLE
Odd single thickness wall bug

### ISSUE THREAD

**Issue by mattsch** [MarlinFirmware/Marlin#853]
I had submitted this issue over to Slic3r first ([#1873](https://github.com/alexrj/Slic3r/issues/1837)),  moved here after their review.

When trying to print the standard 20mm calibration cube to calculate extrusion multiplier with the extrusion width set to .40mm, I get a very interesting leaning tower (picture attached).  If I let Slic3r do it's own calculation, bump the width up manually to .48mm, or rotate the cube 45 degrees before slicing then it prints perfectly.

I went through and checked all my mechanics, haven't had any other issues manifest that would indicate faulty parts.  I'm running the latest from the Marlin_v1 branch and my repo with configs is [here](https://github.com/mattsch/Marlin/tree/mendel90_lcd).

![img_20140317_110330](https://f.cloud.github.com/assets/134440/2495123/95177e40-b2e8-11e3-83a1-c6db8da6e0d2.jpg)

STL, gcode, etc:
http://www.excentral.org/files/slic3r_thing_wall_bug.tar.gz

**Comment by barneycg** [comment]
Sorry to resurrect this but I spent the weekend trying to diagnose why this was happening.

I've been using Slic3r 1.1.7 and I've hand checked the gcode and the start corner x and y coordinates are the same for every level.  I measured the position of the bed on the y axis compared to the frame on my Prusa i3 at the first later and again on the last layer, and the bed is indeed 5mm closer to the frame at the end (the z axis is at 20mm at this point).  The angle of the lean is consistent across prints and too regular within each print to be slippage but I could see or hear no evidence of it while watching several test prints.

The test cube was printed with layer height 0.25 with an extrusion width of 0.5 and 0.55 and 0.3 with extrusion widths of 0.6 and 0.66 ... all exhibited the same behaviour.  Changing Slic3r to do 2 shells or to use infill "fixed" the problem and resulted in a very nice cube.

I tried updating Marlin to the stable version in the Repo and still no change, but I've yet to try another Slic3r but will so at the next opportunity.

**Comment by galexander1** [comment]
Um, either your travel speed is 175mm/s or it isn't and avoiding the
question won't help you fix it.

**Comment by barneycg** [comment]
My travel speed has never been 175mm/s I'm a different person to the person who raised this originally ;).  I will reslice and set all my speeds manually to 5mm/s to confirm.

**Comment by galexander1** [comment]
oh :)

**Comment by mattsch** [comment]
I'm the original submitter, can confirm I still see this under the same conditions.  I'm 100% certain it's not a calibration or other mechanical issue since I only see it in this specific use case.

**Comment by galexander1** [comment]
@mattsch uh, if you're saying that because your robot is reliable it cannot have mechanical problems, would you not also say that because it is reliable it cannot have firmware problems?  It is not wrong to suspect the firmware, but it has not been proven yet.

Anyways,can you tell me: have you tried reducing your travel speed and acceleration settings?

**Comment by mattsch** [comment]
What I'm saying is that I can ONLY reproduce this bug under a very specific set of circumstances and it does NOT show up anywhere else.  I've printed much more complex figures with larger jumps without any loss in accuracy or drift like this.  As barneycg pointed out, there's no travel other than in z at the end of each layer.

I have had to adjust both travel speeds and accel as I've fine-tuned this printer, and I'm familiar with what it looks like when you lose steps or overshoot due to moving too fast.  This isn't that.

**Comment by galexander1** [comment]
Well, if it is a firmware bug, it would be an interesting one, and we need someone who can debug to try to reproduce it.  I have a delta so I doubt it can be me.

**Comment by barneycg** [comment]
Also I can mitigate the problem by adding a 2nd shell ... this inner shell is actually printed faster than the outer one due to my slic3r settings yet somehow this is enough to print a perfect cube with walls that are the expected thickness (ie 2 shells worth).  That is 3 physically different printers with (if I'm interpreting Mattsch right 2 different designs) that see the same problem.  Though I am a little puzzled that Mattsch see's it in the x axis and I'm seeing it in the y axis

**Comment by nophead** [comment]
It would be useful to know what the offset between layers is on terms of micro steps and motor steps. If it is exactly four motor full steps then the motor is skipping as the firmware and electronics work in microsteps.

**Comment by barneycg** [comment]
I was doing 0.25 layer height on 1/16 microstepping with 1.8 degree motors and GT2 belts with 20 tooth pulleys and m6 z axis.  
I'm not sure this maths is correct but :
The top is 5mm further forward than the bottom and it is 20mm high @ 0.25 mm layer height there is 80 layers ... the angle is consistent so that would make each layer offset by about 0.0625mm which with 80 steps per mm for the belts is 5 steps.  Which since there are 80 layers means 0.0625 steps per layer :) - which is exactly 1 microstep per layer.

Does that sound right or have I got it completely wrong ?

**Comment by nophead** [comment]
Yes 5mm over 80 layers is 0.0625mm per layer, I am with you so far. One micro step is 1/80 = 0.0125mm so the offset is 5 microsteps per layer.

That is an odd amount so I am guessing it is perhaps related to the number of changes in direction per layer. What does the gcode for one layer look like?

**Comment by barneycg** [comment]
I'm confused ... where do you get 1 microstep being 1/80 from ? I though that if the steps per mm of the y axis = 80 then the 0.0625mm offset per layer is 5 steps (80*0.0625) not 5 microsteps.

anyway layer 3 ( the first single shell with no infill looks like ):
G1 Z0.750 F9000.000 ; move to next layer (2)
G1 X99.750 Y109.750 F9000.000 ; move to first perimeter point
G11 ; unretract
G1 X80.250 Y109.750 E2.33288 F311.760 ; perimeter
G1 X80.250 Y90.250 E4.66576 ; perimeter
G1 X99.750 Y90.250 E6.99863 ; perimeter
G1 X99.750 Y109.690 E9.32433 ; perimeter
G10 ; retract
G92 E0 ; reset extrusion distance

and layer 80 looks like :
G1 Z20.000 F9000.000 ; move to next layer (79)
G1 X99.750 Y109.750 F9000.000 ; move to first perimeter point
G11 ; unretract
G1 X80.250 Y109.750 E2.33288 F311.760 ; perimeter
G1 X80.250 Y90.250 E4.66576 ; perimeter
G1 X99.750 Y90.250 E6.99863 ; perimeter
G1 X99.750 Y109.690 E9.32433 ; perimeter
G10 ; retract
G92 E0 ; reset extrusion distance

NB it is probably worth saying I'm using FW retract and Volumetric extruder settings.

**Comment by galexander1** [comment]
When he said 80 steps per mm, he meant 80 microsteps per mm.

Maybe it is a red herring, but I am still blown away when I see "F9000".  IIRC when I was calibrating my robot, I found F9000 at the absolute upper end of what it would take, though it is a very different robot than yours.  My point is, if that said F1000 instead, I would not give any credence to @orcinus' theory but while it is there, @orcinus' theory is at the front of my mind.

**Comment by nophead** [comment]
The steps per mm value in the firmware is a misnomer. It is actually pulses on the stepper pin of the driver, which are micro steps, not motor steps, which the firmware knows nothing about.

**Comment by nophead** [comment]
A motor can only skip multiples of four full steps, which is 0.8mm with 80 steps per mm.

The driver can miss one micro step per direction change if the step signal is inverted or the timing of the dir signal is wrong.

**Comment by barneycg** [comment]
@nophead right that makes sense thanks for clearing that up.  Is that miss one microstep per direction change even if that driver isn't changing direction.  In which case am I right in saying there are 5 direction changes per layer which matches with the number of microsteps it is out which implies what you said is the case.  Is there anything I can to to determine this and is the cause of it hardware (ie the stepper drivers, RAMPS board or Arduino board) or in the firmware ?  I assume the answer to the latter is "it depends" :) ... again anything I can do to get you guys more information.

@galexander1 a) that is only on the z axis move so I don't see how it would have any impact on x or y axis moves - those are F311.760 btw and b) the Feed rate is clamped in firmware to a lower value which Slic3r has absolutely no knowledge of.  I can't be sure of the firmware limit and I don't have access to the machine the config file is on from where I a right now but I seem to recall it is 500.

**Comment by orcinus** [comment]
"and there is no travel except when it moves to the start"

So there is travel :)

**Comment by nophead** [comment]
If there is not enough time between the dir signal changing and the step signal or vice versa (setup and hold times) the result is undefined but I think it usually makes the first or last step of the line in the wrong direction. That would be a two microstep error and only when dir changes.

There is high speed XY travel every layer according to the gcode.

G1 X99.750 Y109.750 F9000.000 ; move to first perimeter point

**Comment by orcinus** [comment]
FWIW, i've done feedrates of 14400 and greater with Marlin (SLA machine, double steppers for each axis) at accelerations of 3000 or more and had no issues, so i doubt it's the firmware not keeping up.

I did notice it's fairly easy to cause skipped steps when you mess with the stepper interrupt loop (and produce shifts like above), but that was due to badly optimized third party code (written by someone else and not part of Marlin). Stock works fine.

**Comment by barneycg** [comment]
I suppose there is indeed a move ... but look at where it is moving from G1 X99.750 Y109.690 E9.32433 on the layer below. ... that is 0 mm in the x axis and 0.06mm on the y axis, and again I'll say just coz the gcode says go 9000mm/min the firmware can override this :)

**Comment by nophead** [comment]
0.06 on Y at the start of each layer ! 

Isn't that exactly how much it slants? Seems like a big clue there.

**Comment by orcinus** [comment]
To eliminate some weird rounding / integer casting error, and out of curiosity, could you change your steps/mm slightly and retest?

**Comment by barneycg** [comment]
indeed I was just going there mentally after I hit send.  It still doesn't quite add up in my head though since if I do 2 shells it works fine and from memory the gcode for that looks pretty much the same but with 2 sets of coordinates ... so if it was a missed step for 1 shell why does it not do the same for 2 shells ?
That said once I've got back to my printer I do the following and report back :
confirm the firmware max speed.
manually set all the speeds in slicer to something really low ... would 5mm/s be low enough ?
change my steps/mm for y axis ... any suggestions ?

Did I miss anything ?

**Comment by barneycg** [comment]
oooh thought ... at 0.06mm that is well into the jerk settings would it be sensible to look at those - I believe mine are currently the default.

**Comment by nophead** [comment]
It is starting to look like a firmware bug to me as regardless of speed, acceleration and jerk a motor cannot slip 5 micro steps.

But we have a move per layer that seems to be roughly equal to the error. It would actually be 4.8mm not 5mm over the full height, assuming it does the same on the solid layers.

**Comment by barneycg** [comment]
another thought ... 0.06mm is actually less the calculated offset per layer which was 0.0625 ... and 0.006 / 0.0125 (the distance moved per microstep) = 4.8 

So in my ignorance it seems like the firmware needs to make a choice it can either move 4 microsteps, 5 microsteps or just do nothing.  Is it even vaguely possible it is choosing the latter ?

**Comment by nophead** [comment]
It should move 4 or five microsteps, it shouldn't do nothing.

**Comment by barneycg** [comment]
I like the use of the word "Should" :D

**Comment by nophead** [comment]
Or if it chose to ignore such a short move it should leave its current position unchanged, so the next move would simply go a bit further. There should never be a cumulative error.

**Comment by nophead** [comment]
When I do 
G1 X99.750 Y9.69   (can't go to 109 in my machine)
G1 Y9.75
M114
I get
X:99.75Y:9.75Z:200.00E:810.84 Count X:99.75Y:9.69Z:200.00
What do the Count numbers mean?

**Comment by nicolas-rambaud** [comment]
Hello i’ve written an article about how to choose a pulley

https://nutz95.wordpress.com/2014/12/02/reprap-how-to-choose-your-pulleys-for-your-3d-printer/

And a few pulleys size are not adequate depending on your stepper settings.

If you use 16, 20 or 25 teeth with GT2 belt 2mm pitch and 1.8°/step motor
you should have integer steps/mm values.

In other cases you will get some rounding errors.







*De :* Chris [mailto:notifications@github.com]
*Envoyé :* vendredi 9 janvier 2015 17:38
*À :* MarlinFirmware/Marlin
*Objet :* Re: [Marlin] Odd single thickness wall bug (#853)



Or if it chose to ignore such a short move it should leave its current
position unchanged, so the next move would simply go a bit further. There
should never be a cumulative error.

—
Reply to this email directly or view it on GitHub
<https://github.com/MarlinFirmware/Marlin/issues/853#issuecomment-69359915>.[image:
Image supprimée par l'expéditeur.]

**Comment by ErikZalm** [comment]
The count numbers are position calculated from the stepper pulses.
If both are equal then all pulses are generated as expected.
I added this because in the beginning many people had slipping pulleys an claimed that it was a firmware fault.
This proves that the firmware generated the correct pules.

**Comment by ErikZalm** [comment]
@nicolas-rambaud I do not understand your calculations.
The firmware keeps track of its position with floats.
(float)position + (float)steps/mm = position in microsteps. (Rounded but not having a cumulative error)
Cumulative errors could be checked with M114.

**Comment by nophead** [comment]
@ErikZalm 
So in this case, they are not equal, so does that prove the firmware is not generating correct pulses?

@nicolas-rambaud 
Rounding errors should never be cumulative, so I don't see why steps per mm need to be integers.

**Comment by ErikZalm** [comment]
@nophead I do not know if it the count started at 0. And it could be a rounding error from microsteps - mm.
The count values are only reset at startup. Not by G92 or Homing.

**Comment by nophead** [comment]
They do start at 0. 

Seems like it chooses not to move from 9.69 to 9.75, even though it could get closer with 4 micro steps. It corrects itself if I move to 10.

Doesn't seem right to me and looks like there is a bug somewhere that is related to this.

**Comment by nicolas-rambaud** [comment]
@Chris So now i’m wondering when you put a floating value as steps/mm
inside the firmware how the firmware calculate how many steps he needs in
order to perform some moves?

Has to be cumulative if you use float values because some time you limit
the amount of digits after the coma.

For example the case with a 17 teeth GT2 2mm pitch pulley.

The calculated steps per mm is  for a 1.8°/step motor with a 16 microsteps
driver:



(200*16)/(2 * 17) = 94.117647……..

In the en in the firmware you will write something like 94.12 or 94.118



So here whatever value you put into the firmware you will always have a
rounding error even if it’s very small.

Then imagine you want to move 100mm that means that the small rounding
error will be multiplied by 100.

To me this will be the case even if you use super duper intelligent ways of
avoiding to have cumulative rounding error.



I’m I write?



*De :* Chris [mailto:notifications@github.com]
*Envoyé :* vendredi 9 janvier 2015 17:58
*À :* MarlinFirmware/Marlin
*Cc :* Nicolas Rambaud
*Objet :* Re: [Marlin] Odd single thickness wall bug (#853)



@ErikZalm <https://github.com/ErikZalm>
So in this case, they are not equal, so does that prove the firmware is not
generating correct pulses?

@nicolas-rambaud <https://github.com/nicolas-rambaud>
Rounding errors should never be cumulative, so I don't see why steps per mm
need to be integers.

—
Reply to this email directly or view it on GitHub
<https://github.com/MarlinFirmware/Marlin/issues/853#issuecomment-69363250>.[image:
Image supprimée par l'expéditeur.]

**Comment by orcinus** [comment]
@nophead There's a line somewhere that skips moves that are too short (below a certain number of steps). But that should not happen for a long move, unless for some reason, it got split into smaller segments (i don't think that happens, but i haven't been messing with the planner lately, just stepper.cpp).

**Comment by nicolas-rambaud** [comment]
@Erik

Yes this takes into account the fact that the steps/mm value has a limited
amount of digits after the integer value.



It’s wrong if the user has rounded the value for the steps/mm ex: 17 teeth
200steps/turn 16 microsteps => steps/mm = 94.11764…………



So even if you keep track of position with floats, the initial rounding
error will be cumulative as a matter of fact.





*De :* Erik van der Zalm [mailto:notifications@github.com]
*Envoyé :* vendredi 9 janvier 2015 17:58
*À :* MarlinFirmware/Marlin
*Cc :* Nicolas Rambaud
*Objet :* Re: [Marlin] Odd single thickness wall bug (#853)



@nicolas-rambaud <https://github.com/nicolas-rambaud> I do not understand
your calculations.
The firmware keeps track of its position with floats.
(float)position + (float)steps/mm = position in microsteps. (Rounded but
not having a cumulative error)
Cumulative errors could be checked with M114.

—
Reply to this email directly or view it on GitHub
<https://github.com/MarlinFirmware/Marlin/issues/853#issuecomment-69363208>.[image:
Image supprimée par l'expéditeur.]

**Comment by nophead** [comment]
I wonder if the bug may be to do with the short move being ignored followed by the G10. Would be a good test to try without firmware retraction.

@nicolas-rambaud,
What you are saying is the final size of your object is only as accurate as the precision of a float. Seems good enough to me.

**Comment by nicolas-rambaud** [comment]
@chris that’s it !



*De :* Chris [mailto:notifications@github.com]
*Envoyé :* vendredi 9 janvier 2015 18:54
*À :* MarlinFirmware/Marlin
*Cc :* Nicolas Rambaud
*Objet :* Re: [Marlin] Odd single thickness wall bug (#853)



I wonder if the bug may be to do with the short move being ignored followed
by the G10. Would be a good test to try without firmware retraction.

@nicolas-rambaud <https://github.com/nicolas-rambaud>,
What you are saying is the final size of your object is only as accurate as
the precision of a float. Seems good enough to me.

—
Reply to this email directly or view it on GitHub
<https://github.com/MarlinFirmware/Marlin/issues/853#issuecomment-69371298>.[image:
Image supprimée par l'expéditeur.]

**Comment by boelle** [comment]
is this an issue with marlin? or are we talking in circles here?

**Comment by nophead** [comment]
I think it has to be an issue with Marlin. It is very suspicious that the gcode includes a short move each layer that Marlin chooses to ignore but does update the current position and then that is the amount it shifts each layer.

**Comment by boelle** [comment]
ok, how can the error be reproduced?

**Comment by nophead** [comment]
If somebody has a machine compatible with the gcode from @barneycg they could run it.

I think the bug is this line: https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/Marlin_main.cpp#L1289

The short move is ignored but the current position is updated. The planner maintains the real position that is not updated. The line above sets the planners position to the current position so the fact it did not move is lost, I think. Perhaps somebody who understands the planner can confirm that.

**Comment by barneycg** [comment]
Just to follow up on what I said I would do : 

confirm the firmware max speed - 

#define DEFAULT_MAX_FEEDRATE          {150, 150, 3.0, 10} 
#define DEFAULT_MAX_ACCELERATION      {9000,3000,2500,8000}  
#define DEFAULT_ACCELERATION          3000 
#define DEFAULT_RETRACT_ACCELERATION  3000

manually set all the speeds in slicer to something really low ... would 5mm/s be low enough ? - 

I've just tried a 0.25mm layer height 0.5mm extrusion width print with a single shell with all the speeds set to 5mm/s and the issue is still apparent.

I've not modified my steps per mm for the y axis yet but from what I'm seeing I don't think it will provide any thing more useful.

this is the gcode file : 
https://dl.dropboxusercontent.com/u/926348/SC-025x20-slow.g

NB :- I am using Firmware retraction and volumetric extruder settings.

**Comment by alexborro** [comment]
@barneycg Would you mind posting one or more detailed picture?

@nophead I have some knowledge on planner.cpp. I will look into it as soon
as I get home. You may be right about DropSegments - no movement but the
planner updates the current position.

Cheers.

Alex.
Em 09/01/2015 16:58, "barneycg" <notifications@github.com> escreveu:

**Comment by ErikZalm** [comment]
@barneycg Can you send the g-code file.
Check with M114 if there is a difference between X, Y, Z and Count:X,Y,Z.
Check before starting that all numbers are 0.
I can not imagine that the G10 and G11 are a problem. Lots of people use it and I do not of other people that have problems.

**Comment by Wurstnase** [comment]
at really slow steprates don't forget this
https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/stepper.cpp#L263

**Comment by ErikZalm** [comment]
@alexborro It only updates the Z position. The other values are probably unaffected.
But that is why we have the count values in M114. Play the g-code and check if M114 is still ok.

**Comment by ErikZalm** [comment]
@Wurstnase That is why we have a min steprate.

**Comment by ErikZalm** [comment]
@barneycg Send also your configuration.h

**Comment by barneycg** [comment]
ok so gcode is linked above:
https://dl.dropboxusercontent.com/u/926348/SC-025x20-slow.g
Configuration.h (both my original v1 config and the one for the stable branch) : 
https://dl.dropboxusercontent.com/u/926348/Configuration-old.h
https://dl.dropboxusercontent.com/u/926348/Configuration-stable.h

Image of resulting print : 
![img_20150109_193109](https://cloud.githubusercontent.com/assets/2004769/5685968/18207eca-9837-11e4-8338-c8b3264a3405.jpg)

**Comment by ErikZalm** [comment]
I just checked the G10 / G11 code.
I think this is not correct. It should not do the plan_set_position.
It should do all its work in the g-code interpreter. Then it should not generate problems.
Check the Ultimaker marlin version for a good way to do it.
https://github.com/Ultimaker/Ultimaker2Marlin/tree/master/Marlin

**Comment by alexborro** [comment]
@barneycg try a test without G10/G11.

**Comment by barneycg** [comment]
By that you mean disable FW Retract in the firmware and clear the checkbox in slic3r ?

**Comment by alexborro** [comment]
Exactly.. So you can isolate the problem and check if the FW Retract is
messing up things..

2015-01-09 18:06 GMT-02:00 barneycg <notifications@github.com>:

> By that you mean disable FW Retract in the firmware and clear the checkbox
> in slic3r ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarlinFirmware/Marlin/issues/853#issuecomment-69390929>
> .
>



-- 
*"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )*

Alex Borro

**Comment by ErikZalm** [comment]
@barneycg Wait a few min. I will push a version with a quick fix.

**Comment by ErikZalm** [comment]
@barneycg Test the latest version. I think it is a problem with the fwretract (That has a warning in the header file) in combination with 0 zlift.

**Comment by barneycg** [comment]
Console out from Pronterface when doing a print using fw retract and doing M114 before I start the print and then again when it is finished

https://dl.dropboxusercontent.com/u/926348/console_out.txt

I've tried with the latest Dev commit but either there is another bug or I've missed something in one of the config files as my Thermocouple is reading 485 all the time.  I have enabled the ADC read in Configuration_adv but maybe I missed something else.
In the mean time I've recompiled the Stable Build from the 5th Jan with FWRETRACT disabled and am giving that a try.  Unfortunately I've not got any more time tonight to spend on this but I will resume testing over the weekend.

**Comment by whosawhatsis** [comment]
The warning on fwretract is left over from the old version, which was horribly broken and needed a stronger warning. When I rewrote it, I didn't bother to take that out, though it's had a lot of testing at this point.

I don't see any obvious way fwretract could cause a move preceding it to be skipped, but trying the code without it is definitely worth trying, if only to rule out possibilities.

@ErikZalm Thanks for mentioning Ultimaker's implementation. I've been meaning to port over the extruder switch code from that, and maybe it would be better to just modify their version (which doesn't appear to support Z hop or autoretract) than to add to my version that uses plan_set_position() directly. Honestly, I did that because prepare_move() is bloated with so much compile-time-conditional code not needed by fwretract that I had trouble making sense of it at the time.

**Comment by barneycg** [comment]
Thanks for all the effort guys.

**Comment by whosawhatsis** [comment]
Oh, and once that is all sorted out, I wanted to discuss enabling firmware retraction in the default configuration, now that it's been tested and autoretract is disabled by default, so that it won't affect your machine's operation until you ask for it. Volumetric E is available by default (again, doesn't affect anything until the gcode asks for it), but it's hard to use without firmware retraction also available.

**Comment by orcinus** [comment]
Horribly offtopic, but...
How usable is UM2 fork's simulator for debugging other Marlin versions?

**Comment by galexander1** [comment]
@barneycg you are probably right, i'd just like to rule out its involvement.

FWIW, my next step if i had a printer where i could reprodcuce this would be to strip the 'E' attributes from the g-code (can rule out extrusion is involved, which i think can affect the way the robot thinks about feedrate, plus then we can test it without wasting any filament), and then strip all the 'F' attributes (so the whole thing is theoretically at a constant speed, with the only acceleration being related to changes in velocities).  Of course without extrusion, it'll be harder to detect.  But if it still does it after that, then you can really run a lot of experiments to try to figure out which shapes of movement are the biggest problem, and that might point at which particular movement is the one confusing the printer.

I don't know if that's a feasible plan for you or if there is a better idea.  If you aren't comfortable with something like perl to manipulate g-code as text then it probably seems like a big pain in the butt. :)

**Comment by ErikZalm** [comment]
What probably is causing the error is that plan_set_position is called after a very small move.
Currently it is dangerous to call plan_set_position during printing. (It was designed for homing.)
We should correct plan_set_position.
Make target[] global.
In plan_set_position correct the difference between target[] and position[].

**Comment by galexander1** [comment]
Sorry about my last redundant message, I didn't realize I had missed so much that went on.

@barneycg thanks for humoring me and trying the 5mm/s :)

I have a hunch about what is unique about single-walled things.  In a single-walled thing, the short 0.06mm move in X (or Y, depending on which g-code you're looking at) between layers is a single-axis move, essentially just stepping forward along the rough path it had previously been following.   But in a double-walled thing, it will generally be a two-axis move...it will step along the path of extrusion and then also outward from the inner wall to the outer one (or vice versa, depending on slicer).

**Comment by alexborro** [comment]
@ErikZalm , what about including in the documentation something about the main functions in Marlin?? I mean, there are some functions many don't know the purpose or how to correctly use. I usually don't where I can use them or how to use.. plan_set_position is one example.. I could say others like prepare_move, plan_get_position, the arrays current_position[] and destination[] and so on..

I usually try to understand the functions and see other usages, but sometimes they are not clear and renders issues like this.

Cheers.

Alex.

**Comment by ErikZalm** [comment]
I made plan_set_position more robust for small moves.
I changed it in the set_plan_position branch. Can someone test this?
If it does no harm I will merge it in de Development branch.

**Comment by barneycg** [comment]
So I tried my original Firmware from back in August with FW retract off and I get a cube :)
Then I've got the set_plan_position branch up and running for my system - I'd missed updating pins.h for my ADC last night.  But it crashes my head into the bed.  I connected it up to the console and ran some manual tests : 
>>> G28 x0 y0 z0
SENDING:G28 X0 Y0 Z0
>>> G92 Z0.15
SENDING:G92 Z0.15
>>> m114
SENDING:M114
X:180.00 Y:0.00 Z:0.15 E:0.00 Count X: 180.00 Y:0.00 Z:4.15

background here is my endstop homes Z to about 0.15mm from the bed so I use G92 Z0.15 to adjust for this the first move should obviously take it to 0.25mm (my first layer height) but given this firmware seems to think the head is at 4.15mm after the G92 Z0.15 that is a bit of a problem :)

**Comment by barneycg** [comment]
Dev Branch from last night configured with FW Retract on and my test single wall test gcode file prints correctly

**Comment by boelle** [comment]
yaaa or am i celebrating to fast ?

Den lørdag den 10. januar 2015 skrev barneycg <notifications@github.com>:

**Comment by ErikZalm** [comment]
@barneycg Thanks for testing. Now we know the problem.
Now we need a good solid fix.

**Comment by boelle** [comment]
maybe add this to one of the current milestones?

Den lørdag den 10. januar 2015 skrev Erik van der Zalm <
notifications@github.com>:

**Comment by barneycg** [comment]
@ErikZalm You're welcome, thanks for taking the time to look at it and fix it :)

**Comment by alexborro** [comment]
@ErikZalm , I see you fixed the plan_set_position to check if target[] is different from position[].

What if the fix was made in plan_buffer_line, where the error actually happens:

>  // Bail if this is a zero-length block
>  if (block->step_event_count <= dropsegments)
>  { 
>    return; 
>  }

Here it drops the block without updating the position[]. 
I mean, changing plan_set_position is a workaround for the error instead of avoid it to occur in plan_buffer_line. 

I think it it important making plan_set_position more robust but it is important to avoid the error as well.

Cheers.

Alex.

**Comment by ErikZalm** [comment]
@alexborro Position is the position that is planned. If the move is not planned then the position should not change.
The drop segments was needed in 2011 because the slicers sometimes generated many very small segments. The calculation of these very small segments was starving the buffer.

**Comment by alexborro** [comment]
Thanks @ErikZalm , got it.

But how the position[] has become different from target[]??

**Comment by ErikZalm** [comment]
@alexborro target is the wanted position. If the planner is finished the position is updated to target.
If the move is dropped because it is to small compared to the previous planned position the position is not updated.

**Comment by barneycg** [comment]
@ErikZalam any idea why the the set_plan_position branch gave me thought I was at Z4.15 rather than Z0.15 after I'd done a G92 Z0.15 just after homing ?  Currently I'm running the Development Branch because of this.

A complete aside ... thanks to this bug and me double and triple checking the geometry of my printer plus calibrating my Extrusion multiplier properly (something I'd not done previously as I was too keen to actually print stuff) my printer is printing better than it has done since I built it about a year ago :+1:

**Comment by barneycg** [comment]
I noticed that the set_plan_position has gone away and the changes that were in there have not been merged in anywhere or recorded anywhere to the current Dev Branch but the changes made to the Dev branch to fix this have been retained.  I'm assuming this was the correct course of action and that the Dev branch fix is the direction chosen ?

**Comment by boelle** [comment]
it all boils down to if the issue is fixed in the current dev... is it?

**Comment by nophead** [comment]
A related question: as Marlin chooses to ignore short moves does that mean that a line extruded after a short move will start in slightly the wrong position but correct it at the far end? I.e. do you get a slightly diagonal line instead of a straight one in the case of this simple box with a short move to the first corner each layer?

**Comment by barneycg** [comment]
@boelle ... sorry I don't think its that simple ... if my car door rattles I can "fix it" by removing the door (clearly there will be no more rattles) or by identifying the loose thing and tightening it.  Both stop the rattle only one is the right way of fixing it :)

**Comment by galexander1** [comment]
So we have two questions: On the dev branch, is the door still rattling?
And is there a significant undesired cold breeze when travelling at
speed?

**Comment by barneycg** [comment]
heheheh ... door is not rattling, as for the other I'm not qualified to answer as I don't know the underlying code which is exactly why I was asking

**Comment by orcinus** [comment]
Printers don't run on Closed Issue counters ;)

**Comment by alexborro** [comment]
If you wanna Marlin to perform even the smallest move, set DROPSEGMENTS = 0.

As ErikZalm said, this feature was implemented to avoid buffer underrun due
Slicer doing a lot of small segments.

If your Slicer don't do that, you are safe disabling it. And if does,
replace it by a good one.

Cheers

Alex
Em 15/01/2015 21:34, "Ante Vukorepa" notifications@github.com escreveu:

**Comment by nophead** [comment]
Skeinforge doesn't output short segments so I will do that, but Cura does the last time I tried it. It should probably be more intelligent such as don't drop the last small move before a larger one. And / or only drop them while extruding.

This simple example has nothing that would cause buffer overrun but it seems it will have walls in the slightly the wrong place.

**Comment by justmyopinion** [comment]
Why is this only a problem with FW retracting enabled?
I would not assume retracting to change any position but Z-axes.

**Comment by nophead** [comment]
See https://github.com/MarlinFirmware/Marlin/issues/853#issuecomment-69374779, although I don't know why the retraction code messes with the other axes.
