### ISSUE TITLE
G28 X0 Y0 disables legacy auto-leveling when not using AUTO_BED_LEVELING_UBL

### ISSUE THREAD

**Issue by marcio-ao** [MarlinFirmware/Marlin#8670]
- Description: Running G28 will cause auto-leveling to be disabled when AUTO_BED_LEVELING_UBL is not enabled.
- Expected behaviour: Running "G28 X0 Y0" should retain the autoleveling state.
- Actual behaviour: Running "G28 X0 Y0" will turn off autoleveling, unless using UBL
- Steps to reproduce:
  - Enable some form of auto-leveling that is not AUTO_BED_LEVELING_UBL
  - Do "G28" to home
  - Do "G29" to autolevel
  - Use "M420" to verify that autoleveling is enabled
  - Do "G28 X0 Y0" (after pausing a print, for example)
  - Use "M420" to see that autoleveling is disabled.

The cause of this bug is the check [here](https://github.com/MarlinFirmware/Marlin/blob/4d3c3d0b7384038e12c6eddb14bf717985b8dd7a/Marlin/src/gcode/calibrate/G28.cpp#L158) and [here](https://github.com/MarlinFirmware/Marlin/blob/4d3c3d0b7384038e12c6eddb14bf717985b8dd7a/Marlin/src/gcode/calibrate/G28.cpp#L311):

```
void GcodeSuite::G28(const bool always_home_all) {
  ...
  // Disable the leveling matrix before homing
  #if HAS_LEVELING
    #if ENABLED(AUTO_BED_LEVELING_UBL)
      const bool ubl_state_at_entry = planner.leveling_active;
    #endif
    set_bed_leveling_enabled(false);
  #endif

  ...

    #if ENABLED(AUTO_BED_LEVELING_UBL)
    set_bed_leveling_enabled(ubl_state_at_entry);
    #endif
}
```

The state of leveling is saved and restored only if AUTO_BED_LEVELING_UBL is enabled, but in truth it should be saved and restored for the legacy leveling modes as well.

**Comment by thinkyhead** [comment]
`G28` is specified to always disable bed leveling. UBL marches to a different drummer.

We have not modified `G28` to properly handle a print interrupt and resume situation.

Leaving leveling enabled during `G28` or disabling before then enabling afterward will cause a shift in position with certain forms of bed leveling. Rectification can be complicated, and the homing procedure has other side-effects as well. When re-homing is needed after a print interruption, we will need to use a separate procedure, and not the complete `G28`.

If you think it's viable, or a good idea to keep homing enabled on `G28` for X and/or Y, then take great care and please observe very carefully in crafting your solution.

Rectification relies on being able to ask the steppers for their current position, but with `G28` we throw out that position and tell the steppers where they are. This is all fine if you're doing a complete homing before starting a print, but in the middle of a print this is bad news. To get around it, instead of "homing" you need to use the endstops to "probe" for the end of the axis and preserve the steppers' step-positions.

**Comment by Roxy-3D** [comment]
Just to be clear and make sure nobody jumps to the wrong conclusion....

With UBL enabled...  G28 still disables leveling during its operation.   It needs to do that so it can sense the machine's true position.    But after the homing operation, it restores the current bed leveling state (whether enabled or disabled).

**Comment by marcio-ao** [comment]
@Roxy-3D: When not using UBL, the bed leveling state is not re-enabled, this was the nature of my ticket. I think it should be re-enabled for all leveling modes.

**Comment by marcio-ao** [comment]
@thinkyhead : The reason we added re-homing after a pause is that users sometimes mess with their print heads during a pause and this was causing the head to shift and the resume to fail. I don't think it matters whether bed leveling is on *during* the G28, but re-enabling it after a "G28 X0 Y0" would be useful.

**Comment by thinkyhead** [comment]
Some would obviously like to leave bed leveling on after `G28` if it was on before `G28`. Others, like myself, very much prefer that `G28` leave the machine at 0, 0 with leveling off. So I propose that this be added as an optional behavior, and that it be exposed as a `Cap:` capabilities string so that the host software can tell the difference between machines that do this and machines that don't.

I'm just proposing this as a config option that would make all `G28` restore leveling to its prior state for the given machine. I'm not proposing an extra `L` or `S` parameter to `G28` to apply this behavior, but I'd be open to that. While `G28 X Y\nM420 S1` accomplishes almost the same thing, it's either on or off, and there's no option to bring it back to its previous state.

If that's cool, I can implement it and apply it in `G28` for all forms of bed leveling. This would have the added benefit for fools like me to have UBL always be disabled after `G28` too.
