### ISSUE TITLE
[FR] "advanced" SPI support in the HAL

### ISSUE THREAD

**Issue by revilor** [MarlinFirmware/Marlin#8756]
I'm working on a hardware extension for my printer which requires SPI features beyond what is provided by the HAL at the moment. My printer is based on a MEGA 2560 board, therefore I could just use the Arduino SPI library instead of the HAL SPI functions. But considering there are devices like for example some of the Trinamic stepper drivers which can be configured via SPI, I guess it would make sense to have a more feature-rich SPI implementation in the HAL.

I wonder if there are plans for extending the HAL's SPI feature set or if maybe somebody is already working on that. I'm willing to put some effort into adding better SPI support to the HAL if that is considered a useful extension to Marlin. So please let me know what you think about it.

**Comment by p3p** [comment]
An 'improved' HAL SPI interface was in the works just before my HAL work was merged and became the base of 2.0, but was no where near ready so I reverted it (https://github.com/MarlinFirmware/Marlin/commit/61c0a10efeae9400d517f376278e8f7cb4532a9b) in order to quickly fix builds, in theory all hardware features (SPI, I2C ect) need to be behind some kind of multi-channel interface and then the individual platform will either write an implementation or pass through to a library (so no core Marlin code ever accesses libraries directly) but I ran out of hobby time about 5 months ago and have yet to sit down and plan out how to do it with minimal/no impact on the AVR platform. The use of external device driver libraries also complicates matters as we have no control over how they access the hardware. It is something I planned to look into again .. eventually .. feel free to have a go if you like.

**Comment by victorpv** [comment]
@p3p I had also been thinking about this, I think a way to manage multiple devices, or channels, could be by using a single index value, to a layer in the HAL. If the index is not passed, then it's taken at default value of 0 (that way any code not updated yet to pass the index, would communicate in channel 0).
For the other indexes, we can some more functions to set for example the channel and SS pin to use.
Something like:
HALSPI.channelSet(index, SS pin, SPI channel number);
That sets the SS pin and SPI channel for that index.
Next for let's say the display driver to use it to send data, could do something like:
HALSPI.send(*buffer, num, index,);

The the libraries only need to know about the index, which we can decide, and keep in a central table, while the board file, or configuartion.h, have defines for what SS pin and what SPI channel should be configured for that index.
So depending how many ports are in a board, we can assign the LCD to SPI2, and SS pin 25, the sdcard to SPI1 and SS pin 26, the steppers to SPI1 SS pin 27... 
In configuration.h we would have:
#define LCD_Port 2
#define LCD_SS   25
...
And somewhere in the initialization code:
HALSPI.channelSet(LCD_index, LCD_SS, LCD_Port);

And update all the LCD drivers that use SPI to something like
HALSPI.send(..., LCD_index);
And if index is ommited, like I said reserve index 0 for a default port, to which no SS is configured.
That would also allow an easy transition between software and hardware SPI if we decide some channels are reserved for software SPI, and allow to configure MISO, MOSI and SCK pins for those.
I.e, SPI channels over 32 are for software, and we add another function to the API to configure those:
HALSPI.softPinsSet(MOSI_Pin, MISO_Pin, SCK_Pin);

During usage the HAL code takes care of toggling the SSPin and then calling the actual hardware SPI )or software SPI) transfer functions, and toggling the SS pin again on return.

On I2C since there is no need for SS pin, then just and index with channel number relation, and again reserve 0 for a default one, and over 32 for software ones.

**Comment by Bob-the-Kuhn** [comment]
It would be really nice if the manager had some provision for handshaking and/or locking a channel.  I expect that we're only a couple of years away from going to some type of RTOS.  

There aren't many of the current SPI users that are well enough behaved to make the transition as is.  

Some of the current LCD routines go through a init/setup phase, then a begin transmission and finally an end transmission phase.

I'm looking forward to the next generation of 32 bit boards.  The current generation is so pin limited that it's hard to do anything more than a basic system with them.  NXP has what looks like a LPX1768 compatible chip that has almost twice the I/O, has EEPROM and is priced less than the LPC1768.  DEATH TO THE RAMPS (R3) FOOTPRINT!!!

**Comment by victorpv** [comment]
@Bob-the-Kuhn an API like I described could internally set a flag on entering the function, and clear the same flag on exit, and keep a table of those flags for each index.
I have done it with FreeRTOS with mutexes in the STMF1 and worked well at sharing an SPI port between 2 threads, for LCD and SDcard.
All of this consumes ram with is limited in the AVR, but should be fine in all 32bit ones.

**Comment by thinkyhead** [comment]
Still needs work, I presume.

**Comment by boelle** [comment]
@revilor still need this?

**Comment by boelle** [comment]
wrong label

**Comment by sjasonsmith** [comment]
@rhapsodyv this may be of interest to you.

**Comment by rhapsodyv** [comment]
We already have a rich SPI implementation in STM32F1 and LPC. 

It's multi bus (one spi device can be used by different configurations) and support:

- Data Sizes: 16 and 8 bit 
- All 4 Modes
- byte order
- Speed

And we follow the Arduino SPIClass interface, so it's kind of standard too.

The client code just need to do the PIN select and call SPI.begin().

We need to port that class for other HAL, but in my view, this issue is done and could be close.
