### ISSUE TITLE
[FR] LCD selected menu color inverted (as before)

### ISSUE THREAD

**Issue by spilz87** [MarlinFirmware/Marlin#9166]
Hello

As I got issue with fullLCD to select a menu : 
When I go to fast with encoder, there is only one line ( instead of 2) so I can't know if the selected menu or life is up or down the line :(

Is there a way to have as before the selected menu in invert color (instead of the 2 lines) ?

Regards

**Comment by Sebastianv650** [comment]
I also experienced this missing line or even more than 2 visible lines in recent Marlin versions. But I think we should fix them instead of going back to the inverted version. The reason for this change was performance, the lines are much faster than the inverted text.

I'm quite sure we had them working around 1.0 and 1.1, maybe something got changed since then?

**Comment by spilz87** [comment]
I don't remember when was the change 
Is it as much faster ?
Because inverted was most "beautiful" (my opinion) 

Actually I find LCD menu more and more slower (compare to old version) and got issue when I navigate in sd card's files name : bad refresh, files missed, need to go down then up to see them, etc

**Comment by AnHardt** [comment]
```
  // Enable to save many cycles by drawing a hollow frame on Menu Screens
  #define MENU_HOLLOW_FRAME
```

**Comment by spilz87** [comment]
It works, but it's true it's much slower :(

**Comment by AnHardt** [comment]
I don't remember the numbers for the menu, but at the info-screen the difference was ~3ms. Compared to the time the screen needs ro draw (below 30ms) this was more than 10%, just for reversing the bar.
