### ISSUE TITLE
Plug and play configuration for RAMPS 1.4+20x4 LCD?

### ISSUE THREAD

**Issue by Fireflaker** [MarlinFirmware/Marlin#9215]
Question: Is there a "plug and play" configuration for RAMPS 1.4+20x4 LCD?

**Comment by revilor** [comment]
If you find your printer in the example configurations, then it's "plug and play". Otherwise the answer is no because there is no such thing as "RAMPS 1.4+20x4 LCD". First of all there are different 20x4 LCDs available to connect to the RAMPS board. And how should anybody in the Marlin community know the mechanical setup of your printer, like cartesian or delta design, endstops, thermistors, bed size, etc. to provide you with a "plug and play" configuration?
