### ISSUE TITLE
[2.0.x] Anet A6 Full graphic controller

### ISSUE THREAD

**Issue by Xcorpia07** [MarlinFirmware/Marlin#9255]
------------------------------------------------------------
### Bug Report
- Description: Anet A6 Full Graphic Controller Don't Work
- Expected behaviour: LCD Work ok
- Actual behaviour: LCD Show pixel but wrong.
- Steps to reproduce:
  - Compile Firmware 
  - Send to Anet A6

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1648682/Configuration.zip)

![687474703a2f2f696d616765732e7461706174616c6b2d63646e2e636f6d2f31352f31302f32372f39636431646139363238626533656130343366396137643037353938383765312e6a7067](https://user-images.githubusercontent.com/35557316/35182028-40fb0f6e-fdcd-11e7-9681-ba64c717fdc7.jpg)

I have a Anet A6 with original Board. I use Marlin 1.1.x and I haven't this problem. In the last week I tried all bugfix 2.0.x of every day and the problem persist.

I see the problem same **Full graphic controller issues under Arduino >1.0.6 #3815**

Now I can solved this problem commeting this line in  `ultralcd_st7920_u8glib_rrd_AVR.cpp`

```
//set optimization so ARDUINO optimizes this file
//#pragma GCC optimize (3)
```
------------------------------------------------------------

**Comment by AnHardt** [comment]
Of cause you can slow down the transfer code by optimising it for size instead of for speed.
But what you get is a 'somehow' slower code.
We speeded up the code as far as we could to slow it down with defined delays. This way we can fine tune the code to be slow enough to avoid errors but not wasting time like not optimizing for speed does.
