### ISSUE TITLE
Advanced break

### ISSUE THREAD

**Issue by boubouexpress** [MarlinFirmware/Marlin#9333]
add feature break advanced cut off the heater the bed and hotend for a recovery after several hours of break

**Comment by boubouexpress** [comment]
as the original firmware of the creality 3D CR 10 S

**Comment by MasterPIC** [comment]
I'd suggest to add an hotend standby temperature, useful to change filament at optimal temperature instead of forcing the user to remove the filament at extruding temperature...
Then, after a firmware defined timeout, it could automatically cut off the heater.

**Comment by Grogyan** [comment]
Cold pull temperatures are dependent on the material used.
I can see how this could be useful

**Comment by MasterPIC** [comment]
Maybe opting for setting how many degrees to lower the temperature is a good workaround...

**Comment by boubouexpress** [comment]
to print a large room, pausing during the night for reasons of security and noise and resume the next morning
the pause mode should have a break of the heater

**Comment by MasterPIC** [comment]
@boubouexpress I agree with you about deactivating the heater after a timeout.
But I was suggesting to add also an intermediate temperature state (by lowering the temperature by x°C with x user defined) to properly change the filament...

The workaround I was referring to is related to the need for an appropriate temperature to change filament that depends on the material. So instead of setting a fixed replacement temperature I suggested to set how many degrees to temporarily  lower the temperature to allow filament replacement. This deltaT could be fixed and work whatever the plastic in use (e.g. 40°C to have 190°C in place of 230°C while using PETG, 210°C in place of 250°C for ABS, ...).

**Comment by thinkyhead** [comment]
@tcm0116 I suggest we get down with the heater timeout code and generalize it so it can be used in all pause-like procedures. Currently it only exists within `wait_for_filament_reload` but it appears completely ready to be deployed.

@boubouexpress Shame on you teasing us with the Creality firmware and then not providing a copy so we can study their implementation. We demand a tribute!

**Comment by boubouexpress** [comment]
I'm not the source code just the compiled 

[CR-10S-500Â¤Áþð°┤‗-┤┤¤ÙËó╬─.zip](https://github.com/MarlinFirmware/Marlin/files/1726816/CR-10S-500A.Athd.-.UEo.zip)
