### ISSUE TITLE
Anet A8 with E3d Bowden, NTC 3950 thermistor getting too hot/heating failed.

### ISSUE THREAD

**Issue by CurtisNull** [MarlinFirmware/Marlin#9606]
I'm having trouble with this. I found some code here: https://nutz95.wordpress.com/2014/04/13/marlin-firmware-thermistor-3950-table/ 

This is thermistor information. It doesn't seem to work, as I'm pretty sure the nozzle got red hot at one point. I really just want to get my 3D printer working with Marlin, but it seems that I am unable to.

**Comment by Lyr3x** [comment]
May you post your configuration files

**Comment by Max1963** [comment]
Don't know if this would be of any help, but with my Anet A8 and E3D clone, I'm stuck with default Anet A8 configuration.h, (extruder=5) and all seems to works fine.

**Comment by Lyr3x** [comment]
this isnt helpful, because you got a completely different thermistor. He need to set up Thermistor 11, 13 or 60. I guess 11 is the right one.
I think he did not changed the configuration file for the proper thermistor, which is very dangerous.
Its also dangerous do give such wrong advices!

@CurtisNull you should read some documentation and safety information before using a cheap printer kit like the Anet A8 which have a lot safety issues.

Its also possible that your thermistor is damaged. Is the ambient temperature correct? 

Test with complete cooled down hotend.

**Comment by Max1963** [comment]
> this isnt helpful, because you got a completely different thermistor. He need to set up Thermistor 11, 13 or 60. I guess 11 is the right one.

Sorry, but I've same thermistor on my E3D clone (NTC 3950) and didn't work either with 11, 13 or 60 ones... Work, for me, flawless with stock 5 in config

**Comment by thinkyhead** [comment]
Good luck @CurtisNull — If you find any bugs in Marlin or have a feature request please let us know.
