### ISSUE TITLE
FR: Force Home X before Home Y

### ISSUE THREAD

**Issue by smoki3** [MarlinFirmware/Marlin#9662]
I have a feature request: Can we create an option to force home X before Y (and Force home Y before X)?
I have a fix endstop on my core xy which need to home y before x.

**Comment by GMagician** [comment]
Have you tried HOME_Y_BEFORE_X in configuration_adv.h?

**Comment by smoki3** [comment]
Yes but if I only home x my printer is crashing, because the y axis has to be homed first that my hotend can reach the x endstop

**Comment by GMagician** [comment]
I don't understand... if homing X before Y crash define is for homing Y before X...

**Comment by workheart** [comment]
he means like "safe Homing" feature for Z
X can only be homed if Y is homed already

**Comment by GMagician** [comment]
Ah ok you want to inhibit x homing until Y has been done, not home one before the other...

**Comment by smoki3** [comment]
to change the order when i home ALL there is the option HOME_Y_BEFORE_X. And everything is fine. 

but if i want to home X my printers Y axis has in to be in the home position. otherwise the x axis cant have contact to his endstop and it will end in a crash. 

I now simply added a 'HOMEAXIS(Y);' to 'Marlin/src/gcode/calibrate/G28.cpp' in home (x) part. so its working now but it would be nice to have it in the config

**Comment by ghost** [comment]
You have  G28 X or G28 Y 
Create a custom user command ' in config adv ' you can create 5 scripts

And you make the script you want , in your situation , you can make '  G28 X\nG28Y\nG28Z '
Or if you need the X or Y must be positionned to a special position , you can ' G28X\nG1X...F... ' etcc

But don't forget to tweak your slicer to have the starting gcode like this
But , i prefer , you place the endstop switch on the beginning of the linear guide of each carriage axis to avoid this tweaking

**Comment by smoki3** [comment]
yes thats a workaround :D @studiodyne but if you click home x on display the printer crashes. So I integrated it to the firmware. maybe i upload the code.  mk4duo also has this funktion

**Comment by ghost** [comment]
Ok To home x , the printer need to have a special Y POS , and the pos is the Y=homed
And if Y homed , but not a the pos , if you want to home x , THE WORLD EXPLODES
oK , but homing is just before the print  , and just made once 

Rewrite G28 CPP , and   Home Y + Home x but ' if Y homed --> Y go to home_x_Pos 
But it's individual coding , don't need to be in config files , because each new updated release you will have to rewritte G28cpp---
Not a good idea , because each week a new release have so many fixes , and you will never follow us , if you need to add your own feature

I repeat ,  PLACE YOUR SWITCH a the better place it need to be lolll

**Comment by smoki3** [comment]
i created a pull request for this

https://github.com/MarlinFirmware/Marlin/pull/9676

**Comment by Studiodyne** [comment]
If the PR is pushed , your problem is closed 😸
