### ISSUE TITLE
2.0 +1.1.x  BIG FONT EDIT IS DOWN .... doesn't work ...

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#9685]
MY FAVORITE FUNCTIONNALITY 
The EDIT BIG FONT  not working on all release version

**Comment by Roxy-3D** [comment]
@Studiodyne    Is it possible to find the commit that broke it?   If we know where it got broken...  Usually it is easy to fix.

**Comment by Studiodyne** [comment]
@Roxy-3D , i have enough difficulties to print something with marlin , strong difficulties to debug something wrong , and now , you want i learn this website to understand how to find the tons of commits , and search something like ' BIG EDIT FONT breaker commits '

Lol
Too much for me

**Comment by Studiodyne** [comment]
I TRUST YOU 😸

**Comment by Studiodyne** [comment]
I will wait

**Comment by Studiodyne** [comment]
My wish for UBL
- off mesh Z secure height 'you know all '
- off mesh z secure active only under current z 
- lcd babystepping active is UBL disabled '  seems to be solved '
- And a new wish ..... FADE HEIGHT in LCD , because  fade height change when the object to print change , and there is no possiblity to adjust it by lcd , and if we print by sdcard ,  to set a fade height need usb connection and will reboot the board 
Fade height have been forgotten , but it's a VERY IMPORTANT DATA
I use one millimeter fade height , because i d'ont understand why10mm
if you print a plate of 3 i understand that we want same thickness everywhere , but it's the only object that need a high fade height , all other object want to smooth the plan the more quick as possible

**Comment by ghost** [comment]
The code seems to be very simple , just some line in ultralcd , that increase size , but there is a ton of conditionnals about the CHARSET compatbility 
I have looked for this in commits , and i have found nothing , and I prefer , that the last author of something about LCD char size will quickly fix it

**Comment by Roxy-3D** [comment]
I'm sure they will fix it...   If they see that there is a problem.

**Comment by Roxy-3D** [comment]
@Studiodyne    What font are you using?   I saw this code:
```
// Only Western languages support big / small fonts
#if DISABLED(DISPLAY_CHARSET_ISO10646_1)
  #undef USE_BIG_EDIT_FONT
  #undef USE_SMALL_INFOFONT
#endif
```

**Comment by ghost** [comment]
My old release , one month ago , works fine , and have UTF8 fr 
It's why , i searchin anything else that the font type
and this code , is the same too , i have already check the basic
But , may be the way to define DISPLAY_CHARSET_ISO10646_1 can be the source 
I have looked at this too , but , i was fallen in a jungle of conditionnals
i have stop to think i'm the greatest engineer here , and i have continued to cry ! 😢

**Comment by Roxy-3D** [comment]
.ZIP up the last version you have that works and post it here.   I'll do a visual diff on the Character Set stuff and the BIG_EDIT stuff.    It maybe with a working version to compare against that it is easy to find the problem.

Also....   Please describe exactly how the new code fails.   Does it put up a blank screen when the big font is supposed to be there?   Does it corrupt the screen?   What exactly is the behavior?

**Comment by ghost** [comment]
You're a very cool girl ! Yes !
[Multo 3.1.zip](https://github.com/MarlinFirmware/Marlin/files/1734524/Multo.3.1.zip)

**Comment by Roxy-3D** [comment]
There are a lot of changes for how character size is handled in ultralcd_impl_DOGM.h   My guess is those changes were not tested with the Big Edit fonts.   It is going to be some work to find the bad code.   You may be able to take the old (and working) ultralcd_impl_DOGM.h and replace the current file with it.   That is probably worth a try.   If it compiles, probably you will have the Big Edit Fonts back.   And that would give us confirmation of where the problem is.

**Comment by ghost** [comment]
ok i will place the dogm in my config , and i will try
thks 👍

**Comment by thinkyhead** [comment]
Patched!

**Comment by ghost** [comment]
@Thinkyhead  From what planet do you come from  ? how it's possible to solve so quickly all the issues here ......... Respect !
Note 1 : Try my filament feeding/loading menu !

**Comment by thinkyhead** [comment]
@Studiodyne — I've got a pile of things to follow up on just clearing bugs for the release. I'll look at new features more closely after that.

![image](https://media.giphy.com/media/BHjjcQgNefFS0/giphy.gif)
