### ISSUE TITLE
Auto Level not compensate enough

### ISSUE THREAD

**Issue by idzuwan** [MarlinFirmware/Marlin#972]
Dea all,

On my mendelmax it seem the Auto Level not compensate enough when printing first layer I can always hear my extruder making clicking sound which indicate the nozzle is blocked and it can't extrude plastic on certain part of the bed, It was working fine few days ago now after changed a new batch of filament it started to have this problem.

Anyone know I can I debug this issues

**Comment by boelle** [comment]
did a enclosure solve the issue?

want to know if this was an hardware issue or software... i lean towards an hardware issue

**Comment by MozzaRozza** [comment]
A lot of building gone on since the posts !!!! I think the enclosure is only a minor contributor

I have now built TWO working Prusa i3 with auto-leveling (and water cooling).....and the leveling problems have disappeared on both.
One has enclosure, one does not.

Pretty sure it is the hardware/physics of the table setup..........my simpler Prusa has a single hotbed, plus 3mm glass. The steps I took
were to :-

1/         Make sure that when the servo deploys the micro-switch, the servo arm is vertical, and substantial. Any bend in the servo arm
is catastrophic....it MUST be perfectly repeatable. I use servos with the little roller at the end of the arm.

2/          Beef up the springs on the four corner screws of the table until almost solid !! A little bit of springiness is OK, in case the 
head crashes in to the glass.........but it should be quite solid.....
When solid, lay the glass on top, and see if it jiggles ---- you may well find it is "high" on 2 opposite corners....adjust until
no jiggle in glass......and clamp glass. As I said in post, the table may even not be at all "level" to the head, but it doesn't matter ---
the auto leveling will compensate for this.........THE PRIORITY IS ---- FLAT AND SOLID............being perfectly horizontal is not vital.

3/          My new Prusa build worked auto-levelling without any problems......but it does have TWO hotbeds sandwiched together.
This serves two purposes ----- very quick heat-up.......110C in 2 minutes....and a very rigid table ---- maybe that explains.
All in all, the new one, with my own water-jacketed head, prints like a demon !!!!!!!!!!!. You do need two power supplies though....one for the hotbeds (they take 18A)
and one for all the rest......(takes about 5A). This stops the voltage pull-down when the hotbed heat kicks in causing instability in the electronics.

The software on both machines is identical, .......... Atmega 2560 + Ramps 1.4 (cheap Chinese clones)
Run most prints on Cura, with modified start code to give the auto level, extrude 30mm starter filament in one corner, and then immediately in to print.

Fell free to come back again....if you think a few pictures would help....or whatever !!!

Date: Wed, 11 Mar 2015 01:53:36 -0700

**Comment by boelle** [comment]
ok, i will then conclude that this was a hardware issue and not an issue with marlin as such

closing

can always reopen og open new issue later
