### ISSUE TITLE
Extruder working fine with A4988s, not with DRV8825, repetier works, marlin not

### ISSUE THREAD

**Issue by yellobello** [MarlinFirmware/Marlin#975]
Hi, I did this post on the reprap forum, but after a couple of posts nobody seems to find an answer for this strange behaviour:

http://forums.reprap.org/read.php?13,358655,373531#msg-373531

The thing is that I can´t get DRV8825 driver working with my RAMPS board, but JUST for the EXTRUDER.
XYZ are working fine with the DRVs but not E0. I tried everything, swapping drivers, swapping stepper motors, nothing.
The only thing that helped was switching from Marlin to Repetier, and all of a sudden it worked.
So I asssume It´s Marlin related....  maybe the step width?  Where on Marlin can this be set?
Any other ideas why it´s not working?

**Comment by yellobello** [comment]
Example:

``` cpp
  for(unsigned char i=0; i<4;i++) {
      if (e_steps[0] != 0) {
        WRITE(E0_STEP_PIN, INVERT_E_STEP_PIN);
        delayMicroseconds(2);
        if (e_steps[0] < 0) {
          WRITE(E0_DIR_PIN, INVERT_E0_DIR);
          e_steps[0]++;
          WRITE(E0_STEP_PIN, !INVERT_E_STEP_PIN);
        }
        else if (e_steps[0] > 0) {
          WRITE(E0_DIR_PIN, !INVERT_E0_DIR);
          e_steps[0]--;
          WRITE(E0_STEP_PIN, !INVERT_E_STEP_PIN);
        }
      }
```

This goes only for the extruder E0, so I ASSUME that

``` cpp
WRITE(E0_STEP_PIN, INVERT_E_STEP_PIN);
```

gives a HIGH signal while

``` cpp
WRITE(E0_STEP_PIN, !INVERT_E_STEP_PIN);
```

gives a LOW, right?

And I only need this for `STEP_PIN`, not `DIR_PIN`....

**Comment by yellobello** [comment]
Oh, I just saw that both HIGH and LOW need to be longer, so:

``` cpp
for(unsigned char i=0; i if (e_steps[0] != 0) {
WRITE(E0_STEP_PIN, INVERT_E_STEP_PIN);
delayMicroseconds(2);
if (e_steps[0] WRITE(E0_DIR_PIN, INVERT_E0_DIR);
delayMicroseconds(2);
e_steps[0]++;
WRITE(E0_STEP_PIN, !INVERT_E_STEP_PIN);
delayMicroseconds(2);
}
else if (e_steps[0] > 0) {
WRITE(E0_DIR_PIN, !INVERT_E0_DIR);
e_steps[0]--;
WRITE(E0_STEP_PIN, !INVERT_E_STEP_PIN);
delayMicroseconds(2);
}
}
```

**Comment by amramsey** [comment]
Sounds like the extruder isn't running because you have temperature
protection enabled in Marlin... it reads the temperature and decides it
isn't safe to run the extruder when it is under temp.

Aaron

**Comment by yellobello** [comment]
The first thing someone pointed out to me was also that I would do a cold extrude. Which was of course not the case.

It seems that the issue is not with all DRV8825s, however I also tried some from GE tech and some from sainsmart, and both had the same issues.
Switching the firmware to repetier and the problem is gone, switching to A4988s and the problem is gone, so It must have something to do with how marlin controls the steppers.

Keeping in mind that people are going to use finer microstepping (eric uses 128th microstepping on marlin2 board, I think) in the future and other stepper drivers, this is something that clearly should be adressed. Its good to have the A4988s working well and MOST other drivers too, but since those issues exist, why not look into them?
Unfortunately I don´t know much about those things :-( I have learned some, but my tries with delays as written above did not lead to satisfying results.

**Comment by Ssendog** [comment]
Hello,

I just mounted a DRV8825 driver onto my RAMPS board and I found no problems with my extruder. 
I have a homemade 3D printer with a direct-drive extruder that haven`t enough torque to feed my filament. So I installed a new stepperdriver.
Before I installed my new driver, I`ve studied Pololu documentations and I find something that would ( maybe ) help you guys!

I noticed that: - nobody mentioned about the wiring schematics for your new driver DRV8825 to your bipolar motor.

example: 

with the "old" driver ( A4988 ) you have 2 sets of wiring that energize your steppermotor.
 ==> 2B and 2A, Blue and red. and the others ==> 1A and 1B, green and black.

with the new Pololu driver ( DRV8825 ) you have also 2 sets of wiring. But different than above!
take a look: ==> 1B and 2B, Blue and red. and the others ==> 1A and 2A, green and black.

Result: old driver wiring setting is not compatible with new one. So verify if your wiring is comform specification connected.

Because if your wiring is not properly connected to you hardware. Then it will cause a problem.
Each motor has his 2 coils. And 1 coil has 2 wires = 2 x 2 =4 wires. Can you imagine when mixing up these wires? Nothing will happen. Steppermotor won`t do a thing.

Make sure: Pot-resistor is turned to a minimal. 
And make sure that:  your jumper setting is set to FullStep for fine adjustments with your POT-resistor.

P.S: I`ve nothing changed in the firmware. 

Works for me.

**Comment by nicksears** [comment]
I have not been able to reproduce it with my setup (ramps 1.4, Chinese 8825
with different PCB,
http://www.geeetech.com/stepstick-drv8825-stepper-motor-driver-carrier-reprap-4layer-pcb-p-652.html
)

They work fine, but I'm using them in 1/16 mode and at ~60mm/s
