### ISSUE TITLE
Delta printer chaotic behavior on z probe error

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#9856]
- Description: 
I have an flsun delta xl mk2 printer with marlin 1.1.8
When doing delta auto probing after the probe hit sometimes the probe does not reset to idle.
This causes chaotic behaviour in Marlin, instead of stopping or going up, it goes haywire, and crashes the head into the bed or collides with z pillar.

- Expected behaviour:
The head should keep rising while maintaining X, Y coordinates

- Actual behaviour:
Chaotic movement, head crash

- Steps to reproduce:
Start a delta auto calibration, then after a hit keep the z probe in active status

[config.zip](https://github.com/MarlinFirmware/Marlin/files/1767608/config.zip)
[log.txt](https://github.com/MarlinFirmware/Marlin/files/1767632/log.txt)

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If you still see the bad behavior we should investigate further.

**Comment by ghost** [comment]
I can confirm that bugfix-1.1.x is affected too. I used the configuration example which came with bugfix-1.1.x git clone ony changed a few unrelated options like board type, delta rod length, machine height, and steps/mm.

If the z probe functions correctly then the movements are smooth, precise and always makes slow contact with the bed. However if the endstop does not work then as if the steppers would get contradictory commands: their movement is non-linear / chaotic, and marlin loses the head position vevn without a missed step. This happenes even if the head does not crash anywhere.

The movement mechanics is otherwise good, produces good multi hour prints without a layer shift, the pulleys cannot be moved by hand if steppers are engaged etc.

**Comment by thinkyhead** [comment]
I assume you're referring to `G33` delta auto-calibration. (Since you have no bed leveling enabled.)

When the `probe_pt` function fails to probe correctly it will say "Probing failed" and then return a "magic number" called NAN (not a number). This value poisons everything it touches. My guess is that the `G33` code is not handling the failure gracefully. It should be checking for NAN and should abort the procedure or maybe re-try the probe.

@LVD-AC — Would you mind having a look at `G33` to see whether my hypothesis holds true?

**Comment by LVD-AC** [comment]
This looks more a hardware problem to me of a probe switch that is stuck:

> the probe hit sometimes the probe does not reset to idle
> however if the endstop does not work then

G33 aborts just as it should at the 1st NAN received and spits out an error message on top of "probing failed" (since 1.1.5 if I remember it well). There where some glitches left that were not dealt with properly, but those have all been fixed in #8821.

At the moment NAN is only returned if the probe does not trigger within set limits. But when the probe is stuck a real (but wrong) value is returned, not NAN. We could think of some extra testing during the probing routine e.g. test if the probe is still triggered after retracting and if so message "probe stuck" and `return NAN`.

**Comment by thinkyhead** [comment]
Sounds like a good companion to the "abort procedure if a probe point is way off" concept.

**Comment by boelle** [comment]
@ddenke8 has this not been "fixed" in latest bugfix 2.0?
