### ISSUE TITLE
Heated Bed Pid Autotune Timeout

### ISSUE THREAD

**Issue by markolo25** [MarlinFirmware/Marlin#9905]
### Bug Report
- Description: Heated Bed PID Autotune times out
- Expected behaviour: Print Autotune values
- Actual behaviour: Autotune halts and indicates timeout
- Steps to reproduce:
  - M303 E-1 C8 S60

Attach a ZIP of `Configuration.h` and `Configuration_adv.h` by dropping here.

------------------------------------------------------------
### Bug Report Tips
- Bug has been fixed in 1.1.x-Bugfix, I just merged the Bugfix with the 1.1.x branch and it works got my values. 

```

**Comment by markolo25** [comment]
It's been resolved.

**Comment by madmax2** [comment]
still occurring for me in 2.x bugfix

**Comment by AnHardt** [comment]
@madmax2 
Does your bed heat at all?
What temperature do you want to tune for?
How long does it take to reach that temperature without PIDTEMPBED?
Is the wanted temperature reachable at all? Even with the part cooling fan blowing on the bed?
Is  PIDTEMPBED on at all?

Don't append to an issue closed since half a year.
Please open a new issue. 
Please follow the instructions in the 'new issue template'.
A 'me to' has about no information what could help us to help you.

**Comment by AnHardt** [comment]
Follow up #12265

**Comment by madmax2** [comment]
@AnHardt yes, I just search for this problem on google and found this thread
so I thought to add my problem here..
But I have also created my own post after posting this comment so didn't see your followup comment/question till now..

Normally in other forums or facebook etc..
They prefer people to post on existing problems and sometimes delete or merge it to those existing posts, so coming from that I thought that is what is best to do, instead of creating the same/similar problem title

But I guess on github, the prefer method is to create a new issue.

Please continue in the new thread I created
Thanks
