### ISSUE TITLE
[2.0.x] First things first: Sort out SPI header spaghetti.

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#9931]
@MarlinFirmware/32bit-maintainers !

At the moment the inter-dependency, most especially around the SPI-oriented headers in the HAL is distressing (`BitOrder` not defined, etc.). See #9476, etc. Let's figure out how to disentangle these –and any similar circular dependencies– so that we can move forward.

**Comment by teemuatlut** [comment]
I think the clearest way is `Marlin -> Possible library -> External SPI library -> Platform core`.
Not everything can be included in Marlin since outside resources will not have access to the Marlin defined implementations.

BitOrder can be problematic since some define MSB/LSBFIRST as `#define MSBFIRST` and some use an enum of the two.

**Comment by thinkyhead** [comment]
I mean, we can keep adding workarounds, like defining `BitOrder` in `HAL_SPI.h` differently for each platform. But ultimately, it just keeps digging us deeper.

**Comment by boelle** [comment]
@thinkyhead still working on this one?

**Comment by boelle** [comment]
this one has gone stale and discussion could as well be held on discord


Marlin Discord server. Join link: https://discord.gg/n5NJ59y
