### ISSUE TITLE
[Bug] Motor power timeout during G29 P2

### ISSUE THREAD

**Issue by golobodo** [MarlinFirmware/Marlin#9980]
### Description

During the manual probing I realized, that especially the Z-Motors disables after DEFAULT_STEPPER_DEACTIVE_TIME. The motor slightly move, but haven't enough power to move the Z-Axis -> step losses. I'm able to rotate the Z threaded rod by hand without force. This may affect all axes. 

### Steps to Reproduce

0. Using latest bugfix_1.1.x with UBL configuration.
1. M502
2. M500
3. M501
4. M190 S60
5. M104 S210
6. G28
7. G29 P1
8. G29 P2 B T
9. wait DEFAULT_STEPPER_DEACTIVE_TIME, in my case 240 seconds

**Expected behavior:**
Motors being active during manual probing

**Actual behavior:**
Motors disabled after DEFAULT_STEPPER_DEACTIVE_TIME

#### Additional Information
An workaround is to increase DEFAULT_STEPPER_DEACTIVE_TIME or setting at least DISABLE_INACTIVE_Z to false.

**Comment by Roxy-3D** [comment]
Thank you for finding this problem.  This should not be too hard to fix.  But the problem is I don't have a machine available to test any changes right now.    I think we just need to make
```
void manually_probe_remaining_mesh();
```
suspend the time out on each mesh point....

Can you please try a small code change for me?   (And put your #defines back to the way they were causing trouble) ?    In ubl_g29.cpp, can you change this function to look like this:
```diff
    void unified_bed_leveling::move_z_with_encoder(const float &multiplier) {
      wait_for_release();
      while (!is_lcd_clicked()) {
        idle();
+       refresh_cmd_timeout();     //    <---<<<  This line is new.
        if (encoder_diff) {
          do_blocking_move_to_z(current_position[Z_AXIS] + float(encoder_diff) * multiplier);
          encoder_diff = 0;
        }
      }
    }
```
If we can get confirmation that fixes the problem you are seeing...   I can zap both the bugfix-1.1.x branch and the bugfix-2.0.0 branch so nobody else has a problem with this.

**Comment by thinkyhead** [comment]
> <---<<<  This line is new.

Try out ` ```diff ` for starting pre-formatted text. It colorizes lines starting with `-` and `+`.
```diff
- Not so cool?
+ Very cool!
```

**Comment by golobodo** [comment]
Adding the line solved the problem. You can add it to the source. Thanks!

**Comment by Roxy-3D** [comment]
Oh!   OK!   That is a nice feature...  (the ```diff feature)

@golobodo OK...   I'll do that now.    I like your cat icon.   But the cat looks mean.

**Comment by VanessaE** [comment]
Is this related:

I was re-tuning my E steps/mm after replacing a worn-out hob gear, and as you no doubt are aware, one is supposed to mark the filament, very slowly (in this case, 50 mm/min) extrude 100 mm, measure how much was really moved, adjust E as needed, and repeat until it's right.

At the end of each of those 100 mm extrude-only moves, the extruder bounces backward from the pressure, and I can rotate it by hand easily.  My idle timeout is 120 seconds, which is exactly how long each of those extrude moves takes.

**Comment by thinkyhead** [comment]
From the LCD?

**Comment by VanessaE** [comment]
Nope, from Pronterface (I'm beginning to think I'm the only one whose bot lacks an LCD :stuck_out_tongue: ), though I imagine both end up doing the same thing.

**Comment by thinkyhead** [comment]
I'm guessing the issue is that the stepper timeout isn't respecting that a move is in the buffer as it counts down. It should reset itself in response to any move. I've never liked the fact that Marlin has to use `refresh_cmd_timeout` to prevent steppers from timing out, rather than resetting any time a moves comes into the planner.

**Comment by VanessaE** [comment]
I was thinking along the same lines.

**Comment by thinkyhead** [comment]
I see that the timeout routine _**is**_ checking whether there's a block queued in the planner. However, it's not resetting the countdown. As soon as the long move completes it disables the steppers. I'll fix that now.

**Comment by thinkyhead** [comment]
The PR #10178 should fix things. Please give it a try whenever you have a chance.
